### ISSUE TITLE
[São Paulo] Analista Desenvolvedor

### ISSUE THREAD

**Issue by markgerald** [phpdevbr/vagas#1]
## Descrição da vaga

Projeto de reestruturação de aplicação de comparativos de preços, e novo MarketPlace.
## Local

Região da Higienópolis, próximo metrô Santa Cecília. (Av. Angélica)
## Requisitos

**Obrigatórios:**
- Bons conhecimentos na linguagem PHP e Banco de dados MySQL
- Bom Conhecimento em orientação a objetos.
- Conhecer algum framework de mercado: Symfony, Laravel ou Zend
- Conhecimento básico em AngularJS

**Desejáveis:**
- Bom conhecimento do framework Symfony
- Conhecimento de desenvolvimento de Api REST
- Bom conhecimento de AngularJS
- Noções de Cache(Redis) e Elasticsearch.
## Contratação

PJ
## Nossa empresa

A missão do [pagpouco.com](http://www.pagpouco.com) é aumentar o poder de compra do consumidor.

Divulgamos milhares de preços em supermercados, e comparamos todos eles na nossa plataforma, idealizada para os nossos usuários terem uma experiência extremamente útil, intuitiva e gratuita.

Através do pagpouco.com, é possível adicionar produtos à lista e descobrir quais supermercados têm as melhores ofertas para realizar as compras. Também é possível cadastrar alertas de preços: sempre que um estabelecimento atingir o valor que o usuário quer pagar, a plataforma o avisa imediatamente.

Além das ferramentas disponíveis, somos também uma comunidade multicanal onde os usuários escolhem qual conteúdo desejam ver, quais supermercados e marcas querem seguir e quais notificações preferem receber.

Quem segue o PagPouco.com tem garantia de economizar tempo e dinheiro.
## Como se candidatar

Por favor envie um email para contato@pagpouco.com com seu CV anexado e link do Linkedin no corpo do Email - enviar no assunto: Vaga PHP

**Comment by nic** [comment]
Boa vaga heim!

**Comment by joubertredrat** [comment]
:+1:

**Comment by upcesar** [comment]
@markgerald mandei meu CV no e-mail indicado. Aguardo novo contato.

**Comment by joubertredrat** [comment]
Eu quero uma vaga dessas, mas vou para São Paulo só em Janeiro.

**Comment by markgerald** [comment]
Galera a vaga continua em aberto! Aguardando currículos!

**Comment by joubertredrat** [comment]
@markgerald se a vaga continuar aberta até Janeiro do ano que vem, com certeza enviarei meu CV. Quero montar a minha startup e trabalhar em uma vai ser como uma didática para mim, além de agregar conhecimento.

**Comment by markgerald** [comment]
Vaga preenchida! Obrigado aos envolvidos!

**Comment by joubertredrat** [comment]
Haaaaaaaaa, eu não queria essa vaga mesmo :(

@markgerald Deseje boa sorte ao escolhido por mim :+1:
