### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor(a) Back-End Pleno

### ISSUE THREAD

**Issue by ceasbz** [phpdevbr/vagas#10]
## Descrição da vaga

Estamos começando a expandir o nosso time e precisamos de pessoas que realmente gostam de estar à frente do mercado, aquelas que curtem experimentar novas tecnologias e que estão sempre antenadas ao cenário atual do desenvolvimento back-end.

A nossa missão é de, simplesmente criar uma equipe de ponta, que esteja engajada com a comunidade e que se sinta confortável com o desconfortável e que curta encarar desafios.

### Local

Escritório - Avenida das Américas, 500 - Barra da Tijuca (Shopping Downtown) - Rio de Janeiro

Ou Remoto

### Benefícios

- Horário flexível;
- Vale refeição ou alimentação (Pode escolher);
- Vale transporte;
- Ambiente descontraído;
- Roupa informal (pode bermuda);

### Requisitos

- Especializado em PHP e MySQL;
- Familiaridade com os princípios do S.O.L.I.D;
- Entendimento das melhores práticas/padrões de Design;
- Experiência com sistemas de controle de versão (GIT);
- Desenvolvimento guiado por testes (TDD);
- Integração Contínua;
- Familiaridade com metodologias ágeis (Extreme Programming e SCRUM);

### Gostaríamos de ver

- +3 anos de experiência em desenvolvimento back-end com aplicações web;
- Conhecimento de Domain Driven Design;
- Ter tido experiência com microservices;
- Excelente capacidade de comunicação oral/escrita;
- Escrever código escalável e reutilizável;
- Capacidade de gerir o próprio tempo;
- Paixão pela área;

### Contratação

CLT

### Como se candidatar

Enviar email para recrutamento-ti@personare.com.br com o subject: `Desenvolvedor Back-End Pleno`

Além disso, em uma de nossas etapas do processo seletivo, consta em realizar um desafio técnico. Se quiser ir adiantando, esse [link](https://github.com/Personare/back-end-challenge) contém todas as informações necessárias. Boa sorte \o/

**Comment by nic** [comment]
@ceasbz Vaga preenchida?

**Comment by ceasbz** [comment]
Fala @nic, tudo bem?

Essa vaga continua em aberto pois estamos sempre procurando bons profissionais para agregar o time do Personare. Aliás, vou até mudar a descrição, pois a vaga pode ser home office 😸

**Comment by Piulres** [comment]
Me interesso, http://www.renan.zz.mu

**Comment by ceasbz** [comment]
Fala @Piulres, tudo bem?

Seria interessante você seguir as instruções na descrição, se preferir, pode entrar em contato direto comigo: c.alves@personare.com.br :}

Assim conseguimos marcar um papo p/ nos conhecermos melhor ^.^

**Comment by geekcom** [comment]
Vaga preenchida @ceasbz, enviei um email para você.

**Comment by linikerdev** [comment]
A vaga continua em aberto ?

Tenho interesse....pode postar maiores informações.

Grato.

**Comment by ceasbz** [comment]
@linikerdev Continua em aberto sim, quais dúvidas você teria?

**Comment by linikerdev** [comment]
@ceasbz Trabalho como analista de sistemas web, meu trabalho é focado em projetos principalmente feitos e Laravel, mas já fiz projetos também em cakePHP e magento. Tenho interesse em trabalhar remoto, pelo menos por um tempo.Achei a oportunidade interessante, porém gostaria de saber a faixa salarial da mesma.

Enviei e-mail com meu currículo.

**Comment by zabaala** [comment]
Tai um lugar que eu queria conhecer. Acho o Personare massa!

**Comment by upcesar** [comment]
A vaga continua em aberto? Mandei meu CV.

**Comment by deyvisonrocha** [comment]
@ceasbz Vaga em aberto?

**Comment by ceasbz** [comment]
Olá \o

Desculpe-me pelo atraso, estamos reformulando algumas vagas e irei encerrar essa issue. Mas não há problemas, guardamos os currículos de todos que enviaram e iremos entrar em contato caso esteja batendo com o nosso novo perfil 💃 💃

Depois irei criar uma nova issue para a vaga reformulada \o

**Comment by ceasbz** [comment]
@zabaala Se quiser marcar uma visita, estamos no Rio de Janeiro \o

**Comment by zabaala** [comment]
@ceasbz Pow... se tivesse visto antes, tinha passado ai. Estive ai no final de novembro.

**Comment by zabaala** [comment]
A vaga ainda está aberta? Acabei de ver que ela foi atualizada. :)
