### ISSUE TITLE
[Florianópolis/SC] Desenvolvedor(a) Full Stack na Stock & Info

### ISSUE THREAD

**Issue by ConsultoriaContato** [phpdevbr/vagas#101]
**O que esperamos de você:**
Receber, entender e discutir funcionalidades a serem desenvolvidas nos sistemas mantidos pela empresa.
Melhorar, corrigir e testar funcionalidades nos sistemas mantidos pela empresa.
Avaliar, propor, aplicar, melhorar e corrigir falhas de arquitetura e desenvolvimento dos sistemas da empresa.
Avaliar, propor e aplicar as melhores soluções e tecnologias para problemas de desenvolvimento.
 
**O que buscamos em você:**
Experiência profissional mínima de 2 anos em desenvolvimento Java para a Web.
Experiência em modelagem e conceitos de banco de dados relacional, Java, HTML5.
Experiência em framework Javascript, Spring, Bootstrap.
Desejável experiência em Jenkins, SVN, FileMaker, Web services.
 
**O que oferecemos:**
Oferecemos um ambiente de trabalho descontraído e super informal (valorizamos o que você diz e o que você faz, não o que você veste). Incentivamos o debate e o compartilhamento de idéias; queremos candidatos que gostem de expor suas opiniões. Se você encaixa-se na expressão "think outside the box" e se considera uma pessoa criativa, essa é a sua oportunidade. Além disso, oferecemos Assistência Médica / Medicina em grupo, Assistência Odontológica, Convênio com farmácia, Participação nos lucros, Seguro de vida em grupo, Vale alimentação ou vale refeição, Vale transporte, Dia da fruta, Vídeo Game nos intervalos, Ginástica laboral, Convênio com academia.
 
Se você se sentiu desafiado, seu lugar é aqui! Venha ser um Stocker! :)

**Sobre a Stock:**
 
A Stock & Info é uma empresa jovem que desenvolve soluções inteligentes para Previdência Privada.
Com sede em Florianópolis, capital com melhor qualidade de vida, é referência no mercado de previdência, com soluções que administram mais de 100 mil vidas.
Se você gosta de desafio, curte trabalhar com metodologia ágil e, assim como nós, prefere trabalhar numa empresa de médio porte e ser conhecido pelo nome, seu lugar é aqui!
 
O seu trabalho vai impactar o futuro da área de previdência complementar do Brasil através da tecnologia!

**Como se candidatar**
Cadastrar CV em www.selecaodevagas.com.br e candidatar-se à vaga!

**Comment by rscafi** [comment]
Olá, esse repositório é somente para vagas PHP, essa vaga no caso é para Java, são tecnologias diferentes.
