### ISSUE TITLE
[Belo Horizonte/MG] Programador(a) Fullstack Web Developer PHP no Grupo República

### ISSUE THREAD

**Issue by guireisbh** [phpdevbr/vagas#102]
## Descrição da vaga

Trabalhar com sistemas tailor-made, Wordpress, e-commerce, JS. Equipe com 4 programadores. Procuramos um profissional que goste de programar, focado, comprometido e que goste de desafios.

## Local

Trabalho presencial - Região: Santa Efigênia - Belo Horizonte - MG

## Benefícios

- Horário Flexível
- VT + VR + bônus por produtividade
- Café e lanches <3

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com PHP 5+
- Experiência com Bootstrap, JQuery/Javascript, MySQL, Rest API's
- Portfólio com construção de Plugins para Wordpress

**Desejáveis:**
- conhecimentos em Laravel

## Contratação

CLT - R$3.200 iniciais + bônus por produtividade

## Nossa empresa

O Grupo República é formado por empresas consolidadas no mercado e com experiência. Trabalhamos muito para entregar o melhor para nossos clientes.

## Como se candidatar

Por favor envie um email para dev@gruporepublica.com.br com seu CV anexado - enviar no assunto: Vaga FullStack PHP

**Comment by ravanscafi** [comment]
Olá @guireisbh ,
A vaga ainda está aberta?

_(sou administrador das vagas e estou fechando as que já foram preenchidas)_

**Comment by ravanscafi** [comment]
_(fechado por falta de resposta)_
