### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) PHP Pleno/Sênior na Btime

### ISSUE THREAD

**Issue by vaynard** [phpdevbr/vagas#103]
# Quero ser Btime!

Nossa solução é um SaaS de Gestão de Equipes Externas, atuando em PHP com Symfony Framework. Procuramos profissionais que tenham sólidos conhecimentos de arquitetura e capacidade de pensar fora da caixa solucionando problemas de forma simples e rápida, levando-se em conta temas como segurança, tratamento de erros, separação de camadas/responsabilidades, performance, reusabilidade e aderência a padrões de projetos.

## Local

Oxigênio Aceleradora, São Paulo - SP | próximo ao metrô Marechal Deodoro

## Nossa empresa

A Btime é uma startup que está mudando a forma com que as pessoas trabalham. Fomos acelerados pela Liga AutoTech e agora pelo Oxigênio Aceleradora, com investimento da Porto Seguro e Plug and Play, e buscamos formar uma equipe qualificada e multidisciplinar para atender a crescente demanda, com objetivo de construir soluções inovadoras, onde maior valor é o sucesso de nossos clientes.

Nós oferecemos um ambiente descontraído em que todos os membros possuem a liberdade e responsabilidade de criar as melhores soluções possíveis, isso contando com o suporte de todos os membros, do estagiário até o CEO.

Se você quer mudar a vida das pessoas e a forma que elas trabalham, ou melhor, se você quer mudar o mundo =), venha com a Btime e faça parte dessa história.

## Aqui você irá

- Garantir o desenvolvimento de software com qualidade, através de integração contínua, automação de testes e profundos code-reviews;
- Construir plataformas sustentáveis e estáveis para novas ideias de produto; 
- Encontrar soluções simples e elegantes para problemas difíceis; 
- Trabalhar com TDD e Testes Automatizados; 
- Trabalhar com metodologia ágil scrum;
- Trabalhar com APIs REST;
- Trabalhar com time multidisciplinar.

### [Como me candidato?](id:ComoMeCandidato)
1. Forka esse projeto, escolha um dos testes aleatórios do [DojoPuzzle](http://dojopuzzles.com/), resolva-o com sua linguagem favorita e nos envie um e-mail para **team@btime.com.br** com o seu **fork** e o **link do problema** (link para o GitHub, BitBucket, tarball anexada, whatever). Junto do seu e-mail, adicione um link para seu curriculum, portfolio ou linkedin. Avaliaremos seu *fork* o quanto antes.<br />
**Duração:** de 30min à 2h

2. Com hora marcada, um dos membros do nosso time entrará em contato com você por telefone ou Skype, para uma conversa descontraída sobre suas habilidades.<br />
**Duração:** de 30min à 40min

3. Visita aqui no escritório, com uma sessão de pair-programming.<br />
**Duração:** de 1h à 1h30min

\* Este processo pode ser alterado sem prévio aviso. Então, fique esperto com as atualizações deste README! :-)

### [Requisitos Básicos](id:RequisitosBasicos)
Precisamos de gente que:

* Procure o estado da arte do código, da arquitetura e do design de software, **MAS** que tenha **plena noção** de que nem sempre é possível alcançá-lo em um ambiente ágil =(;
* Tenha experiência com desenvolvimento para web;
* Que reconheça que a linguagem **&lt;escolha sua linguagem favorita&gt;** não é a melhor linguagem/solução para todos os problemas.
* Ter graduação é legal! Mas se você não for formado, não tem problema. Conhecemos vários profissionais plenamente capacitados que não são formados.

## Modelo de contrato

PJ presencial, remuneração a combinar

#### [Backend Engineer PHP](id:Qualificacoes-BE)
**Qualificações mínimas**
- PHP
- Symfony Framework
- MySQL
- RESTFul API
- Design Patterns

**Desejáveis:**
- Git/BitBucket
- Google APIs
- Redis
- RabbitMQ
- Docker
- Agile/SCRUM

**Diferenciais:**
- TDD
- SOLID (object-oriented design)
- Elastic Search
- Java
- NodeJs

## [Nossos Links](id:Extra-Links)
* [Btime](https://btime.com.br/)

**Comment by ravanscafi** [comment]
Olá @vaynard ,
A vaga ainda está aberta?

_(sou administrador das vagas e estou fechando as que já foram preenchidas)_

**Comment by ravanscafi** [comment]
_(fechado por falta de resposta)_
