### ISSUE TITLE
[São Paulo/SP] Programador(a) PHP remoto na SMS Soluções

### ISSUE THREAD

**Issue by marcelod** [phpdevbr/vagas#105]
## Descrição da vaga

Irá trabalhar no desenvolvimento de  uma aplicação e reestruturação da mesma.

## Local

Empresa fica em São Paulo, mas irá trabalhar remoto (as vezes precisamos nos reunir).

## Benefícios

- Remoto

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com PHP
- 2 anos de experiência com SQL (MySQL, Postgres, SQL Server...)
- GIT
- Javascript

**Desejáveis:**
- conhecimentos em algum framework PHP MVC (Laravel, Yii, Cake, Codeigniter)
- conhecimentos em Bootstrap, materialize
- conhecimentos em VueJS, Jquery

**Diferenciais:**
- conhecimento na AWS
- conhecimento com noSQL (Mongo) e redis
- contribuições em projetos opensource

## Contratação

à combinar

## Nossa empresa

A [SMS Soluções](https://smssolucoes.eco.br/) é uma empresa de consultoria em gestão de empresas que fornece sistema informatizados para uso dos clientes.ambiental.

## Como se candidatar

Por favor envie um email para vagas@smssolucoes.eco.br com seu CV anexado - enviar no assunto: Vaga PHP

**Comment by vinyguedess** [comment]
@mateusguedess

**Comment by diegovilarinho** [comment]
Vaga aberta ainda?

**Comment by marcelod** [comment]
Sim

Em 28 de dez de 2017 1:50 PM, "Diego Vilarinho" <notifications@github.com>
escreveu:

**Comment by andersao** [comment]
CV enviado!
