### ISSUE TITLE
[Belo Horizonte/MG] Desenvolvedor PHP Júnior/Pleno pela Capgemini

### ISSUE THREAD

**Issue by jansenfelipe** [phpdevbr/vagas#107]
## Descrição da vaga

Estamos a procura de desenvolvedores para compor nosso time. Por aqui estamos utilizando PHP com Laravel Framework.

## Local

**Presencial**

O funcionário será contratado pela Capgemini e irá trabalhar alocado no Sebrae Minas:
Av. Barão Homem de Melo, 329 - Nova Granada - Belo Horizonte/MG

## Requisitos

**Obrigatórios:**
- PHP OO
- Laravel Framework
- SQL
- GIT
- Composer
- Graduação na área de TI (Cursando ou Formado)
- Projetos publicados no GitHub (vamos utilizar para análise curricular)

## Contratação

CLT Salário 3k~4k + Benefícios VT, VR ou VA, Plano de Saúde, PLR e Previdência Privada. 

## Como se candidatar

Para se candidatar, envie currículo para o email jansen.vitor@sebraemg.com.br com o assunto: "Vaga: Backend PHP"

**Comment by guilherme90** [comment]
Tem benefícios?

**Comment by jansenfelipe** [comment]
@guilherme90 desculpa a demora em responder. Tem benefícios sim! Atualizei a descrição da vaga.

**Comment by jansenfelipe** [comment]
Vaga preenchida!
