### ISSUE TITLE
[São Paulo/SP] Desenvolvedor Sênior na Natue

### ISSUE THREAD

**Issue by pvgomes** [phpdevbr/vagas#108]
## Descrição da vaga

Estamos a procura de um(a) desenvolvedor(a) que tenha o PHP como linguagem principal mas que também tenha vontade em aprender novas tecnologias.

## Local

Escritório, São Paulo - Bela Cintra

## Benefícios

- Horário flexível
- Home office (alguns dias da semana combinado com o gestor)

## Requisitos

**Obrigatórios:**
-  Tenha experiência em desenvolvimento de software com PHP e controle de versão como Git ou Mercurial

-  Conheça muito bem estruturas de dados (listas, filas, arrays, hashes, grafos);

- Tenha experiência em codificação com frameworks/ferramentas modernas de desenvolvimento web, como: Symfony, Zend Framework, Laravel, Yii;

- Conheça também banco de dados relacionais e não-relacionais;

**Desejáveis:**

-  Tenha experiência significativa usando e implementando web services (REST, SOAP, RPC, RMI) e APIs de monitoramento;

-  Domine as melhores práticas de desenvolvimento moderno, como Design Patterns, micro-serviços, TDD, CI;

-  Goste de trabalhar com metodologias ágeis e tenha vivência em pelo menos uma delas (Scrum, Kanban, XP).

**Diferenciais:**
-  Conhecimento em sistemas de engenharia de dados/Big Data, sistemas de mensagens / filas altamente escaláveis;

- Compreensão sólida de sistemas distribuídos, programação orientada a eventos  programação reativa;

- Experiência com nuvens públicas (AWS, Azure, Google Cloud Platform);

-  Experiência anterior em empresas de varejo/ecommerce.

## Contratação

PJ a combinar

## Nossa empresa

No ar desde dezembro de 2012, a Natue nasceu do sonho de um médico e de uma economista, que juntos se propuseram a criar uma plataforma de e-commerce que pudesse levar mais saúde e bem-estar aos consumidores que não encontram tempo livre na agenda. Mais do que simplesmente uma loja online; a Natue foi criada para ser um espaço feito sob medida para quem procura ter uma vida mais balanceada e saudável.
Apesar de brasileiríssima, a Natue já recebeu diversos aportes de investimento. 

Nascemos como uma plataforma de e-commerce. Hoje somos uma marca que representa um estilo de vida.

## Como se candidatar

Para se candidatar envie seu currículo no link https://jobs.kenoby.com/natue/job/desenvolvedor-back-end-senior/5a09f66c6455370e3f1524f8 e faça um fork do nosso teste no Github https://github.com/natuelabs/challenge

**Comment by ravanscafi** [comment]
Olá @pvgomes,
A vaga ainda está aberta?

_(sou administrador das vagas e estou fechando as que já foram preenchidas)_

**Comment by ravanscafi** [comment]
_(fechado por falta de resposta)_
