### ISSUE TITLE
[100% Remoto] -  SQUAD LEADER PHP - Red Pill RH

### ISSUE THREAD

**Issue by Kethlynaraujog** [phpdevbr/vagas#1080]
**A Red Pill juntamente a Pontomais está em busca de um novo Squad Leader!** 

**O que buscamos?**

- Como Squad Leader você será o facilitador para que o time da sua Squad entregue o valor esperado para o nosso Produto.
- Experiência com Desenvolvimento de Software - Aqui você não vai precisar codar mas esse conhecimento faz diferença no dia a dia;
- Experiência com Gestão de Projetos;
- Experiência com Liderança técnica;

**Você vai brilhar se:**

- Tiver conhecimento com gestão de pessoas;
- Conhecimento em PHP;

**O que você fará?**

- Tirar os impedimentos ajudando seu time a ter os melhores resultados;
- Avaliar os melhores cenários para entregas;
- Ser referência técnica para o time;
- Gerenciar priorizações e os impactos nas tomadas de decisões das estratégias seguidas pelo time;
- Conduzir cerimonias e 1:1 para manter a sinergia do time;
- Facilitar o Desenvolvimento da Equipe;

## Local
-Remoto

## Benefícios

- Vale Refeição de R$30 por dia;
- Vale Alimentação de R$300 (quando vc sair de férias ainda recebe o VA, viu).  VR e VA não tem aquele desconto na folha de pagamento;
- Plano de Saúde sem custo na mensalidade;
- Plano Odontológico sem custo na mensalidade;
- Serviço de ambulância para emergências médicas;
- Vale Farmácia;
- Totall pass - Seguindo a linha da saúde temos mais esse beneficio para você;
- R$100,00 de vale home office;
- Plano de Carreiras, Cargos e Salários;
- PAE - Programa de Assistência Jurídica, Psicológica, Previdenciária e mais;
- Licença Maternidade e Paternidade estendida;
- Treinamentos e workshops (internos e externos);
- Parcerias com Instituições de Ensino;
- Day-off em 1 dia do mês do seu aniversário - pq é um dia especial e vc merece esse mimo de escolher qual dia vc quer folgar no mês do seu aniversário (só não esquece de trazer um pedacíneo de bolo pra gente!);

## Como se candidatar

Por favor envie um e-mail para  kethlyn.araujo@redpillrh.com.br com seu CV anexado ou LinkedIn - enviar no assunto: Vaga SQUAD LEADER PHP

## Labels
- 100% Remoto
- CLT
- Especialista

**Comment by s4muelat** [comment]
Olá, ainda está disponível?
