### ISSUE TITLE
[São Paulo] Desenvolvedor PHP Pleno 

### ISSUE THREAD

**Issue by thierryrene** [phpdevbr/vagas#11]
## Descrição da vaga

Somos uma startup de moda, e buscamento um candidato com experiência plena em PHP (saber trabalhar com a linguagem em si em qualquer ambiente, com frameworks ou não), JS, MySQL, HTML e CSS (temos um estagiário para ajudar com o front-end).

A principal função do profissional será desenvolver novas funcionalidades em um sistema de gerenciamento de conteúdo próprio integrado ao nosso site, que foi desenvolvido com o WordPress.

## Local

Escritório (locado), São Paulo - Itaim Bibi

## Requisitos

**Obrigatórios:**

- No mínimo 3 anos de experiência com PHP.
- Conhecimento em frameworks PHP
- Conhecimentos em Git
- Boas práticas de desenvolvimento
- Conhecimento em banco de dados
- Facilidade para trabalhar em equipe
- Inglês técnico

**Desejáveis:**

- conhecimento da linguagem PHP em si, para trabalhar em qualquer ambiente.
- Experiência em desenvolvimento ágil
- Curiosidade e vontade de aprender novas ferramentas e tecnologias
- Capacidade de pensar e resolver problemas de forma criativa

**Diferenciais:**

- conhecer a linguagem a nível de trabalhar com qualquer solução baseada na mesma, seja framework ou qualquer outra solução/plataforma.
- Perfil ativo no GitHub e/ou StackOverflow.

## Contratação

- CLT

## Como se candidatar

Por favor envie um email para arthur@stealthelook.com.br com seu CV anexado - enviar no assunto: Vaga PHP - STL

**Comment by joubertredrat** [comment]
Currículo enviado

**Comment by nic** [comment]
@thierryrene Vaga preenchida?
