### ISSUE TITLE
[Floripa/SC] Backend Sênior na SocialBase

### ISSUE THREAD

**Issue by lhzsantana** [phpdevbr/vagas#110]
![vaga_backend](https://user-images.githubusercontent.com/5663741/33858069-7572e8f2-deb5-11e7-8c40-cc404db13e83.gif)

Mais detalhes em:

https://socialbase.workable.com/j/A8791A9650

**Comment by rscafi** [comment]
@lhzsantana a vaga é CLT ou PJ?

**Comment by lhzsantana** [comment]
desculpa @rscafi , a gente contrata em ambos regimes.

**Comment by ravanscafi** [comment]
Olá @lhzsantana,
A vaga ainda está aberta?

_(sou administrador das vagas e estou fechando as que já foram preenchidas)_

**Comment by lhzsantana** [comment]
Não, já foi fecahda.
