### ISSUE TITLE
[Aquiraz/CE] Symfony/PHP Developer na oowlish

### ISSUE THREAD

**Issue by clmadrazo** [phpdevbr/vagas#111]
## Descrição da vaga

Venha fazer parte do time oowlish!
Na oowlish estamos à procura de desenvolvedores Symfony/PHP para juntar-se a nossa equipe!

## Local

Escritório, Ceará - Aquiraz

## Benefícios

- Trabalhar na “oowlish Mansion” 😉
- Uso de SCRUM, trabalhar numa das nossas squads.
- Ambiente de trabalho internacional, descontraído e cooperativo
- Trabalhar em produtos de sucesso internacional
- Salário
- Horário flexível

## Requisitos

**Obrigatórios:**
- Amplo conhecimento em PHP
- Ampla experiência em RESTFull APIs.
- HTML5, JS, CSS3
- Design patterns.
- Experiência em produtos mobile.
- Inglês básico (leitura/escrito)

**Desejáveis:**
- Conhecimentos de administração de servidores (AWS)
- Conhecimentos de Node.js

**Diferenciais:**
- Espanhol
- Backbone, require.js, Phonegap.

## Contratação

CLT

## Nossa empresa

oowlish é uma empresa de desenvolvimento dinâmico com sede no Porto Das Dunas. Nós adoramos móveis, web e excelente trabalho! Ajudamos às empresas a desenvolver e produzir seus produtos de mídia digital.

## Como se candidatar

Por favor envie um email para career@oowlish.com com seu CV anexado - enviar no assunto: Symfony/PHP Developer

**Comment by giovannicruz97** [comment]
Existe a possibilidade de remoto ?

**Comment by clmadrazo** [comment]
@giovannicruz97 não, só presencial

**Comment by ravanscafi** [comment]
Olá @clmadrazo,
A vaga ainda está aberta?

_(sou administrador das vagas e estou fechando as que já foram preenchidas)_

**Comment by ravanscafi** [comment]
_(fechado por falta de resposta)_
