### ISSUE TITLE
PHP Developer

### ISSUE THREAD

**Issue by thaynateixeiras** [phpdevbr/vagas#1118]
## Descrição da vaga
Atuação alocado no maior e-commerce da América Latina 

## Local

Remoto 

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com PHP 5+
Vivência arquitetura de software, microserviços, CI/CD, Docker e metodologia Ágil. 

**Desejáveis:**
- conhecimentos em Laravel

## Contratação

PJ

## Nossa empresa

Aqui na Nexmuv atuamos com foco em inovação, produtos e tecnologia; 

## Como se candidatar

Por favor envie um email para thayna,silva@nexmuv.com.br com seu CV anexado - enviar no assunto: Vaga PHP

### Alocação:
Remoto

### Contratação:
- PJ

### Experiência
- Pleno

**Comment by JoaoPdSsilva** [comment]
> @thaynateixeiras este email esta certo?

possivelmente é thayna.silva@nexmuv.com.br eles devem ter clicado na virgula sem querer
