### ISSUE TITLE
[Rio de Janeiro/RJ] Desenvolvedor(a) PHP Jr na Agência Titânio

### ISSUE THREAD

**Issue by rgvweb** [phpdevbr/vagas#112]
## Descrição da vaga

Desenvolvedor web nível junior com habilidade em php e front-end

## Local

Rio de Janeiro - Centro

## Benefícios

Vale refeição
Vale alimentação
Vale transporte

## Requisitos

**Obrigatórios:**
- Experiência com PHP, banco de dados MySQL ou SQL Server;
- Experiência em JavaScript e, principalmente, jQuery;
- Conhecimentos de AJAX e Bootstrap;

**Diferenciais:**
- Pré-processadores de CSS;
- Automatizador de tarefas (Gulp ou Grunt);
- Framewoks em PHP (Laravel, CakePHP, CI);
- Animações com CSS3. 

## Contratação

CLT a combinar

## Nossa empresa

A Titânio é uma agência de marketing digital com 8 anos de mercado e um time formado para entregar as melhores soluções as clientes. Acesse nosso site e entenda nossa filosofia organizacional. 

## Como se candidatar

Envie seu currículo pelo site:
http://www.agenciatitanio.com.br/carreira
Aproveite para deixar na carta de apresentação alguns links de projetos que você tenha feito ou participado.

**Comment by ravanscafi** [comment]
Olá @rgvweb,
A vaga ainda está aberta?

_(sou administrador das vagas e estou fechando as que já foram preenchidas)_

**Comment by ravanscafi** [comment]
_(fechado por falta de resposta)_
