### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) Full Stack PHP na Memed

### ISSUE THREAD

**Issue by williamespindola** [phpdevbr/vagas#113]
![vaga](https://user-images.githubusercontent.com/2197005/28040232-8be9e3c6-659b-11e7-9bee-b86e00241fbd.png)
## Descrição da vaga

Gosta de inovar e quer ajudar a melhorar a saúde do Brasil? Venha para a Memed! 
Estamos a procura de 3 Devs (Pleno e Sênior) que sejam full stacks natos e saibam mexer em 100% de uma aplicação web.

O que você vai fazer: 
- Desenvolver a maior plataforma médica de prescrição digital do Brasil; 
- Criar novas funcionalidades, executar manutenções e melhorias, realizar testes; 
- Nos ajudar a manter/implementar boas práticas, adoramos padrões e simplicidade.

O que usamos no front-end: Arquitetura modular + CQRS/ES + Vue.js (migrando de Backbone.js + Underscore Templates) + jQuery/Zepto + Grunt/NPM + LESS + Semantic.UI. 
O que usamos no back-end: Arquitetura modular + CQRS/ES (sim, no back-end também ;-D) + JSON API + JWT + PHP 7.2 + Composer + Lumen + Eloquent (e PDO) + Memcached + RabbitMQ + ElasticSearch + Docker.

## Local

Rua Artur Prado, 513, Bela Vista - São Paulo, SP
A 7 minutos da estação de metrô Brigadeiro

## Benefícios

- VR
- VT
- Seguro de Vida
- Seguro Saúde

## Requisitos

**Obrigatórios:**

- Experiência com php 7
- Experiência com rest, json api, jwt e oauth
- Gosta de vanilla javascript e sabe quando utilizar frameworks
- Experiência em ferramentas de automação de tarefas (ex: grunt)
- Conhecimento de design patterns (ex: repository, service layer, locator)
- Conhecimento sobre psrs
- Experiência em motores de busca (ex: elasticsearch)
- Desenvolvimento de código com organização, modularização e documentação
- Capacidade de autogestão e aprendizado rápido
- Vontade em inovar e melhorar a saúde do brasil

**Desejáveis:**
- Experiência com docker
- Experiência com laravel/lumen
- Experiência com vue.js
- Experiência com ferramentas para tdd (ex: phpunit, jest, codeception)
- Experiência com ferramentas para bdd (ex: behat, nightwatch, codeception, selenium)
- Experiência com gitflow

## Contratação

CLT

## Como se candidatar

Por favor envie um email para gabriel.couto@memed.com.br com seu CV anexado - enviar no assunto: Desenvolvedor Full Stack (PHP).

Caso queira bater um papo, no Slack do PHPSP (http://phpsp.org.br/) é só chamar o @bob.

**Comment by clmadrazo** [comment]
Alguma possibilidade de aceitar remoto?

**Comment by gabrielrcouto** [comment]
@clmadrazo totalmente, mostrando que é responsável e organizado para trabalhar remotamente, a gente se ajeita 😄

**Comment by rafael-franca** [comment]
Ainda está aberto?

**Comment by williamespindola** [comment]
Sim @rafael-franca

**Comment by ravanscafi** [comment]
Olá @gabrielrcouto,
A vaga ainda está aberta?

_(sou administrador das vagas e estou fechando as que já foram preenchidas)_

**Comment by ravanscafi** [comment]
_(fechado por falta de resposta)_
