### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) PHP Full Stack na Fred

### ISSUE THREAD

**Issue by alfredbaudisch** [phpdevbr/vagas#114]
## Descrição da vaga

Desenvolvedores Full Stack, com foco em PHP, para trabalhar na criação de dezenas de aplicações e produtos na plataforma Fred!

As aplicações são compostas dos seguintes componentes:

- API RESTful pública
- API Administrativa
- Painel Administrativo

## Local

São Paulo, na nossa sede na Av. Paulista.

## Benefícios

- Horário flexível
- Remoto negociável
- Cursos e livros

## Requisitos

**Obrigatórios:**

- Experiência comprovada no desenvolvimento de RESTful APIs e painéis administrativos/SPAs.
- Longa experiência backend e arquitetura de sistemas
- Facilidade de interpretar e criar documentações e especificações
- Experiência em modelagem de dados
- Experiência com painéis administrativos
- Inglês (documentações e especificações em inglês)
- PHP, REST, PostgreSQL, Redis, MySQL
- Git
- JavaScript, CSS, SASS, jQuery e qualquer framework.

**Desejáveis:**

- Desenvolvimento customizado em cima da WordPress WP REST API e Admin API
- Customização WooCommerce via API
- React

## Contratação

PJ a combinar

## Nossa empresa

Fred é um ecossistema self service com múltiplas plataformas para criação e deployment de chatbots. Nosso core é desenvolvido em Elixir e nossas APIs para setores específicos em PHP e Node.js.

## Como se candidatar

Para se candidatar, para mais informações sobre a vaga e sobre a startup, por favor envie um email para vagas@fredbots.com com seu CV anexado - enviar no assunto: Desenvolvedor PHP Full Stack.

**Comment by clmadrazo** [comment]
Remoto 100%?

**Comment by ravanscafi** [comment]
Olá @alfredbaudisch,
A vaga ainda está aberta?

_(sou administrador das vagas e estou fechando as que já foram preenchidas)_

**Comment by ravanscafi** [comment]
_(fechado por falta de resposta)_
