### ISSUE TITLE
[Brasil] PHP Developer na OSF Digital

### ISSUE THREAD

**Issue by talitasaldanha** [phpdevbr/vagas#1142]
## Descrição da vaga

Projeto em PHP para nosso departamento DCOS.

## Local

Remoto.

## Benefícios

- Cartão flash alimentação/refeição - 1.300 por mês; Bônus educação - 150 por mês; Curso de inglês (1h - até 2x por semana) gratuito; Bônus de certificações na área de atuação pago em dólar canadense; Incentivo por entrega de projetos pago em dólar canadense; Bônus de indicação de candidatos (De 3% a 5% do salário anual - Pago em dólar canadense); Bônus de performance; Plano de carreira com avaliações de desempenho; Plano odontológico bradesco (Gratuito para funcionários); Plano de saúde top bradesco apartamento (Gratuito para funcionários e dependentes); Seguro de vida e viagem bradesco; Gympass; Empréstimo consignando; Horário flexível - 40 hrs semanais.

## Requisitos

**Obrigatórios:**
- Desenvolvimento e implementação de aplicativos web práticos;
- Experiência anterior na implementação de APIs de terceiros;
- Fortes habilidades de depuração / diagnóstico e analítica;
- Forte conhecimento de POO;
- Conhecimento em PHP e MySQL;
- Conhecimento em frameworks PHP é um diferencial;
- Conhecimento de provedores de serviços em nuvem e Web Services é um diferencial;
- Bom inglês é obrigatório.

## Contratação

CLT.

## Nossa empresa

Empresa global sólida, com mais de 19 anos de mercado;
Uma das empresas líderes em comércio global e transformação de nuvem digital;
Presença global REAL (clientes na América do Norte, América Latina, Europa e APAC);
Grandes chances de crescimento, através de um efetivo plano de carreira.

## Como se candidatar

Por favor envie um e-mail, com pretensão salarial, para hr@osf.digital com seu CV anexado - enviar no assunto: Vaga PHP Developer.

### Contratação:
- CLT.

### Experiência
- Pleno;
- Sênior;
- Consultor.

**Comment by BAD-WOLF** [comment]
# Vaga PHP Developer.
[BAD-WOLF (Matheus Vieira ) · GitHub.pdf](https://github.com/phpdevbr/vagas/files/9079352/BAD-WOLF.Matheus.Vieira.GitHub.pdf)
