### ISSUE TITLE
[Remoto] PHP Developer PL na WKJobHub

### ISSUE THREAD

**Issue by DanielleEstrazulas** [phpdevbr/vagas#1156]
`Skills`

- Desenvolvedor Pleno PHP
- Experiência em JavaScript, HTML e CSS
- Conhecimento em banco de dados SQL Server e MySQL
- Conhecimento e experiência em WordPress (temas e plugins)
- Conhecimento e experiência com Java será considerado diferencial

`Atividades`

- Desenvolver aplicações em PHP
- Desenvolver integrações, plugins e temas no WordPress
- Realizar manutenção e melhorias em aplicações existentes

`Contratação`
PJ

`Atuação`
Remota

`Empresa`
Startup do ramo de tecnologia, voltada à saúde.Sua missão é fazer as pessoas viverem mais. E a tecnologia não é o fim, mas o meio para fazer tal propósito acontecer.

`Como se candidatar`

Pelo link [https://bit.ly/3QABX93](url)

_**OU**_ 

Envie email para danielle.estrazulas@wkrh.com.br, com seu CV atualizado anexado - enviar no assunto: Vaga PHP GitHub

**Comment by eduardo92005-debug** [comment]
Ainda está disponível e aceita desenvolvedor junior?
