### ISSUE TITLE
[São Paulo/SP] Senior Software Engineer na Bovcontrol

### ISSUE THREAD

**Issue by FernandaAbreu** [phpdevbr/vagas#116]
## Descrição da vaga

O time de desenvolvimento da BovControl está procurando desenvolvedores apaixonados por desafios exponenciais.

Somos uma startup global que vem conectando todas as vacas e fazendas do planeta numa 'nuvem diferente' (antes do modismo do blockchain) - com o objetivo de erradicar a fome no mundo, empoderando produtores rurais com tecnologia para serem mais eficientes e sustentáveis.

Nossas soluções combinam coleta e a análise de dados, para toda a cadeia produtiva.

Os dados são coletados no campo por aplicativos móveis e podem ser analisados por vários meios, por diferentes elos da cadeia (varejo, bancos, processadores de leite, etc).

Alimentar 1 bilhão de pessoas por dia, em 10 anos de existência da empresa, é a nossa meta.

## Formação e Conhecimento:

-Formação em Ciências da Computação, Engenharia da Computação e afins;

-Sólidos conhecimentos em programação orientada a objetos, padrões de projeto e engenharia de software;

-Conhecimentos em PHP, laravel, node.js, react, firebase, elasticsearch, MySQL, mongoDB, Redis e Git;

-Conhecimento em Mining, PoS e Paxos;

-Conhecimento em criptografia, incluindo criptografia assimétrica hash functions, encryption / signatures;

-Conhecimentos em infraestrutura de servidores Windows e Linux;

-Inglês avançado;

-Pro atividade;

-Gosto por desenvolver pessoas [tecnicamente];

## Experiências:

-Mais de 6 anos de experiência em programação

-Ter trabalhado com ferramentas de build e automação;

-Ter trabalhado anteriormente com P2P Networking e sistemas distribuidos;

-Experiência em construir aplicações com as seguintes linguagens: PHP, Python, C, C++, C#, golang, Rust, Scala, Haskell, Erlang ou Clojure;

-Desejável ter experiência com Nginx;

-Experiência com Testes Funcionais;

-Experiência com gestão de equipes;

-Experiência com Teste A /B é desejável;

## Responsabilidades:

-Participar de todas as etapas do aplicativo, com foco no desenvolvimento e solução de problemas;

-Escrever códigos limpos e funcionais para aplicações web;

-Utilizar linguagens de marcação como HTML para criar páginas amigáveis;

-Manter e aperfeiçoar sites;

-Solução de problemas de aplicações;

-Realizar testes unitários para aumentar a performance;

-Utilizar novas tecnologias para melhorar as aplicações antigas;

-Definir e atender os requerimentos técnicos e de design das aplicações;

-Construir código que seja reutilizável e bibliotecas para uso futuro;

-Acompanhar novas tecnologias;

-Experiência em algum dos cloud providers Azure, AWS ou Google Cloud;

-Conseguir aprender novas ferramentas de trabalho de forma rápida e por conta própria;

-Opinar em decisões de arquitetura (sistemas) dos produtos;

-Utilizar boas práticas de segurança durante no desenvolvimento;

-Como BovER você desfrutará de:

-Ambiente descontraído e global;

-Contato com escritórios da empresa no Vale do Silício, Boston e São Paulo;

-Tecnologia de ponta e disruptiva;

-Ambiente de startup;

-Code Review;

-Meetups internos e externos sobre tecnologias usadas na empresa.

Venha ajudar a alimentar 1 bilhão de pessoas por dia!

Let's rock!

Let's #mooo!!

##Contratação
Regime: CLT

## Como se candidatar

Por favor acesse a página [https://bovcontrolcareers.squarespace.com](https://bovcontrolcareers.squarespace.com)

**Comment by rscafi** [comment]
@FernandaAbreu qual o regime de contratação? e a alocação? e para qual cidade é a vaga?

**Comment by FernandaAbreu** [comment]
Oi Ravan , é para São Paulo.E o regime é CLT.
