### ISSUE TITLE
[Sao Paulo/SP] Estagio Front-End Developer na BovControl 

### ISSUE THREAD

**Issue by BovControlRH** [phpdevbr/vagas#119]
O time de desenvolvimento da BovControl está procurando um programador apaixonado por desafios envolvendo programação. Nós somos uma empresa inovadora que cria mudanças na conexão entre o mundo agrícola e a tecnologia de ponta. Em outras palavras, ajudamos o agricultor a gerenciar melhor seus rebanhos diretamente da ponta dos dedos.

Nossa solução combina a coleta de dados e a análise de dados. Os dados são coletados usando o aplicativo BovControl, que está disponível em todos os dispositivos Android e os dados podem ser analisados através de um dashboard que pode ser acessado a partir de qualquer computador ou dispositivo com a Internet. Buscamos alcançar todos os criadores de gado do planeta e aumentar a eficiência e a produtividade. Combater a fome global através deste método motiva muito nossa equipe.

## O que é esperado desse novo Bover

- Cursando formação em Ciências da Computação, Engenharia da Computação e afins;
- Ter trabalhado com alguma linguagem de programação orientada a objetos

## Desejáveis:

- Node.JS
- React ou outro SPA
- Firebase
- Elasticsearch
- MongoDB
- Git

## Como um BovER desfrutará de:

- Ambiente descontraído
- Tecnologia de Ponta
- Macbook Pro para você desenvolver
- Ambiente de startup
- Code Review para te ajudar a evoluir
- Meetups internos sobre tecnologias usadas na empresa

## Como se candidatar:

Acesse o link a seguir: [https://jobs.bovcontrol.com/mern-intern](https://jobs.bovcontrol.com/mern-intern )

**Comment by rscafi** [comment]
Olá, este repositório é somente para vagas PHP.
Para vagas frontend, utilize o frontendbr/vagas
