### ISSUE TITLE
[São Paulo] Analista Desenvolvedor Web(Junior/Pleno)

### ISSUE THREAD

**Issue by markgerald** [phpdevbr/vagas#12]
## Descrição da vaga

Projeto de reestruturação de aplicação de comparativos de preços, e novo MarketPlace.
## Local

Região da Higienópolis, próximo metrô Santa Cecília. (Av. Angélica)
## Requisitos

**Obrigatórios:**
- Bons conhecimentos na linguagem PHP e Banco de dados MySQL
- Bom Conhecimento em orientação a objetos.
- Conhecer algum framework de mercado: Symfony, Laravel ou Zend
- Conhecimento básico em AngularJS

**Desejáveis:**
- Bom conhecimento do framework Symfony
- Conhecimento de desenvolvimento de Api REST
- Bom conhecimento de AngularJS
- Noções de Cache(Redis) e Elasticsearch.
## Contratação

PJ
## Nossa empresa

A missão do [pagpouco.com](http://www.pagpouco.com) é aumentar o poder de compra do consumidor.

Divulgamos milhares de preços em supermercados, e comparamos todos eles na nossa plataforma, idealizada para os nossos usuários terem uma experiência extremamente útil, intuitiva e gratuita.

Através do pagpouco.com, é possível adicionar produtos à lista e descobrir quais supermercados têm as melhores ofertas para realizar as compras. Também é possível cadastrar alertas de preços: sempre que um estabelecimento atingir o valor que o usuário quer pagar, a plataforma o avisa imediatamente.

Além das ferramentas disponíveis, somos também uma comunidade multicanal onde os usuários escolhem qual conteúdo desejam ver, quais supermercados e marcas querem seguir e quais notificações preferem receber.

Quem segue o PagPouco.com tem garantia de economizar tempo e dinheiro.
## Como se candidatar

Por favor envie um email para contato@pagpouco.com com seu CV anexado e link do Linkedin no corpo do Email - enviar no assunto: Vaga PHP

**Comment by ftonato** [comment]
@markgerald alocado ou remoto?

**Comment by markgerald** [comment]
@ftonato alocado

**Comment by palma200** [comment]
Faixa salarial ?

**Comment by markgerald** [comment]
@palma200 a faixa salarial é de acordo com o perfil de mercado, e com analise da entrevista. Caso haja interesse, envie seu currículo já com a pretensão salarial.

**Comment by markgerald** [comment]
Vaga preenchida!
