### ISSUE TITLE
[Berlim/Alemanha] Senior Software Engineer na Campsy

### ISSUE THREAD

**Issue by nawarian** [phpdevbr/vagas#120]
## Descrição da vaga

Procuramos por um desenvolvedor sênior com domínio na linguagem PHP para atuar principalmente com:

- Um legado escrito em PHP 5.6 + Phalcon
- Outro legado escrito em PHP 5.3 + ZF 1
- Outro legado escrito em PHP 5.6 escrito a mão
- Futuros legados, porque é o tipo de empresa que a gente compra hahahah
- Modernização de aplicações legadas 
- Integrações entre plataformas distribuídas
- Planejamento e arquitetura de novas aplicações
- Migração dos nossos monolitos para uma estrutura escalável tanto tecnicamente quanto na perspectiva de negócio

## Local

Área central de Berlim, Alemanha.

## Benefícios

- Auxílio com aulas de Alemão do básico ao intermediário dentro da empresa
- Snacks saudáveis e cereais (infinitos)
- Sucos e refrigerantes não tão saudáveis assim, mas também infinitos
- Ambiente compartilhado com Ventures da Rocket Internet (networking a todo tempo)
- Troca de conhecimento constante entre o time e entre times da Rocket Internet
- Mesa de pebolim e área de lounge
- Pizza e Cerveja todas as sextas-feiras
- Playstation e Xbox no décimo terceiro andar, onde podemos também infernizar o time de mobile da Rocket ;)
- A equipe é 100% internacional: composta pro Brasileiros, Alemães, Chineses, Italianos, Franceses... é simplesmente incrível conhecer tanto de cada cultura num mesmo ambiente
- Custo de alocação inicial (processo de visto + 15 dias de hotel) por conta da empresa

## Requisitos

**Obrigatórios:**
- Inglês fluente: aceitamos sotaque e sempre tem um brasileiro por perto pra te ajudar a lembrar como falar "couve-flor" ou "repolho" em inglês, mas estar confortável com comunicação 100% em inglês a nível técnico e de business é essencial!
- Estar confortável com PHP, REST, SOAP e integrações em geral
- Saber alinhar-se com os objetivos de negócio e tomar a postura de defensor do mesmo

** Toque de parceiro sobre o inglês: **
Por favor, tenha certeza de que se sente confortável com a linguagem. Viver em outro país pode significar abrir mão completamente da sua lingua materna: imagine-se pedindo socorro, precisando fazer uma consulta médica ou alugando um apartamento. Antes de pensar na responsabilidade do escritório, pense como consegue ser responsável por si mesmo e, talvez, sua família.

**Desejáveis:**
- Phalcon versão 2
- Jenkins
- Amazon infra
- Vue JS (não precisa programar, mas só entender já é ótimo)
- SCRUM e metodologias em geral

## Contratação

Formal: você passa a ser um empregado padrão Berlinense, com contrato de trabalho.

## Nossa empresa

Dá uma olhadinha aqui: https://campsy.bamboohr.co.uk/jobs/view.php?id=1

Vale citar também que trata-se de uma equipe distribuída: parte do time está em Berlim (Alemanha) e a outra em Saint Malo (França). A vaga é para Berlim, esteja atento nisso.

## Como se candidatar

No mesmo link: https://campsy.bamboohr.co.uk/jobs/view.php?id=1

Sintam-se livre para saber através do `nickolas@phpsp.org.br`, vou tentar responder o quanto antes.
E sem síndrome do impostor ein, galera. Vamo botá pra fudê aqui em Berlim que aqui é HueBR!

**Comment by claudiomelo** [comment]
Hello I really liked it, I have send my resumé last week!!!

**Comment by andrezap** [comment]
Que massa! To tentando há um tempo me realocar pra Alemanha, enviei meu CV.

**Comment by nawarian** [comment]
Aberta. Só mandar CV.

**Comment by ravanscafi** [comment]
Olá @nawarian ,
A vaga ainda está aberta?

_(sou administrador das vagas e estou fechando as que já foram preenchidas)_

**Comment by nawarian** [comment]
Boa @ravanscafi. Desculpe por não atualizar. A vaga não está mais disponível. Vou fechar essa daqui.
