### ISSUE TITLE
[São Paulo/SP] Dev. Pleno Fullstack na Affinibox 

### ISSUE THREAD

**Issue by emanuellarini** [phpdevbr/vagas#121]
## Descrição da vaga

Temos um sistema multi tenant simplificado e atualmente, estamos reescrevendo-o do zero.
Atualmente utilizamos React e React Native para frontend (sim, fazemos apps!) e backend (API) em Laravel 5.5.
Gostaríamos de um Dev Pleno Fullstack, com experiência maior em Backend que, caso não tenha conhecimentos sólidos em React, se disponha a aprender para ajudar a dar manutenções no frontend Web. 

## Local

Escritório, São Paulo - Entre a Rua Oscar Freire e a Rua Haddock Lobo.
Relativamente perto da Paulista, bastante perto da estação em construção Oscar Freire.

## Benefícios

- Vale Alimentação + Vale Refeição
- Vale Transporte
- Plano de Saúde (Omint)
- Horário flexível

## Requisitos

-  Orientação a Objeto, Clean Code, Design Patterns 
-  PHP (usamos Laravel 5.5 =DD)
-  MySQL (fazemos queries somente via Eloquent, ainda assim tem que saber modelar)
- AWS 
- ReactJS
- Inglês Avançado

**Desejáveis:**
- Docker (por enquanto utilizamos em dev)
- Inglês Fluente

## Contratação

Pleno
Somente CLT
Vaga 100% presencial

## Nossa empresa

A Affinibox é uma plataforma de gestão de clubes de benefícios. Oferecemos uma solução whitelabel para associações e empresas que queiram disponibilizar benefícios a seus colaboradores de forma mensurável e prática. Parte do nosso trabalho é prospectar novas parcerias e temos alguns grandes nomes.
A composição da empresa é bastante enxuta. A gestão é bastante horizontalizada e as decisões são bastante rápidas. Qualquer um no time realmente tem influência em como o produto se desenvolve e como os problemas dos nossos clientes são resolvidos.

## Como se candidatar

Por favor envie um email para emanuel.meli@affinibox.com.br com seu linkedIn e GitHub com o assunto “[Vaga Fullstack]”

**Comment by ravanscafi** [comment]
Olá @emanuellarini ,
A vaga ainda está aberta?

_(sou administrador das vagas e estou fechando as que já foram preenchidas)_

**Comment by emanuellarini** [comment]
Pode fechar sim, desculpe ter esquecido de avisar aqui.

Abraço
