### ISSUE TITLE
[Hibrido - Alphaville/ SP] Pessoa Desenvolvedora PHP Fullstack - Pleno @Mollica IT

### ISSUE THREAD

**Issue by raissaime** [phpdevbr/vagas#1217]
## Descrição da vaga
A Mollica IT está em busca de profissionais inovadores e criativos, que tenham paixão em crescer, evoluir e aprender.
Estes profissionais serão enviados para o cliente empregador. 

**Qual será sua missão?**

- Atuar com PHP, atualizando o software;
- Cuidar do SGA (Sistema de Gestão de Acesso);
- Terá a missão de migrar a versão do PHP de 5.0 para 8.0.

## Requisitos

**Obrigatórios:**
- Experiência com PHP (versões 5.0 e 8.0);
- Experiência em desenvolvimento utilizando HTML, CSS, Javascript (jQuery);
- Experiência com banco de dados MySQL;
- Framework Laravel;
- Necessário conhecimentos em e-commerce;
- Git

## Local

Híbrido - 2x presencial em Alphaville / SP.

## Benefícios

✔️ Assistência Médica;
✔️ Assistência Odontológica;
✔️ Seguro de Vida;
✔️ Vale Refeição R$ 35,00/dia;
✔️ Vale Alimentação R$ 515,00/mês;
✔️ Auxílio Combustível de R$ 390,00/mês ou Vale Transporte.

## Contratação

CLT;

## Nossa empresa

Com peças exclusivas que vão ao encontro das exigências da mulher moderna, a empresa é hoje uma das maiores redes de bijuterias e acessórios do Brasil. São mais de 300 operações em shoppings e ruas comerciais no Brasil e Estados Unidos. Eclético e fiel, o público é composto por mulheres de todas as faixas etárias.

Revolucionou o conceito de varejo de bijuterias ao lançar peças com aparência de joia e com alta qualidade para as consumidoras que não abrem mão da beleza clássica e do acabamento impecável. Todas as semanas chegam novidades às lojas, criadas por um grande time de designers e fornecedores escolhidos com muito critério. Tudo isso é possível graças às pesquisas realizadas pela empresa, no Brasil e exterior, e pelo apoio de consultorias de moda.

## Como se candidatar

Por favor envie um email para raissaime@outlook.com com seu CV anexado - enviar no assunto: Vaga PHP @Mollica IT 

### Alocação:
- Flexível (Remoto parcial)

### Contratação:
- CLT

### Experiência
- Pleno
- Sênior

**Comment by sabinomachado** [comment]
Ainda aceita candidatura ? :)

**Comment by raissaime** [comment]
@sabinomachado , a vaga foi fechada.
