### ISSUE TITLE
[Franca/SP] Desenvolvedor(a) Full Stack PHP na MazzaFC

### ISSUE THREAD

**Issue by brunoti** [phpdevbr/vagas#122]
## Descrição da vaga

Desenvolvedor Full Stack PHP (Laravel) pra trabalhar em sistemas diversos, api's e sustação, de diversos clientes.

**estamos buscando devs com níveis >= pleno**

## Local

Remoto ou no escritório no centro de Franca. Prefirimos que o desenvolvedor esteja alocado em Franca, mas, se valer a pena, é negociável.

## Benefícios

- Horário flexível

## Requisitos

**Obrigatórios:**
- PHP 
- Laravel
- MySQL
- HTML, CSS, Javascript
- Git

**Diferenciais:**
- Projetos open source
- Conhecimentos gerais de Oracle
- React Native (seria ótimo)
- C# (seria ótimo)
- Portfólio 

## Contratação

PJ ou CLT a combinar. Damos preferência a PJ.

## Nossa empresa

[http://www.mazzafc.tech]()

A MazzaFC é uma empresa completa especializada em outsourcing de sistemas e profissionais de TI, provedora também de outras soluções em TI para empresas dos mais variados segmentos.
Atendemos por completo as necessidades das empresas das regiões de Franca, Ribeirão Preto,  Campinas, São Paulo, possibilitando que alcancem metas e objetivos pré definidos. Afinal, nossa missão a partir de agora também é transformar oportunidades em sucesso, impulsionando o potencial de cada profissional através da precisão em identificar talentos.
Para atingir tal objetivo, continuamos valorizando o capital humano, nosso time de profissionais especializados e apaixonados por TI, além é claro, do respeito aos ideais de cada cliente.

## Como se candidatar

Por favor envie um email para bruno.oliveira@mazzafc.tech e lais.bernardes@mazzafc.tech com seu CV anexado. 

**Utilizar assunto "[VAGA PHP GITHUB] Seu Nome". Ex.: [VAGA PHP GITHUB] Bruno Oliveira**

![vaga_fc](https://user-images.githubusercontent.com/6011421/34896417-f06bdaa8-f7d0-11e7-965d-de69aec8084e.png)

**Comment by zabaala** [comment]
@brunoti,

O e-mail lais.bernardes@mazza.fc parece estar errado. Não seria lais.bernardes@mazzafc.tech?

**Comment by brunoti** [comment]
@zabaala sim! Corrigido. Obrigado 😄
