### ISSUE TITLE
[REMOTO] PHP Developer PLENO

### ISSUE THREAD

**Issue by alcpntrbr** [phpdevbr/vagas#1224]
## Descrição da vaga

Construir software em uma empresa que diariamente captura e transforma um grande volume de dados em informação e conhecimento para advogados de todo o Brasil.

**Suas principais atividades serão:**

- Realizar reuniões com clientes parar entender as necessidades de negócio;
- Propor soluções de acordo com as regras de negócio estabelecidas pelo cliente;
- Manutenção e melhoria nos sistemas legados da área;
- Documentação.

## Local

Remoto (Matriz em Porto Alegre/RS)

## Requisitos

**Obrigatórios:**

- Cursando Ciência da Computação, Sistemas de Informação ou Análise e Desenvolvimento de Sistemas.
- Experiência em programação PHP orientada a objetos, com banco de dados PostgreSQL;
- Domínio de ferramentas de controle de versão de software (GIT);
- Pacote Office avançado;
- Redação clara e objetiva;

**Diferenciais:**
- Será um diferencial se você possuir experiência com Kanbam, Soluções ETL, NoSQL.

## Contratação

PJ

## Nossa empresa

**OLÁ, SOMOS A ZALLPY! 🚀**
Imagine uma empresa focada em reunir talentos para acelerar a transformação digital do mundo em que vivemos.

 Muito prazer, somos a Zallpy!

**Somos especialistas em tecnologia**

Desenvolvemos soluções digitais customizadas, com tecnologia de ponta e de alto impacto. Somos parceiros estratégicos de grandes empresas internacionais, entregando inovação e inteligência a multinacionais de diversos segmentos. A gente atua como uma extensão do cliente, com alto grau de envolvimento no negócio e na geração de resultados.

**Estamos em todos os lugares**

Seja no remoto ou presencial nossa cultura de trabalho é leve, colaborativa e integrada, inspirando a troca de experiências e a criatividade.

Atuamos em diferentes modelos, com flexibilidade e agilidade para compor os times conforme a demanda, oferecendo o perfil e expertise técnico mais adequado para cada desafio.

**Acreditamos na diversidade**

Na Zallpy acreditamos na diversidade, na equidade e na inclusão, e investimos para que nosso espaço de trabalho seja um local de crescimento profissional e pessoal para todos. Em 2021, criamos nossa comunidade de Diversidade, Equidade e Inclusão com o objetivo de realizar uma série de ações e debates sobre as questões de gênero, raça, pessoas com deficiência e LGBTQIAP+.

**Vem ser Zallpy!**

Mais do que uma empresa que gera empregos, a Zallpy é uma criadora de oportunidades, descobrindo e formando talentos para o mercado que mais cresce no mundo.

 **Vem fazer carreira na Zallpy!**

## Como se candidatar

Por favor envie um e-mail para alice.ribeiro@zallpy.com com seu CV anexado - enviar no assunto: Vaga PHP

### Alocação:
- Remoto

### Contratação:
- PJ

### Experiência
- Pleno

**Comment by BrenoSantanaBruno** [comment]
[Breno+Santana+Bruno+-+English+Resume.pdf](https://github.com/phpdevbr/vagas/files/11902089/Breno%2BSantana%2BBruno%2B-%2BEnglish%2BResume.pdf)
