### ISSUE TITLE
PHP Developer Laravel na GRASK

### ISSUE THREAD

**Issue by xrogix** [phpdevbr/vagas#1226]
## Descrição da vaga

A [Grask](http://grask.com.br/) está buscando um PHP Developer para compor seu time de desenvolvimento. Sua principal atribuição será desenvolver novas features.

## Local

Remoto

#### Diferenciais

- Horário flexível

## Requisitos

**Obrigatórios:**
- 1 ano PHP 5+
- 1 ano experiêcia Laravel
- 1 ano experiêcia Mysql

**Desejáveis:**
- conhecimentos em Livewire

## Contratação

PJ a combinar

## Nossa empresa

Grask é um projeto novo, estamos no estágio inicial e estamos procurando pessoas apaixonas por código.

## Como se candidatar

Por favor envie um email para contato@grask.com.br com seu CV anexado - enviar no assunto: Vaga PHP Laravel

### Alocação:
- Flexível (Remoto parcial)

### Contratação:
- PJ

### Experiência
- Júnior
- Pleno

**Comment by sabinomachado** [comment]
LiveWire S2!
