### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) Back-end PHP na Mastertest

### ISSUE THREAD

**Issue by Chiquetti** [phpdevbr/vagas#123]
## A MASTERTEST está procurando um(a) Desenvolvedor(a) Back-end Ninja para integrar nosso time. Você trabalhara diretamente com a equipe de desenvolvimento e criação da empresa.

- Documentação do sistema já existente 
- Sugestões de melhorias e otimização de sistema 
- Proatividade para resolução de problemas 
- Espírito de equipe 
- Ter facilidade de comunicação com pessoas não técnicas

## Local (Exclusiva presencial) 
Mastertest, São Paulo - Rua James Watt, 142 - sala 111 - Brooklyn 

## Benefícios
- 1 hora de almoço
- Segunda a Sexta das 09:00 às 18:00 

## Requisitos
**Obrigatórios:**
- Conhecimento avançado em php
- Ter conhecimento avançado em back-end
- Ter conhecimentos de front-end (html5, css, javascript)
- Banco de dados sql server
- Mysql
- Windows / iis
- Linux / apache

**Desejáveis:**
- Noções de ui/ux
- Ter trabalhado no desenvolvimento de sistemas web
- Inglês técnico
- Experiência com integração com CRM e outros sistemas de automação
- Experiência com integração com ERP e outros sistemas de gestão
- Experiência com integração com API 
- Experiência com integração com Webservices

**Diferenciais:**
- Conhecimento em metodologia Scrum 
- Conhecimento avançado em Back-end 
- Ter implementado sistema ERP e CRM 

## Contratação
- PJ 
- R$ 5.000,00

## Como se candidatar
Por favor envie um email para victor@mastertest.com.br com seu CV anexado - enviar no assunto: Vaga PHP

**Comment by giovannicruz97** [comment]
Existe a possibilidade de remoto ?

**Comment by Chiquetti** [comment]
Não, conforme informado: Local (Exclusiva presencial) - São Paulo.

**Comment by ravanscafi** [comment]
Olá @Chiquetti ,
A vaga ainda está aberta?

_(sou administrador das vagas e estou fechando as que já foram preenchidas)_

**Comment by ravanscafi** [comment]
_(fechado por falta de resposta)_
