### ISSUE TITLE
[Sorocaba/SP] Programador(a) PHP Pleno na Squid Fácil

### ISSUE THREAD

**Issue by lhpalacio** [phpdevbr/vagas#124]
## Descrição da vaga

A Squid Fácil procura desenvolvedores PHP com experiência para desenvolvimento de novas ferramentas em nosso sistema.
## Local

Remoto ou Escritório, Sorocaba/SP

## Benefícios

- Vale-transporte
- Vale-refeição
- Descontos para compra de produtos

## Requisitos

**Obrigatórios:**
- Experiência com PHP 5.6/7
- Experiência com Zend Framework 2/3
- Experiência com REST, JWT e OAUTH
- Experiência com Vanilla JS
- Experiência com testes de unidade
- Conhecimento dos design patterns básicos (ex: Abstract Factory, Factory Method, Adapter, Decorator, Proxy, Facade, etc.)
- Conhecimento sobre o (PHP-FIG) e suas recomendações (PSRs)

**Desejáveis:**
- Experiência em Zend Expressive
- Experiência com Docker e Vagrant
- Experiência em bancos de dados NoSQL
- Conhecimento sobre TDD, DDD e Microsserviços
- Conhecimento sobre Cloud Computing (IaaS, PaaS e SaaS)

## Contratação

Indiferente

## Nossa empresa

Squid Fácil é uma start-up B2B que conecta a industria ao varejo, permitindo que lojistas virtuais trabalhem sem a necessidade de estoque físico de produtos. 

Somos a primeira distribuidora completamente online que permite ao varejista virtual competir em nível de igualdade com os grandes e-commerce do mercado. Nós fornecemos produtos de 30 fabricantes no atacado sem a necessidade de pedido mínimo e com entrega direta ao consumidor final, trazendo agilidade e redução de custos na cadeia e suprimentos.

Com crescimento superior a 900% nos últimos 3 anos, a Squid Fácil foi vencedora dos prêmios Inovativa Brasil e Start-up Brasil, sendo também acelerada pela ACE. Somos uma empresa jovem, dinâmica, focada em resultados, por isto buscamos pessoas com idéias inovadoras, com gás competitivo e espírito de tubarão para crescer junto conosco.

Se você tem este perfil, venha conosco.

## Como se candidatar

Para se candidatar envie seu currículo no email luiz.palacio@squidfacil.com.br

**Comment by Piulres** [comment]
Enviado

**Comment by ravanscafi** [comment]
Olá @lhpalacio ,
A vaga ainda está aberta?

_(sou administrador das vagas e estou fechando as que já foram preenchidas)_

**Comment by lhpalacio** [comment]
@ravanscafi Vaga encerrada.
