### ISSUE TITLE
[Remoto/Híbrido] Fullstack Developer (Laravel/PHP/Vue) - Pleno/Sênior @ Mollica IT

### ISSUE THREAD

**Issue by raissaime** [phpdevbr/vagas#1258]
## Descrição da vaga
Buscando projetos internacionais?

Então vem com a Mollica IT e encontre a oportunidade certa pra dar match!

Estamos em busca de profissionais inovadores e criativos, que tenham paixão em crescer, evoluir e  aprender.

**Qual será a sua missão:**

- Desenvolver código eficiente e de alto desempenho;
- Trabalhar em POCs, pequenos projetos de desenvolvimento/melhoria;
- Desenvolver componentes frontend e backend;
- Integrar elementos voltados para o usuário aos aplicativos;
- Projetar e inovar tecnologias e soluções para alocação eficaz de recursos, implantação automatizada de aplicativos, atualizações e manutenção com tempo de inatividade zero;
- Colaborar dentro da estrutura Agile para desenvolvimento e entrega de software;
- Trabalhar com outras equipes para entender o escopo e projetar soluções eficientes;
- Melhorar a funcionalidade dos sistemas existentes;
- Auxiliar nas atividades de planejamento e execução de liberação/implantação;
- Fornecer documentação conforme necessário e participar de revisões de código, sessões de planejamento e levantamentos de status de rotina;
- Fornecer estimativas (nível de esforço, tempo e recomendações) para priorização de recursos;
- Transmitir de forma eficaz todo o progresso das tarefas, avaliações, sugestões, cronogramas, juntamente com questões técnicas e de processo;
- Criar aplicativos inovadores e de última geração e colabore com a equipe de Experiência do Usuário (UX);
- Demais rotinas.

## Requisitos

**Obrigatórios:**

- Experiência em desenvolvimento Laravel;
- Experiência com PHP, Vue, Javascript, HTML5, CSS3;
- Profundo conhecimento de PHP orientado a objetos e framework Laravel 7;
- Experiência com VueX Store, Vue Router e Provide/Inject;
- Experiência em escrever Javascript moderno (ES6/ES2015, ES2017, Typescript, etc);
- Experiência na otimização de códigos existentes para desempenho e escalabilidade;
- Forte compreensão de frameworks MVC;
- Solucionador de problemas criativo e eficiente;
- Experiência em realizar migrações de dados complexas;
- Experiência em considerações de segurança de aplicações web;
- Experiência prática com design de esquema SQL, princípios SOLID, design de API REST;
- Habilidades em ferramentas de versionamento de código, como Git;
- Experiência avançada em Laravel (middleware, coleções, políticas, solicitações, recursos e contêineres de serviço);
- Experiência com AWS;
- Obrigatório Ensino superior completo;

🌎**Idioma:**

**Inglês Avançado para conversação (Haverá etapa de entrevista no idioma).**

## Local

Você poderá escolher as seguintes opções:

São Paulo, SP - Atuação em modelo Home Office e/ou híbrido 
Londrina, PR - Atuação em modelo Home Office e/ou híbrido 
Home Office - Aceitamos Pessoas Candidatas de todo o Brasil!

## Benefícios
✔️Assistência Médica para colaboradores e dependentes com abrangência nacional da Bradesco ou Unimed

✔️Assistência Odontológica com abrangência nacional

✔️Vale Refeição ou Vale Alimentação (a escolha do colaborador)

✔️Auxílio creche

✔️Seguro de Vida para associados e dependentes

✔️Gympass para associados e dependentes

✔️EAP (Employee Assistance Program) com os seguintes serviços: Assistência Financeira, Assistência Jurídica, Assistência Social, Assistência Psicológica (24 horas – 7 dias por semana).

✔️Descontos e tarifas diferenciadas junto a Universidades (Mackenzie, SENAC, FIA, FIAP e BBS Business School) e escola de idiomas (CNA, Cultura Inglesa, Wizard, CCAA, Indeed).

✔️Descontos em pacotes de tarifas e taxas diferenciadas para Bancos Itaú e Bradesco

✔️Opção de crédito consignado, com desconto diretamente no salário do colaborador

✔️Programa de reembolso de algumas certificações externas

✔️Treinamento: A TCS oferece plataforma de treinamento e desenvolvimento a distância e presencias, em soft skills, tecnologias e domínios em mais de 15.000 temas.

✔️Premiação por tempo de casa: A TCS premia associados por seu comprometimento e lealdade durante o período em que trabalhar na empresa (3, 5 e 10 anos e cada 5 anos posteriormente).

✔️Prêmio de indicação de novos colaboradores - recebendo um bônus para cada nova contratação.

✔️TCS Fit4life - Programa para incentivar a prática de exercício físico junto a seus associados, com agenda de treinamentos funcionais online.

✔️Experiência internacional: Dependendo de seus conhecimentos e das demandas do negócio você pode se candidatar a vagas no exterior (dentro e fora da América Latina).

✔️Entre outros;

## Contratação

CLT

## Nossa empresa

O que nós fazemos? Como líderes globais em serviços de TI, soluções digitais e negócios, fazemos parcerias com clientes para simplificar, fortalecer e transformar, ajudando clientes a criar o futuro!

Somos uma das 5 principais empresas de tecnologia na Top 100 do mundo da Forbes, o maior grupo multinacional de negócios da Índia, com instalações de fabricação em mais de 40 países com presença operacional em 180 países. Suas operações são apoiadas por uma pilha de mais de 80 aplicativos SAP e mais de 1900 Aplicativos não SAP.

Oferecemos perspectiva de crescimento, e oportunidade de aprendizado e certificações. Desejamos construir a próxima geração de sistemas e fábricas que envolvem as mais recentes Tecnologias e migrando para a Nuvem nos próximos 2 anos. Possuímos desenvolvimento Agile, Devops e oportunidades em 60 países.

A TCS combina experiência em tecnologia e inteligência de negócios para catalisar mudanças e entregar resultados.

## Como se candidatar

https://jobs.quickin.io/mollicait/jobs/65b17b876e07af0013b01b97

### Alocação:
- Presencial
- Flexível (Remoto parcial)

### Contratação:
- CLT

### Experiência
- Pleno
- Sênior

**Comment by TilsonM17** [comment]
Ainda disponivel? se ainda estiver, tem possibilidade de ser contrato PJ?
