### ISSUE TITLE
Desenvolvedor Front-End Pleno

### ISSUE THREAD

**Issue by radenberger** [phpdevbr/vagas#126]
## Descrição da vaga

Vaga para Desenvolver novas funcionalidades e manutenção. 

## Local

Presencial, São Paulo - Itaim Bibi

## Benefícios

- Vale Alimentação
- Vale Transporte ou Estacionamento
- Bicicletário
- Acesso a Investimentos com redução de determinadas taxas
- Smart Hour: Espécie de Happy Hour para discutir os projetos e expor temas da empresa, em uma conversa aberta, com salgadinhos e cerveja
- Academia

## Requisitos

**Obrigatórios:**
- Experiência com Javascript
- Experiência com React, Redux ou Angular JS
- Experiência com API Rest
- Experiência com PHP/Wordpress

**Diferenciais:**
- Conhecimento de NodeJS
- Conhecimento de UX

## Contratação

CLT Full

## Nossa empresa

Somos especializados na identificação de Talentos para as áreas de TI / Telecom como também para as áreas operacionais e administrativas.

## Como se candidatar

Por favor envie um email para felipe.radenberger@psmcompany.com.br e seu CV anexado com pretensão salarial - enviar no assunto: Vaga Front-End

**Comment by rscafi** [comment]
Esse repositório é somente para vagas PHP.
Para vagas de frontend, utilizar o frontendbr/vagas.

**Comment by carloshskp** [comment]
Obrigatório PHP, na verdade a vaga é pra full stack

**Comment by deyvisonrocha** [comment]
Acho que o ideal seria alteração da issues. @carloshskp
