### ISSUE TITLE
[remoto Brasil] Developer FullStack at Thoughtworks

### ISSUE THREAD

**Issue by IsadoraMarques07** [phpdevbr/vagas#1267]
## Local

Remoto- necessário residir dentro do território brasileiro

## Benefícios
(https://www.thoughtworks.com/pt-br/careers/benefits)

## Requisitos

**Obrigatórios:**
Experiência em PHP com Laravel e Livewire. 
Experiência com frameworks de desenvolvimento web (por exemplo, React, Angular, Vue.js) 
Experiência com frameworks do lado do servidor (por exemplo, Laravel, Django, Flask, FastAPI, Express.js).  
Experiência com construção e implementação de APIs RESTful
Experiência no desenvolvimento de interfaces responsivas utilizando frameworks HTML, CSS e JavaScript 
Experiência com diferentes tipos de bases de dados (por exemplo, MySQL, PostgreSQL, AWS RDS, Google Spanner, MongoDB, CouchDB, Redis, Neo4J) 
Conhecimentos sólidos de git e CI/CD com Jenkins ou GitHub.  
Conhecimento sobre a implantação de Docker e Kubernetes. 
Inglês avançado para conversação

## Contratação

CLT - pagamento em real

## Nossa empresa

A Thoughtworks é uma consultoria global de tecnologia que integra estratégia, design e engenharia de software para alavancar a inovação digital. Há mais de 30 anos, nossas clientes confiam em nossos times autonômos para criar soluções que vão além do óbvio. 

## Como se candidatar

Se aplique aqui https://www.thoughtworks.com/pt-br/careers/jobs/5832524

### Alocação:
- Remoto

### Contratação:
- CLT

### Experiência
- Sênior
- Lead

**Comment by ejklock** [comment]
Olá, o link está dando pra outra vaga

Analista de Infraestrutura de TI Júnior (posição temporária)
