### ISSUE TITLE
[Remoto] Desenvolvedor Laravel na SOIRTEC

### ISSUE THREAD

**Issue by marciojustino** [phpdevbr/vagas#127]
## Descrição da vaga

Atuará em diversos projetos da empresa como backend laravel.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- Laravel
- PHP
- Banco de dados (MySQL / Postgres)
- Git

**Desejáveis:**
- TDD

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para marciojustino@gmail.com com seu CV anexado - enviar no assunto: Vaga Laravel

**Comment by andersao** [comment]
CV enviado!

**Comment by marcelosousa46** [comment]
CV enviado!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>


Marcelo Sousa
(85) 98502-3111

2018-01-22 13:10 GMT-03:00 Anderson Andrade <notifications@github.com>:

**Comment by carloshskp** [comment]
CV Enviado
