### ISSUE TITLE
[Remoto] Junior PHP  - WordPress Developer @ WorkDay INTERNATIONAL USD

### ISSUE THREAD

**Issue by henryzybs** [phpdevbr/vagas#1276]
## Descrição da vaga

Estamos buscando um talentoso Desenvolvedor Júnior PHP com experiência em WordPress para se juntar à nossa equipe de desenvolvimento. O candidato ideal será apaixonado por programação, terá habilidades sólidas em PHP e uma compreensão profunda da plataforma WordPress. Esta posição oferece a oportunidade de crescer e desenvolver suas habilidades em um ambiente colaborativo e dinâmico.

## Local

Remoto 

## Benefícios

- Aulas de Inglês
- Auxilio estudo
.

## Requisitos
**NÃO É REQUISITO A FALA EM INGLÊS APENAS A ESCRITA NO MOMENTO.**
Experiência prática com desenvolvimento web utilizando PHP, HTML, CSS e JavaScript.
Conhecimento sólido de WordPress, incluindo temas, plugins e funcionalidades principais.
Capacidade de trabalhar de forma independente e em equipe, gerenciar prazos e prioridades.
Excelentes habilidades de comunicação verbal e escrita.

**Obrigatórios:**
- 1 anos de experiência com PHP 5+

**Desejáveis:**
- conhecimentos em Laravel

**Diferenciais:**
- Conhecimento sólido de WordPress, incluindo temas, plugins e funcionalidades principais.

## Contratação

A combinar

## Nossa empresa

Workday é uma plataforma de software de gestão empresarial na nuvem que oferece uma ampla gama de soluções para gerenciamento de recursos humanos, finanças, planejamento e análise. É projetado para empresas de todos os tamanhos, desde pequenas empresas até grandes corporações, e visa simplificar e otimizar processos de negócios complexos.

## Como se candidatar

Por favor envie um mensagem no Whatsapp wa.me/5548996356187
Aos cuidados de Fernando da BCI Consultoria

### Alocação:
- Remoto

### Contratação:
- CLT
- PJ
- Freelance
- Estágio
- Outros (especificar)

### Experiência
- Estágio
- Júnior

**Comment by lauf8** [comment]
https://github.com/lauf8

**Comment by Raphael-Assis** [comment]
[DOC-20240503-WA0000. (1).pdf](https://github.com/phpdevbr/vagas/files/15239869/DOC-20240503-WA0000.1.pdf)

**Comment by Raphael-Assis** [comment]
[DOC-20240503-WA0000. (1).pdf](https://github.com/phpdevbr/vagas/files/15239874/DOC-20240503-WA0000.1.pdf)

**Comment by teixeira-alexandre** [comment]
É golpe. Cuidado.

**Comment by silviooosilva** [comment]
> É golpe. Cuidado.

Tem como explicar melhor?

**Comment by teixeira-alexandre** [comment]
> > É golpe. Cuidado.
> 
> Tem como explicar melhor?

Claro! Qual tipo de empresa recebe aplicações por WhatsApp, instantaneamente marca entrevista técnica POR ESCRITO e pela plataforma Signals (que tem reputação por ser usada em golpes por ter a funcionalidade de apagar mensagens)? Dica: nenhuma.
Detalhe, conta do GitHub criada dia 05 de maio de 2024, séries de posts exatamente iguais nos repositórios de outras stacks, todas voltadas para Juniors, mudando apenas a stack.
Detalhe2, a empresa Workday é GIGANTE, tem perfil no LinkedIn e não possui nenhuma vaga condizente com a issue, e para piorar, só estão contratando em regime híbrido, pode pesquisar por conta própria no LinkedIn.

**Comment by teixeira-alexandre** [comment]
O cara está fechando as issues kkkkkkkk
