### ISSUE TITLE
[São Paulo/SP] Programador(a) PHP Pleno meeta.com.br

### ISSUE THREAD

**Issue by wsilva** [phpdevbr/vagas#130]
## Descrição da vaga

Empresa jovem, busca profissionais proativos, dinâmicos e com vontade de  fazer parte de um time vencedor.

Atuar na análise de novas demandas e projetos solicitados pelas áreas de negócio. Responder pelo desenvolvimento de projetos internos, entendendo as necessidades das áreas e aplicando os conhecimentos em análise, programação PHP orientada à objeto e banco de dados.

## Local

Moema - São Paulo/SP

## Horário
9:00 às 18:00hs

## Requisitos

**Obrigatórios:** 
 - MVC (avançado)
 - Lógica de programação (avançado)
 - Orientação a objeto (avançado)
 - Javascript (avançado)
 - Jquery (avançado)
 - Jquery  UI (intermediário)
 - Bootstrap ou semantic-ui (intermediário)
 - CSS e CSS3 (intermediário)
 - HTML e HTML5 (intermediário)
 - Apache ou Wamp (intermediário)
 - PHP (avançado)
 - SQL Server (avançado)
 - Git (básico) 

**Desejáveis:**
 - Netbeans (ou semelhante)
 - Notepad++
 - Pacote office
 - Windows e Linux
 - Redes

## Contratação

CLT ou PJ 

## Como se candidatar

Por favor envie um email para cgarcia@meeta.com.br com seu CV anexado

**Comment by vinyguedess** [comment]
Aceita remoto

**Comment by wsilva** [comment]
Não tenho certeza, só repassei, vou confirmar.
