### ISSUE TITLE
[Santa Barbara D'Oeste/SP] Backend PHP Developer na Acruxx

### ISSUE THREAD

**Issue by santoja** [phpdevbr/vagas#131]
**Descrição da vaga**
Criar APIs com PHP e GraphQl;
Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;
Participar do processo criativo e auxiliar na construção dos sistemas;

**Local**
Remoto ou Escritório, Santa Barbara D'Oeste/SP

**Benefícios**
VA
Reembolso de viagens caso seja remoto e venha para a empresa esporadicamente.
No caso de home office, ou caso o profissional deseje trabalhar com seu próprio equipamento, há um reembolso mensal pelo uso.

**Diferenciais**
Area de descanso
Frutas no escritório
Café expresso ou coado
Chá
Cachorro no ambiente de trabalho
Troca de experiencias com profissionais de outras equipes

**Requisitos**
**Obrigatórios:**

Experiência relevante em PHP OOP
Usar os conceitos SOLID.
Desenvolver utilizando boas praticas de programação

**Desejáveis:**
PHP 7.1 e mais novos
Ter trabalhado com nonSQL
Conhecer os conceitos de GraphQL

**Diferenciais:**
Contratação
CLT presencial ou remoto

Como se candidatar
Por favor envie um email para kaue@acruxx.com.br com seu CV anexado - enviar no assunto: Vaga PHP

**Comment by santoja** [comment]
Olá, alguém poderia adicionar que a vaga é remota?

**Comment by ravanscafi** [comment]
@santoja alocação em aberto signfica tanto presencial quanto remoto
