### ISSUE TITLE
[São Paulo/SP] Programador(a) PHP Pleno/Sênior na Avec  

### ISSUE THREAD

**Issue by salaovip** [phpdevbr/vagas#132]
## Descrição da vaga

A AVEC é uma startup acelerada pela Wayra (Telefonica) e pelo StartupBrasil, hoje nosso time conta com +50 pessoas, entre elas colaboradores, sócios e franqueados, temos um espirito jovem e acreditamos na meritocracia como melhor caminho de crescimento, onde os melhores são destacados e reconhecidos, fazemos avaliações constantes e temos planos de Stock Option.

Entre os nossos produtos estão um sistema de gestão para salões de beleza online (www.salaovip.com.br), aplicativos de agendamento online personalizados como https://goo.gl/yWZjeF e mais recentemente iniciamos o projeto de um MarcketPlace de produtos de beleza. Nossas tecnologias são (PHP, LARAVEL, CODEIGNITER, ANGULAR, REACT, NODE.JS). Para essa vaga procuramos um profissional com foco em back-end Laravel, mas que se arrisque em outras tecnologias.

## Local

Rua Haddock Lobo, 585, 7o Andar - São Paulo/SP

## Benefícios

- Mesa de ping-pong,
- Video games
- Copa com puffs para um cochilo depois do almoço
- VR (R$20,00/dia)
- VT
- Horário Flexível 
- Eventual HomeOffice

## Requisitos

- Experiência com PHP / Laravel

**Desejáveis:**
- Conhecimentos em Angular ou React
- Conhecimentos em Node.js

## Contratação

PJ ou CLT a combinar

## Como se candidatar

Por favor envie um email para victor.sorroche@avecbrasil.com.br com seu CV anexado - enviar no assunto: Vaga PHP

**Comment by giovannicruz97** [comment]
Existe a possibilidade de home-office full-time ?

**Comment by anthmarques** [comment]
Qual seria a pretensão salarial?

**Comment by ravanscafi** [comment]
_(fechado por falta de resposta)_
