### ISSUE TITLE
[Belo Horizonte/MG] PHP Developer na MaxMilhas

### ISSUE THREAD

**Issue by maxmilhas** [phpdevbr/vagas#136]
## Descrição da vaga

Estamos procurando por um(a) Desenvolvedor(a) PHP que seja apaixonado(a) por tecnologia e, claro, tenha vontade de fazer parte de algo grandioso. Na MaxMilhas, já negociamos mais de 6 bilhões de milhas, levamos mais de 300 mil pessoas para viajar e comemoramos o 3º maior NPS (Net Promoter Score) do Brasil. Nosso time de Engenharia conta com pessoas motivadas para entregar um produto de alta qualidade, trabalhando em um ambiente colaborativo e leve <3

## Local

Escritório, Floresta - Belo Horizonte

## Benefícios

- Plano de saúde
- Vale Refeição/Vale Alimentação
- 20000 milhas para curtir suas férias
- Aula de inglês (50%)

#### Diferenciais

- Horário Flexível
- Frigobar sempre cheio :P
- Sala de entretenimento (video-game, violão)

## Requisitos

**Obrigatórios:**
- Domínio de programação orientada a objetos.
- Domínio de PHP 5.6+
- Testes automatizados;
- Experiência em arquiteturas escaláveis;
- Experiência em integração com Webservices, RESTful, JSON;
- Controle de versão com GIT / GIT Flow
- Inglês (leitura e escrita)

**Desejáveis:**
- Conhecimento em Symfony 3+
- Experiência com Web Crawlers
- Processamento assíncrono
- Modelagem de bancos de dados relacionais (preferencialmente MySQL/PostgreSQL)
- Experiência com Docker
- AWS (EC2, S3, SNS e SQS)

**Diferenciais:**
- Experiência com gateways de pagamento
- Forte cultura de testes
- Metodologia Ágil

## No dia a dia, você será responsável por
- Realizar code review de seus pares sempre que necessário;
- Implantação de micro-serviços;
- Auxiliar na implantação de Teste de Código;
- Elaborar a implantação de Integração Contínua;
- Manutenção e evoluções pontuais de código legado

## Contratação

CLT a combinar

## Nossa empresa

Somos uma startup mineira com sede em Belo Horizonte e nascemos de uma inquietação: as pessoas merecem viajar mais. Então, criamos um marketplace capaz de conectar quem deseja (e precisa) comprar passagens econômicas a vendedores de milhas. Assim, desde 2013, contamos grandes histórias.

Logo quando começamos, vencemos o Prêmio InfoStart da Revista INFO Exame. Ainda nesse período, fomos considerados a startup brasileira mais promissora do ano de 2013. Superamos as expectativas e, com crescimento de mais de 15% ao mês desde então, dobramos de tamanho a cada 6 meses. É, o time não para de crescer.

Em 2014, fizemos parte do Programa Startup Brasil e fomos acelerados pela 21212 Digital Accelerator, quando conquistamos reconhecimento nacional como uma das startups de maior crescimento do programa. Ainda nesse período, participamos também dos eventos internacionais, como London Technology Week e DemoDay San Francisco. No ano seguinte, em 2015, marcamos presença no ranking entre as 15 empresas mais inovadoras pela Exame.com.

Pra gente, as grandes conquistas não se limitam aos dados. São as histórias que tornamos realidade todos os dias. As pessoas merecem viajar mais e, com a gente, isso se torna possível.

## Como se candidatar

Acesse a [página da vaga](https://maxmilhas.gupy.io/jobs/4673) e mande seu currículo.

## Labels

- Alocado
- CLT
- Pleno
- Senior

**Comment by ravanscafi** [comment]
_(fechado por falta de resposta)_
