### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) na Leroy Merlin

### ISSUE THREAD

**Issue by ravanscafi** [phpdevbr/vagas#137]
<p align="center">
    <br/>
    <a href="https://www.leroymerlin.com.br" title="Leroy Merlin">
        <img src="https://cdn.leroymerlin.com.br/assets/lizard/images/logo-leroy.svg" alt="Leroy Merlin"/>
    </a>
</p>

## Descrição da vaga
Estamos procurando novos integrantes para nossos times aqui na Leroy Merlin Brasil!

Crescemos de forma ordenada, sendo atualmente responsáveis pelo Site/E-commerce/Plataforma de Vendas das Lojas, além de outros projetos que estão surgindo e que você poderá ajudar a construir :smile:

Priorizamos qualidade e valor de negócio. Adotamos boas práticas de desenvolvimento como TDD, Pair Programming, Code Review, entre outros, nos embasando em Metodologias Ágeis para o sucesso de nossos projetos e equipes. Estamos constantamente nos atualizando e buscando novas tecnologias que façam sentido para os nossos desafios. 

Valorizamos e contribuímos para o _open source_, tendo vários projetos publicados em @leroy-merlin-br.

Nossas stacks são basicamente `PHP 7+` com `Laravel 5+`, `MongoDB`, `Elasticsearch`, `Redis`.
Utilizamos `Docker` e provisionamos nossa infraestrutura na `AWS`, utilizando boas práticas de `IaC`.

## Local

**Presencial**, Chácara Santo Antônio - Zona Sul, São Paulo/SP

## Benefícios

- PPLR e outras bonificações
- Assistência Médica
- Assistência Odontológica
- Vale Refeição
- Vale Transporte
- Cesta Básica
- Seguro de Vida
... entre outros.

## Requisitos

Estamos buscando devs que tenham os seguintes conhecimentos:
- `PHP 7+`
- `OOP`
- Pelo menos um dos frameworks MVC: `Laravel`, `Symfony`, `Rails`, `Zend`
- `Testes automatizados`*

\* Caso você não possua conhecimentos em testes automatizados, haverá oportunidade de demonstrar sua capacidade de aprendizado em nosso teste prático.

## Contratação

CLT - Presencial

## Nossa empresa

A [Leroy Merlin](https://www.leroymerlin.com.br/) é líder em Home Center no Brasil. Somos um dos maiores cases de e-commerce Laravel no Brasil e talvez até no mundo.
Trabalhamos em projetos de transformação digital, atuando como e-commerce para nossos Clientes e plataforma de venda para nossos Assessores das Lojas no Brasil. Além disso, possuímos outros projetos em fase de desenvolvimento.

## Como se candidatar

Ficou interessado? Envie um e-mail para `maaraujo@leroymerlin.com.br` com o assunto _”[Vaga-backend]”_, informando seu GitHub/LinkedIn/Portfólio juntamente com seu CV e bora bater um papo, que explicamos mais e nos conhecemos! :wink:

---
Também estamos com vagas de frontend em aberto, confira em: [Front-End Developer na Leroy Merlin](https://github.com/frontendbr/vagas/issues/809)

**Comment by rscafi** [comment]
### Notas: 
1. Vagas de desenvolvimento são somente para São Paulo/SP, no momento não temos equipes de desenvolvimento em outras cidades onde possuímos lojas.
1. Vagas somente presenciais.
1. Se você já participou do processo seletivo antes, pode se aplicar novamente.

**Comment by ravanscafi** [comment]
Boa tarde pessoal!
Informo que ainda temos vagas :wink:

**Comment by ravanscafi** [comment]
Não, @helderjosex.

**Comment by LucasOliveiraJBQ** [comment]
@ravanscafi tem algum níveis especifico para se candidatar, como por exemplo, Júnior, Pleno ou Sênior?

**Comment by LucasOliveiraJBQ** [comment]
@ravanscafi tem algum nível especifico para se candidatar, como por exemplo, Júnior, Pleno ou Sênior?

**Comment by ravanscafi** [comment]
Não, @LucasOliveiraJBQ. Possuímos mais de uma vaga e avaliamos o candidato como um todo (pessoal + profissional).
