### ISSUE TITLE
[Remoto] Senior PHP Developer na Portabilis

### ISSUE THREAD

**Issue by fernandosjp** [phpdevbr/vagas#138]
![alt text](https://upload.wikimedia.org/wikipedia/commons/1/1d/Ieducar.svg)

## Descrição da vaga

A Portabilis, empresa que hoje lidera a comunidade, está procurando 2-4 desenvolvedores PHP experientes para trabalhar em um sistema de gestão escolar desenvolvido em código aberto chamado i-Educar! O software já está em aproximadamente 100 municípios brasileiros e beneficia 300-400 mil estudantes em escolas públicas! Em 2018, a Portabilis deseja que ele esteja por todo o Brasil! (https://softwarepublico.gov.br/social/i-educar/blog/em-2018-queremos-o-i-educar-por-todo-o-brasil). 

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento Web em PHP usando boas práticas (inclusive uso de frameworks)
- HTML, CSS e JavaScript/jQuery
- Conhecimento de banco de dados e queries SQL (usamos postgreSQL)
- Conhecimento sobre controle de versão (Git, Github, Gitlab)
- Saber trabalhar em ambiente Unix/Linux
- Inglês (proficiência em leitura)
- Experiência com métodos ágeis
- Conhecimento de RESTful APIs
- Experiência com Ajax/JSON
- Conhecimento sobre performance
- Conhecimento sobre testes automatizados (TDD)
- Boa comunicação
- Querer ser uma pessoa melhor todos os dias

**Desejáveis:**
- participação em projetos opensource

## Contratação

PJ a combinar

## Como se candidatar

Inscreva-se na vaga pelo site https://www.portabilis.com.br/site-novo/oportunidades/desenvolvedor-php-senior.

## Labels

- PJ
- Remoto - Total
- Sênior

**Comment by fernandosjp** [comment]
Obrigado @ravanscafi! Vi que vc alterou o titulo. Desculpa, acabou saindo um pouco do padrão mas queria destacar que o projeto é para desenvolvimento de software livre. Acho que é um diferencial da vaga. Existe um label `software-livre`?

**Comment by ravanscafi** [comment]
Sim @fernandosjp , achei importante manter a padronização, mas concordo que software livre é algo ótimo! Acha que a nova label está de acordo?

**Comment by fernandosjp** [comment]
Achei que ficou ótimo @ravanscafi!

**Comment by clmadrazo** [comment]
CV enviado!

**Comment by ValdeiltonFelix** [comment]
Vaga ótima !!

**Comment by joubertredrat** [comment]
Vaga ainda aberta? grato

**Comment by ravanscafi** [comment]
_(fechado por falta de resposta)_
