### ISSUE TITLE
[São Paulo/SP] PHP Developer na 5A Talentos

### ISSUE THREAD

**Issue by gfreitas** [phpdevbr/vagas#139]
## Descrição da vaga
**ATIVIDADES:**
Atuação no desenvolvimento de produtos Web em times ágeis, com auxilio no levantamento de requisitos de negócio e tecnologia.

## Local
Escritórios em São Paulo - (Centro)

## Benefícios
- Não Há.

## Diferenciais
- Horario Flexivel

## Requisitos
**Obrigatórios:**
Conhecimento em PHP e MySQL
Conhecimentos em serviços REST
Conhecimento em orientação a objeto, SOLID e Padrões de Projeto
Familiaridade com frameworks PHP de mercado
Familiaridade com arquitetura voltada a serviços

**Desejáveis:**
Conhecimento em nodejs
Conhecimento em GO
Conhecimento em banco de dados NOSQL
Experiência com metodologias ageis
Experiência com Docker ou outra tecnologia de containers

**Diferenciais:**
- Experiência ou conhecimento em metodologias ágeis (Scrum e Kanban)
- Conhecimentos em segurança da informação

## Contratação
PJ a combinar

## Nossa empresa
A 5A Talentos, atua no mercado de serviços de TI desde 2003 e estamos buscando pessoas com espirito inovador e que amam de tecnologia;

## Como se candidatar
Caso tenha interesse ou conhecidos para indicar, enviar e-mail com cv para g.freitas@5Atalentos.com.br com assunto: "[São Paulo] PHP Developer na 5A TALENTOS"

## Labels
- PJ
- Alocado
- Júnior
- Pleno

**Comment by ravanscafi** [comment]
_(fechado por falta de resposta)_
