### ISSUE TITLE
[Salvador / BA] Desenvolvedor Back-End Estágio

### ISSUE THREAD

**Issue by marcosalberto** [phpdevbr/vagas#14]
## Descrição da vaga

Você gosta de programação e de desenvolvimento de software?  Gosta de novas tecnologias e de desafios? Tem espírito de equipe e é comprometido? Você gostaria de colocar tudo isto em prática numa empresa?

## Local

Escritório, Itaigara - Salvador, BA

## Benefícios

- Ambiente de trabalho descontraído
- Oportunidade de crescimento e contratação
- Trabalhar de bermuda, afinal, é Salvador.

## Requisitos

**Obrigatórios:**
- Conhecimento em lógica de programação.
- Ter conhecimento básico em SQL
- Ter conhecimento básico em HTML e como funciona a Web  
- Capacidade de comunicação, comprometimento e vontade de pôr a mão na massa;
- Capacidade de aprender rapidamente tecnologias emergentes.
- Ter curiosidade para se aprofundar e dominar um CMS.

**Diferenciais:**
- Conhecimento básico em Orientação a Objetos
- Conhecimento básico em PHP
- Conhecimento básico em MySQL
- Conhecimento básico em Javascript
- Conhecimento básico em Wordpress, TYPO3 ou algum outro CMS
- Conhecimento básico em MVC e outros padrões de projeto
- Conhecimento básico em Linux
- Conhecimento básico em GIT
- Conhecimento básico em Inglês Básico

## Contratação

- 6 horas/dia
- Manhã ou Tarde
- R$ 900,00

## Nossa empresa

A Convergence Works, que chamamos de CW, é uma empresa de TI especializada em transformar ideias e projetos de interatividade em negócios reais.

## Como se candidatar

Por favor envie um email para kellyene.coelho@convergenceworks.com.br com seu CV anexado - enviar no assunto: CW - BACK-END - < Nome do Candidato >

**Comment by nic** [comment]
@marcosalberto Vaga preenchida?

**Comment by marcosalberto** [comment]
@nic,

Vaga preenchida, desculpa a falta de resposta.
