### ISSUE TITLE
[São Paulo/SP] PHP Developer na Mobly

### ISSUE THREAD

**Issue by aquilaphp** [phpdevbr/vagas#141]
## Descrição da vaga

Alguém que tenha experiência com várias versões de PHP, sólidos conhecimentos em programação orientada a objetos, experiência com ferramentas de cache(Redis), conhecimento em banco de dados Mysql, experiência com testes unitários e integrados, conhecimento em GIT e Composer.

### O que você vai fazer
Análise e desenvolvimento de novas funcionalidades para a plataforma de e-commerce e backoffice com foco em performance, escalabilidade, segurança e qualidade. Integração de sistemas internos e de parceiros através de webservices REST/SOAP.

## Local

Presencial, Vila Leopoldina -  São Paulo/SP

## Benefícios

- Assistência Médica
- Assistência Odontológica
- Vale Refeição
- Vale Transporte

#### Diferenciais

- Bônus por performance/produtividade
- Home-Office uma vez por semana
- Horário Flexível

## Requisitos

**Obrigatórios:**
- PHP 5.3+
- OOP
- Controle de versão GIT
- Mysql

**Desejáveis:**
- Conhecimento de frameworks MVC: Laravel, Symfony, Zend
- Testes Automatizados
- Vivência em projetos utilizando metodologia ágil (Scrum)

**Diferenciais:**
- Redis
- Elasticsearch

## Contratação

CLT - Presencial

## Nossa empresa

A maior loja online de móveis e decoração do Brasil! 
Aqui, ideias são esperadas e seus resultados te levam além. Venha fazer parte do nosso SUPER TIME!

## Como se candidatar

Envie um e-mail para vempra@mobly.com.br com o assunto ”Vaga - Programador(a) PHP”,  informando seu GitHub, LinkedIn ou Portfólio juntamente com seu CV e pretensão salarial.

## Labels

- CLT
- Presencial
- Júnior
- Pleno
- Sênior

**Comment by aquilaphp** [comment]
A vaga ainda está aberta.

**Comment by ravanscafi** [comment]
_(fechado por falta de resposta)_
