### ISSUE TITLE
[Remoto] Desenvolvedor PHP na Lamego MKT Digital

### ISSUE THREAD

**Issue by LamegoMKTDigital** [phpdevbr/vagas#142]
## Descrição da vaga

A Lamego MKT Digital, abre seu Programa de Contratações de 2018, em busca de profissionais na área de programação que conheçam PHP, Wordpress e servidores linux.

## Local

Remoto - Trabalhe diretamente de casa

#### Diferenciais

- Seja seu próprio chefe

## Requisitos

**Obrigatórios:**
- CNPJ

**Desejáveis:**
- conhecimentos PHP
- conhecimentos HTML 5 e CSS3
- conhecimentos Wordpress
- conhecimentos Woocommerce

**Diferenciais:**
- projetos todo o tempo

## Contratação

PJ - Prestação de Serviços

## Nossa empresa

Empresa de Marketing Digital, que atende o pequeno e médio empresário.

## Como se candidatar

Por favor acesse o link http://mktdigital.com.vc/contratacao/ e preencha os seus dados e as habilidades que você possui.

## Labels

- Freela
- Remoto - Total

**Comment by brunoreisnascimento** [comment]
Vaga preenchida ?

**Comment by LamegoMKTDigital** [comment]
@brunoreisnascimento 
Não a vaga ainda se encontra aberta, por favor acesse o link http://mktdigital.com.vc/contratacao/ e preencha os seus dados e as habilidades que você possui.

**Comment by ravanscafi** [comment]
_(fechado por falta de resposta)_
