### ISSUE TITLE
[Sorocaba/SP] Full Stack PHP Developer na Goomer

### ISSUE THREAD

**Issue by rafalag** [phpdevbr/vagas#143]
## Descrição da vaga

A Goomer é uma start-up de Sorocaba que trabalha com tecnologias de auto atendimento para restaurantes. Temos 3 anos de vida e já ajudamos os restaurantes no atendimento de 6,5 milhões de pedidos. Temos a missão de melhorar a experiência de consumo dos restaurantes do Brasil.

A vaga é para desenvolvedor full stack com foco em PHP (Laravel), programação web (html, css e javascript) e Node.js

## Local

Sorocaba/SP

## Benefícios

- Vale Refeição
- Vale Transporte
- Cursos
- Horário flexível
- Stock Option (participação na empresa)

## Requisitos

**Obrigatórios:**
- PHP
- Javascript
- HTML e CSS

**Desejáveis:**
- Conhecimentos em Laravel
- Conhecimentos de Node.js

**Diferenciais:**
- AngularJS, Ractive.js ou Vue.js

## Contratação

CLT ou PJ (a combinar)

## Como se candidatar

Inscreva-se pelo link: https://goo.gl/forms/wsY6rjZ1re4IVGZY2

**Comment by rafalag** [comment]
@ravanscafi a vaga está aberta, mas estamos migrando mais para javascript. Então a vaga que temos hoje é javascript full stack (com bastante foco em nodejs). Nosso backend hoje usa Laravel, mas já temos serviços em Node. Também estamos reestruturando um pouco a arquitetura. Se quiser conversar, pode falar comigo no linkedin, te adicionei lá.

**Comment by ravanscafi** [comment]
@rafalag, creio que houve uma confusão. sou administrador desse repositório e estou fazendo uma limpeza de vagas antigas.

Como você comentou que está migrando para JS, creio que seja melhor postar a vaga aqui:
https://github.com/frontendbr/vagas
e/ou aqui:
https://github.com/backend-br/vagas
