### ISSUE TITLE
[São Paulo] Desenvolvedor PHP Pleno Senior PJ Presencial

### ISSUE THREAD

**Issue by jbaladao** [phpdevbr/vagas#15]
## Descrição da vaga

Procuramos um desenvolvedor PHP para trabalhar no backend de nosso SaaS para Prestadores de Serviços. Usamos MVC Joomla mas pretendemos migrar para outra solução em breve, então se você gosta de desafios seu lugar é conosco!

## Local

Próximo ao metro Jabaquara, São Paulo - SP (Condomínio Green Work Boulevard)

## Benefícios

- 1 hora de almoço e horário flexível
- café da manhã, bebidas no frigobar
- PS4 liberado com vários jogos para descontrair
- usamos metodologia ágil SCRUM

## Requisitos

**Obrigatórios:**

Dominar algum framework MVC PHP
Conhecimentos avançados em Git
Conhecimentos avançados em banco de dados MySQL
Facilidade para trabalhar em equipe
Disponibilidade para trabalho presencial

**Desejáveis:**

Experiência com APIs RESTful
Noções sobre MVC Joomla
Algum conhecimento em NodeJS e MongoDB
Noções em front, HTML, CSS e JavaScript
TDD, testes unitários e funcionais
Alguma experiência com desenvolvimento ágil (SCRUM)

## Diferenciais

Projetos Open Source
Experiência em startups
Perfil ativo no GitHub e StackOverflow

## Contratação

PJ a combinar.

## Nossa empresa

O SuperAgendador.com é um dos maiores sistemas de gestão para Prestadores de Serviços do Brasil, nossos clientes movimentaram juntos aproximadamente 25 milhões de reais em dezembro de 2016. A empresa já foi acelerada em 2016 no evento InvestorsDay da CampusParty (anjos via Broota) e agora em 2017 recebeu um novo investimento do grupo Bossa Nova (pré-seed).
Estamos naquela fase incrível onde uma pequena startup pode evoluir rapidamente para um empresa com mais de 200 funcionários. Esse é o sonho, se quiser participar dele, venha trabalhar conosco. Vivenciar o nascimento e transformação de uma Startup é incrível e as oportunidades de crescimento e aprendizado são muitas!

## Como se candidatar

Por favor envie um email para jbaladao@superagendador.com com o título "Vaga PHP".

**Comment by upcesar** [comment]
Curriculum enviado. Aguardo contato.

**Comment by nic** [comment]
@jbaladao Vaga preenchida?
