### ISSUE TITLE
[São Paulo/SP] PHP Developer Sênior na Vindi

### ISSUE THREAD

**Issue by lyoncesar** [phpdevbr/vagas#151]
## Descrição da vaga

Estamos ampliando nossa contribuição para a comunidade com projetos open source e procuramos um especialista.

## Local

Escritório, São Paulo - Vila Mariana

## Benefícios

- Plano de saúde
- VR
- VT

## Requisitos

**Obrigatórios:**
- 5 anos de experiência com PHP
- MySQL
- Orientação a objetos
- SOLID

**Desejáveis:**
- Experiência com plataformas open source de e-commerce (Magento, OpenCart e WooCommerce)

**Diferenciais:**
- Participação em projetos open source

## Contratação

CLT a combinar

## Nossa empresa

A Vindi é uma startup brasileira que presta serviços em pagamentos avulsos e assinaturas recorrentes. Fornecemos conexão com adquirentes, subadquirentes e bancos.

Nossa missão é ajudar empreendedores a vender mais: potencializamos recebimentos através de tecnologia inovadora e confiável.

Leia mais sobre a Vindi em:
[Pagamento.Me](https://pagamento.me/vindi-e-referencia-de-pagamento-recorrente-brasil/)
[Conexão Fintech](https://conexaofintech.com.br/fintech/aporte-vindi-setembro-2017/)

## Como se candidatar

De preferencia pelo link da vaga no [hipsters.jobs](https://hipsters.jobs/job/2157/desenvolvedor-s%C3%AAnior-php/), ou envie email para vagas.tecnologia@vindi.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor PHP Sênior.

## Labels

- CLT
- Sênior

**Comment by ravanscafi** [comment]
Vaga linda, recomendo!

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
