### ISSUE TITLE
[Bragança Paulista/SP] PHP Developer Pleno na Quicktech AS

### ISSUE THREAD

**Issue by jameskennerly85** [phpdevbr/vagas#154]
## Descrição da vaga

PHP Developer - PLENO

## Local

Escritório, Bragança Paulista - SP

## Benefícios

- Plano de saúde
- Seguro de vida
- Aulas de Inlgês

#### Diferenciais

- Horas flexíveis
- Banco de horas remuneradas
- Atendemos mercado internacional

## Requisitos

**Obrigatórios:**
Experiência mínima de 4 anos com desenvolvimento em PHP e MySQL.

**Desejáveis:**
- Conhecimentos em Laravel
- Trabalho em equipe
- Metodologia SCRUM

**Diferenciais:**
- Inglês fluente
- Zend Framework
- Node.js
- MongoDB
- Vue.js
- AWS
- Zurb Foundation
- Twitter Bootstrap
- Bulma

## Contratação

PJ a combinar

## Nossa empresa

A [Quicktech AS](http://quicktech.no/) é uma empresa norueguesa que atua no mercado de desenvolvimento de apps e web apps.

## Como se candidatar

Por favor envie um email para recruiting@quicktech.no com seu CV anexado.
Enviar no assunto: PHP Developer - PLENO

## Labels

- Fulltime
- Escritório
- PJ
- Pleno

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
