### ISSUE TITLE
[Remoto] PHP/WordPress Developer na Nova Horda

### ISSUE THREAD

**Issue by alancpazetto** [phpdevbr/vagas#155]
## Descrição da vaga

Atuação em projetos gringos no desenvolvimento e manutenção em sites institucionais, landing pages, portais e lojas virtuais com WordPress e WooCommerce.

Codificação a partir do PSD e com briefing detalhado.

## Local

Remoto ou alocado no escritório ou se preferir híbrido (Dias em casa e se quiser alguns dias no escritório com a galera). Escritório em Jundiaí - SP

## Benefícios

- Flexibilidade no horário
- Homeoffice

## Requisitos

**Obrigatórios:**
- HTML e CSS pleno
- PHP com conhecimento em WordPress
- Inglês para leitura de briefing e escrita de reports

**Desejáveis:**
- Desenvolvimento de plugins

**Diferenciais:**
- Conhecimento em WooCommerce
- Conhecimento do theme starter Roots Sage 8 ou 9
- Participação em projetos open sources
- Clean Code

## Contratação

- Freela PF
- PJ

## Nossa empresa

A NHRD é uma agência full service (desde o offline ao online) que atua no mercado imobiliário e food, entregando soluções inovadoras que geram resultados para todos os seus clientes.

## Como se candidatar

Por favor envie um email para alan@novahorda.com com seu CV / Portfólio anexado - enviar no assunto: Vaga PHP WordPress.

## Labels

- Freela
- Júnior
- PJ
- Pleno
- Remoto - Parcial
- Remoto - Total

**Comment by guilhermeoa07** [comment]
Entrevista via Skype?

**Comment by mvnp** [comment]
Disponível para trabalhos remotos. Experiência em PHP e muita lógica na veia. Sou adminsitrador de Programadores Incríveis no facebook (https://www.facebook.com/groups/programadoresincriveis). Abraço

**Comment by rodineicosta** [comment]
Vaga ainda disponível, para Freela?

**Comment by alancpazetto** [comment]
Fala galera! 
A vaga foi preenchida.
Agradecemos todos os currículos enviados, alguns já encaminhei para outros amigos que estavam precisando também, se pintar mais alguma coisa post o aqui.

=)
