### ISSUE TITLE
[Porto Alegre/RS] Desenvolvedor(a) PHP Sênior pela Holden RH

### ISSUE THREAD

**Issue by jokapoa** [phpdevbr/vagas#156]
**Descrição da vaga**

Estamos selecionando para empresa de tecnologia em Porto Alegre -RS

**Local**

Presencial - Porto Alegre -RS
## Faixa salarial
Entre R$ 5mil e 7mil CLT ( dependendo da senioridade)

**Benefícios**

- Plano de saúde
- Seguro de vida
- Vale refeição

 **Requisitos Obrigatórios:**
- 3 anos de experiência com PHP 5+
- experiencia com framework PHP ( Laravel /Zend ou Codigniter)
- Solidos conhecimentos   em arquitetura e padrões de desenvolvimento
- Experiência com deploy em AWS ou Azure

 Contratação
CLT

** Como se candidatar**
Envie curriculo para  jonask@holdenrh.com.br

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
