### ISSUE TITLE
[São Paulo/SP] Programador(a) PHP na EasyforPay

### ISSUE THREAD

**Issue by EasyforPay** [phpdevbr/vagas#157]
## Descrição da vaga

Programador(a) PHP em empresa de pagamentos / ticketeria em São Paulo

## Local

Escritório, São Paulo - Moema

#### Diferenciais

- Exposição em grandes clientes
- Rotina de trabalho com uso de SCRUM
- Possibliade de crescimento

## Requisitos

**Obrigatórios:**
- Experiência com PHP
- Conhecimento em bancos de dados

**Desejáveis:**
- Já ter trabalhado com empresas de pagamento ou análogas
- Conehcimento em JavaScript

**Diferenciais:**
- projetos opensource

## Contratação

A combinar

## Nossa empresa

A EasyforPay trabalha com projetos estruturados que envolvam pagamentos, ou seja, focamos em resolver todas as questões de vendas de grandes clientes incluindo pagamento, controle de acesso, vendas 'in loco' entre outros. Temos um ambiente desafiador e grandes oportundiades de crescimento.

## Como se candidatar

Por favor envie um email para admin@easyforpay.com.br com seu CV anexado - enviar no assunto: Vaga PHP

## Labels

- Alocado
- CLT
- Freela
- Júnior
- PJ
- Pleno
- Sênior

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
