### ISSUE TITLE
[São Paulo/SP] PHP Developer na Bitshopp

### ISSUE THREAD

**Issue by phixies** [phpdevbr/vagas#158]
## Descrição da vaga
Estamos criando o primeiro marketplace de produtos baseado em criptomoedas e precisamos de um dev PHP visionário, preferencialmente de São paulo para trabalhar com nosso CTO no backend do projeto, com possibilidade de participação (%) no projeto.

## Local

O trabalho será executado de forma Remota, mas iremos disponibilizar também uma posição em nosso escritório para quando você quiser tomar um ar. 
( Por isso damos preferência por profissionais de são paulo pois eventualmente podemos realizar reuniões em nossa sede localizada na Rua da consolação prox. ao metrô Higienópolis)

## Benefícios

Caso o contratado venha a fazer parte da equipe fixa, ofereceremos.
- Plano de saúde
- Auxilio transporte
- Plano odontológico

#### Diferenciais

- Somos uma empresa que detesta burocracia
- Trabalhamos de forma inovadora
- Gostamos de explorar novas tecnologias

## Requisitos

**Obrigatórios:**
- Ser foda em PHP (Usamos a versão 7)
- Manjar de MySQL
- Saber usar o GIT

**Desejáveis:**
- NodeJS
- SSH
- Linux
- Experiência em ecommerce

**Diferenciais:**
- MongoDB
- Javascript
- Angular
- Conhecer criptos e tecnologias Blockchain
- Experiência em marketplaces

## Contratação

A combinar

## Nossa empresa

Acreditamos que podemos criar coisas legais e boas para tornar nossa sociedade melhor para todas as pessoas e não apenas para alguns. Por isso acreditamos no potencial das criptomodeas e queremos ajudar a difundir o uso delas através do nosso marketplace.

## Como se candidatar

Por favor envie um email de apresentação para admin@bitshopp.com falando sobre suas skills, experiências e links de referência.

Se der "match" , iremos agendar uma conversa via whatsapp ou telegram.

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
