### ISSUE TITLE
[São Paulo] Dev PHP/Laravel Presencial na Leroy Merlin

### ISSUE THREAD

**Issue by rscafi** [phpdevbr/vagas#16]
## Descrição da vaga
Estamos procurando novos integrantes para nossos times aqui na Leroy Merlin Brasil!

Priorizamos qualidade e valor de negócio. Adotamos TDD, Scrum, XP e fazemos tech talks semanalmente.

Nossa stack é `PHP 7` com `Laravel 5`, `MongoDB`, `Elasticsearch`, `Redis`.
Utilizamos `Docker` para desenvolvimento local e provisionamos nossa infraestrutura na `AWS`.

## Local

Presencial, Zona Sul, São Paulo (o local específico pode variar, já que são várias vagas para vários projetos)

## Benefícios

Depende de diversos fatores, mais detalhes serão esclarecidos após contato inicial

## Requisitos

Estamos buscando devs que tenham os seguintes conhecimentos:
- `PHP 7+`
- `OOP`
- Pelo menos um dos frameworks MVC: `Laravel`, `Symfony`, `Rails`, `Zend`
- `Testes automatizados`*

\* Caso você não possua conhecimentos em testes automatizados, haverá oportunidade de demonstrar sua capacidade de aprendizado em nosso teste prático.

## Contratação

Depende de diversos fatores, mais detalhes serão esclarecidos após contato inicial

## Nossa empresa

A [Leroy Merlin](http://www.leroymerlin.com.br/) é líder em Home Center no Brasil. Somos um dos maiores cases de e-commerce Laravel no Brasil e talvez até no mundo.
Trabalhamos em projetos de transformação digital, atuando como e-commerce para nossos Clientes e construindo a plataforma de venda dentro de nossas Lojas no Brasil.
Temos diversos projetos open-source publicados, podem conferir em @leroy-merlin-br

## Como se candidatar

Ficou interessado? Envie um e-mail para `gguitte@leroymerlin.com.br` com o assunto _”[Vaga-backend]”_, informando seu GitHub/LinkedIn/Portfólio e bora bater um papo! :wink:

**Comment by rscafi** [comment]
Galera, ainda estamos com mais algumas vagas em aberto =D

**Comment by daviaugustos** [comment]
@rscafi É pra inicio imediato? Ou é possível iniciar em janeiro por exemplo? :)

**Comment by hakuno** [comment]
Eita, se fosse no Goiás :laughing:

**Comment by rscafi** [comment]
@daviaugustos, pra quanto antes, melhor! :wink: 
mas como temos mais de uma vaga, manda um email pra gente conversar ;)

**Comment by Dreanmer** [comment]
@rscafi eu mandei meu currículo (25/07) mas nem me confirmaram recebimento, vc pode dar uma olhada? Ou mando de novo? Vlw

**Comment by rscafi** [comment]
Fala @Dreanmer, recebemos sim, tá na fila pra entrar em contato! :wink:

**Comment by NandoKstroNet** [comment]
Só presencial? Abs!

**Comment by rscafi** [comment]
Fala @NandoKstroNet, no momento somente presencial

**Comment by brnbp** [comment]
Mandei email @rscafi

**Comment by wtorres** [comment]
Buenas tardes, me interesa el puesto de developer, pero puedo trabajo remoto. Es posible esa modalidad?

**Comment by rscafi** [comment]
@wtorres, lo siento, pero en el momento sólo tenemos vacantes para trabajo presencial.

**Comment by joaoprado** [comment]
@rscafi Opa, mandei um email :)

**Comment by criarti** [comment]
Enviei email mas não me retornaram... :/

**Comment by leandrogrillo** [comment]
@criarti qual seu e-mail? pra pedir pros caras olharem aqui :)

**Comment by vitorhugoro1** [comment]
@criarti Rolou a mesma coisa comigo

**Comment by rscafi** [comment]
Pessoal, devido ao volume recebido de e-mails (mais de 50) e a forma mais próxima que gostamos de abordar os candidatos, pode levar um tempinho até respondermos, mas vamos responder a todos :wink:

**Comment by Cperbony** [comment]
Há vagas para Ribeirão Preto - interior SP?

**Comment by rscafi** [comment]
@Cperbony vagas de desenvolvimento são somente para a matriz, aqui em São Paulo.

**Comment by Cperbony** [comment]
Obrigado pelo retorno. São Paulo esta fora para mim no momento infelizmente. Abraço

**Comment by paulodealmeida** [comment]
@rscafi acabei de enviar um e-mail me candidatando a vaga. :(

**Comment by rscafi** [comment]
@paulodealmeida fica tranquilo que ainda temos vagas, só vamos reestruturar tudo porque de lá pra cá já evoluímos bastante \o/
