### ISSUE TITLE
[São Paulo/SP] Senior PHP/Wordpress Developer na BRQ

### ISSUE THREAD

**Issue by ReAnne123** [phpdevbr/vagas#160]
Sr PHP/Wordpress Developer
Estamos em busca de um profissional com experiência em: WordPress, PHP e front (HTML e CSS).
Atuará no desenvolvimento de sistemas internos e sites.
Contratação CLT, salário a combinar mais atrativo pacote de benefícios (VR, VA, assistência médica, odontológica, seguro de  vida, entre outros)
Horário comercial.
Local: Faria Lima- Itaim Bibi- SP (vaga presencial).

Nossa empresa
Fundada em 1993, a BRQ é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife, Salvador, Brasília, Natal e Nova Iorque. 

Como se candidatar
Por favor envie um email para ryokota@brq.com com seu CV anexado e pretensão salarial CLT - enviar no assunto: Vaga PHP

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
