### ISSUE TITLE
[Belo Horizonte/MG] FullStack Developer PHP na Sapiens

### ISSUE THREAD

**Issue by sapiensbh** [phpdevbr/vagas#161]
## Descrição da vaga

Participará do desenvolvimento de novos projetos, aplicações web, aplicações mobile, webservices e blockchain.

## Local

Escritório, Belo Horizonte - Santa Efigênia

## Benefícios

- VT e VR

#### Diferenciais

- 1 hora de almoço
- Café e Snacks :P
- Flexibilidade de Horário

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com PHP 5+
- Estar confortável para trabalhar com demandas e datas pré-definidas com metas de produtividade;
- Ser proficiente com as ferramentas ágeis mais comuns;
- Experiência de pelo menos 2 anos com desenvolvimento backend em PHP;
- Ser proficiente com PHP, HTML & CSS;
- Saber o essencial de JavaScript, para por exemplo, lidar com a exibição dos dados advindos do backend através de 'templates engines';
- Ter como pontos fortes, ter plena posse de suas ideias e resolver problemas desafiadores;
- Ter o desejo de trabalhar de forma colaborativa com uma equipe.
- Experiência com Frameworks (Laravel, Angular, React , Vue e etc...)
- Git (Command Line)
- Inglês Técnico para leitura
- Conhecimentos de pré-compiladores de CSS

**Desejáveis:**
- Angular
- React
- Desenvolvimento Mobile
- Inglês Fluente ou Alemão Intermediário

**Diferenciais:**
- Portfólio de Projetos Desenvolvidos

## Contratação

PJ a combinar

## Nossa empresa

Somos a Sapiens, estamos há 09 anos no mercado e esse ano estamos fazendo uma fusão com outras empresas e buscando expansão no mercado nacional e internacional. Aqui você terá possibilidade de trabalhar em diversos projetos no Brasil e no exterior.

## Como se candidatar

Por favor envie um email para rh@sapiensolutions.com.br com seu CV anexado - enviar no assunto: Vaga FullStack PHP

## Labels

- Alocado
- PJ
- Pleno
- Sênior

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
