### ISSUE TITLE
[Toronto/Canada] ETL Developer na Statflo

### ISSUE THREAD

**Issue by kinncj** [phpdevbr/vagas#164]
# [ETL Developer @Statflo.com](https://statflo.com/about-careers.html)
## Job Description:

As a **_Statflo_** team member, you inspire your teammates with ideas for how to continuously learn and improve. You’re like everything we build: Smart and helping to do what matters. You're always trying to automate yourself out of a job, so you can move on to a new challenge and greater things. You lead by example, bring positivity to work and leave your ego at home. You collaborate and cooperate with everyone to move us closer to our goals every day. You believe in the Statflo mission and values and act in alignment with them.

As an _ETL Engineer_, you always leave data in better condition than you found it. You enthusiastically strive to gather, prepare, manipulate, produce and publish valuable and meaningful data. You aim for focus and expertise, but you'd never say: "That's not in my job description." when you're the best person to help.

## You will be successful in this role if you:
- Are a well-rounded data engineer with 3+ years of industry experience. We need someone who can pair with software engineers and strategize our large scale data quality, processing, management and automation
- Have experience with ETL design, development and processing in PDI (Pentaho)
- Have excellent knowledge of database design, SQL, and data warehousing
- Have experience with reports and dashboards and other analytical tool design, creation, and maintenance
- Have problem solving and critical thinking and communication skills within the company Have a mastery of relational databases.
- Bonus points for R, Java, Spring Cloud Data Flow, Kafka streams, AMQP, etc.
- Can develop guidelines and standards for cataloging and maintaining data repositories

If you have all the skills stated above and feel like working for one of Canada's best work places, apply at https://statflo.bamboohr.com/jobs/view.php?id=11

PS: This is not a PHP position, but it's an amazing international opportunity.

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
