### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) PHP na Radar Profissional

### ISSUE THREAD

**Issue by RADARProfissional** [phpdevbr/vagas#169]
## Descrição da vaga

Desenvolvimento PHP

## Local

Morumbi - SP

## Benefícios

Contratação PJ

## Requisitos

**Obrigatórios:**
•	Superior completo;
•	Conhecimento sólido em PHP e em desenvolvimento de produtos com orientação a objetos;
•	Experiência com MySQL, SQL Server, PostGreSQL e com CSS2 / CSS3;
•	Conhecimento sólido Jquery/ Jquery UI / twitter bootstrap / JSON e experiência com Framework (Symfony, Zend, CodeIgniter);

**Desejáveis:**
- conhecimentos em Laravel

**Diferenciais:**
- experiência Symfony, ‘deploy’ (Capistrano, phing) e alguma ferramenta de testes (unitário, integrado).

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para recrutamento@radarprofissional.com.br com seu CV anexado - enviar no assunto: Vaga PHP

## Labels

- Alocado
- PJ
- Pleno
- Senior
- PHP
- Radar Profissional

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:

**Comment by RADARProfissional** [comment]
A vaga está aberta! 

 



 

Esta mensagem pode conter informações confidenciais e/ou privilegiadas. Se você não for o destinatário ou a pessoa autorizada a recebê-la, não pode usar, copiar ou divulgar as informações nela contidas ou tomar qualquer ação baseada nelas. Se você recebeu esta mensagem por engano, por favor, avise imediatamente o remetente, e em seguida, apague-a. Comunicações pela Internet não podem ser garantidas quanto à segurança ou inexistência de erros ou de vírus. O remetente, por esta razão, não aceita responsabilidade por qualquer erro ou omissão no contexto da mensagem decorrente da transmissão via Internet. "ECONOMIZE PAPEL - PENSE ANTES DE IMPRIMIR!"

 

De: Ravan Scafi <notifications@github.com> 
Enviada em: sexta-feira, 1 de fevereiro de 2019 14:35
Para: phpdevbr/vagas <vagas@noreply.github.com>
Cc: RADAR Profissional - Consultoria de Recrutamento & Seleção <cristiane@radarprofissional.com.br>; Author <author@noreply.github.com>
Assunto: Re: [phpdevbr/vagas] [São Paulo/SP] Desenvolvedor(a) PHP na Radar Profissional (#169)

 

favor repostar caso ainda esteja em aberto 😉
