### ISSUE TITLE
[São Paulo] Dev PHP7/Phalcon presencial na AMARO

### ISSUE THREAD

**Issue by bobbythiele** [phpdevbr/vagas#17]
## Description

AMARO is an online women's fashion brand based in São Paulo. We monthly launch new collections with the latest international trends at disruptive prices, delivered speedily and in style. Through technology, vertical integration and omni-channel distribution, AMARO is changing the way Brazilians consume fashion. www.amaro.com

AMARO is looking for a talented Back-end Software Engineer to assist in the development and administration of our state-of-art technology platform and infrastructure. The ideal candidate has a profound passion for computer science and for solving complex real world analytical problems.

This is a highly analytical role that requires a driven, self-reliant and generalist hacker.

## Location
Our office is located in the Água Branca region of São Paulo, close to Marginal Tietê.

## Responsibilities
- Develop software in the logic and data tiers of our e-commerce platform, using a PHP7 MVC Framework
- Develop systems integrations via REST APIs using JSON
- Develop and fine-tune batch jobs with sophisticated algorithms (recommendations, business intelligence metrics, popularity scores, email reminders, etc)
- Monitor and fine-tune our platform for performance

## Requirements
- BSc degree in computer science, computer engineering, software engineering, mathematics or related courses
- 3+ years of professional or academic experience in software development
- Knowledge in software engineering best practices and trends
- Full-stack knowledge of modern web technologies
- Experience with back-end MVC frameworks
- Advanced level of English a plus

## Personality
- Highly analytical and focused
- Passion for technology, e-commerce and startups
- Entrepreneurial, driven and proactive
- Excellent technical communication skills

## Our values
At AMARO we believe creativity and technology are limitless, allowing us to innovate beyond linearity. We seek fearless entrepreneurs who are hungry to change the status quo. We are not fixers but enjoy to collaboratively build from the ground up. We only engage where we foresee long-term scalability. We like to take smart risks and always opt for action over 100% certainty. There has never been a more exciting time than today and we are enthusiastic about the future we are creating.

## How to apply
Please apply here:
https://jobs.lever.co/amaro/e2a29f87-0d3a-49bd-8588-a3a4ff4d3ee8

**Comment by nic** [comment]
@bobbythiele Vaga preenchida?
