### ISSUE TITLE
[São Paulo/SP] Programador(a) PHP Fullstack no Fotop

### ISSUE THREAD

**Issue by azizvc** [phpdevbr/vagas#171]
## Descrição da vaga

Programador PHP Fullstack para atuar diretamente no desenvolvimento e manutenção de nossa plataforma.

## Local

Escritório, São Paulo - Perdizes prox. a PUC-SP

## Benefícios
- Salário: a combinar (enviar pretensão)
- Regime: CLT
- Período: Integral (9h00 às 18h00)
- Vale Refeição
- Vale Transporte
 
#### Diferenciais

- Ambiente startup 
- Máquina de café liberada
- Frutas frescas todos os dias.

## Requisitos

**Obrigatórios:**
- Linguagem PHP com Orientação a Objetos
- Conhecimento de arquitetura MVC
- Banco de dados MySQL
- HTML, CSS,  Bootstrap e Javascript com JQuery
- Conhecimentos básicos de Linux

**Desejáveis:**
- conhecimentos em Zend Framework
- GIT

## Contratação

CLT

## Nossa empresa

Empresa nacional em uma missão global para se tornar a melhor(e mais humilde) plataforma para fotógrafos de eventos. Somos a empresa de fotografia oficial do Rally Dakar, Rally dos Sertões e da Arena Corinthians.

## Como se candidatar

Por favor envie um email para tecnologia@fotop.com.br com seu CV anexado - enviar no assunto: Vaga PHP

## Labels

- Alocado
- CLT
- Experiência em aberto

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
