### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) PHP Laravel Backend Sênior na D2P

### ISSUE THREAD

**Issue by SergioSCF** [phpdevbr/vagas#173]
## Detalhes da Vaga

Localização: **Faria Lima, SP** (potencial mudança para Miami/FL)
Contratação: **PJ**
Remuneração: **R$6.000,00 - R$10.000,00/mês** (a combinar dependendo da experiência)

### Benefícios:

- Férias remuneradas de 30 dias;
- Horário Flexível;
- Bônus extra mensal dependendo das entregas, dedicações e evoluções.

### Responsabilidades da vaga

- Entender e melhorar a arquitetura do sistema; 
- Escalar sistemas; 
- Realizar testes de carga, identificar gargalos e otimizar o desempenho de sistemas;
- Identificar, monitorar e corrigir bugs e exceptions;
- Desenvolver e garantir a qualidade do software;

Experiência em infraestrutura, testes, monitoramento e otimização;

### Experiência Requerida:

- PHP OOP (avançado);
- Boas noções em MVC;
- MySQL (avançado)
- GIT;
- Configuração de NGINX em servidor Linux;
- Laravel;

### Experiência Desejável:

- Php 7.1 (principalmente type hinting);
- Serviços da AWS;
- Integrações de serviços externos (REST)

## Sobre a D2P (Diagnosis to Perform)

Somos ums startup de 2 anos e que estamos lançando em Maio/2018 nossa plataforma global. Viemos de uma empresa consolidada de +25 anos e decidimos simplificar a complexidade da logística no Brasil e no mundo.

## Sobre a Equipe

Somos uma equipe enxuta de 3 desenvolvedores (backend), um CTO e dois diretores de produto. Trabalhamos com metodologia ágil e gostamos de aprender e ensinar diariamente, sempre compartilhando conhecimentos.

Dúvidas? sergio.costa@i-d2p.com.br

## Labels

- PJ
- Sênior
- Presencial

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
