### ISSUE TITLE
[São Paulo/SP] PHP Developer - Backend Senior at Easy Taxi

### ISSUE THREAD

**Issue by gustavo-easytaxi** [phpdevbr/vagas#175]
## **Backend Developer**

The Backend Team keeps everything running under the hood of our mobile applications, from the back office systems operations use, the API used by mobile systems, to systems that pay  drivers and charge companies for multiple countries. You will work directly with the product team helping to define our next steps and implement them.

**Responsibilities:**

Design and iterate on existing systems comprising different language ecosystems such as PHP, Go, Python, Ruby and Elixir.
Manage internal customer expectations through constant and reliable communication, delivering value through small iterations.
MacGyver style troubleshooting for dealing with bugs and unpredictable behaviors of complex systems.
Deploy your own changes and ensure everything continue to work as expected.
Architect the solutions and refactor existing ones to ensure readable and maintainable code. Technical debt is not something special, you keep it under control every day.
Automate repetitive tasks. No one should do work which can be done by machines.

**Qualifications:**

Proficiency with at least one web based, dynamically typed language.
Strong understanding of the web and on Object-Oriented Programming.
Previous experience or equivalent knowledge on maintaining and designing high available systems.
Ability to iterate on ideas quickly, with loose or no directions. Being able to talk with customers to better understand a problem is a plus.
Experience with Open Source software and philosophy, knowing your way on a Unix-like platform is a much appreciated plus.
Care for version controlled artifacts through deep Git understanding - we only do fast-forwards here and love to read those nice chubby commit messages.
Familiar with internationalization and the challenges that come with it.

## Local

Work Adress: Rua Hungria, Jardim Europa - near Faria Lima, SP

## Benefits

At Easy you will find a relaxed, informal and dynamic environment, where everyone has room to contribute to initiatives, no matter your seniority and role - **we are all a single team!** You will have autonomy and flexible hours to develop what you need, we will give you the space for creating and putting in practice good ideas. **We value people who always want more!**

- Full benefits according to Brazilian labor laws: VR + VT
- Health plan, Dental plan and life insurance
- GymPass
- Regular open-source community meetups
 - Community Friendly
- Supervised learning activities to improve professional skills on themes such as TDD, Design Patterns and Refactoring
- A flexible-hour policy: work 8h every day, in any manner you see fit
- Young and relaxed environment, a team full of musicians and Nerf snipers!

## Type of Contract

CLT

## About Easy/What is Easy?

Easy is a pioneer in the urban mobility market and the biggest success case of international expansion by a Latin American digital company. Founded in Brazil in 2011, Easy scaled to 37 countries around the globe, fostering a culture based on constant learning, diversity and entrepreneurship. After the merge with Cabify in 2017, we are part one of the first Ibero-American Unicorn companies. The group has now presence in Latin America and Europe, reinventing the daily transportation of people in around 200 cities.

## About the Tech team/Why is software engineering important for us?

Based on transparency, teamwork, technical excellence and fun, we build client features and scalable architecture to solve urban mobility problems and improve our customers' lives, leveraging the company's business potential. We are based on cross-functional agile teams responsible for all aspects in the product life cycle and have among us some of the most respected members of tech/open-source communities. Our teams work with autonomy on a diversified stack to deliver the solutions to some of the most challenging problems you will find on software development, such as:

High availability systems design and maintenance
Localisation of products to fit specific market culture and needs
Dynamic fleet management
Pricing automatisation

**We organise our work based on best practices of Agile Engineering and DevOps, such as:**

TDD
Continuous Integration
Collective Code Ownership
Infrastructure as Code

## How to apply?

Please send an email to gustavo.veiga@easytaxi.com.br  or through our page in StackOverflow  https://stackoverflow.com/jobs/170146

Do not forget to attach your resume and put in the title of the email - PHP Developer

## Labels

- CLT
- Senior
- PHP
- Go
- Python
- Ruby
- Elixir

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
