### ISSUE TITLE
[Campinas/SP] PHP Developer na Every System

### ISSUE THREAD

**Issue by renanevery** [phpdevbr/vagas#176]
## Descrição da vaga

Desenvolver sistemas de e-commerce utilizando Magento, VTEX  e WordPress. 

## Local

Remoto e Escritório (à combinar), Campinas/SP

## Benefícios

- Plano de saúde
- VR

#### Diferenciais

- horário flexível
- possibilidade de alguns dias da semana trabalhar home office
- frigobar sempre cheio =)

## Requisitos
- Ter trabalhado com construção de E-commerce
- Experiência mínimo de 3 anos
- Experiência com Frameworks (Laravel, Angular, React , Vue e etc...)
- Vontade de crescer
- Ajudar a equipe com inovações

**Desejáveis:**
- conhecimentos em Laravel
- Trabalho em equipe
- Metodologia SCRUM
- Desenvolvimento para Mobile

**Diferenciais:**
- AWS
- PostgreSQL
- MySQL

## Contratação
CLT ou PJ (à combinar)

## Nossa empresa

A Every System é uma empresa especializada em Cloud Computing e Segurança da Informação, relativamente nova, mas com um grande potencial de crescimento, onde você poderá crescer junto. Somos movidos por inovação!

## Como se candidatar

Por favor envie um email para renan@everysystem.com.br com seu CV anexado - enviar no assunto: Vaga PHP - E-Commerce 

## Labels

- Alocado
- CLT
- Freela
- PJ
- Pleno
- Remoto - Parcial

**Comment by moreiraandre** [comment]
@renanevery currículo enviado!

**Comment by renanevery** [comment]
Vaga preenchida!
Obrigado!
