### ISSUE TITLE
[Campinas/SP] Desenvolvedor(a) PHP Pleno na Moot Consulting

### ISSUE THREAD

**Issue by NoemiMolinillo** [phpdevbr/vagas#177]
## Descrição da vaga

Desenvolvimento PHP voltado a sistemas web.

## Local

Escritório em Campinas - SP

## Benefícios

- Plano de saúde
- Plano Odontológico
- Vale Trasporte
- VR

## Requisitos

**Obrigatórios:**
- 4 anos de experiência com PHP
- 4 anos de experiência com Javascript / JQuery, Bootstrap
- 4 anos de experiência com: Banco de Dados MySQL

**Desejáveis:**
Front: HTML5, CSS3, NodeJS,AngularJs 
Serviços AWS (S3, Mobile Hub, Lambda, API Gateway, Dynamo DB, CodeCommit, CodeDeploy, Device Farm, Step Function, SQS, SNS, SES)

## Contratação

CLT

## Nossa empresa

A Moot Consulting traz ao mercado, a experiência de seus colaboradores obtida ao longo dos últimos mais de 20 anos no mercado de tecnologia da informação, atuando em serviços de Consultoria e Outsourcing por meio de seu portfólio de produtos e serviços.

## Como se candidatar

Por favor envie um email para noemi@mootit.com.br com seu CV anexado - enviar no assunto: PHP - CAMPINAS

## Labels

- CLT

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
