### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) PHP Full Stack na Moot Consulting

### ISSUE THREAD

**Issue by NoemiMolinillo** [phpdevbr/vagas#178]
## Descrição da vaga

Desenvolvimento PHP voltado a aplicações. Realização de Deploy em AWS.  

## Local

Escritório, São Paulo - Pinheiros

## Benefícios

- VR de R$ 25,00 | ao dia
-  Pagto INSS
- Plano médico | sem custos
- Bônus semestral de 30% do valor acumulado de salário dos 6 meses.

#### Diferenciais

- Ambiente colaborativo e moderno;
- Equipe extrovertida e leve;
- Novos projetos (não apenas sustenção | manutenções)

## Requisitos

**Obrigatórios:**
- 4 anos de experiência com Back end em PHP.
- 2 anos de experiência com Front end: CSS, HTML, BootStrap 
- 2 anos de experiência com Deploy em AWS - Amazon

 
**Desejáveis:**
- conhecimentos em Laravel
- Conhecimento com Doker (apenas container) 
- Conhecimento com Linux (Ubunto)

**Diferenciais:**
- Bônus semestrais
- regime de contratação sem burocrácias.

## Contratação

Sócio de Serviços - (Associado) 

## Nossa empresa

A Moot Consulting traz ao mercado, uma experiência de longo prazo com os últimos anos no mercado de tecnologia, atuando em serviços de Consultoria e Outsourcing para o seu portfólio de produtos e serviços.

## Como se candidatar

Por favor envie um email para noemi@mootit.com.br com o seu CV anexado - enviar no assunto: VAGA de PHP.

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
