### ISSUE TITLE
[Brasília] Desenvolvedor WooCommerce

### ISSUE THREAD

**Issue by leomiranda92** [phpdevbr/vagas#18]
## Descrição da vaga

Procuramos desenvolvedor PHP com conhecimento em WooCommerce para criação de plugins e addons.É necessário conhecimento com API para integração entre plataformas e o WooCommerce.

## Local

SHN QD 01, ED Fusion Live & Work (Ao lado do Conjunto Nacional);

## Benefícios

- Flexibilidade de Horári o / Homeoffice (Mínimo 01 encontro semanal)
- Vale transporte (deslocamento)
- Trabalhos recorrentes de variadas complexidades
- Remuneração compatível com cada projeto
- Utilização da nossa estrutura para projetos pessoais
- Cápsulas de Dolce Gusto da sua escolha

## Requisitos

**Obrigatórios:**
- PHP
- MySQL / MariaDB
- Git
- Experiência comprovada com Wordpress( Plugins e/ou Themes)
- WooCommerce
- API Rest

**Diferenciais:**
- Projetos Opensource

## Contratação

- Freelancer PF;
- PJ;
- À combinar por projeto;
- Possibilidade de efetivação;

## Nossa empresa

A SysCoin é uma agência especializada em Lojas Virtuais com utilização 100% em WooCommerce.
Há 02 anos no mercado atendendo clientes de Brasília e de outros estados.
Temos solução de integração de loja física (PDV) e loja online para omnichannel.
Atendemos todos os portes de empresas.

http://www.syscoin.com.br

## Como se candidatar

Enviar email para atendimento@syscoin.com.br com seu CV anexado - enviar no assunto: Vaga WooCommerce

**Comment by Piulres** [comment]
Enviado :)

**Comment by nic** [comment]
@leomiranda92 Vaga preenchida?

**Comment by leomiranda92** [comment]
@nic estamos precisando ainda.

**Comment by rscafi** [comment]
@leomiranda92 Vaga preenchida?

**Comment by leomiranda92** [comment]
@rscafi Disponível ;)

**Comment by ravanscafi** [comment]
Olá @leomiranda92,
A vaga ainda está aberta?

_(sou administrador das vagas e estou fechando as que já foram preenchidas)_

**Comment by ravanscafi** [comment]
_(fechado por falta de resposta)_
