### ISSUE TITLE
[São Paulo/SP] Technical Solutions Engineer na RTB House

### ISSUE THREAD

**Issue by anankran** [phpdevbr/vagas#180]
## What you will do:

- Help to manage complex technical integrations, which require, for instance, integrating to clients APIs in order to fetch data frequently
- Support Technical Account Coordinators with tasks that require custom configuration and access that only you will have
- Build custom reports to clients, by fetching data from our API and deliver it as requested
- Constantly defy the status quo to come up with solutions to enhance the daily work
- Build web apps to enable both Technical Account and Account Managers to perform their work easier

## What we are looking for:

- +3 years of experience
- Familiar with JavaScript, ES6, HTML, CSS and PHP
- Solid background in building Node.JS applications
- Experience with UI web frameworks (React/SemanticUI/Vue or others) is a plus
- Previous experience with SQL databases is a plus
- Experience with versioning systems (Git/GitLab) is a plus
- Knowledge in Linux and Bash
- Strong analytical skills
- Eagerness to work with new technology and being up to date with the latest trends
- Self-reliance
- Good time management skills and attention to detail
- Ability to solve problems efficiently
- High level of motivation and willingness to learn

## What we offer:

- Unique opportunity to join creative, fast growing company in online advertising
- Ability to work in a truly international environment and win the market with the best people
- Opportunity for professional development and growth as we grow fast in the region
-  Being the part of company pointed as the Innovation Leader on the market
- Attractive salary and a package of benefits

## To apply:
https://www.rtbhouse.com/career/#!/jobs/oiLa7fw4

**Comment by anankran** [comment]
é alocada no escritorio da empresa em São Paulo, e o tipo de contrataçao ao que parece pode ser negociado.

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
