### ISSUE TITLE
[São Paulo/SP] Full Stack PHP Developer na Lexis Nexis

### ISSUE THREAD

**Issue by richardh8** [phpdevbr/vagas#181]
## Job Description

We're looking for smart and driven individuals who will help us build and deliver solutions on data and linking products for the Brazilian Insurance Market. You will be working with local and global technology teams at LexisNexis on deploying Big Data and Analytics products and services. This position will be responsible on designing and implementing tools used to run billing processes and back office functions for our LexisNexis Risk Solutions Brazil at Sao Paulo office.

## Local

Escritório, São Paulo - Bela Vista

## Benefits

- Plano de saúde
- Plano odontológico
- VR
- VA

####  Pluses

- 1- 2 hours lunch time
- Flex time
- Leading edge Big Data & Analytics business
- Global interactions
- Great people

## Requirements

**Minimum Qualifications**
- Strong experience as  Software Engineering 
- Bachelor Degree in Engineering, Computer Science or equivalent
- Proficiency in English and Portuguese

**Key Responsibilities**
- Participate in the process of converting functional requirements into technical design models
- Follow design guidelines to implement great user experiences
- Write automated unit tests
- Give helpful code reviews
- Follow coding standards, software management processes, etc.
- Maintain and contribute to internal code libraries
- Take ownership of the entire code base (tools, application and libraries). This means learn as much as possible and find ways to make things better.
- Remain up to date on industry advancements and share with the team
- Assist in maintaining the environments that run our applications

**Must Haves**
- Strong understanding of Object Oriented Programming in PHP, knowing the difference between Interfaces and Abstract Objects, and how to break a problem down into classes/interfaces that separate different concerns
- Strong understanding of Design Patterns like Model View Controller, Factory, Adapter, etc.
- Have some experience on writing automated unit tests on PHP and Javascript
-Working experience on Git source control system works, like forking, branch management and promoting
- Experience writing and shipping a PHP application using a third party framework like Zend
- Strong knowledge of JavaScript application development
- Proficient on writing SQL for databases managements systems such in MySQL

**Nice to Have**
- Experience setting up and maintaining web apps in a UNIX/Linux environments
- Experience setting up and configuring web apps to run in Cloud environments
- Knowledge of IT configuration management, automation engines such as Ansible or Chef. Ansible is preferred.
- Cloud Computing applications management and deployment knowledge using DevOps techniques are highly desirable with one or more of the following Cloud technologies:
- Amazon Web-services (AWS) EC2 and S3 , experience preferred.
- OpenStack Private Clouds - experience desired 

## Contract

CLT fulltime

## About Lexis Nexis

If you are looking for a career with an innovative company in a growing market, few employers can offer the opportunities LexisNexis Risk Solutions can. Our mission is to provide essential insights to advance and protect people, industry and society. Combining cutting-edge technology, unique data and advanced scoring analytics, we help customers across industry and government assess, predict and manage risk while upholding the highest standards of security and privacy.

## How to Apply

Just click [here ](https://epartner.vagas.com.br/PagVagaDirSS.asp?v=1683033&pp=https%3A//epartner.vagas.com.br/GoHome.asp%3Fv%3D1683033%26j%3Dt%26sslon%3D1&wiw=1366)

## Labels

- CLT
- Pleno
- Sênior

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
