### ISSUE TITLE
[São Paulo/SP] Estágio PHP Developer na OKN Group

### ISSUE THREAD

**Issue by marcosfreitas** [phpdevbr/vagas#187]
## Descrição da vaga

Estamos precisando de alguém que venha para unir forças conosco. Nossos estagiários tem como responsabilidade a busca de aprendizado e experiência prática.

Devem ser capazes de se adaptar ao *workflow* e padrões de desenvolvimento da equipe para no futuro sugerir melhorias.

São capazes de absorver demandas (ainda que desafiadoras) e buscar soluções através da orientação de nossos líderes técnicos.

Descrevemos melhor o perfil que procuramos aqui:

https://github.com/okngroup/perfis-profissionais/blob/master/EstagiarioProgramacao.md

## Local

Escritório, São Paulo - Pinheiros.

**Candidate-se mesmo que você já tenha um estágio.**

#### Diferenciais

- Nosso espaço de trabalho é descontraído, com direito à fliperama  e café da manhã. Esperamos você para conhecer o ambiente e trocarmos um ideia.

## Contratação

PJ a combinar

## Nossa empresa

Conheça-nos http://okngroup.com.br

## Como se candidatar

Por favor envie um email para marcos@okn.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Vaga PHP Estágio

## Labels

- Alocado
- Estágio
- PJ

**Comment by ravanscafi** [comment]
@marcosfreitas se preferir, pode postar as duas vagas separadas com mais detalhes de cada, fica mais fácil pro pessoal encontrar inclusive. aí é só fechar esse issue. senão, pode deixar assim mesmo.

**Comment by marcosfreitas** [comment]
Perfeito, vou refazer.
