### ISSUE TITLE
[São Paulo/SP] PHP Developer na OKN Group

### ISSUE THREAD

**Issue by marcosfreitas** [phpdevbr/vagas#188]
## Descrição da vaga

Estamos precisando de alguém que venha para unir forças conosco mas que consiga andar sozinha quando necessário. Nossos **Juniores** são capazes de pegar um projeto e tocar sozinhos, conseguem ajudar e orientar os colegas estagiários a resolver problemas no dia-a-dia e quando precisão de uma mãozinha eles dão um grito.

Entendemos que você é um desenvolvedor em início de carreira, acabou de sair da faculdade, está cursando uma ou até mesmo não tem formação acadêmica.

Provavelmente você não tem experiência comprovada no desenvolvimento de software dentro de uma empresa mas talvez saiba construir um CRUD sozinho. Que maravilha!

Acredite que você deve ser capaz de se adaptar ao *workflow* e padrões de desenvolvimento da equipe podendo sugerir melhorias.

Descrevemos melhor o perfil que procuramos aqui:

https://github.com/okngroup/perfis-profissionais/blob/master/ProgramadorJunior.md

## Local

Escritório, São Paulo - Pinheiros.

**Candidate-se mesmo que você já tenha um emprego.**

#### Diferenciais

- Nosso espaço de trabalho é descontraído, com direito à fliperama  e café da manhã. Esperamos você para conhecer o ambiente e trocarmos um ideia.

## Contratação

PJ a combinar

## Nossa empresa

Conheça-nos http://okngroup.com.br

## Como se candidatar

Por favor envie um email para marcos@okn.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Vaga PHP Júnior.

## Labels

- Alocado
- Júnior
- PJ

**Comment by irwingmax** [comment]
Alguma possibilidade de contratação CLT?

**Comment by guilhermeoa07** [comment]
Possibilidade de entrevista via Skype?

**Comment by marcosfreitas** [comment]
@guilhermeoa07 basta mandar o currículo que a entrevista pode acontecer da melhor forma.
