### ISSUE TITLE
[São Paulo/SP] PHP Jr. Developer na MGov

### ISSUE THREAD

**Issue by dianaarnos** [phpdevbr/vagas#193]
## Descrição da vaga

Procuramos desenvolvedor Jr. tanto para atuar em mapeamento e resolução de bugs quanto para ajudar no desenvolvimento de novos sistemas e funcionalidades.
Sistemas em PHP (Laravel, Symfony) e Vue.js.

## Local

Parcialmente remoto (mas pode estar presencialmente todos os dias, se quiser), São Paulo - Av. Paulista.

#### Diferenciais

- Remoto sempre que necessário
- Trabalhar com impacto social

## Requisitos

**Obrigatórios:**
- PHP 7.1+ (PSRs, boas práticas em geral)

**Desejáveis:**
(Conhecimento em ou pelo menos a vontade e disponibilidade de aprender):
- Laravel 5+
- Symfony 4
- Vue.js
- Google Cloud

**Diferenciais:**
- Envolvimento com comunidades de desenvolvimento
- Participação em eventos da área

## Contratação

PJ

## Nossa empresa

A MGov é uma startup focada no uso da tecnologia para o impacto social. Por meio de uma plataforma de comunicação inteligente entregamos um meio de comunicação simples e conteúdos específicos para engajamento do público alvo. Atualmente, desenvolvemos bibliotecas de conteúdos para educação financeira e para educação básica, como engajamento dos pais.

Trabalhamos com Governos, Organismos Internacionais, Fundações, Institutos, ONGs e Empresas Privadas preocupadas com impacto social.

Estamos entre as [12 startups brasileiras de impacto social para ficar de olho](http://www.valor.com.br/empresas/5427613/startups-brasileiras-para-ficar-de-olho), conforme ranking "Pequenas Empresas & Grandes Negócios" e "Época Negócios"

Com atuação em mais de mil municípios em todo o Brasil e projetos internacionais em quatro continentes, a MGov é comprometida em gerar impacto social comprovado onde importa: na ponta. Com mais de 170 mil usuários engajados em 2017, apoiados por comunicação e engajamento nas bibliotecas de conteúdos, o objetivo é chegar a pelo menos 1 milhão de usuários ativos até o final de 2018.

## Como se candidatar

Só mandar um email para diarnos@mgovbrasil.com.br com seu CV anexado - enviar no assunto: Vaga PHP

## Labels

- Júnior
- PJ
- Remoto - Parcial

**Comment by joaogabrieljs** [comment]
Currículos fora de SP serão considerados?

**Comment by guilhermeoa07** [comment]
Possibilidade de entrevista via Skype?

**Comment by dianaarnos** [comment]
@joaogabrieljs sim, serão :)

@guilhermeoa07 a entrevista é via hangout mesmo

**Comment by guilhermeoa07** [comment]
@dianaarnos legal. Vou enviar o currículo.

**Comment by dianaarnos** [comment]
Processo ainda aberto, apenas pausamos por alguns dias para tratar de questões internas

**Comment by BiraCarvalho** [comment]
Nossa @dianaarnos, acabei de enviar o meu currículo, mas já contando que o processo estava encerrado. Voltei aqui só pra confirmar umas informações, e você publica que o processo está aberto.  =)

**Comment by LeticiaLCavalcanti** [comment]
Uau! Estou focando em backend há pouco tempo, aprendendo agora o php 7, com conhecimentos básicos em Zend. Adorei a vaga especificamente por não ter muitos requisitos, normalmente vejo vagas com cobram uma experiência muito elevada para JR. 
Ainda não me sinto muito segura em relação a dominar a linguagem, mas logo entrarei em contato, espero que ainda haja um espacinho na empresa.

**Comment by guilhermeoa07** [comment]
A vaga já foi preenchida?

**Comment by moreiraandre** [comment]
@dianaarnos currículo enviado!

**Comment by dianaarnos** [comment]
Gente, a vaga já foi preenchida :)
Assim que novas oportunidades aparecerem, colocaremos aqui :D
