### ISSUE TITLE
[São Paulo/SP] PHP Developer na Ventron

### ISSUE THREAD

**Issue by Dani-Ventron** [phpdevbr/vagas#194]
## Descrição da vaga

Projeto de tempo indeterminado, atuação na zona Norte de São Paulo

## Local

São Paulo - Zona Norte

## Benefícios

a combinar

## Requisitos

Procuramos programadores PHP + Frontend fullstack plenos, com conhecimento de frameworks como Laravel e JQuery , conhecimentos de banco de dados SQL-Server e MySQL, conhecimento de Linux.
 
Desejável inglês leitura + escrita

## Contratação

PJ a combinar

## Nossa empresa

A Ventron é uma empresa de consultoria que pertence ao grupo Cadmus

## Como se candidatar

Por favor envie um email para daniele.silva@ventron.com.br  com seu CV anexado - enviar no assunto: Vaga PHP SP

## Labels

- Alocado
- CLT
- PJ
- Pleno

**Comment by Dani-Ventron** [comment]
Experiência Pleno

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
