### ISSUE TITLE
[Rio de Janeiro/RJ] PHP Developer na Ventron

### ISSUE THREAD

**Issue by Dani-Ventron** [phpdevbr/vagas#195]
## Descrição da vaga

Projeto de tempo indeterminado para atuação no centro do Rio de Janeiro.
Profissional irá atuar com programação Web; Organizar e coordenar atividades de desenvolvimento de aplicações; Executar atividades de desenvolvimento ou suporte em aplicações digitais; Saber Identificar  e resolver problemas técnicos

## Local

Rio de Janeiro - Centro

## Benefícios

- Plano de saúde
- Seguro de vida
- VR 
- VT

## Requisitos

- a partir de 5 anos de experiência
- WEB (PHP / HTML 5 / Css 3 / Bootstrap / JS / Jquery /Mysql) 
- Java 
- Linux

Diferencial ter conhecimento em arquitetura de software 
 
- Inglês  fluente 

## Contratação

CLT

## Nossa empresa

A Ventron é uma empresa de Consultoria que faz parte do grupo Cadmus. Temos mais de 20 anos de atuação no mercado de TI

## Como se candidatar

Por favor envie um email para daniele.silva@ventron.com.br com seu CV anexado - enviar no assunto: Vaga PHP

## Labels

- Alocado
- CLT
- Sênior

**Comment by ArieltonPires** [comment]
?

**Comment by ravanscafi** [comment]
@Dani-Ventron, acredito que você esqueceu de colocar a descrição da vaga. Pode editar e colocar?

**Comment by Dani-Ventron** [comment]
Vaga atualizada! obrigada

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
