### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) PHP Pleno ou Senior na Netlolo

### ISSUE THREAD

**Issue by ghost** [phpdevbr/vagas#196]
Pessoal estamos buscando desenvolvedores #PHP, para atuar em projetos utilizando #WebSocket, #firebase, #loopback, #iOS, #Android e outras muitas...
Procuramos alguém com nível Pleno/Sr, que possa atuar na Avenida Paulista.
Email: vagas@netlolo.com
Assunto: Vaga PHP

**Comment by ravanscafi** [comment]
@pauloluedy qual o regime de contratação, CLT ou PJ?

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
