### ISSUE TITLE
[São Paulo/SP] PHP Developer na e-HTL Viagens Online

### ISSUE THREAD

**Issue by andersondanilo** [phpdevbr/vagas#197]
## Descrição da vaga
Temos duas aplicações principais sendo executadas, uma é em Laravel e outra é em PHP sem framework (porém com importação de algumas bibliotecas do laravel).

Consumimos o webservice de fornecedores (soap e rest) para fornecer para os nossos clientes os produtos através do nosso portal e de nossos webservices (o antigo webservice é soap, o novo é uma API JSON).

## Local
Escritório, São Paulo - República

## Requisitos
- Experiência com PHP, MySQL, Postgres e Javascript
- Experiência com integrações em API ou webservices SOAP
- Proatividade

## Desejáveis:
- Conhecimentos em Laravel
- Conhecimentos em Docker
- Conhecimentos em Linux
- Conhecimentos em Design Patterns

## Diferenciais
- Experiência na área de turísmo

## Benefícios
- VR 29,60 por dia trabalhado
- Vale Transporte
- Assistência médica

## Contratação
CLT a combinar

## Nossa empresa
A e-HTL viagens online é uma operadora de turismo com foco em venda de hospedagem em hotéis, porém também trabalhamos com aluguel de veículos e outros serviços.

https://www.e-htl.com.br/

## Como se candidatar
Por favor envie um email para rh@e-htl.com.br com seu CV anexado - enviar no assunto: Vaga Programador PHP

## Labels
- CLT
- Pleno

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
