### ISSUE TITLE
[Fortaleza/CE] PHP Fullstack developer na iGet

### ISSUE THREAD

**Issue by iget-master** [phpdevbr/vagas#199]
## Descrição da vaga

Vaga para PHP Fullstack developer.

Conhecimentos mínimos:

- PHP
- Laravel
- TDD
- HTML5+CSS
- Less/Sass
- Javascript
- Angular 2
- Linux básico

Conhecimentos desejáveis:

- Adobe XD e/ou Illustrator
- Ionic
- Linux avançado

## Local

Escritório em Fortaleza/CE - próximo a praça portugal

## Benefícios

- VR de R$ 16/dia
- Vale transporte

#### Diferenciais

- Equipe descontraída
- Flexibilidade de horários

## Requisitos

**Obrigatórios:**
- Experiência em PHP + Laravel
- Experiência com HTML5 + CSS + Less/Sass + Javascript
- Experiência com desenvolvimento Angular 2
- PHPUnit
- Conhecimento básico de Linux
- Inglês básico

**Desejáveis:**
- Desenvolvimento de temas Wordpress
- Desenvolvimento de temas Magento
- Adobe XD
- Adobe Illustrator
- Inglês avançado ou técnico
- Linux avançado

**Diferenciais:**
- Gestão de servidores AWS
- Foco em performance
- Foco em segurança

## Contratação

CLT, valor a combinar de acordo com sua experiência

## Nossa empresa

Somos a IGET, e trabalhamos com desenvolvimento de sites, lojas virtuais e sistemas sob medida, sendo esta vaga focada para desenvolvimento de sistemas sob medida.

## Como se candidatar

Enviar email para esoares@iget.com.br, com o assunto "VAGA Fullstack", com:

- Curriculo
- Portifolio (Github)
- Pretensão salarial

## Labels

- CLT

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
