### ISSUE TITLE
[São Paulo ] Desenvolvedor PHP Jr

### ISSUE THREAD

**Issue by brunohulk** [phpdevbr/vagas#2]
## Desenvolvedor PHP Jr

Integrar time de desenvolvimento e manutenção da plataforma de blogs e sites do Portal R7
## Requisitos

**Obrigatórios:**
- Bons conhecimentos na linguagem PHP e Orientação a Objetos
- Banco de dados Mysql e Redis
- Conhecimentos sólidos em Git
- Experiência em desenvolvimento em WordPress (plugins e themes)Diferencial
- Conhecimento em Ruby e NodeJs
- Banco de dados Mongo
- Experiência com ferramentas de integração contínuaContato:

**Diferenciais:**
- Conhecimento em Ruby e NodeJs
- Banco de dados Mongo
- Experiência com ferramentas de integração contínua
## Local

Barra Funda, São Paulo
## Contratação

CLT
## Nossa empresa

Portal R7
## Como se candidatar

Por favor envie dreboucas@rederecord.com.br ou brbsilva@sp.r7.com com o seu currículo

**Comment by enieber** [comment]
@brunohulk alocado ou remoto?

**Comment by ftonato** [comment]
@enieber melhor que o @brunohulk responda isso, mas acredito que seja alocado. =(

**Comment by upcesar** [comment]
Estão aceitando perfis Plenos / Sênior?

**Comment by nic** [comment]
@brunohulk vaga preenchida?
