### ISSUE TITLE
[Goiânia] BRLOTO - Desenvolvedor PHP

### ISSUE THREAD

**Issue by antonyalkmim** [phpdevbr/vagas#20]
## Descrição da vaga

Procuramos desenvolvedores PHP (júnior ou pleno) que queiram fazer parte do nosso time de desenvolvimento e que sejam apaixonados por desenvolvimento de aplicações. O candidato deve ser pró-ativo e ter boa comunicação com a equipe além de acompanhar às novidades através das comunidades de desenvolvimento.

## Local

Escritório próximo à Saga T-7, Goiânia - Setor Oeste

## Benefícios

- Salários competitivos com base na experiência e potencial
- 2 horas de almoço
- Horário Flexível
- Vale alimentação
- Ambiente informal

## Requisitos

**Obrigatórios:**
- conhecimento em PHP
- experiência com Javascript
- conhecimento em SQL
- conhecimento em desenvolvimento de API RESTFull

**Desejáveis:**
- conhecimentos em algum framework: ZendFramework, Laravel, Synfony ou CakePHP
- experiencia com Javascript, CSS e seus processadores
- experiência com ferramentas de controle de versão: GIT ou SVN

**Diferenciais:**
- projetos opensource
- Proatividade, gostar de aprender e ter boa comunicação

## Contratação

CLT

## Nossa empresa

Fundada e sediada em Goiânia, atua na gestão e desenvolvimento de sistemas para loterias e prognósticos.

Nosso foco principal está em promover o desenvolvimento e crescimento dos negócios de nossos clientes, oferecendo serviços direcionados utilizando tecnologia de ponta.

Acreditamos que a tecnologia pode ser utilizada para melhorar a vida das pessoas, e por isso estamos constantemente buscando inovação.

Atuamos com uma equipe de profissionais selecionados e altamente capacitados, desenvolvendo soluções para o entretenimento online que visam atender as necessidades de nossos clientes e parceiros.
- Veja mais no nosso [Site](http://brloto.com.br)

## Como se candidatar

Para se candidatar, envie um email para rh@brloto.com.br com seu CV anexado e assunto "Vaga PHP". Além disso, nos envie também alguns links onde podemos saber mais sobre o candidato como o perfil do Linkedin e GitHub.

**Comment by nic** [comment]
@antonyalkmim Vaga preenchida?

**Comment by antonyalkmim** [comment]
@nic Não foi preenchida mas pode fechar. O pessoal não está mais contratando.

**Comment by nic** [comment]
@antonyalkmim Poxa, bom, qualquer coisa reabre aqui. Tem cada vez mais pessoas com watch neste repositório, da próxima espero que role! Abração. ;)
