### ISSUE TITLE
[São Paulo/SP] PHP Developer na QueroQuitar!

### ISSUE THREAD

**Issue by thiagoericson** [phpdevbr/vagas#200]
### A missão do Desenvolvedor: Implementar rotinas pesadas de ETL. 

O papel do Programador PHP Pleno na QueroQuitar! é de atuação em integrações diretas com os nossos parceiros, garantindo o tracionamento dos produtos com consistência e performance. Auxiliando na tomada de decisão do melhor fluxo de integração, baseado em empirismo da equipe.

### Em novos projetos

- Auxiliar na análise dos requisitos da integração.
- Apoiar a tomada de decisão do melhor fluxo de integração.

### Em projetos correntes

- Daily Sync para o time.
- Reportar dificuldades encontradas, para serem superadas em conjunto.
- Desenvolver e sustentar as integrações.
- Buscar melhorias possíveis para aumento de performance.

### O que esta vaga pode agregar para a sua carreira?

No que se refere ao crescimento, à medida que ele(a) trabalha em diferentes projetos, por ter contato com diferentes realidades, contextos e pessoas, o conhecimento, a maturidade e a responsabilidade vão aumentando. Possibilidade de trabalhar com parceiros de nível nacional. Poderá inclusive se preparar para uma posição gerencial.

## Local

Remoto ou Escritório, São Paulo - Higienópolis

## Requisitos

**Obrigatórios:**
- Conhecimentos sólidos em PHP, LARAVEL e GIT.
- Conhecimentos avançados em SOAP, NoSQL e DDD.
- Vivencia em Integrações de WebServices.

**Desejáveis:**
- Conhecimento em metodologia ágil - Scrum ou Kanban.
- Conhecimento em aplicativos de gestão de projetos - Trello, Jira, etc.
- Prévia experiência no cargo, mínimo de 2 anos.
- Conhecimentos em AWS
- Conhecimentos em DDD
- Conhecimentos em Docker

## Contratação

PJ a combinar

## Nossa empresa

Aqui na QueroQuitar trabalhamos com Recuperação Digital de Crédito, escalando o volume de negociação de débitos entre inadimplentes e grandes empresas do mercado.

## Como se candidatar

Enviar email para contato@queroquitar.com.br com:

- Assunto: [São Paulo/SP] PHP Developer na QueroQuitar!
- Seu CV anexado - enviar no assunto: Vaga PHP
- Link de repositórios, como portfólio
- Pretenção salarial
- Local
- Disponibilidade

## Labels

- Alocado
- PJ
- Pleno
- Remoto

**Comment by tifannyknox** [comment]
Eles querem uma pessoa verticalizada em laravel

**Comment by geekcom** [comment]
Essa vaga é para devs experientes em Laravel sim @tifannyknox,é uma boa vaga, já trabalhei com @thiagoericson.

**Comment by thiagoericson** [comment]
Oi pessoal, 

Apenas para explicar a "verticalização" em Laravel.

O escopo de trabalho da vaga é focado em rotinas **artisan**, integrando em WebServices SOAP, Serviços da AWS, etc., o que pode frustrar profissionais que possuem aspiração a VueJs/React, etc.

É bem back-end mesmo!

--

@geekcom Valeu pela menção, grande abraço!

**Comment by mvnp** [comment]
Disponível para trabalhos remotos. Experiência em PHP e muita lógica na veia. Sou adminsitrador de Programadores Incríveis no facebook (https://www.facebook.com/groups/programadoresincriveis). Abraço

**Comment by moreiraandre** [comment]
@thiagoericson currículo enviado.

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
