### ISSUE TITLE
[São Paulo/SP] PHP Developer Pleno e Sênior na Radar Profissional 

### ISSUE THREAD

**Issue by RADARProfissional** [phpdevbr/vagas#201]
## Local

Zona Sul de São Paulo - SP

## Benefícios

15 dias de férias remuneradas 

## Requisitos

•	Superior completo em Administração, Análise de Sistemas, Ciências da Computação, Tecnologia da Informação, Engenharia da Computação ou áreas afins;
•	Conhecimento sólido em PHP e em desenvolvimento de produtos com orientação a objetos;
•	Experiência com MySQL, SQL Server, PostGreSQL e com CSS2 / CSS3;
•	Conhecimento sólido Jquery/ Jquery UI / twitter bootstrap / JSON e experiência com Framework (Symfony, Zend, CodeIgniter);
•	Controle de versão (GIT ou SVN) versionamento, branchs, merge, hotfix;
•	Ferramenta de ORM (Doctrine, propel, pdo) e Webservices (SOAP, REST) e Integração com API’s de terceiros e Criação, manutenção (Apache);
•	Modelagem de dados, modelo relacional, modelagem E-R e Design Patterns;
•	Metodologias, ferramentas e técnicas de desenvolvimento e manutenção de sistemas;
•	Diferencial: o profissional que tenha experiência Symfony, ‘deploy’ (Capistrano, phing) e alguma ferramenta de testes (unitário, integrado).

## Contratação

PJ 

## Nossa empresa

RADAR Profissional, Consultoria de R&S.

## Como se candidatar

Interessados, por gentileza, enviar CV para cristiane@radarprofissional.com.br

## Labels

- CLT
- Pleno
- Sênior
- PJ

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
