### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) PHP Pleno na Voxus

### ISSUE THREAD

**Issue by gustavomgregorio** [phpdevbr/vagas#202]
## Descrição da vaga

Estamos procurando um desenvolvedor de nível Pleno com muita vontade de aprender e crescer, enquanto ajuda a Voxus a crescer mais rápido também.

A pessoa trabalhará na melhoria dos produtos e algoritmos da Voxus, assim como em novos projetos. Terá um papel importante no dia-a-dia de entrega de tarefas - especialmente as de complexidade média e alta. Além de ter um papel ajudando o time júnior a se desenvolver.

## Conhecimentos e tecnologias

**Obrigatórios:**
- PHP5+ 
- CakePHP ou Zend Framework
- PHPUnit
- MySQL 
- Configuração de ambientes de desenvolvimento em Ubuntu ou Debian

**Diferenciais:**
- Utilização de APIs da AWS
- ElasticSearch
- Vim

## Local

Empresa localizada em São Paulo, a um quarteirão da Av. Paulista, próxima à estação Brigadeiro do metrô

## Benefícios

- VT
- VR
- Opcional de plano de saúde

## Sobre nós

A Voxus (www.voxus.com.br) é uma empresa de tecnologia focada no mercado de e-commerces. 

A tecnologia da Voxus entende padrões de consumo através da coleta, processamento e cruzamento de dados comportamentais, prevendo quem são as melhores pessoas para exibir os banners de seus clientes. 

A Voxus estima impactar R$500 milhões de receita para e-commerces em 2018. 

## Como se candidatar

Envie um email para gustavo@voxus.tv

## Labels

- regime/CLT
- alocação/Presencial

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
