### ISSUE TITLE
[Goiania/GO] PHP Developer - FederalST

### ISSUE THREAD

**Issue by lucenarenato** [phpdevbr/vagas#203]
## Requisitos
* Amplo conhecimento na linguagem;
* Boa lógica de programação e conhecimento de OO.
* Banco de dados PostgreSQL;
* Boas práticas de desenvolvimento;
## Desejável:
* Framework Laravel
## Salário:
* Negociável. Enviar pretensão salarial.
- Interessados enviar e-mail para: suporte@federalst.com.br

**Comment by jcdourado** [comment]
Há possibilidade de ser remoto?

**Comment by lucenarenato** [comment]
Mande seu curriculo, que vao analisar.

**Comment by devLopez** [comment]
Opa, envio ainda hoje
