### ISSUE TITLE
[Colombo/PR] Programador(a) PHP Jr

### ISSUE THREAD

**Issue by mayronceccon** [phpdevbr/vagas#207]
## Descrição da vaga

Programador(a) PHP Jr

Desenvolvimento de aplicações PHP, criação de novas funcionalidades e melhorias em sistemas existentes.

## Local

Presencial - Colombo/PR
obs: Região metropolitana de Curitiba

## Requisitos

**Obrigatórios:**
- PHP estruturado
- PHP OO
- HTML5
- CSS3
- JavaScript
- SQL
- Lógica de Programação

**Desejáveis:**
- Postgresql
- GIT
- Linux

**Diferenciais:**
- Frameworks PHP (Laravel, Slim) 

## Contratação

CLT

## Como se candidatar

Interessados enviar CV para o e-mail sistemas@tecnorisk.com.br

## Labels

- CLT
- Junior

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
