### ISSUE TITLE
[São Paulo] Vaga PHP Pleno/Sênior Back-End Presencial - Vila Madalena - São Paulo

### ISSUE THREAD

**Issue by rgmd** [phpdevbr/vagas#21]
## Descrição da vaga

Empresa Startup localizada em São Paulo busca dev PHP sênior para trabalho presencial na Vila Madalena. Ambiente de trabalho descontraído, empresa em fase de aceleração com grandes desafios a serem vencidos e oportunidade de crescimento. Trabalho inovador no mercado.

## Local
 
Vaga presencial, Vila Madalena - São Paulo

## Benefícios
- 1 hora de almoço
- laptop da empresa para trabalhar
- frigobar sempre cheio
- ambiente descontraído

## Requisitos

Buscamos profissinal desenvolvedor PHP Pleno/Senior com experiência em:

Framework Yii2 (Preferencialmente), Laravel ou Similar;
Aptidão em Javascript/Jquery;
Banco de Dados Relacional (MySQL, Oracle, MSSQL) e NoSQL (MongoDB);
Amazon AWS;
Composer, GIT e outros;
Metodologias ágeis (SCRUM)
Local de trabalho: Vila Madalena
Vaga CLT, salário a combinar.
CVs para rgmd@ymail.com

**Diferenciais:**
Projeto inovador

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para rgmd@ymail.com com seu CV anexado.

**Comment by carloshskp** [comment]
Ainda disponível?

**Comment by nic** [comment]
@rgmd Vaga Preenchida?
