### ISSUE TITLE
[São Paulo/SP] Senior PHP Developer na Techsocial

### ISSUE THREAD

**Issue by helton001** [phpdevbr/vagas#210]
## Local

Escritório, São Paulo - Paulista (Próximo ao metrô Consolação)

## Benefícios

- VR de R$ 30,00
- Bônus salarial - 1x ano.
- Férias - 30 dias/ano

## Requisitos

**Obrigatórios:**
- 5 anos de experiência com PHP 
- Experiência sólida em Framework Laravel

Superior completo em Análise de Sistemas, Ciências da Computação, Tecnologia da Informação, Engenharia da Computação ou áreas afins;
Mínimo de 5 anos de exp. atuando com desenvolvimento web - PHP, utilizando arquitetura MVC e orientado a objetos; - 
Conhecimento e experiência em métodos ágeis (Scrum e Kanban);
Proficiência em desenvolvimento de testes (PHPUnit);
Conhecimento sólido Jquery/ Jquery UI / twitter bootstrap / JSON e experiência com Framework Laravel;
Webservices Rest API / WCF /, GIT;
Dominar react, angular ou vue será considerado diferencial;

O que se espera:
Qualidade e Responsabilidade de entrega, inclusive na manutenção dos sistemas no pós-implantação, garantindo todo o lifecycle do mesmo;
Pesquisa e desenvolvimento trazendo novas tecnologias e melhores formas de evolução dos sistemas e das formas de construí-lo;
Visão ampla dos processos e integrações entre sistemas, buscando prever os impactos em áreas afetadas por novas rotinas desenvolvidas;

## Contratação

PJ/CLT a combinar

## Nossa empresa

Aqui na Techsocial a gente faz trabalho de Consultoria e Desenvolvemos Sistemas, estamos em expansão de produtos e serviços, com isso o investimento no time de desenvolvimento se faz necessário. 
O momento é de ressignificação tanto da marca, como também no processo de desenvolvimento de sistemas, aplicando métodos tradicionais de mercado.
O ambiente que você irá encontrar é desafiador, você terá autonomia para opinar e criar novidades, com isso possibilidades de crescimento profissional não faltarão.
Somos pequenos, porém ágeis e pensamos grande. 

## Como se candidatar

Por favor envie um email para contato@techsocial.com.br com seu CV anexado e pretensão salarial

## Labels

- PHP
- Laravel
- Sênior

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
