### ISSUE TITLE
[Santa Barbara D'Oeste/SP] Desenvolvedor(a) PHP na Acruxx

### ISSUE THREAD

**Issue by santoja** [phpdevbr/vagas#211]
Descrição da vaga
Atuar no desenvolvimento de nossos sistemas PHP/jQuery/HTML/CSS.
Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;
Participar do processo criativo e auxiliar na construção dos sistemas;

Local
Distrito industrial - Santa Barbara D'Oeste/SP

Benefícios
VA
Reembolso de viagens caso seja remoto e venha para a empresa esporadicamente.
No caso de home office, ou caso o profissional deseje trabalhar com seu próprio equipamento, há um reembolso mensal pelo uso.

Diferenciais
Area de descanso
Frutas no escritório
Café expresso ou coado
Chá
Cachorro no ambiente de trabalho
Troca de experiencias com profissionais de outras equipes

Requisitos
Obrigatórios:

Experiência relevante em PHP OOP
Usar os conceitos SOLID.
Desenvolver utilizando boas praticas de programação

Desejáveis:
PHP 5.6 e mais novos

Diferenciais:
Contratação
CLT presencial

Como se candidatar
Por favor envie um email para kaue@acruxx.com.br com seu CV anexado - enviar no assunto: Vaga PHP

**Comment by guilhermeoa07** [comment]
Senioridade? (Cachorro no ambiente de trabalho, It's a dream)

**Comment by santoja** [comment]
Na realidade eu tenho 2 vagas aqui na empresa, uma senior e a outra pode ser junior/pleno

**Comment by andrezap** [comment]
aceita remoto?

**Comment by andrezap** [comment]
enviado! :D

**Comment by mvnp** [comment]
Disponível para trabalhos remotos. Experiência em PHP e muita lógica na veia. Sou adminsitrador de Programadores Incríveis no facebook (https://www.facebook.com/groups/programadoresincriveis). Abraço

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
