### ISSUE TITLE
[Amsterdam/Holanda] Web Developer na Werkspot

### ISSUE THREAD

**Issue by brunonm** [phpdevbr/vagas#212]
## Descrição da vaga

Estamos procurando desenvolvedores sêniors que possam nos ajudar a manter e expandir nossa plataforma para toda a Europa. Atualmente estamos presentes na Holanda, Itália e em processo de transição para França. 

A Werkspot faz parte do grupo IAC, que é o mesmo grupo de empresas como Tinder e Vimeo. Nossa missão é ser a mais fácil e confiável maneira de contratar home services (pintor, encanador, arquitetos, etc).

Na nossa stack usamos metodologias/técnicas/padrões como arquitetura hexagonal, CQRS, DDD, queues/workers, data science e etc. É um ambiente excelente para contribuir e se desenvolver como profissional e pessoalmente.

## Local

Herengracht, Área central de Amsterdam, Holanda.

## Benefícios

- Almoço gratuito na empresa todos os dias (padrão holandês)
- Academia gratuita no prédio da empresa
- Budget anual pra participar de conferências na Holanda e no exterior
- Reembolso para compra de livros e outros materiais educacionais
- 25 dias úteis de férias por ano
- Qualquer notebook que atenda as suas necessidades, junto com um monitor de 27" de alta definição (geralmente usamos MacBook Pro 13" com 16GB RAM)
- Salário competitivo

#### Diferenciais

- Ambiente internacional, você terá a oportunidade de trabalhar com pessoas de vários países
- Cerveja liberada todas as sextas feiras
- Ping-pong, pebolim e PS4
- Escritório extremamente bem localizado, perto de vários bons restaurantes e bares
- Oportunidade de trabalhar com profissionais extremamente qualificados, contribuidores de diversos projetos open source da comunidade

## Requisitos

**Obrigatórios:**
- PHP 7+
- Symfony 3+
- SCRUM
- TDD
- CI
- PSR's
- Inglês suficiente para se comunicar, você precisar entender e ser entendido

**Desejáveis:**
- Arquitetura hexagonal
- DDD
- CQRS
- GraphQL
- Vagrant
- Ansible
- Docker
- Elasticsearch
- Redis
- RabbitMQ
- Kubernetes

**Diferenciais:**
- Contribuições em projetos Open Source

## Contratação

Formal: você terá um contrato de trabalho com todos os direitos normais holandeses.

## Nossa empresa

https://www.careersatwerkspot.com/

## Como se candidatar

Por favor envie um email com o seu CV em inglês para o rodrigo.prestes@werkspot.nl. Diga que viu essa vaga no GitHub.

### Importante
Apesar do Rodrigo ser brasileiro, é importante que desde o primeiro email toda a comunicação seja em inglês, ok?!

## Labels

- Sênior
- Presencial
- Exterior

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
