### ISSUE TITLE
[Porto Alegre/RS] PHP Developer na Deliver IT

### ISSUE THREAD

**Issue by deliver-it** [phpdevbr/vagas#214]
## Descrição da vaga

Buscamos profissionais inquietos e em busca de desafios, para atuar em projetos PHP.

## Local

Alocado na sede da empresa, Porto Alegre - RS

## Benefícios

- Plano de saúde
- Seguro de vida
- VR 
-VT
- Gympass (convênio com academias)
- Convênio com instituições voltadas a tecnologia (SEPRORGS e ASSESPRO)

## Requisitos
Experiência em PHP, JavaScript, HTML/CSS

**Desejáveis:**
- conhecimentos em Fluig, Laravel.

## Contratação

CLT

## Nossa empresa

Aqui na Deliver IT somos líderes em entregar valor ao cliente.

## Como se candidatar

Por favor envie um email para sejadeliver@deliverit.com.br com seu CV anexado - enviar no assunto: Vaga PHP

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
