### ISSUE TITLE
[São Paulo/SP] PHP DRUPAL Developer na Guiropa

### ISSUE THREAD

**Issue by danilocolombo13** [phpdevbr/vagas#215]
## Descrição da vaga

Conhecimento em DRUPAL, PHP, MCV, MySQL, HTML, CSS, Javascript, Jquery.
Para desenvolvimento de aplicações web e manutenção de site. Desejável conhecimento em CMS, JSON, Ajax, Web Services, Web API. Conhecimentos em Frameworks que sejam em PHP.
Ensino Superior Completo em cursos relacionados à área de TI.

## Local

Remoto ou Escritório, São Paulo - Mooca

## Benefícios

- Plano de saúde
- VR de R$ 20/dia
- VT

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com PHP 5+
- 2 anos de experiência com DRUPAL 7

**Desejáveis:**
- conhecimentos em Laravel
- Língua inglesa

## Contratação

CLT

## Nossa empresa

http://www.guiropa.com

## Como se candidatar

Por favor envie um email para danilo.colombo@guiropa.com com seu CV anexado - enviar no assunto: Vaga PHP

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
