### ISSUE TITLE
[Campinas/SP] PHP Developer na Superlógica Tecnologias

### ISSUE THREAD

**Issue by emersonsilva75** [phpdevbr/vagas#216]
### Descrição da vaga

Procuramos devs, nos níveis pleno ou seniores, que tenham sólidos conhecimentos comprovados em PHP, que tenham foco em resolver problemas e gerar valor ao negócio.

## Local

Presencial na sede da empresa, Campinas - Vila Teixeira

## Benefícios

- Plano de saúde
- Plano odontológico
- Refeição no local
- Vale transporte

#### Diferenciais

- Modelo de gestão startup
Times enxutos, auto-geridos com modelo similar ao [squad do Spotify](https://www.youtube.com/watch?v=4GK1NDTWbkY)
Ambiente colaborativo 
Pouca burocracia
Pouca hierarquia
Ambiente inclusivo
Ambiente de aprendizado continuo

- Plataforma Alura para treinamento online
- Espaço próprio para eventos [Superlógica Labs](https://labs.superlogica.com/) com execução, apoio e presença nos eventos na cidade 
- 280 títulos de livros em nossa biblioteca particular
- Lanchonete interna 
- Mesa de ping-pong
- Video-Game
- Convenio com escola de idiomas [Excellent Global](https://www.excellentglobalcampinas.com.br/) com aulas internas (opcional)

## Requisitos

**Obrigatórios:**
- Experiência comprovada com PHP 5+
- Experiência comprovada com banco MySQL e otimização de queries
- Experiência comprovada com API
- Experiência comprovada de testes unitários
- Experiência comprovada com cacheamento
- Experiência comprovada com Threads e paralelismo
- Domínio do Apache e NGinx
- Base sólidas em orientação a objetos
- Experiência em validar performance de aplicação
- Gestão de logs
- Experiência comprovada em projetos com altíssimo volume de transações

**Desejáveis:**
- Conhecimentos em Zend Framework
- Inglês intermediário

**Diferenciais:**
- Projetos próprios
- Certificação Zend ou Certificação PHP iMaster

## Contratação

CLT

## Nossa empresa

A [Superlógica Tecnologias](https://www.superlogica.com/) é uma empresa de software fundada em 2.001 em Campinas, onde contamos com 200 colaboradores e experimentamos um crescimento de 300% no ano faturamento de 2.017.

Somos lideres em software SaaS para negócios recorrentes.

Um negócio recorrente gerido por um ERP transacional é perda de tempo e muito dinheiro. O ERP tradicional nasceu para ser transacional.

Mas não o Superlógica. Nascemos com a proposta de atender negócios da nova economia da recorrência. Só quem tem esta visão consegue extrair o máximo de um negócio assim.

## Como se candidatar

Por favor envie um email para emerson.rodrigues@superlogica.com com o link do seu Linkedin, GitHub no corpo e pretensão salarial - enviar no assunto: PHP Developer
**Observação : Não enviem curriculum, não precisamos**

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
