### ISSUE TITLE
[Hamburgo/Alemanha][Amsterdã/Holanda] PHP Developer at Sprint & Partners

### ISSUE THREAD

**Issue by johnmichaelgott** [phpdevbr/vagas#217]
## Job Description

You will be joining a DevOps culture building the best e-commerce eco-system possible. They operate in small teams that operate like a start-up and take full ownership on core components of the eco-system. They are also setting up a B2B Service in which they will offer their E-commerce platform (Cloud infrastructure on AWS) as a SaaS to other shops to scale their business. This brings a whole other level of challenges along that are interesting for you to work on. Furthermore, you will:

- Together with your team be motivated to think of new and better solutions to challenges in the company or market – as a front-runner these are mostly new things to the market
- Working in one of the best Architectures for this stack and for every level of Engineer there is both interesting stuff to learn & contribute
- Mostly working with **_PHP (object-oriented) in Laravel on AWS_**
- Build a lot of new features / expand core components in an output-driven work environment
- Mostly working on (complex) backend topics but also building internal & external API’s that
process huge amounts of data

## Local
Hamburg in Germany or Amsterdam in Netherlands

## Benefícios
The salary is competitive with the top companies in Germany/Netherlands and depends on what you bring to the table in terms of skills, personality and other experience. Secondary benefits are mentioned throughout this page but things we did not mention yet are; Holidays, laptop of choice, travel allowance, _**relocation help for internationals**_, training budget, 40% discount on products, VISA sponsorship, free Laracast account, regular Events, free yoga or language courses, flexible hours etc.

#### Diferenciais

- **relocation help for internationals**
- **VISA Sponsorship**

## Requisitos

**The must-have skills are**: 
- **English Advanced**
- Backend PHP on Laravel or Symfony,
- MySQL, 
- Git or BitBucket
- Jira 

**The good-to-have skills are**: 
- AWS,
- DevOps (CI/CD etc.), 
- Redis, 
- MongoDB, 
- e-Commerce

## Nossa empresa

Sprint & Partners is an Recruiting Agency in Amsterdam and we are hiring PHP developer to work for two e-Commerce clients. One located in Hamburg and other in Amsterdam.

## Como se candidatar

Por favor envie um email para michaelgottfridsson@gmail.com com seu CV anexado - enviar no assunto: PHP e-Commerce position

## Labels

- senior professional
- relocations package
- visa sponsorship

**Comment by ravanscafi** [comment]
thanks for posting this position @johnmichaelgott! I took the liberty to update the title. I will look into make this repo friendlier for non-portuguese speakers in the future 😉

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
