### ISSUE TITLE
[Amsterdam/Holanda] PHP Developer na SCRiBBR

### ISSUE THREAD

**Issue by kbca** [phpdevbr/vagas#218]
## Descrição da vaga

Você vai trabalhar no produto principal (único) da empresa, que se chama Houston.
Houston é usado por estudantes (nossos clientes), equipe operacional, equipe de marketing e o time de gerencia para manter a Scribbr funcionando perfeitamente. Estamos melhorando Houston todos os dias para automatizar cada vez mais nossos processos e os serviços que entregamos.
 
#### Algumas features do Houston
- Análise automática de documentos para rastrear e verificar a performance dos nossos editores freelancer
- Operações em várias moedas e vários idiomas; Estudantes do mundo todo usam nossos serviços
- Atribuição automática de novos pedidos a um dos nossos editores disponíveis
- CRM-system completo para auxiliar os nossos estudantes
- Serviço de detecção de plágio

## Local

No centro de Amsterdam, [TQ Prédio](https://www.google.com/maps/place/TQ/@52.3667082,4.8910731,18.25z/data=!4m5!3m4!1s0x47c609ea9f09d0bf:0x45d87e43633373ea!8m2!3d52.3666038!4d4.8927234) Prédio dividido por várias startups, com 3 andares, salão de jogos, 10 minutos de bike da estação central.

## Benefícios

- Transporte
- Almoço (comida típica holandesa)
- 25 Dias úteis de férias

#### Diferenciais

- Budget anual para gadgets
- Ótimo setup de trabalho (dois monitores de 32 dell, computador dell/mac)
- Drinks grátis na sexta-feira
- Passeio de barco com o barco da empresa pelos canais de amsterdam
- Geladeira com rango sempre cheia (free)
- Salão de jogos
- Auxílio mudança (Para família de primeiro grau)

## Requisitos

**Obrigatórios:**
- 5+ Anos de experiência com OOP PHP.
- Usa ativamente princípios SOLID
- Ansioso para pegar tarefas complexas
- Experiência melhorando código e arquitetura. Você sabe o que melhorar primeiro, como e quando.
- Ansioso para aprender as regras de negócio
- Experiencia com SCRUM/Agile process
- Inglês Avançado / Fluente

**Diferenciais:**
- DDD
- CQRS

## Contratação

- Contrato

## Nossa empresa

Somos uma família de graduados que têm um objetivo mútuo: Ajudar estudantes a se graduar!

Scribbr ajuda mais de 200 estudantes por dia, oferecendo serviços de revisão e edição textual, detecção de plágio e mais de 1.000 artigos escritos sobre tese.

Juntos com nosso time em Amsterdam, e mais de 500 editores freelancers, fazemos tudo possível para fornecer o melhor serviço ao estudantes. Essa paixão nos proporcionou uma média satisfação de clientes de 9.9/10 de mais de 1.000 reviews.

## Como se candidatar

Vá no nosso [site](https://jobs.scribbr.com/senior-php-developer-amsterdam/en) e clique em [Apply now](https://jobs.scribbr.com/senior-php-developer-amsterdam/en/apply)

## Labels

- Sênior

**Comment by vinyguedess** [comment]
Enviei

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:
