### ISSUE TITLE
[Luxemburgo/Luxemburgo] PHP Developer at Docler Holding

### ISSUE THREAD

**Issue by quintanilhar** [phpdevbr/vagas#219]
## Descrição da vaga

- Work with multiple technologies: PHP, MySQL, MSSQL, MongoDB, Memcache, Redis, RabbitMQ, FMS, other distributed and in-house built systems
- High availability systems
- High traffic systems (35 million daily visitors)
- 2000 servers distributed among 4 datacenters worldwide
- Take part in the research of new technologies and solutions

## Local

Luxembourg/Luxembourg

## Benefícios

- Relocation package and support
- Meal vouchers
- Private health insurance
- Sympass card
- Conferences, certifications, technical workshops, trainings and language courses
- Latest hardware, multiple monitors

#### Diferenciais

- Chill rooms, creative areas, LAN parties and fun events
- Voted as the second richest country in the world, Luxembourg offers a high quality of life that is hard to match 
- Multi-cultural environment, 30 different nationalities, English being the official language

## Requisitos

**Obrigatórios:**

- 3 years of software development experience (in PHP projects)
- OOP skills and knowledge of design patterns
- Clean Coding is your most important principle
- Experience with Relational Databases and NoSQL technologies
- Passionate about self-improvement and web technologies
- Upper intermediate English knowledge (B2) or higher

**Desejáveis:**

- Experience in any other Web Development technology
- Knowledge of Unit Testing and Test Driven Development

- Familiarity with Extreme Programming (XP)
- Knowledge of Agile methodologies

**Diferenciais:**

- Experience with Live Streaming and Stream Encoding technologies
- Experience working with high-availability, high-performance, scalable systems

## Contratação

Relocation required to Luxembourg

## Nossa empresa

Does the thought of working with Scalable Web Architecture intrigue you? Over 200 developers are working around the world (and clock) always ensuring that our service maintains its highest standard at all times. If you would like to join a diverse international team and work on interesting projects that challenge your knowledge and expertise, you’re the kind of person we want! Come and join us at our headquarters in Luxembourg!

## Como se candidatar

Por favor envie um email para ricardo.quintanilha@doclerholding.com com seu CV anexado - enviar no assunto: PHP Developer DH

## Labels

- CLT
- Pleno
- Sênior

**Comment by vinyguedess** [comment]
Sent

**Comment by ravanscafi** [comment]
favor repostar caso ainda esteja em aberto :wink:

**Comment by quintanilhar** [comment]
Nós ainda temos bastante vagas na empresa, se tiver interesse é só encaminhar o seu cv no email citado acima. :D

**Comment by ravanscafi** [comment]
@quintanilhar sou o adminstrador do repo, só fechei vagas que pareciam antigas/abandonadas. se quiser repostar, ganha uma nova divulgação nos slacks que estão integrados com esse repo :wink: 

(PS: estive em luxemburgo mês passado, devia ter passado aí pra tomar um café hahaha)
