### ISSUE TITLE
[Joinville/SC] Desenvolvedor(a) PHP/WooCommerce na Volts Digital

### ISSUE THREAD

**Issue by eversonjp** [phpdevbr/vagas#22]
## DESCRIÇÃO

Se você é um desenvolvedor back-end com experiência em e-commerces e já domina o WordPress e o WooCommerce, é perfeito. Você DEVE trabalhar aqui conosco. Caso conheça muito bem o Magento, também tá bem legal e podemos conversar a respeito.

## LOCAL

Presencial em Joinville / SC (2a melhor cidade do Brasil para se viver :)

## BENEFÍCIOS

- Salário justo com sua experiência;
- Plano de saúde 100% subsidiado;
- Auxílio refeição pago em dinheiro para ser utilizado como preferir;
- Vale-transporte;
- Aquisição de livros, sob demanda;
- Subsídio de cursos, sob demanda e análise;
- Comemorações de aniversário com um bolo delicioso, pago por nós;
- Mesa de sinuca e café da tarde compartilhado;
- Ah sim, café infinito também!

## REQUISITOS

**Obrigatórios:**
Gostaríamos muito que você fizesse TDD nos projetos mais complexos e que soubesse de metodologias ágeis, Git flow, clean code e PHP. Claro que é importante que você já tenha experiência na área e que seja muito responsável pois essa posição exige isso. Sua dedicação sempre será reconhecida e seu espírito colaborativo deve ser aflorado, pois compartilhamos muito conhecimento entre o time. Ah, bom humor é indispensável! :)

**O que você vai precisar fazer:**
Nesta posição, você irá analisar e recomendar soluções, estimar e detalhar atividades de desenvolvimento, implementar novas linguagens e tecnologias, guiar e trabalhar em conjunto com o time de desenvolvimento, arquitetar e desenvolver projetos de e-commerces e intermediar contatos com serviços de terceiros como gateways de pagamentos e servidores, por exemplo.

## CONTRATAÇÃO

Por CLT ou PJ.

## SOBRE A VOLTS DIGITAL

Começamos dizendo que este carma de ser agência é uma m*. Que vida de agência só dá estresse, que “ninguém merece” e que fazer horas extras é “normal”. Queremos dizer que não. Não é normal, não é bom e que realmente ninguém merece. A gente não trabalha assim por aqui. Obviamente exigimos comprometimento e dedicação das pessoas para que tudo ande dentro dos conformes. É uma via de duas mãos: ser produtivo para ter organização e vice-versa.

Fundada em 2011, a Volts Digital é uma agência de marketing digital orientada a entrega de resultados através do empoderamento de seus clientes e do fortalecimento de marca para uma perspectiva a longo prazo. 

Nosso jeito de trabalhar é diferente e é isso que você precisa saber:

- Gostamos de sair no horário;
- Gostamos de desafios e sermos desafiados;
- Adoramos inovação e mudanças tecnológicas que nos levam a aprender mais;
- Zelamos muito por uma equipe estável, sem rotatividade;
- Trabalhamos muito para ser a mudança nos negócios de nossos clientes;
- Temos um ambiente bacana com pessoas muito especiais;
- Projetos que vão te tirar da zona de conforto;
- Ampla abertura para inovações e experimentações;
- Pautas de trabalho bem definidas;
- Sem “loucuragem” de prazos inacreditáveis e impossíveis de serem cumpridos;
- Feedbacks constantes e conversas transparentes.

## COMO SE CANDIDATAR

Temos certeza que você irá curtir trabalhar aqui, porque somos muito legais. Então envie seu currículo para vagas@voltsdigital.com.br com o título #DEVnaVOLTS juntamente com sua pretensão salarial e disponibilidade para início que vamos analisar e te dar um retorno, sem falta. Nunca deixamos de responder os e-mails e os candidatos. Achamos isso uma falta de respeito enorme com quem se dispõe a falar conosco.

Ah, muito importante: A vaga é presencial na cidade de Joinville/SC. Caso seja de outra cidade, deve ter disponibilidade para mudar-se.

**Comment by nic** [comment]
@eversonjp Vaga preenchida?

**Comment by eversonjp** [comment]
Não ainda. Podemos conversar se tive interesse ;)

**Comment by nic** [comment]
@eversonjp Estou organizando as issues abertas aqui (fechando as que já estão preenchidas). Boa sorte meu amigo. :)

**Comment by Piulres** [comment]
Tenho interesse, http://renan.zz.mu

**Comment by rscafi** [comment]
@eversonjp Vaga preenchida?

**Comment by eversonjp** [comment]
Estamos sempre abertos a novos talentos. Dá uma olhada aqui: http://voltsdigital.com.br/trabalhe-conosco

Valeu!

**Comment by ravanscafi** [comment]
Olá @eversonjp,
A vaga ainda está aberta?

_(sou administrador das vagas e estou fechando as que já foram preenchidas)_

**Comment by eversonjp** [comment]
Oi @ravanscafi, estamos com a vaga em aberto. Podemos mantê-la :)

**Comment by eversonjp** [comment]
@ravanscafi pode fechar então. Vou abrir uma issue nova. Obrigado!
