### ISSUE TITLE
[São Paulo/SP] PHP Developer Jr e Sênior na Uello

### ISSUE THREAD

**Issue by jmarcelocjr** [phpdevbr/vagas#229]
## Descrição da vaga

Estamos procurando developers Jr. e Sr.  para fazer parte do nosso time.

## Local

Escritório, São Paulo - Vila Leopoldina

## Benefícios

- VT
- VR

#### Diferenciais

- Horários flexiveis
- Possibilidade de Home Office

## Requisitos

**Obrigatórios:**
- PHP 7
- Microservices
- Rest API
- Linux
- MySQL

**Desejáveis:**
- Metodologia Agile
- Docker
- Framework: Silex/Laravel

**Diferenciais:**
- Data Science
- Machine Learning
- Android
- C++

## Contratação

PJ/CLT a combinar

## Nossa empresa

A Uello é uma startup de entregas e fretes urbanos focada em pequenos e médios negócios. Utilizamos tecnologia e otimização de ponta para viabilizar serviços com alto grau de customização, acessível e de grande conveniência para nosso clientes.

## Como se candidatar

Por favor envie um email para marcelo.cerqueira@uello.com.br com seu CV anexado.

## Labels

- Alocado
- CLT
- PJ
- Júnior
- Sênior
- Remoto - Parcial

**Comment by jmarcelocjr** [comment]
@guilhermeoa07 , bom dia!

A entrevista inicial seria via Skype, caso ambos lados tenha interesse em dar continuidade, é feito um bate papo presencial.

**Comment by guilhermeoa07** [comment]
No meu caso sou de fora do Estado, só poderia ir em caso de contratação, então o processo teria de ser totalmente remoto, é possível?

**Comment by jmarcelocjr** [comment]
@guilhermeoa07 Acredito que seja possível sim, poderia me encaminhar seu CV pelo email informado na vaga?

Obrigado!

**Comment by guilhermeoa07** [comment]
Ok. Vou enviar logo que chegar em casa

**Comment by leonampd** [comment]
@irwing-max :point_up:

**Comment by moreiraandre** [comment]
@jmarcelocjr Currículo enviado!

**Comment by ravanscafi** [comment]
@moreiraandre evite fazer spam por favor, tem mais de 15 notificações suas, todo mundo do repositório recebe por email, não é muito legal :confused:
