### ISSUE TITLE
[Franca/SP] Desenvolvedor(a) PHP Pleno/Senior na MazzaFC

### ISSUE THREAD

**Issue by rafaelqm** [phpdevbr/vagas#232]
## Descrição da vaga

Diversos projetos sob-demanda de vários clientes da empresa.

## Local

Remoto ou Escritório, Franca - São Paulo - Centro
Franca-SP,  possibilidades para Ribeirão Preto-SP e Campinas-SP.

## Benefícios

- Flexibilidade de horário
- Ótimo ambiente
- Projetos desafiadores

## Requisitos

**Obrigatórios:**
- 3 anos de experiência
- PHP 7
- Laravel (mín. 5.3)
- MySQL
- AWS ou AZURE
- GIT
- Javascript
- CSS

**Desejáveis:**
- Node

**Diferenciais:**
- projetos opensource

## Contratação

PJ a combinar

## Nossa empresa

A MazzaFC é uma empresa completa especializada em outsourcing de sistemas e profissionais de TI, provedora também de outras soluções em TI para empresas dos mais variados segmentos.
Atendemos por completo as necessidades das empresas das regiões de Franca, Ribeirão Preto, Campinas, Sorocaba, São Paulo, possibilitando que alcancem metas e objetivos pré definidos. Afinal, nossa missão a partir de agora também é transformar oportunidades em sucesso, impulsionando o potencial de cada profissional através da precisão em identificar talentos.
Para atingir tal objetivo, continuamos valorizando o capital humano, nosso time de profissionais especializados e apaixonados por TI, além é claro, do respeito aos ideais de cada cliente.

Tire suas dúvidas, conheça nossos serviços e seja muito bem-vindo!

https://www.linkedin.com/company/mazzafc/
https://www.mazzafc.tech/

## Como se candidatar

Por favor envie um email para lais.bernardes@mazzafc.tech e caio.padovani@mazzafc.tech com seu CV anexado - enviar no assunto: Vaga PHP

## Labels

- Alocado
- Remoto
- PJ
- Pleno
- Remoto - Parcial
- Remoto - Total
- Sênior

**Comment by jonaswebdev** [comment]
mandei email :)

**Comment by vinyguedess** [comment]
Enviado

**Comment by rafaelqm** [comment]
Vou falar com o pessoal do RH. @jonaswebdev

**Comment by joubertredrat** [comment]
@rafaelqm vagas ainda abertas? Grato.

**Comment by rafaelqm** [comment]
Sim, apenas presencial.

**Comment by mvnp** [comment]
Disponível para trabalhos remotos. Experiência em PHP e muita lógica na veia. Sou adminsitrador de Programadores Incríveis no facebook (https://www.facebook.com/groups/programadoresincriveis). Abraço

**Comment by moreiraandre** [comment]
@rafaelqm currículo enviado!

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
