### ISSUE TITLE
[São Paulo/SP] Back-End Developer na McCANN Health 

### ISSUE THREAD

**Issue by tiagords** [phpdevbr/vagas#237]
## Descrição da vaga

Contratação PJ desenvolvedor(a) para vaga de Back-End.

## Local

Rua Loefgren 2527 
04040-033 - SP 
Vila Clementino  (Metro Santa Cruz)
São Paulo

## Benefícios

- VR

## Requisitos

**Obrigatórios:**
- PHP7 (Intermediário)
- MySQL
- Laravel
- Wordpress

**Desejáveis:**
- Conhecimentos em Git
- Conhecimentos em Angular ou Vue.js

**Diferenciais:**
- Joomla

## Contratação

PJ

## Como se candidatar

Por favor envie um email para alvaro.silva@mccannhealth.com.br e tiago.rodrigues@mccannhealth.com.br com seu CV em anexo e pretensão salarial.

## Labels

- Semi Presencial
- PJ
- Sênior

**Comment by helderjosex** [comment]
Possibilidade full time remoto?

Em Ter, 31 de jul de 2018 00:01, Tiago Rodrigues <notifications@github.com>
escreveu:

**Comment by jonaswebdev** [comment]
Oi, vocês poderiam me explicar/detalhar o que seria "Semi Presencial"?

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
