### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) PHP na WeJam Digital

### ISSUE THREAD

**Issue by crispossa** [phpdevbr/vagas#239]
### Descrição
Vaga para desenvolvedor(a) PHP para dar manutenção em projetos que estão ativos, desenvolver novas features e apoiar no desenvolvimento de novos projetos.
A maioria dos projetos é em PHP mas utilizamos também outras linguagens como Node e Python.

### Skills necessárias
- PHP 7+
- Laravel 5.1+
- MySQL intermediário (Procedures, Functions, Joins, Views)
- Noções dos principais Design Patterns
- Git
- Lógica aplicada a solução de problemas
- HTML Básico
- JS Básico

### Skills desejáveis
Pelo menos 1 delas é esperado que vc domine.
- NodeJS
- Python
- Crawling
- MongoDB ou outro banco de dados não relacional
- Graph DB (Neo4J ou ArangoDB)
- Excel (Macros e Fórmulas)
- DevOps
- PostgreSQL avançado

### Contratação
- Alocado
- PJ (Pode ser MEI)
- R$ 2 a 3k (dependendo do nível)
- Início imediato

### Benefícios
- 13º salário
- Férias remuneradas

### Sobre a WeJam
Somos uma agência com DNA digital que desenvolve projetos de alta qualidade e com grande impacto em negócios, desde sites institucionais até plataformas de treinamento e gamification.

Somos uma agência com uma proposta diferente. Não apenas executamos jobs, mas criamos envolvimento com nossos clientes e projetos.

Participamos desde a concepção do projeto até sua publicação numa filosofia ponta-a-ponta, onde planejamos, construímos e desenvolvemos ideias incríveis.

Venha fazer parte da nossa equipe!

We Ad! We Rock! We Jam!

Tags: PJ, PHP, Presencial, Junior, Senior

**Comment by xtfs** [comment]
2-3k pj, é pra trabalhar quantas horas por semana?

**Comment by crispossa** [comment]
@xtfs a carga horária da agência é das 9 as 18 de segunda a sexta, com flexibilidade de horários.

**Comment by marcosvicente** [comment]
Qual é o local da agência?

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
