### ISSUE TITLE
[Belo Horizonte] Desenvolvedor Full Stack | conta.MOBI

### ISSUE THREAD

**Issue by rhcontamobi** [phpdevbr/vagas#24]
## Descrição da vaga

ATIVIDADES:
•	Entender toda a estrutura de desenvolvimento definida pela empresa;
•	Sinalizar possíveis problemas ou a trazer as soluções mais adequadas;
•	Proteger e resguardar os produtos e processos;
•	Estar atento às regras definidas para o desenvolvimento de um projeto de software.

## Local

Belo Horizonte/MG

## Benefícios

Salário: a combinar
Benefícios: VT + Vale Alimentação
Horário de Trabalho: 08h30 ás 18h18

- ...

## Requisitos

PRÉ REQUISITOS:
•	Formação na área de Tecnologia da Informação, preferencialmente em Desenvolvimento de Software;
•	Conhecimento de linguagens de programação, bancos de dados, softwares, frameworks, metodologias e ferramentas para projetar, desenvolver, testar e acompanhar o ciclo de vida de um projeto de desenvolvimento de software, como:
o	Sistemas Operacionais
o	Ferramentas de versionamento e de virtualização
o	Servidores web e hospedagem
o	Design de interface
o	UX – Experiência do usuário
o	Web Services
o	Desenvolvimento e manipulação de APIs
o	Frameworks de desenvolvimento
o	Padrões de arquitetura

## Contratação

CLT Efetivo

## Nossa empresa

A ideia da conta.MOBI surgiu em 2013 como forma de  facilitar a gestão de recursos e diminuir a burocracia para Microempreendedores Individuais (MEI). 
Em 2015 o projeto foi lançado e desde então já são milhares de usuários habilitados. A conta.MOBI oferece possibilidades que vão desde a assistência contábil até a contratação de planos de saúde. 
O que move a empresa é a certeza de que o fortalecimento efetivo da economia como um todo passa necessariamente pela valorização, regularização e inclusão do micro e pequeno empresário. 

http://www.conta.mobi

## Como se candidatar

Interessados deverão enviar o currículo atualizado para rh@conta.mobi com o assunto DESENVOLVEDOR FULL STACK.

**Comment by nic** [comment]
@rhcontamobi Vaga preenchida?

**Comment by rhcontamobi** [comment]
@nic Estamos com uma posição ainda em aberto!

**Comment by rscafi** [comment]
@rhcontamobi Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.
