### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) PHP na 2mundos

### ISSUE THREAD

**Issue by vsardito** [phpdevbr/vagas#244]
## Descrição da vaga

This developer will be working with PHP and MySQL. The professional will work with the API team, creating new API endpoints and providing maintenance to the existing ones.

Daily tasks also include creating database schemas, procedures, optimization, importing large amounts of data and data migration.

## Local

Escritório, São Paulo - Vila Madalena

## Benefícios

Relaxed environment and a dress down culture
 Flat organizational structure
 Next Star Wars launch will be day off

## Requisitos
- Good communications skills in spoken English
- Ability to follow code standards is a must
- PHP5 (raw PHP with no frameworks)
- OOP (Classical OOP, Namespaces)
- Experience in JSON based APIs
- Experience in Object-relational mapping (ORM)
- Database modelling (layout, indexes, foreign keys)
- Ability to write MySQL stored procedures and functions
- Experience writing SQL intensive scripts for stats/data warehousing purposes
- Proficiency in using Git from the command line
- Ability to comment code as you go

**Desejáveis:**
- Real-time infrastructure experience (Meteor, Socket.io, Node.js)
- Front-end development using AngularJS

## Contratação

PJ a combinar

## Nossa empresa

https://www.2mundos.net

## Como se candidatar

Por favor envie um email para jobs@2mundos.net com seu CV anexado - enviar no assunto: Vaga PHP

**Comment by filipecsweb** [comment]
job@2mundos.net email incorreto.

**Comment by vsardito** [comment]
Alteração efetuada ... e-mail correto jobs@2mundos.net 
Obrigada

**Comment by vsardito** [comment]
Obrigada ... Já arrumei.

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
