### ISSUE TITLE
[São Paulo/SP] PHP Developer na Auditto Tecnologia

### ISSUE THREAD

**Issue by fabricio-auditto** [phpdevbr/vagas#246]
## Descrição da vaga

Empresa de Tecnologia em forte crescimento na área fiscal está a procura de profissionais com os seguintes requisitos para atuar em projetos WEB gestão e integração entre sistemas

## Local

Escritório, São Paulo - Morumbi (próximo ao shopping Jardim Sul)

## Benefícios

- Alimentação
- Transporte

## Requisitos

**Obrigatórios:**
- Trabalho em equipe
- Metodologia MVC
- Banco de dados MySQL
- Interface Bootstrap + JQuery
- Versionamento em Git
- Webservices SOAP/REST

**Diferenciais:**
- Dinamismo e capacidade de análise
- Uso de tecnologias de Crawling e Scraping
- Plataforma AWS
- Microservices
- Trabalhado com temas tributários/fiscais: NFe, SPED, 

## Contratação

PJ a combinar

## Nossa empresa

AUDITTO é uma empresa inovadora na recuperação de crédito de ICMS e PIS/COFINS, auditoria e gestão de documentos fiscais eletrônicos, unindo sua expertise em Sistemas Web e Tecnologia Cloud Computing ao know-how fiscal de seus colaboradores e parceiros.

## Como se candidatar

Por favor envie um email para vagas@auditto.com.br com seu CV anexado - enviar no assunto: Vaga PHP

## Labels

- PJ
- Pleno

**Comment by grrlopes** [comment]
Ola,
Esse vaga contempla trabalho remoto ?

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
