### ISSUE TITLE
[São Paulo/SP] FullStack Developer na ExpVentures

### ISSUE THREAD

**Issue by lgaitan** [phpdevbr/vagas#248]
## Descrição da vaga

Programador full stack junior para atuação em projeto startup dentro de uma aceleradora de startups :brazil:

## Local

Escritório ao lado do metro Paulista. Ambiente moderno e descontraido

#### Diferenciais

- Sala de jogos
- :coffee: Free Coffee whole day
- :beer: free beer

## Requisitos
- HTML5, CSS3, JS  Front-end.
- Noções de UI/UX Design.
- PHP
- REST Api
- Bancos de dados SQL opensource
- Git/Github

**Desejáveis**
- Npm e Webpack
- noSQL

## Contratação

PJ a combinar

## Nossa empresa

A Exp é uma aceleradora de projetos de inovação, especializada em startups

## Como se candidatar

Entrar em contato através do email selecoes@expventures.com.br com seu CV anexado - enviar no assunto: Vaga desenvolvedor - [Nome]

## Labels

- Júnior
- PJ

**Comment by guilhermeoa07** [comment]
Olá, a entrevista pode ser remota?

**Comment by guilhermeoa07** [comment]
@lgaitan é que moro em outro estado, mais tenho disponibilidade para mudança, caso seja contratado.

**Comment by lgaitan** [comment]
@guilhermeoa07, temos preferência por pessoas de sp e região, e também necessitamos de inicio ASAP.

Obrigado

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
