### ISSUE TITLE
[Catalão/GO] Desenvolvedor(a) Web na Fretebras (Encerrado)

### ISSUE THREAD

**Issue by pedrosalpr** [phpdevbr/vagas#250]
## Descrição da vaga

Estamos a procura de um profissional com conhecimento pleno em desenvolvimento web, que goste realmente de programar, seja focado na qualidade das entregas e goste de ambientes dinâmicos. Estar disposto a aprender é extremamente importante!

Contamos hoje como principal linguagem o PHP,  mas aqui você também irá trabalhar com NodeJS, API's, Angular, AWS Amazon, Mongo, integração contínua, code review, Git, Jenkins e Big Data, tudo isso em um ambiente focado em desenvolvimento ágil.

Na Fretebras o time tem liberdade de explorar novas tecnologias com desafios que são criados mensalmente, além de promover tech talks.

## Local

Escritório, Catalão - GO

## Benefícios

- Plano de saúde
- Vale-alimentação
- Custeio de eventos/treinamentos
- Day off no dia do aniversário

#### Diferenciais

- Café Expresso (Nespresso)
- iMac ou Macbook

## Requisitos

**Diferenciais:**
- Gostar de programar!
- Ter experiência profissional ou colaboração com projetos open-source
- Conhecer Orientação a Objetos e técnicas de refatoração
- Ter muita vontade de aprender e pesquisar novas tecnologias
- Entender que diferentes linguagens podem trazer diferentes benefícios
- Gostar de trabalhar em equipe

## Contratação

CLT - Pleno

## Nossa empresa

- Empresa: Fretebras
- Site: www.fretebras.com.br
- App: https://goo.gl/W3KKtL

A Fretebras é uma empresa de tecnologia que atua no setor de transporte de cargas e é líder de mercado em divulgação de fretes. Disponibilizamos ferramentas que permitem o compartilhamento de veículos de diferentes empresas para o transporte de cargas, possibilitando que motoristas autônomos e frotistas (através de computadores, celulares ou tablets) encontrem fretes compatíveis com as características e posição geográfica de seus veículos.

Na contramão da crise, a Fretebras só cresce. Fundada em 2008, a empresa possui mais de 100 milhões de pageviews/mês e aplicativo Android com quase 600 mil downloads.

## Como se candidatar

Envie seu currículo para jobs@fretebras.com.br com o título: Desenvolvedor Web.

**Comment by rbezerra** [comment]
Aceitam remoto?

**Comment by pedrosalpr** [comment]
Apenas alocado, a entrevista pode ser remota.

**Comment by pedrosalpr** [comment]
Vaga encerrada.
