### ISSUE TITLE
[São Paulo/SP] PHP Developer na PontoCode

### ISSUE THREAD

**Issue by leoallvess** [phpdevbr/vagas#251]
## Descrição da vaga

Procuramos um(a) Desenvolvedor PHP Pleno / Sênior com vontade de aprender e ensinar, disposto a vestir a camisa e crescer conosco. 
Estamos modelando nossos processos, então sua experiência será importante para nós.

## Local

Avenida Paulista, próximo ao metro consolação, São Paulo

## Requisitos

**Obrigatórios:**
- Experiência significativa com desenvolvimento em php 5+
- Experiência com laravel 5+
- Controle de versão com git
- Vagrant
- Mysql
- Comprometimento

**Desejáveis:**
- Experiência em plataformas open source (wordpress e magento)
- Experiência em integrações com apis
- Aws
- Npm
- Estrutura de servidores e processos de deploy
- Proatividade para resolução de problemas

**Diferenciais:**
- projetos opensource

## Contratação

PJ a combinar

## Nossa empresa

Somos uma software house nova em busca do nosso espaço no mercado!!

## Como se candidatar

Por favor envie um email para leonardoalves@coldvector.com com seu CV anexado - enviar no assunto: Vaga PHP

## Labels

- Alocado
- PJ
- Pleno
- Sênior

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
