### ISSUE TITLE
[Vinhedo/SP] PHP Developer na AGV Logística

### ISSUE THREAD

**Issue by caiquebb** [phpdevbr/vagas#254]
## Descrição da vaga

A AGV desafia você a fazer parte do nosso time de desenvolvedores e utilizar tecnologia para deixar processos logísticos ágeis e com transparência. 
 
Buscamos pessoas que queiram fazer parte do nosso time em Vinhedo, e que gostem de desenvolver e experimentar novas tecnologias tanto no desenvolvimento de nossos sistemas de apoio (TMS, WMS e ERP) quanto nas inovações como mapas interativos para visualização das rotas, acompanhamento das entregas e acompanhamento e suporte aos nossos motoristas através de aplicativos mobile e portais na web. Temos oportunidades para Pleno e Sênior. 

## Local

Remoto Parcial, Vinhedo - SP

## Requisitos

**Obrigatórios:**
- Linguagens: PHP7+ Javascript, HTML5 e CSS3 
- Frameworks/Bibliotecas: Laravel 5.4+, JQuery 
- Versionamento: GIT 
- Ferramentas: Composer, NPM 

**Desejáveis:**
- Experiencia com bancos de dados relacionais (MySQL, SQL Server) 
- Experiencia na Construção e Consumo de APIs 

**Diferenciais:**
- Javascript ES6+ 
- Vue.js 
- Webpack 
- Docker 
- IONIC 

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para thales.padovani@agv.com.br com seu CV anexado - enviar no assunto: Vaga PHP

## Labels

- Alocado
- PJ
- Remoto - Parcial
- Pleno
- Sênior

**Comment by helderjosex** [comment]
Aceita remoto full time?

Em Seg, 3 de set de 2018 14:03, Caique Bertolozzi <notifications@github.com>
escreveu:

**Comment by caiquebb** [comment]
@helderjosex tem algumas reuniões presenciais que são quinzenais em algum casos semanais.

**Comment by moreiraandre** [comment]
@caiquebb currículo enviado!

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
