### ISSUE TITLE
[Campinas/SP] Fullstack PHP Developer Pleno na Dcide

### ISSUE THREAD

**Issue by dcide** [phpdevbr/vagas#257]
## Perfil do Profissional

• Capacidade de realizar uma grande quantidade de trabalhos importantes e de impacto;
• Ter a habilidade de identificar causas raízes de problemas, ao invés de ficar atuando somente sobre os sintomas, mostrando domínio de conceitos como depuração, testes e organização;
• Capacidade de articulação e precisão na fala e escrita, de maneira a conseguir expor claramente seus pontos de vista, sabendo ouvir, e mantendo um nível de diálogo e respeito compatível com o grau de profissionalismo da empresa.
• Nível de desempenho alto, consistente e contínuo, de maneira a inspirar confiança dos outros funcionários e se tornando referência para todos da empresa;
• Sabedoria para tomar decisões, tomando riscos de forma inteligente e demonstrando
capacidade de priorização e pragmatismo;
• Capacidade de aprendizado rápida e espontânea se mantendo atualizado e
sugerindo novas tecnologias, processos ou ferramentas que venham a trazer
benefícios;
• Buscar entender nossa estratégia, mercado, clientes e fornecedores, não se
restringindo a um técnico generalista;
• Redefinir conceitos e processos para encontrar soluções práticas e factíveis para
problemas complexos;
• Inspirar os outros com sua busca por excelência, demonstrando legítimo prazer pelo
que faz, desafiando-se a melhorar continuamente;
• Ser franco e direto, mantendo o respeito e a polidez;
• Ter postura agregadora, contribuindo para a melhoria do ambiente de trabalho e
produtividade da equipe;

## Perfil Técnico
- Mínimo de 4 anos de experiência como desenvolvedor PHP com demonstrada
capacidade em HTML, CSS e JS;
- Experiência em desenvolvimento de aplicações com Angular JS;
- Experiência em desenvolvimento de sistemas de alta complexidade;
- Experiência com framework CakePHP e Zend Expressive e eventualmente outros de
mercado;
- Experiência em desenvolvimento de API e Webservices;
- Experiência com Bootstrap;
- Facilidade de construir gráficos interativos em diversos frameworks;
- Capacidade de desenvolvimento de aplicações responsivas;
- Experiência na modelagem de dados relacionais e em escrita de código PL/SQL;
- Domínio do paradigma de orientação à objetos empregando princípios SOLID e
padrões de projeto;
- Conhecimento em aplicação de testes unitários e testes de aceitação;
- Conhecimento de Continuous Integration e ferramentas de deploy;

**Diferenciais**
- Experiência com componentes Kendo UI;
- Conhecimento em desenvolvimento mobile;
- Conhecimento de MongoDB e NoSQL;
- Utilização avançada de sistemas de controle de versão: Git
- Experiência em DDD e TDD;
- Experiência com padrão de arquitetura Message Bus;
- Facilidade para resolver problemas matemáticos;
- Conhecimento da linguagem de programação R
- Experiência em sistemas operacionais Linux.
- Experiência em segurança e criptografia de dados.

**Exemplos de Atribuições** 
- Ajudar a desenhar a arquitetura de backend e desenvolvimento de APIs;
- Garantir alta performance e escalabilidade das aplicações;
- Garantir uma aplicação modular e de baixo acoplamento;
- Realizar a revisão do código dos colegas;
- Prototipar e criar interfaces de usuário;
- Garantir alta performance do front-end;
- Garantir baixo acoplamento do Core da aplicação com frameworks JavaScript;
- Escrever código limpo, que funcione em todos os browsers e é referência para os demais desenvolvedores;
- Escrever testes de unidade e aceitação tanto no backend como frontend;
- Ajudar a definir e implantar processos de integração continua para desenvolvimento backend;

## Local e horário de trabalho

- Local: Centro de Campinas, SP.
- Horário: De segunda a sexta, das 8h às 17h.

## Dados da Contratação e Benefícios

- Regime de contratação: CLT, salário a negociar.
- Plano de saúde e odontológico.
- Vale de alimentação

## Nossa empresa

A Dcide é uma empresa de informação que tem como um dos seus pilares o desenvolvimento de plataformas de gestão e análise quantitativa voltadas para o setor de comercialização de energia elétrica do Brasil. Reconhecida por seus clientes por oferecer produtos e serviços de excelência é a principal referência de mercado para preços de energia elétrica e análise de risco, com produtos que atendem toda a cadeia de comercialização de eletricidade e com um abrangente portfólio de clientes, que inclui as mais importantes empresas do país.

Buscamos um profissional que terá como foco de atuação a construção de aplicações modernas, robustas, fluídas, amigáveis e flexíveis e que sejam a base para o desenvolvimento da nova geração de aplicações web e mobile da Dcide e também pela migração e manutenção das arquiteturas legadas que hoje possuímos.

Interagindo com os executivos da empresa, o profissional deverá ter capacidade de raciocínio e comunicação para compreender corretamente as necessidades do negócio e propor soluções rápidas, factíveis e eficientes com o objetivo de consolidar a Dcide como excelência em soluções para comercialização de energia elétrica.

Trabalhamos com metodologias ágeis de desenvolvimento, o que implica facilidade para trabalho em equipe, acurácia na estimação de prazos, dimensionamento de tarefas, capacidade de organização de código e alta performance na conclusão de trabalhos, minimizando possibilidade de refactoring.
O profissional deverá demonstrar especialidade em todas as etapas do desenvolvimento de softwares e contribuir constantemente com a melhoria continua do processo de desenvolvimento do time, aportando conhecimento e novas visões.

Visite nosso site: [Dcide](https://dcide.com.br)

## Como se candidatar

Por favor envie um email para contato@dcide.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Fullstack PHP Pleno

## Labels

- CLT
- Pleno
- Fullstack

**Comment by BiraCarvalho** [comment]
Moço, isso é descrição vaga para programador meamo ou para rei da Dinamarca?

-
Ubiratã Carvalho
Goiânia - GO

Em seg, 10 de set de 2018 11:10, Dcide <notifications@github.com> escreveu:

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
