### ISSUE TITLE
[Remoto] Back-End Developer

### ISSUE THREAD

**Issue by tuliovargas** [phpdevbr/vagas#258]
## Descrição da vaga

Buscamos um desenvolvedor com solidos conhecimentos em PHP e grandes habilidades com os seguintes frameworks: 
LARAVEL 5+;

**Comment by omarkdev** [comment]
Ficou um pouco confuso, é para freela?

**Comment by tuliovargas** [comment]
Sim.. será para Freela.

**Comment by andrezap** [comment]
é essêncial experiência com Vue? já que a vaga é backend e no assunto deve ser "LARAVEL". Pergunto pois tive interesse mas não possuo experiência com Vue mas com Laravel sim.

**Comment by deleugpn** [comment]
Essa vaga ainda está aberta?

**Comment by moreiraandre** [comment]
@tuliovargas currículo enviado!

**Comment by lucas-barros** [comment]
https://github.com/frontendbr/vagas/issues/1683?fbclid=IwAR3zRw-sKGhup2mHvWlZT6X7TRK6cFABkGAAtPYDMAXbY7sTmu9irsLcJ0Q
