### ISSUE TITLE
[Curitiba/PR] PHP Developer na Send4

### ISSUE THREAD

**Issue by rafael-iop** [phpdevbr/vagas#259]
## Descrição da vaga

Vaga para PHP backend developer júnior, pleno ou sênior.

## Local

Curitiba, Paraná.

**Desejáveis:**
- conhecimentos em Laravel

## Contratação

CLT ou PJ a combinar.

## Como se candidatar

Por favor envie um email para finger@send4.com.br com seu CV anexado - enviar no assunto: Vaga PHP

## Labels

- Alocado
- CLT
- Júnior
- PJ
- Pleno
- Sênior
- Laravel

**Comment by guilhermeoa07** [comment]
A entrevista pode ser remota?

**Comment by rafael-iop** [comment]
> A entrevista pode ser remota?

Bom dia Guilherme. 

Pode sim, só enviar as informações para o e-mail finger@send4.com.br.

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
