### ISSUE TITLE
[RS] Programador PHP Pleno/ Sênior - Meta

### ISSUE THREAD

**Issue by michelicamillo** [phpdevbr/vagas#26]
## Descrição da vaga
Estamos procurando novos integrantes para nosso time de PHP na nossa Fábrica de Software.

Priorizamos qualidade e valor de negócio e estamos inseridos em um local com ótima qualidade de vida no interior do RS.

O profissional atuará com desenvolvimento de diferentes sistemas em PHP.

## Local

Presencial, Recanto Maestro (20km de Santa Maria/RS)

## Benefícios

- Ambiente com ótima qualidade de vida;
- Nossa proposta de valor é "Aprendizado e Crescimento Profissional";
- Programa de Incentivo à Certificações;
- Programa Evoluir (incentivo à qualificação);
- Vale Transporte;
- Vale Refeição;
- Seguro de Vida;
- Plano de Saúde;
- Pleno Odontológico;
- Demais variáveis dependendo de cada forma de contratação.

## Requisitos

**Obrigatórios:**
- Experiência com em desenvolvimento PHP;
- Experiência com Javascript e CSS3;
- Conhecimento em Banco de Dados.

**Desejáveis:**
- Conhecimentos em Laravel
- Banco de Dados Oracle ou Postgres

**Diferenciais:**
- Vue.js ou outro framework frontend
- Inglês

## Contratação

CLT

## Nossa empresa

O Grupo Meta é uma consultoria de TI com mais de 26 anos de mercado e 06 escritórios no Brasil. A nossa proposta de valor é aprendizado e crescimento profissional, o que pode ser notado em todas as áreas da empresa.
A nossa fábrica de software está inserida em um local de alto nível de desenvolvimento pessoal e profissional no interior do Rio Grande do Sul.

## Como se candidatar

Ficou interessado ou possui indicações? Então envie um e-mail com o currículo para micheli.camillo@meta.com.br e venha fazer parte do time! :+1:

**Comment by Marlysson** [comment]
Preenchida?

**Comment by nic** [comment]
@michelicamillo Vaga preenchida?
