### ISSUE TITLE
[Florianópolis/SC] Fullstack PHP Developer na Blueticket

### ISSUE THREAD

**Issue by victorpinheiro** [phpdevbr/vagas#262]
## Descrição da vaga

Temos como propósito Aproximar as pessoas de experiências ao vivo, desenvolvendo ferramentas para os organizadores dos eventos gerenciarem seus eventos, além de tecnologias que permitam que os clientes comprem seus ingressos, seja através do site, aplicativos mobile ou das tecnologias para pontos de venda que também desenvolvemos.

Nossos produtos são utilizados diariamente por mais de 1 milhão de visitantes no nosso site, além de centenas de organizadores que emitem mais de 3 milhões de ingressos por ano na nossa plataforma

Estamos vivendo um momento muito especial, criando uma nova plataforma de gestão de eventos, utilizando nossos mais de 10 anos de experiências e aprendizados para criar um novo ambiente completo, possibilitando mais eficiência e recursos incríveis para organizadores e para o público final!

Quer embarcar nesse desafio? Conheça um pouco mais sobre nosso ambiente, sobre a vaga e o que esperamos de você:

## Local

Escritório, Florianópilis

## Benefícios e Diferenciais

Uma cultura que valoriza o compromisso com a excelência e a persistência para que o ótimo seja ainda melhor;
Um ambiente de trabalho leve e estimulante, com equipes engajadas pela busca da qualidade e satisfação dos nossos clientes;
Apoio no seu crescimento e aprendizado, com bolsas de graduação, pós-graduação, crédito para cursos e eventos de aprendizado externos;
Uma biblioteca corporativa, com a aquisição ilimitada de livros, baseada nas sugestões dos colaboradores;
Uma área de convivência com puffs para relaxar e instrumentos musicais para fazer aquele som;
Frutas frescas todos os dias e ginástica laboral;
Remuneração compatível com mercado e com suas atribuições;
Além dos benefícios básicos como Vale Alimentação/Refeição (você escolhe), Vale Transporte e Plano de saúde (após 3 meses)

## Requisitos

**Obrigatórios:**
Graduação em Análise e Desenvolvimento de Software, Ciências da Computação, Sistemas de Informação ou Desenvolvimento de Sistemas ou conhecimento equivalente;
Domínio em arquitetura de APIs RESTFul;
Experiência backend em PHP e disposição para desenvolver em outras linguagens;
Conhecimento em Javascript;
Conhecimento frontend em framework JS de mercado, HTML5, CSS (Material Design, Sass/Less);
Experiência com MySQL e modelagem de dados;
Vivência sobre a cultura do desenvolvimento de software ágil (Scrum, Kanban ou XP);
Conhecimento sobre integração contínua e os conceitos do Git(Hub) como branching, pull-requests, etc;
Gosto por atuar em um ambiente com foco no cliente, valorização pela comunicação e feedback, auto disciplina, empreendedorismo, autopercepção e autodesenvolvimento, etc.;
Inglês intermediário.

**Desejáveis:**
Conhecimentos avançados sobre os serviços da AWS;
Conhecimentos avançados em Laravel;
Conhecimentos avançados em PHP, ORMs e gerenciadores de dependências com Composer;
Experiência com desenvolvimento de APIs RESTful estáveis, seguras, confiáveis e escaláveis;
Gosto pelo desenvolvimento utilizando técnicas de TDD/BDD;
Experiência com integração de meios de pagamento.
**Diferenciais:**
- projetos opensource

**Responsabilidades:**

Escrever código claro, simples e otimizado utilizando orientação a objetos
Trabalhar no processo de construção de soluções, o que envolve projeto, requisitos, execução, manutenção e suporte
Trabalhar para melhorar nossas soluções existentes
Buscar constantemente seu aperfeiçoamento, mantendo-se atualizado sobre novas tecnologias e metodologias de desenvolvimento
Ter a proatividade em compartilhar seus conhecimentos, contribuindo com desenvolvimento profissional da equipe

**Tecnologias que utilizamos:**

Frameworks e Linguagens: Laravel, Vue.js (Vuetify), PHP
Banco de Dados: MySQL, Redis
Cloud: AWS, Docker
Ferramentas: Trello, Github, NewRelic

## Contratação

CLT

## Como se candidatar

Aplique para a vaga através do link: https://blueticket.recruiterbox.com/jobs/fk014rn/

## Labels

- Alocado
- CLT
- Fullstack
- PHP
- VueJS
- Javascript
- Laravel

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
