### ISSUE TITLE
[São Paulo/SP] Líder técnico PHP na Auditto

### ISSUE THREAD

**Issue by rowrodrigues** [phpdevbr/vagas#263]
## Descrição da vaga

Estou compartilhando para uma amiga minha do RH da empresa

O que nós buscamos:
Buscamos um Líder Técnico em Programação PHP, para atuar em todas as camadas dos projetos de desenvolvimento e na gestão e orientação da equipe técnica em todo o processo.

## Local

São Paulo - Morumbi

## Requisitos

**Obrigatórios:**
- Banco de dados MySQL
- Metodologia em MVC
- Versionamento em GIT
- JQuery / Bootstrap / Java Script / Ajax
- Conhecimentos profundos em PHP

**Principais atividades:**
- Desenhar estruturas de processos, integrações entre módulos, definindo Arquitetura
- Integração Contínua, Deploy
- Normatização de classes / métodos
- Classes de apoio: BD /Session / Usuário / Conta
- Revisar o código, solucionar problemas

## Nossa empresa

Descrição da Empresa:

AUDITTO é uma empresa inovadora na recuperação de crédito de ICMS e PIS/COFINS, auditoria e gestão de documentos fiscais eletrônicos, unindo sua expertise em Sistemas Web e Tecnologia Cloud Computing ao know-how fiscal de seus colaboradores e parceiros.

O que nós buscamos:
Buscamos um Líder Técnico em Programação PHP, para atuar em todas as camadas dos projetos de desenvolvimento e na gestão e orientação da equipe técnica em todo o processo.

## Como se candidatar

Encaminhar CV com Código LTP 180820:  vagas@auditto.com.br com pretensão salarial e disponibilidade para início imediato.

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
