### ISSUE TITLE
[São Paulo/SP] Programador (a) PHP na Auditto

### ISSUE THREAD

**Issue by rowrodrigues** [phpdevbr/vagas#265]
## Descrição da vaga

Estou compartilhando para uma amiga minha do RH da empresa

O que nós buscamos:
Buscamos um Programador (a) PHP, para atuar em todas as camadas dos projetos de desenvolvimento trabalhando em equipe utilizando metodologias de mercado.

## Local

São Paulo - Morumbi

## Requisitos

**Obrigatórios:**
- Conhecimentos profundos em PHP
- Metodologia em MVC
- Visionamento em GIT
- JQuery / Bootstrap 
- Banco de dados MySQL

**Principais atividades:**
- Desenvolver programas para o negócio da empresa
- Analisar e diagnosticar problemas nos programas existentes
- Manutenção das bases de dados

## Nossa empresa

Descrição da Empresa:
AUDITTO é uma empresa inovadora na recuperação de crédito de ICMS e PIS/COFINS, auditoria e gestão de documentos fiscais eletrônicos, unindo sua expertise em Sistemas Web e Tecnologia Cloud Computing ao know-how fiscal de seus colaboradores e parceiros.

O que nós buscamos:
Buscamos um Programador (a) PHP, para atuar em todas as camadas dos projetos de desenvolvimento trabalhando em equipe utilizando metodologias de mercado.

## Como se candidatar

Encaminhar CV com Código PRGPHP 180820 para:  vagas@auditto.com.br com pretensão salarial e disponibilidade para início imediato.

## Labels

- Alocado/Presencial
- Regime/A combinar
- Experiência/Outros

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
