### ISSUE TITLE
[Contagem/MG] PHP Developer na Infornet

### ISSUE THREAD

**Issue by megandavulpi** [phpdevbr/vagas#269]
### Sobre a empresa: Infornet

Fundada em 2008, a Infornet desenvolve softwares e aplicações específicas para as necessidades do seu negócio. Nosso diferencial é desenhar soluções customizadas, de acordo com os requisitos do sistema e com a realidade de sua empresa. Como resultado, oferecemos uma experiência única em desenvolvimento de software web. Nossos profissionais acompanham todas as etapas do processo, desde o levantamento de requisitos à implantação final, passando por testes, acompanhamento e treinamento. Contamos com casos de sucesso e experiência acumulada em projetos para diversas empresas.

### Descrição: Atividades do nosso programador:

Desenvolvimento de sistemas utilizando PHP e framework Laravel
Integração e/ou Criação de API’s e Web Services
Diagnosticar e resolver problemas nos sistemas
Analisar e planejar novas funcionalidades
Eventualmente atender clientes

**Aqui você terá:**

Vale Transporte ou Auxilio Combustível;
Vale Refeição;
Lanche na empresa;
Plano de Saúde (coo participativo - Unimed);
Programa de Remuneração Variável (Participação nos Resultados de acordo com o desempenho).
Ambiente descontraído :)
Oportunidade de aprender e trabalhar com outras linguagens como: Node.js, WebSocket, AWS, Xamarin, Linux, dentre outros.

**Gostamos de pessoas:**

Proativas;
Que trabalhem bem em equipe;
Estejam sempre antenadas a novas tecnologias;
Sejam muito organizadas.

### Informações complementares:

Residir em Contagem ou proximidades
Conhecimento em JavaScript, HTML e CSS.

### Labels

CLT
Junior
Alocado

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
