### ISSUE TITLE
[São Paulo] Desenvolvedor PHP - Pleno | L4U

### ISSUE THREAD

**Issue by matheuslugon** [phpdevbr/vagas#27]
## Descrição da vaga

Estamos em busca de um profissional para complementar nosso time e atuar em um projeto paralelo voltado para filmes

## Local

Escritório, São Paulo - Vila Madalena

## Benefícios

- Flexibilidade de horário
- Possibilidade de trabalho remoto
- Vale Transporte
- Vale Refeição

## Requisitos

**Obrigatórios:**
- Experiência com PHP 5+
- Experiência com CakePHP
- Experiência com banco de dados MySQL

**Desejáveis:**
- GIT
- SCRUM
- TDD
- Redis

**Diferenciais:**
- Conhecimento em AWS/Ops
- Construção de serviços REST

## Contratação

PJ

## Nossa empresa

A L4U é uma startup voltada para negócios digitais, construída por uma equipe jovem com o objetivo de transformar o negócio em uma aceleradora digital

Trabalhamos com diversos tipos de projetos de transformação, tais como: aplicativos web e mobile, e-commerce, plataformas SaaS e sites

## Como se candidatar

Ficou interessado? Envie um e-mail para rh@l4u.com.br com o assunto _"[Vaga/Dev-PHP]"_, informando seu Currículo/GitHub/LinkedIn/Portfólio e bora trocar uma ideia!

**Comment by zoraiard** [comment]
Curriculum enviado

Abraço!

**Comment by nic** [comment]
@matheuslugon Vaga preenchida?
