### ISSUE TITLE
[São Paulo/SP] PHP Developer na Interamerican

### ISSUE THREAD

**Issue by megandavulpi** [phpdevbr/vagas#270]
### Sobre a empresa: Grupo Interamerican

O Grupo Interamerican é uma empresa total e exclusivamente dedicada a clientes da indústria do turismo, hotelaria e gastronomia que oferece soluções estratégicas, criativas e integradas nos três principais pilares: Relações Públicas, Digital e Marketing.

### Descrição: Ocupações do cargo

O profissional deverá criar novas plataformas de tecnologia para a empresa, liderar o departamento de desenvolvimento com foco na inovação disruptiva e será responsável por mudar o modelo de negócios do grupo.

### Benefícios

Vale transporte;
Vale refeição;
Convênio Médico.

### Aptidões e qualidades

O profissional deverá ter muita vontade de fazer as coisas acontecerem, ser empreendedor, ter sangue nos olhos e ser uma pessoa que está sempre em busca de novos conhecimentos. É fundamental ter foco na identificação dos problemas e nas soluções deste.

### Informações complementares

O horário de trabalho é flexível, o profissional poderá trabalhar de forma remota e deverá está sempre focado nas metas e nas entregas.

### Labels

Senior
Alocado
CLT

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
