### ISSUE TITLE
[São Paulo/SP] PHP Developer na Sennit 

### ISSUE THREAD

**Issue by kathedrall** [phpdevbr/vagas#271]
## Descrição da vaga
 Experiência com análise e desenvolvimento na linguagem PHP. 
Experiência com desenvolvimento de APIs REST, OAuth, segurança. 
Experiência em integrações XML. 
Conhecimento com frameworks (Laravel, Codeigniter, Yii, Cake PHP.
 Conhecimento com APIs externas, banco de dados Mysql. 
Conhecimento com a metodologia SCRUM.

## Local
  Berrini – SP  
## Contratação

PJ a combinar

## Nossa empresa
Tecnologia da Informação

## Como se candidatar

Por favor envie um email para silvana.ferreira@sennit.com.br com seu CV anexado - enviar no assunto: Vaga PHP

## Labels

- Alocado
- PJ
- Pleno
- Sênior

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
