### ISSUE TITLE
[Belo Horizonte/MG] PHP Developer/DevOps na Oficina Conectada

### ISSUE THREAD

**Issue by megandavulpi** [phpdevbr/vagas#272]
### Descrição: Ocupações do cargo

O candidato(a) selecionado(a) irá colaborar no desenvolvimento e manutenção do backend da plataforma Oficina Conectada, que usa a linguagem PHP e o framework Laravel. Além de atuar com desenvolvimento PHP irá também colaborar no desenvolvimento e manutenção das tarefas de Dev Ops como: deploy automatizado da plataforma (que usa o Bitbucket Pipelines da Atlassian), configuração dos ambientes Linux, etc.

### São requisitos para a vaga as seguintes linguagens e frameworks:

﻿ PHP

 Lavarel

### Benefícios

- Vale transporte

- Alimentação.

### Aptidões e qualidades

**Precisamos de pessoas:**

- Proativas

- Independentes

- Ageis

- Alegres

- Participativas.

### Informações da empresa

Oficina Conectada é uma solução completa de gestão empresarial e conteúdo técnico que atende mais de 80 mil oficinas mecânicas em todo o país. 

### Informações complementares

O candidato ao ser contratado irá participar de um processo vivo e ágil, codificando a solução entendida utilizando as melhores ferramentas disponíveis e participando no processo de teste e especificação de software junto com o time.

### Labels

Pleno
CLT
Alocado

### Candidatar: http://bit.ly/oficinaconectadaphp_github

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
