### ISSUE TITLE
[Joinville/SC] Back-End Developer na Volts Digital

### ISSUE THREAD

**Issue by eversonjp** [phpdevbr/vagas#274]
## DESCRIÇÃO

Se você é um desenvolvedor back-end com experiência e WordPress é moleza pra você, esperamos seu contato. 

## LOCAL

Presencial em Joinville / SC (2a melhor cidade do Brasil para se viver :)

## BENEFÍCIOS

- Salário justo com sua experiência;
- Auxílio refeição pago em dinheiro para ser utilizado como preferir;
- Vale-transporte, se necessário;
- Aquisição de livros, sob demanda;
- Subsídio de cursos, sob demanda e análise;
- Comemorações de aniversário com um bolo delicioso, pago por nós;
- Mesa de sinuca e café da tarde compartilhado;
- Ah sim, café infinito também!

## REQUISITOS

**Obrigatórios:**
Domínio do PHP e um ótimo conhecimento do WordPress. 
Se conhecer o WooCommerce, melhor ainda. Magento é um plus+.

Uso de metodologias ágeis, Git flow, clean code e PHP. Esperamos responsabilidade pois essa posição exige isso. Sua dedicação e seu espírito colaborativo será muito bem visto e reconhecido. Ah, bom humor e espírito de equipe é indispensável!

**O que você vai precisar fazer:**
- Trabalhar e liderar outros desenvolvedores; 
- Desenvolver e dar manutenção em aplicações web; 
- Realizar a manutenção e criação de novas funcionalidades em clientes da casa; 
- Aplicar as melhores práticas de documentação de código; 
- Desenvolver e sustentar integrações; 
- Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;
- Analisar e recomendar as melhores soluções;
- Estimar e detalhar atividades de desenvolvimento;
- Arquitetar e desenvolver projetos de e-commerces;
- Intermediar contatos com serviços de terceiros como gateways de pagamentos e servidores;

## CONTRATAÇÃO

Por PJ.

## SOBRE A VOLTS DIGITAL

Começamos dizendo que este carma de ser agência é uma m*. Que vida de agência só dá estresse, que “ninguém merece” e que fazer horas extras é “normal”. Queremos dizer que não. Não é normal, não é bom e que realmente ninguém merece. A gente não trabalha assim por aqui. Obviamente exigimos comprometimento e dedicação das pessoas para que tudo ande dentro dos conformes. É uma via de duas mãos: ser produtivo para ter organização e vice-versa.

Fundada em 2011, a Volts Digital é uma agência de marketing digital orientada a entrega de resultados através do empoderamento de seus clientes e do fortalecimento de marca para uma perspectiva a longo prazo. 

Nosso jeito de trabalhar é diferente e é isso que você precisa saber:

- Gostamos de sair no horário;
- Gostamos de desafios e sermos desafiados;
- Adoramos inovação e mudanças tecnológicas que nos levam a aprender mais;
- Zelamos muito por uma equipe estável, sem rotatividade;
- Trabalhamos muito para ser a mudança nos negócios de nossos clientes;
- Temos um ambiente bacana com pessoas muito especiais;
- Projetos que vão te tirar da zona de conforto;
- Ampla abertura para inovações e experimentações;
- Pautas de trabalho bem definidas;
- Sem “loucuragem” de prazos inacreditáveis e impossíveis de serem cumpridos;
- Feedbacks constantes e conversas transparentes.

## COMO SE CANDIDATAR

Temos certeza que você irá curtir trabalhar aqui, porque somos muito legais. Então envie seu currículo para vagas@voltsdigital.com.br com o título #DEVnaVOLTS juntamente com sua pretensão salarial e disponibilidade para início que vamos analisar e te dar um retorno, sem falta. Nunca deixamos de responder os e-mails e os candidatos. Achamos isso uma falta de respeito enorme com quem se dispõe a falar conosco.

Ah, muito importante: A vaga é presencial na cidade de Joinville/SC. Caso seja de outra cidade, deve ter disponibilidade para mudar-se.

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
