### ISSUE TITLE
[São Paulo/SP] PHP Developer na Mobly

### ISSUE THREAD

**Issue by arthurprogramming** [phpdevbr/vagas#276]
![Descricao](https://github.com/mobly/teste-programador-php/blob/master/img/descricao.png?raw=true&cache=nooooooo)

**Comment by guilhermeoa07** [comment]
A entrevista pode ser remota?

**Comment by rattones** [comment]
bom dia Arthur, a vaga é somente presencial ou o home office 1x por semana pode ser mudado para always??? sou do interior de mg e gostaria de ficar por aqui onde minha esposa é concursada.

**Comment by arthurprogramming** [comment]
Olá @rattones, tudo bom?

Por hora não conseguimos ter o home office para todos os dias. Se mudar de ideia estamos à disposição.

Grande abraço.

**Comment by giovannicruz97** [comment]
Como funciona o processo de seleção ?

**Comment by arthurprogramming** [comment]
Olá @giovannicruz97, envie seu cv e github (se houver) para o email vempra@mobly.com.br.
Nós iremos avaliá-lo, o passo seguinte é uma entrevista e um teste (nem sempre necessário) que depende do decorrer da entrevista.

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
