### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) PHP / Laravel no Pluggto

### ISSUE THREAD

**Issue by fabriciovieira** [phpdevbr/vagas#277]
## Descrição da vaga

Estamos contratando PHP Developer para trabalhar com Laravel, Vue.js e Integrações entre APIs. Que goste de desafios e queira aprender sempre.

## Local

Escritório, São Paulo - Barra Funda (5 minutos do metrô)

## Requisitos

**Obrigatórios:**
- Sólidos conhecimentos em PHP e framework Laravel
- Sólidos conhecimentos em MySQL
- Sólidos conhecimentos em APIs RESTFul
- Conhecimento de Vue.js
- Conhecimentos em GIT
- Conhecimentos em HTML, CSS, JavaScript
- Experiência significativa comprovada em desenvolvimento

**Desejáveis:**
- Conhecimentos em Bootstrap e Datatables
- Conhecimentos em MongoDB
- Conhecimentos em Linux/Ubuntu
- Conhecimentos em Node.js
- Conhecimentos em SOAP
- Configuração/Tuning Apache

## Benefícios

- Vale Refeição
- Vale Transporte
- Plano de Saúde

#### Diferenciais

- Ambiente informal
- Horário de trabalho flexível
- Aprendizado continuo em novas tecnologias

## Contratação

CLT ou PJ - a combinar

## Nossa empresa

O Plugg.to é um hub de integração de ecommerce que não para de crescer. Somos referência no mercado e o temos integração com mais de 50 plataformas e marktplaces no Brasil. Aqui você terá todo o suporte que precisa para alcançar todo o seu potencial. 

## Como se candidatar

Por favor envie um email para fabricio.vieira@plugg.to com seu CV anexado - enviar no assunto: Vaga PHP

## Labels

- Alocado
- PJ
- CLT
- Pleno
- Senior

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:

**Comment by fabriciovieira** [comment]
Continuamos contratando :)
