### ISSUE TITLE
[Natal] Desenvolvedor PHP | Nova M3

### ISSUE THREAD

**Issue by davidcostadev** [phpdevbr/vagas#28]
## Descrição da vaga

Saber dominar a técnica e conseguir atingir as metas

## Local

Softhouse - Natal  - RN - Presencial

## Benefícios

- 2 horas de almoço
- Ambiente descontraído
- sala de jogos

## Requisitos

**Obrigatórios:**
- 1 anos de experiência com PHP 5+

**Desejáveis:**
- conhecimentos em Laravel
- conhecimentos em Cakephp 

**Diferenciais:**
- portfólio

## Contratação

CLT - Mandar Pretensão Salarial

## Nossa empresa

Nova M3 - Produto digitais

## Como se candidatar

Por favor envie um email para gerencia@novam3.com com seu CV anexado - enviar no assunto: Vaga Backend

**Comment by rscafi** [comment]
@davidcostadev essa vaga é presencial?

**Comment by davidcostadev** [comment]
Sim, atualizei a informação.

**Comment by nic** [comment]
@davidcostadev Vaga preenchida?

**Comment by davidcostadev** [comment]
Ainda Não

**Comment by davidcostadev** [comment]
Vaga Preenchida
