### ISSUE TITLE
[Santo André/SP] PHP Developer no Apponte.me

### ISSUE THREAD

**Issue by malheirosrafa** [phpdevbr/vagas#282]
## Descrição da vaga

Estamos em busca de um desenvolvedor PHP pleno, presencial com foco em backend (criação e consumo de webservices / modelagem de dados / escalabilidade / segurança. A maior parte do nosso backend está desenvolvida em symfony.

## Local

Santo André/SP

## Requisitos

**Obrigatórios:**
- OOP
- PSR2, Clean code

**Desejáveis:**
- Conhecimentos em Symfony 3/4
- TDD, BDD
- Docker

**Diferenciais:**
- DDD

## Contratação

PJ a combinar

##  Como se candidatar

Interessados enviar currículo com pretensão salarial para rafael@apponte.me com assunto: #Programador PHP#

### Alocação:
- Presencial

### Contratação:
- CLT
- PJ

### Experiência
- Pleno
- Sênior

**Comment by X-X-Xavito** [comment]
Tem alguma vaga para Estágio? Sou de Santo André.

Abs

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
