### ISSUE TITLE
[São Paulo/SP] PHP Developers na Convenia

### ISSUE THREAD

**Issue by conveniadev** [phpdevbr/vagas#283]
## Descrição da vaga

Acreditamos em um trabalho inteligente, com bom relacionamentos, alinhamento de cultura e que seja divertido. 

Se você tem uma pegada de startup e tá afim de vir fazer acontecer e compor nossos times de devs, chega mais.

Um pouco sobre a nossa stack:
- Frameworks Laravel e Codeigniter
- RabbitMQ
- Infra AWS
- API Rest e GraphQL

## Local

Alameda Campinas 977 - São Paulo - SP

## Benefícios

- VT ou estacionamento
- VR de R$ 500
- Clube de vantagens
- Plano odontológico

## Requisitos

**Obrigatórios:**
- 1 ano de experiência com Laravel
- Experiência com API REST
- Experiência com testes (BDD, TDD)
- Princípios SOLID

**Diferenciais:**
- Behat (http://behat.org/en/latest/)
- Mensageria - RabbitMQ
- Microserviços
- Graphql
- Experiência com SCRUM

## Contratação

CLT

## Nossa empresa

A Convenia tem a responsabilidade de transformar o RH das empresas, transformando a burocracia em uma experiência fluida e agradável.

Estamos buscando desenvolvedores(as) Back-end para uma vaga presencial, em São Paulo - Capital.

## Como se candidatar

Por favor preencha o formulário: https://convenia.recruitee.com/o/desenvolvedora-backend-pleno-php/c/new

### Alocação:
- Presencial

### Contratação:
- CLT

### Experiência
- Pleno

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
