### ISSUE TITLE
[São Paulo/SP] PHP Developer na Webhub

### ISSUE THREAD

**Issue by niltos** [phpdevbr/vagas#285]
## Descrição da vaga

A Webhub está em busca de devs PHP com criatividade e paixão pelo que fazem para integrar parte de seu time de desenvolvimento. A pessoa ideal para esta oportunidade deve ser capaz de desenvolver sistemas, APIs e serviços utilizando linguagem e frameworks PHP, além de possuir um perfil analítico, boa capacidade de autogestão e trabalho em time, e será responsável por:

- Desenvolver novos sistemas utilizando frameworks PHP7+ / MVC
- Desenvolver serviços em sistemas existentes e para novos sistemas que utilizem arquitetura de microsserviços
- Desenvolver APIs e clientes de APIs para exposição e consumo de recursos com clientes e parceiros
- Sustentação de aplicações legadas desenvolvidas em linguagem PHP
- Realizar tunning de aplicações visando melhorias de performance

## Local

Escritório, Liberdade - São Paulo (3 minutos do metrô)

## Benefícios

- Horário Flexível
- Incentivo para participação em eventos
- Auxílio para cursos

#### Diferenciais

- 1 PS4 com jogos na área de descanso
- Happy friday no escritório com refrigerente, cerveja e coxinhas

## Requisitos

**Obrigatórios:**
- Formação em engenharia da computação, ciências da computação, análise de sistemas, sistemas de informação, ou experiência profissional equivalente
- Conhecimento das melhores práticas de desenvolvimento de software para a web
- Experiência com frameworks MVC PHP7+
- Experiência com sistemas unix like
- Conhecimentos avançados em git

**Desejáveis:**
- Experiência com TDD e BDD
- Experiência em times que utilizam metodologias ágeis

**Diferenciais:**
- Noções de NodeJS
- Experiência com CI / CD

## Contratação

PJ a combinar

## Nossa empresa

A Webhub é uma empresa nova, mas que já nasceu com grandes responsabilidades. Uma delas é gerar grande valor para clientes que são grandes em seus segmentos, através do desenvolvimento de soluções digitais com alto uso da tecnologia e de visão de negócios. Tudo isso comprometido com o sucesso do cliente e não apenas com a entrega de um sistema. Além disso, queremos sempre gerar valor para os nossos colaboradores e sociedade, com uma atuação focada na ética e transparência. 

Acreditamos no poder da mistura trabalho duro e inteligente, skill técnico fod..., bom relacionamento, atitude, humor e no resultado que isso gera para todo o grupo.

## Como se candidatar

O primeiro passo é preencher o formulário disponível [neste link](http://careers.webhub.com.br/jobs/back-end).

### Alocação:
- Presencial

### Contratação:
- PJ

### Experiência
- Pleno
- Sênior

**Comment by guilhermeoa07** [comment]
Entrevista pode ser remota?

**Comment by niltos** [comment]
Ainda temos uma vaga em aberto

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
