### ISSUE TITLE
[Campinas/SP] Fullstack PHP Pleno na Dcide

### ISSUE THREAD

**Issue by disalvo** [phpdevbr/vagas#287]
## Descrição da vaga

O profissional deverá desenvolver aplicações demonstrando experiência e fluidez no desenvolvimento de softwares com qualidade, eficiência, produtividade e autonomia. 
 
O profissional terá como foco de atuação a análise e desenvolvimento das funcionalidades dos softwares, sugerindo melhorias nas funcionalidades atuais e futuras nos softwares da Dcide e também propondo melhorias no processo de desenvolvimento de software em geral. 
 
O profissional também deverá auxiliar os programadores júnior e estagiários sempre que houver possibilidade e/ou necessidade.

## Conhecimentos desejáveis
 
Formação técnica ou superior;
Conhecimento avançado em PHP, Javascript, SQL, HTML e CSS;
Experiência com componentes de interface de usuário Bootstrap ou outros;
Experiência com desenvolvimento de API’s REST;
Conhecimento avançado em um framework MVC PHP (CakePHP, Laravel, Zend, CodeIgniter, Symfony etc);
Realizar com tarefas de identificação de erros e refatoração de códigos;
Utilização avançada de sistemas de controle de versão: Git;
Conhecimento avançados em programação avançada em orientação à objetos;
Conhecimento de arquitetura de software;
Conhecimento em Scrum;
Ser focado em resultados, pró ativo, gostar de aprender e possuir facilidade para trabalhar em equipe;
Entendimento de conceitos e processos de negócio;
Procurar sempre as melhores práticas.

## Será considerado diferencial
 
Ter participado em desenvolvimento de grandes aplicações;
Conhecimento da linguagem de programação R;
Linguagem de programação PL/SQL;
Experiência com componentes Kendo UI;
Conhecimentos em sistemas Linux.
 
## Informações adicionais e benefícios
 
Regime de contratação: CLT;
Plano de saúde e odontológico;
Vale de alimentação;
Horário: De segunda a sexta, das 8h às 17h;
Local de trabalho: Centro de Campinas - SP. 

## Como se candidatar
Envie seu CV atualizado para contato@dcide.com.br, com o assunto "Fullstack PHP Pleno na Dcide"

### Alocação:
- Presencial

### Contratação:
- CLT

### Experiência
- Pleno

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
