### ISSUE TITLE
[Campinas/SP] Fullstack PHP Sênior na Dcide

### ISSUE THREAD

**Issue by disalvo** [phpdevbr/vagas#288]
## Descrição do perfil
 
O profissional terá como foco de atuação a construção de uma arquitetura backend e/ou moderna e a migração/manutenção dos sistemas legados da Dcide. 
 
Deverá ter a capacidade de entendimento correto das necessidades dos usuários e propor soluções eficientes e eficazes, assim como sua organização e codificação. 
 
Deverá possuir experiência consolidada em todas as etapas do desenvolvimento de software e contribuir constantemente com a melhoria contínua do processo de desenvolvimento ágil da Dcide, bem como auxiliar todo o time de desenvolvimento sempre que houver necessidade.
 
## Conhecimentos desejáveis
Mínimo de 6 anos de experiência como desenvolvedor PHP, HTML, CSS e JS;
Experiência consolidada com framework CakePHP, Zend Expressive e outros frameworks de mercado;
Utilização avançada de sistemas de controle de versão: Git
Experiência em orientação à objetos e design patterns;
Experiência em escrita de testes unitários e testes de aceitação;
Experiência na modelagem de dados relacionais, banco de dados Oracle e PL/SQL;
Experiência com Scrum;
Experiência em Integração contínua e deploy;
Facilidade para trabalho em equipe, auto gerenciável, comunicativo e auto motivado;
Ser pragmático, focado em resultados e responsável pelos prazos estimados;
Ser organizado e disciplinado;
Experiência com arquitetura de sistemas;
Garantir alta performance e escalabilidade;
Garantir uma aplicação modular e de baixo acoplamento;
Seguir as recomendações dos guias de código e ajudar a aprimorá-los;
Escrever código limpo que seja a referência para os demais desenvolvedores;
Realizar a revisão do código do time de desenvolvimento, bem como propor  melhorias;
Ajudar a definir e implantar processos de integração contínua;
 
 
## Será considerado diferencial
Conhecimentos em estatística;
Experiência em DDD e TDD;
Facilidade para resolver problemas matemáticos;
Experiência em desenvolvimento de aplicações com AngularJs;
Conhecimento da linguagem de programação R
Experiência com componentes Kendo UI
Experiência em sistemas operacionais Linux.
Experiência em segurança e criptografia de dados.
 
## Informações adicionais e benefícios
Regime de contratação: CLT
Plano de saúde e odontológico.
Vale de alimentação
Horário: De segunda a sexta, das 8h às 17h.
Local de trabalho: Centro de Campinas - SP. 
 
## Como se candidatar
Envie seu CV atualizado para contato@dcide.com.br, com o assunto "Fullstack PHP Sênior na Dcide"

### Alocação:
- Presencial

### Contratação:
- CLT

### Experiência
- Sênior

**Comment by moreiraandre** [comment]
@disalvo tá tendo algo na **Dcide** pra remoto?

**Comment by disalvo** [comment]
> @disalvo tá tendo algo na **Dcide** pra remoto?

Fala @moreiraandre beleza? No momento, somente presencial.

**Comment by moreiraandre** [comment]
@disalvo valeu mano, obrigado!

**Comment by disalvo** [comment]
@moreiraandre :+1:

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
