### ISSUE TITLE
[São Paulo] Desenvolvedor Full-Stack Pleno/Sênior | Dafiti Group

### ISSUE THREAD

**Issue by hussani** [phpdevbr/vagas#29]
## Nossa empresa

Somos o time de desenvolvimento do maior e-commerce de moda da América Latina, com operações na Argentina, Brasil, Chile e Colômbia Aqui mantemos e evoluímos os sistemas da [Dafiti](https://www.dafiti.com.br), [Kanui](https://www.kanui.com.br) e [Tricae](https://tricae.com.br).

## Descrição da vaga

Se você é uma pessoa criativa e com bom senso, é flexível e comprometida, tem paixão por tecnologia e engenharia de alta qualidade, venha trabalhar conosco, pois temos muito em comum :)

Boa parte do trabalho é feita no back-end, no entanto você deve se sentir confortável em interagir com o front-end, em resumo: esperamos que você se envolva em todas as partes do desenvolvimento do produto.

No dia-a-dia você irá ajudar no refinamento de requisitos, planejamento e execução das tarefas que serão realizadas pelo time, POCs relacionadas à evolução do produto e elaboração de techtalks, além de discutir bastante sobre arquitetura para sistemas de larga escala.

Nossos sistemas estão mudando de um sistema monolítico para serviços e micro-serviços onde utilizaremos a melhor ferramenta para cada caso. Atualmente temos sistemas en PHP, Python, Java, JavaScript e GO.

## Local

Av. Francisco Matarazzo, 1350 - Água Branca, São Paulo - SP. Presencial.

## Benefícios

- Vale Transporte :bus: 
- Vale Refeição :meat_on_bone: 
- Plano de Saúde :pill: 
- Plano de Participação nos Resultados :moneybag: 

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento de software em uma ou mais linguagens de alto nível:
    - PHP
    - Python
    - Java
    - JavaScript
    - GO
- Experiência em dois ou mais:
    - Web application development
    - Unix/Linux environments
    - Mobile application development
    - Sistemas distribuídos e paralelos
    - Machine learning
    - Developing large software systems
    - NoSQL/SQL databases and/or security software development

**Desejáveis:**
 - Superior completo em Ciências da Computação ou áreas correlatas.
 - Conhecimento em TDD
 - Conhecimento em DDD
 - Conhecimento avançado de algum framework de mercado

**Diferenciais:**
- Projetos opensource

## Contratação

CLT

## Como se candidatar

Comece com o que se sentir mais confortável: 
- Nos envie um email: selecao-dev@dafiti.com.br
- Envie um teste para nós [aqui](https://github.com/dafiti/fast-tech-review)

## Dúvidas

Qualquer dúvida, sinta-se a vontade para perguntar aqui nesta issue.
Se for sobre o teste, abra uma issue no repositório do teste.

**Comment by nic** [comment]
@hussani Vaga preenchida?

**Comment by hussani** [comment]
@nic ainda temos vagas a preencher.
Entra em contato se precisar de mais detalhes :)

**Comment by nic** [comment]
@hussani Ahh blz! Tô dando uma limpada aqui nas vaga que já foram preenchidas, fechando as issues. Boa sorte aí pra conseguir mano. Abração!

**Comment by leonardobmartins** [comment]
@hussani como faço para enviar meu Currículo, não consigo através do site, tem algum email por favor?

**Comment by hussani** [comment]
@leonardobmartins pode enviar para o email abaixo.
```
Cristian Medeiros <cristian.medeiros@dafiti.com.br>
```

Pode mandar email ou perguntar nessa thread se tiver alguma dúvida :smiley:

**Comment by rscafi** [comment]
@hussani Vaga preenchida?

**Comment by hussani** [comment]
@rscafi desculpe a demora em te responder.
Ainda temos vagas.

Você prefere fechar essa issue e reabrir, ou mantém como está?

**Comment by rscafi** [comment]
Pode deixar aberto @hussani :wink:
