### ISSUE TITLE
[Belo Horizonte/MG] PHP Developer na Grupo Ânima

### ISSUE THREAD

**Issue by megandavulpi** [phpdevbr/vagas#290]
### Sobre a empresa: Grupo Anima

A Ânima é formada por pessoas apaixonadas pelo que fazem. E que não têm medo de desafios. Superamos dificuldades. Fazemos as coisas sempre da melhor maneira. Somos fascinados pela magia da educação: acreditamos que só ela pode transformar vidas. E isso reforça a sensação de que estamos participando ativamente do desenvolvimento do nosso país.

### Descrição: Ocupações do cargo

Desenvolvimento e acompanhamento de projetos.
Manutenções evolutivas e corretivas em sistemas desenvolvidos em PHP7 e Banco de dados Oracle.
Propor soluções e desenvolver novas tecnologias para melhorar sistemas legado.
Trabalhar com equipe multidisciplinar em ambiente ágil de desenvolvimento.

### Benefícios

Vale transporte
Vale alimentação ou refeição
Plano médico e odontológico
Seguro de vida em grupo
Bolsa de estudos de até 90% em cursos de graduação e 50% nos cursos de pós-graduação.
Possibilidade de Home Officce
Horário Flexivel

### Buscamos por Pessoas

Buscamos uma pessoa que apresente proficiência em desenvolvimento de sistemas e bons conhecimentos em Banco de Dados, preferencialmente Oracle. Que seja proativa para buscar conhecimento e crescimento, além de se sentir motivada por desafios.

### Diferenciais

Vivência em métodos ágeis de desenvolvimento
AWS
Framework Laravel,
Integração com API's,
HTML
Javascript
JQuery
Ajax
VueJs

### Labels:

Alocado
CLT
Senior

### Candidatar: http://bit.ly/anima_github

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
