### ISSUE TITLE
[São Paulo/SP] Full-stack PHP Sênior na MediaPost

### ISSUE THREAD

**Issue by vcampitelli** [phpdevbr/vagas#292]
## Descrição da vaga

Procuramos programadores PHP experientes mas que se mantenham atualizados com tendências e novidades na área. Possuímos 4 produtos em que nos ajudará a sustentar e desenvolver novas funcionalidades, todos feitos em PHP. Você será o líder da equipe na migração de um desses produtos para o PHP 7.

## Local

Escritório no bairro de Pinheiros, São Paulo/SP _(a 3 quarteirões da estação Fradique Coutinho da Linha 4 Amarela do Metrô)_.

## Benefícios

- Assistência Médica
- Participação nos lucros
- Vale-Refeição _(R$ 25,00 / dia)_
- Vale-Transporte
- Convênio de academias Gympass

#### Diferenciais

- Horário flexível
- Equipe unida
- Liberdade para incorporar novas ferramentas e tecnologias
- Reuniões quinzenais para compartilhamento de conhecimentos

## Requisitos

**Obrigatórios:**
- PHP avançado _(OOP, Design Patterns, boas práticas etc)_
- SQL avançado _(de preferência MySQL)_
- Linux intermediário

**Desejáveis:**
- Conhecimentos em Symfony

**Diferenciais:**
- NoSQL _(principalmente MongoDB)_
- Gerenciamento de filas _(principalmente RabbitMQ)_

## Contratação

CLT ou PJ, a combinar

## Nossa empresa

A MediaPost é uma empresa especialista em e-mail marketing que atua há mais de 10 anos na área. Temos uma plataforma própria com alto grau de tecnologia envolvida e diversos serviços para ajudarmos nossos clientes a performarem o máximo possível através do relacionamento por e-mail.
Temos uma arquitetura robusta em mais de 100 servidores utilizando PHP, Python, MariaDB, RabbitMQ entre outros.
Utilizamos SCRUM no dia-a-dia para gerenciar nossos sprints.

## Como se candidatar

Por favor envie seu currículo com assunto "Programador PHP MediaPost" para calves@mt4.com.br

### Alocação:
- Presencial

### Contratação:
- A combinar _(CLT ou PJ)_

### Experiência
- Sênior

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
