### ISSUE TITLE
[Remoto] PHP/Wordpress Developer Pleno/Sênior na Webholdingusa

### ISSUE THREAD

**Issue by jadsonsoares** [phpdevbr/vagas#293]
## Descrição da vaga

Sr PHP/Wordpress Developer
Estamos em busca de um profissional com experiência em: WordPress, PHP e front (HTML e CSS).
Atuará no desenvolvimento de sistemas internos e sites.
Freelancer, preço a combinar.
## Local

Vaga 100% remoto.

## Como se candidatar

Por favor envie um email para gsantos@webholdingusa.com com seu CV anexado - enviar no assunto: Senior PHP/Wordpress Developer
### Alocação:
- Remoto

### Contratação:
- Freelance

### Experiência
- Pleno
- Sênior

**Comment by mvnp** [comment]
Enviado! Senior PHP/Wordpress Developer

**Comment by rodineicosta** [comment]
Enviado!

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
