### ISSUE TITLE
[Florianópolis/SC] Desenvolvedor(a) PHP na BDR 

### ISSUE THREAD

**Issue by juliaheadhunter** [phpdevbr/vagas#294]
## Descrição da vaga

A empresa contratante está procurando por um Desenvolvedor PHP, que seja criativo, capaz de projetar, desenvolver e garantir a qualidade de sistemas Web, e que não se intimide com plataformas que irão atender potencialmente milhões de usuários ao redor do mundo. Se você também tem intimidade com o Frontend, certamente eles querem te conhecer.

## Local

Trindade - Florianópolis.

## Benefícios

Coffee-break nas sextas + Ambiente (realmente) descontraído + Flexibilidade de horários + Cerveja no frigobar  + VT.

## Requisitos

Requisitos:
Experiência com Programação PHP;
Experiência com HTML5;
Domínio de algum framework Javascript para front-end.

Desejável: 
Superior na área de Tecnologia;
Inglês Avançado;
Experiência com Laravel / Symfony;
Conhecimento em Bootstrap;
Conhecimento em Sass;
Conhecimento em Angular 5x/6.x e Angular 1.x;
Conhecimento em Ionic, Node.js e React;
Conhecimentos em AWS.

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para recrutamento@empresabdr.com.br enviar no assunto: Vaga PHP

### Contratação:
- CLT

### Experiência
- Júnior
- Pleno
- Sênior

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
