### ISSUE TITLE
[Balneário Camboriú/SC] Fullstack Developer na Systêxtil

### ISSUE THREAD

**Issue by DieguinhoHR** [phpdevbr/vagas#297]
## Descrição da vaga

Projeto smart (mini erp) em Java, React, Docker, TDD e muito mais.

## Local

Escritório, Balneário Camboriú – SC.

## Benefícios

- Seguro de vida
- VA de R$ 17.50

#### Diferenciais

- 1:30 horas de almoço
- monte a sua máquina como desejar

## Requisitos

**Obrigatórios:**
- 1 ano de experiência com Java
- 1 ano de experiência com Oracle
- 1 ano de experiência com Javascript/React

**Desejáveis:**
- conhecimentos em Java e React

**Diferenciais:**
- projetos opensource

## Contratação

CLT

## Nossa empresa

Aqui na Corporação Systextil temos um ambiente bem voltado para o aprendizado e compartilhamento de experiências entre os colaboradores.

## Como se candidatar

Por favor envie um email para rh@systextil.com.br com seu CV anexado - enviar no assunto: Vaga Java

### Alocação:
- Presencial

### Contratação:
- CLT
- Estágio
- Outros (especificar)

### Experiência
- Estágio
- Júnior
- Pleno
- Sênior
- Especialista
- Outros (especificar)

**Comment by ravanscafi** [comment]
Olá, esse repositório é apenas para vagas PHP.
