### ISSUE TITLE
[São Caetano do Sul/SP] PHP Developer na KYMO Tecnologia e Inovação

### ISSUE THREAD

**Issue by KYMOIT** [phpdevbr/vagas#298]
## Descrição da vaga

Projeto de Reestruturação de Sistema Proprietário em PHP

## Local

São Caetano do Sul/SP - Região do ABC Paulista

## Benefícios

- Plano de saúde
- Seguro de vida

#### Diferenciais

- Ambiente amistoso
- Desafios interessantes para quem deseja colocar em prática o seu lado mais inovador

## Requisitos

*Obrigatórios:*
- Experiência com PHP 5+
- Experiência com MySQL e SQL Server
- Experiência com Bootstrap e Git 

*Desejáveis:*
- Experiência com desenvolvimento de aplicações com e sem a utilização de frameworks
- Experiência com Laravel
- Configuração de servidores (setup webserver, banco de dados)
- Criação de Apps
- Conhecimento em IONIC
- Integração com Telegram e WhatsApp

## Contratação

PJ a combinar

## Nossa empresa

A KYMO é especialista em serviços de Monitoramento de IT e Backup. Criamos soluções proprietárias para agregar inteligência a diversas ferramentas e soluções de mercado.
Parece chato, mas o que fazemos é muito legal ;-)

## Como se candidatar

Por favor envie um email para eliane.bagarin@kymo.it com seu CV anexado - enviar no assunto: Vaga PHP

### Alocação:
- Presencial (Remoto parcial)

### Experiência
- Pleno
- Sênior
- Especialista

Se você é bom no que faz, gosta de inovar, de estudar novas tecnologias e de impressionar as pessoas com as suas criações, nos dê a chance de mostrarmos à você de que podemos fazer algo bem legal juntos!

**Comment by ravanscafi** [comment]
@KYMOIT a contratação é CLT ou PJ? as informações estão conflitantes

**Comment by KYMOIT** [comment]
Boa tarde!

Contratação PJ.

Att;



[KYMO_Assinatura_Email_PortEliane-Port]

De: Ravan Scafi <notifications@github.com>
Enviada em: quinta-feira, 20 de dezembro de 2018 14:44
Para: phpdevbr/vagas <vagas@noreply.github.com>
Cc: Financeiro Konics <financeiro@kymo.it>; Mention <mention@noreply.github.com>
Assunto: Re: [phpdevbr/vagas] [São Caetano do Sul/SP] PHP Developer na KYMO Tecnologia e Inovação (#298)


@KYMOIT<https://github.com/KYMOIT> a contratação é CLT ou PJ? as informações estão conflitantes

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
