### ISSUE TITLE
[Rio de Janeiro/RJ] PHP Developer Full Stack no Grupo Unicad

### ISSUE THREAD

**Issue by jheliodoro** [phpdevbr/vagas#299]
## Descrição da vaga

Colabore com projetos inovadores e desafiadores na área de segurança. Analisar, desenvolver, manter, corrigir e evoluir nossos sistemas e crescer com a gente. Sempre visando atender as necessidades dos usuários.

Você precisa ter experiência com desenvolvimento em Laravel nas últimas versões, domínio de orientação a objetos, conhecimentos de padrões de projeto, conhecimentos no desenvolvimento front-end (HTML + CSS + JavaScript). Diferenciais: API GoogleMaps, Docker, Integração contínua (CI) e SCRUM

## Local

Presencial - Rio de Janeiro / RJ - Centro

## Benefícios

- Plano de saúde
- Vale Refeição
- Vale Transporte

## Requisitos

**Obrigatórios:**
PHP;
Angular

**Desejáveis:**
- conhecimentos em Laravel
- conhecimentos em Bootstrap

**Diferenciais:**
- Experiencia com API Google Maps

## Contratação
CLT

## Nossa empresa

De 2004 em diante começamos a navegar nos mares da tecnologia, trazendo Informações em tempo real via Webapp, alertas via SMS e um Aplicativo para informar situações críticas na cidade. Temos um time de programadores em expansão, com trabalhos por projeto e contínuos, dando manutenção e implementando novas funcionalidades nos sistemas já existentes e também criando novas aplicações para as informações que nossa equipe de monitoramento insere no sistema.

## Como se candidatar

Mande seu curriculo e um link para o desafio concluído no email rh@grupounicad.com.br com o assunto: "[PHP] Desenvolvedor Full Stack"

Link Desafio: https://drive.google.com/open?id=1HDD3fA4yRVFA2XZHa2UtVZmKpluqrxBT

### Alocação:
- Presencial

### Contratação:
- CLT

### Experiência
- Júnior
- Pleno
- Sênior

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
