### ISSUE TITLE
[Belo Horizonte] Desenvolvedor PHP na WCOM

### ISSUE THREAD

**Issue by yanmagale** [phpdevbr/vagas#3]
*\* Repassando Vaga pubica pelo facebook**
## Descrição da vaga

Atuar no desenvolvimento de sistemas para demandas internas da empresa
## Local

WCOM - R. Curitiba, 1269 - Centro, Belo Horizonte - MG
## Benefícios

Maiores informações com o RH
## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento de Sistemas
- PHP
- MySQL
- Experiência em desenvolvimento com frameworks PHP

**Desejáveis:**
- Codeigniter
- Drupal
## Nossa empresa

WCOM (Grupo Feira SHOP)
## Como se candidatar

Por favor envie um email para andre.carvalho@feirashop.com.br

**Comment by enieber** [comment]
@YanMagale Alocado ou remoto?

**Comment by YanMagale** [comment]
@enieber Alocado

**Comment by ByTecno** [comment]
Enviado!

**Comment by tidias17** [comment]
Ainda em aberto esta vaga?

**Comment by yanmagale** [comment]
Acredito que não viu @tidias17 , melhor chegar através do e-mail `andre.carvalho@feirashop.com.br`
