### ISSUE TITLE
[SP - São Bernardo do Campo] AppFactory - Desenvolvedor PHP Pleno

### ISSUE THREAD

**Issue by maiconpeixinho** [phpdevbr/vagas#30]
## Descrição da vaga

Programar, desenvolver e implantar sistemas em linguagem PHP. Realizar correções em sistemas para atender às necessidades dos usuários. Desenvolver trabalhos de montagem, depuração e testes de programas já desenvolvidos.
Experiência em desenvolvimento de software com PHP, utilizando framework CodeIgniter para sites e APIs REST usando JSON. Conhecimento em MySQL, HTML5, CSS3, JavaScript e jQuery. Ensino Superior.

## Local

São Bernardo do Campo

## Requisitos

**Obrigatórios:**
- Experiência com PHP 5+
- MySQL
- HTML5
- CSS3 
- JavaScript
- jQuery
- CodeIgniter

## Contratação

PJ a combinar

## Nossa empresa

Fabrica de aplicativos estabelecida em São Bernardo do Campo - SP

## Como se candidatar

Por favor envie um email para jobs@appfactory.com.br com seu CV anexado - enviar no assunto: Vaga PHP com pretensão salarial.

**Comment by nic** [comment]
@maiconpeixinho Vaga preenchida?
