### ISSUE TITLE
[São Paulo/SP] Programador(a) PHP na GSN

### ISSUE THREAD

**Issue by RHGSN** [phpdevbr/vagas#300]
Programador PHP Jr/Pl
Local: São Paulo/SP | Paraíso
Tipo de Contratação Pessoa Jurídica

PHP
HTML5
CSS 3
MySQL
Jquery
Nível Júnior em Photoshop e Ilustrator
Opencart
WordPress
Journal

Diferencial:

Angular
Magento
ESS GRID

Para se cadastrar entre no Link: https://gsn.compleo.com.br/Visualizar/29142
Ou envie um e-mail para: kevin.marcel@gsn.com.br

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
