### ISSUE TITLE
[São Paulo/SP] Programador(a) PHP na F2LTI

### ISSUE THREAD

**Issue by gugaws** [phpdevbr/vagas#302]
## Descrição da vaga

• Desenvolver novos sistemas utilizando frameworks PHP7+ / MVC
• Desenvolver serviços em sistemas existentes e para novos sistemas que utilizem arquitetura de micros serviços
• Desenvolver APIs e clientes de APIs para exposição e consumo de recursos com clientes e parceiros
• Sustentação de aplicações legadas desenvolvidas em linguagem PHP
• Realizar tunning de aplicações visando melhorias de performance

## Local

• Escritório, Vila Leopoldina - São Paulo (8 minutos da estação de trem Imperatriz Leopoldina)

## Benefícios
• A negociar

#### Diferenciais
• Projeto desafiador com alocação mínima de 1 ano

## Requisitos

**Obrigatórios:**
	• Conhecimento das melhores práticas de desenvolvimento de software para a web
	• Experiência com frameworks MVC PHP7+
	• Experiência com sistemas unix (like)
	• Conhecimentos em git

**Desejáveis:**
	• Experiência com TDD e BDD
	• Experiência em times que utilizam metodologias ágeis
	• Conhecimentos em Vuejs

**Diferenciais:**
	• Experiência com CI / CD
	• Conhecimento do sistema CEWE (https://company.cewe.de/en/home.html)

## Contratação

A combinar

## Nossa empresa

Nós da F2L Soluções em TI amamos tecnologia e, acima de tudo, amamos utilizá-la de forma a 
melhorar os resultados de nossos clientes.  Trabalhamos de forma ágil e sem burocracia 
focados na solução, e evitamos desperdício de tempo e recursos valiosos. 

Fundada por profissionais que vivem tecnologia há mais de 20 anos e possui clientes no Brasil e exterior.

## Como se candidatar

Por favor envie um email para suporte3d@f2lti.com.br com seu CV anexado - enviar no assunto: Vaga Programador PHP (Pleno/Júnior)

### Alocação:
- Presencial

### Contratação:
- CLT
- PJ

### Experiência
- Júnior
- Pleno

**Comment by gugaws** [comment]
> Ou postou a vaga sem querer ou falta editar muita informação amigo

Acabei de ajustar as informações

**Comment by gugaws** [comment]
> > Ou postou a vaga sem querer ou falta editar muita informação amigo
> 
> Acabei de ajustar as informações

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
