### ISSUE TITLE
[São Paulo/SP] Arquiteto(a) PHP na F2LTI

### ISSUE THREAD

**Issue by gugaws** [phpdevbr/vagas#303]
## Descrição da vaga

 - Experiência em projetos com arquitetura de microserviços
 - Conhecimento de ambientes em cloud
 - Linguagens de programação como python, java, frameworks java script
 - Banco de dados SQL, noSQL e Grafos
- Ferramentas de automação de testes

## Local

• Escritório, Vila Leopoldina - São Paulo (8 minutos da estação de trem Imperatriz Leopoldina)

## Benefícios

• A negociar

#### Diferenciais

• Projeto desafiador com alocação mínima de 1 ano

## Requisitos

**Obrigatórios:**
- 4 anos de experiência com PHP 5+

**Desejáveis:**
- conhecimentos de micro serviços
- Conhecimento de IA e Machine Learning

**Diferenciais:**
- projetos opensource
- Experiência com CI / CD
- Conhecimento do sistema CEWE (https://company.cewe.de/en/home.html)

## Contratação

A combinar

## Nossa empresa

Nós da F2L Soluções em TI amamos tecnologia e, acima de tudo, amamos utilizá-la de forma a
melhorar os resultados de nossos clientes. Trabalhamos de forma ágil e sem burocracia
focados na solução, e evitamos desperdício de tempo e recursos valiosos.

Fundada por profissionais que vivem tecnologia há mais de 20 anos e possui clientes no Brasil e exterior.

## Como se candidatar

Por favor envie um email para suporte3d@f2lti.com.br com seu CV anexado - enviar no assunto: Vaga Programador PHP Sênior/Arquiteto

### Alocação:
- Presencial

### Contratação:
- CLT
- PJ

### Experiência
- Pleno
- Sênior
- Especialista

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
