### ISSUE TITLE
[São Paulo/SP] PHP Developer na e-Midia Informações

### ISSUE THREAD

**Issue by nagamuta** [phpdevbr/vagas#304]
## Local

CoWorking - Vila Gertrudes - São Paulo

## Benefícios

- Plano de saúde
- VR
- VT
- PLR
- Seguro de Vida

## Requisitos

Requisitos mínimos
- PHP >= 5.6
- SQL
- GIT
- MVC
- Docker
- Linux
- Utilização e consumo de API Restful
- HTML

Requisitos diferenciais
- Principais protocolos da internet
- Websocket
- Javascript (ecma6)
- CSS (sass, less …)
- Nodejs (edited) 

## Contratação

CLT - 40 horas semanais

## Como se candidatar

Por favor envie um email para vagas@e-midia.com com seu CV anexado - enviar no assunto: Vaga Desenvolvedor PHP Pleno

### Alocação:
- Presencial
### Contratação:
- CLT
### Experiência
- Pleno

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
