### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) na Adalov

### ISSUE THREAD

**Issue by erikprogramador** [phpdevbr/vagas#306]
## Descrição da vaga

Procuramos um novo desenvolvedor fullstack para o time da Adalov!

Buscamos alguém que goste de solucionar problemas, seja curioso, disposto, e proponha melhorias em diferentes tipos de projetos.

Nossas stacks são basicamente `PHP 7+` com `Laravel 5+`, `CodeIgniter`, `Elasticsearch`, `Redis`, `Vue js`, `Jquery`, `Bootstrap CSS`, `Tailwind css`

Também temos alguns projetos com `Python 3`

## Onde vou trabalhar?

Presencial em São Paulo/SP. Com horário flexível e possibilidade de home office (um ou dois dias da semana) dependendo do projeto/cliente.

## O que eu preciso saber?

Estamos buscando devs que tenham os seguintes conhecimentos:

-   `PHP 7+`
-   `OOP`
-   Conhecimento no modelo MVC
-   Facilidade para aprender e utilizar qualquer tipo de framework
-   Conhecimento front end em `Vue js`, `Jquery`, `Bootstrap CSS`, `Tailwind CSS`

## Quero me candidatar

Ficou interessado? Envie um e-mail para `vagas@adalov.com` com o assunto _”Vaga desenvolvedor”_, informando seu GitHub/LinkedIn/Portfólio e seu CV e pretensão salarial!

**Comment by erikprogramador** [comment]
A vaga continua aberta.

**Comment by joaoprado** [comment]
Uma pena ser presencial. Se fosse 100% remoto eu me interessaria.
