### ISSUE TITLE
[Holanda/Espanha] Múltiplas vagas PHP e Magento pela Opus Recruitment Solutions

### ISSUE THREAD

**Issue by Bakhi123** [phpdevbr/vagas#308]
After a long holiday I am back in Amsterdam with some exciting news for my network. I have a diverse set of roles available in The Netherlands and Spain. 

Urgent roles: 
1) Magento Developers (1 and 2) - BE/FE
2) PHP Developers (Laravel) - Amsterdam and Madrid
3) PHP Developers (Symfony) - Amsterdam and Madrid
4) Python Developers (Django) - Amsterdam and Madrid 
5) Ruby on Rails - Amsterdam 

If you have any questions, please like/comment below and send your CV to bakhtawar.baloch@opusrs.com

#python #php #magento #laravel #django #networking

**Comment by ravanscafi** [comment]
@Bakhi123, usually we recommend opening an issue for each role, explaining a little bit about each role, the company, etc. But we can leave it like that for this one, no problem.
One thing that you must have in mind that this repository is for Brazilian public and if you are going to post jobs here, that there might be some migration involved/etc.

**Comment by Bakhi123** [comment]
Hi Ravan,

Thank you for your message.

I’ll keep that in mind – next time I’ll open a new issue for each role. It’s my first time here ☺

All my clients are willing to help people with relocation. I have helped more than 5 PHP Developers from Brazil relocate to The Netherlands in the past 1 year.

All the best,
Bakhtawar.

[cid:image001.jpg@01D40257.27CEC6A0]



Bakhtawar Baloch | RECRUITMENT CONSULTANT
https://www.linkedin.com/in/bakhtawar-baloch-a49b42121/

T:+31207979053
A: HERENGRACHT 124 1015 BT AMSTERDAM, NETHERLANDS
W: OPUSRECRUITMENTSOLUTIONS.COM<https://www.opusrecruitmentsolutions.com/>

PART OF OPUS TALENT SOLUTIONS<https://www.opustalentsolutions.com/>






The contents of this email are confidential and are solely for the person(s) at the above email address(es); it may be read, copied and used only by the intended recipient. If you have received this email in error, please notify the sender immediately and delete the original message from your server.
Opus Recruitment Solutions accepts no legal liability for the contents of this email; any views or opinions presented are solely those of the author and do not represent those of Opus Recruitment Solutions unless otherwise explicitly stated.





   Please click UNSUBSCRIBE<mailto:contactus@opusrs.com?subject=Unsubscribe> to opt out from marketing.
   Please read our updated privacy policy here<http://www.opusrecruitmentsolutions.com/privacy-policy>.

**Comment by ravanscafi** [comment]
@Bakhi123 awesome! good luck with the spots :wink:

**Comment by ravanscafi** [comment]
@Bakhi123 please repost if the spots are still open :wink:
