### ISSUE TITLE
[São Paulo/SP] PHP Developer na NerdMonster Digital Retail

### ISSUE THREAD

**Issue by lavorato** [phpdevbr/vagas#309]
## Descrição da vaga
O time de desenvolvimento da [NerdMonster](https://nerdmonster.com/) está procurando um programador frontend apaixonado por desafios envolvendo programação e que está sempre atualizado com as evoluções das tecnologias do mercado.

Nossas stacks são basicamente PHP 5.6+ com CodeIgniter 3+, Node.js, MySQL, MongoDB, Jquery e Bootstrap CSS.

## Local
[Escritório, Vila Mariana / Paraíso - São Paulo (ao lado do metrô Ana Rosa)](https://www.google.com.br/maps/place/NerdMonster+Digital+Retail/@-23.581608,-46.637762,15z/data=!4m5!3m4!1s0x0:0x8e407a7bb020c0ed!8m2!3d-23.581608!4d-46.637762)

## O que você vai fazer?
- Desenvolvimento de projetos com arquitetura de microserviços e API's;
- Utilização e consumo de API Restful;
- Implementação de novos recursos na aplicação;
- Criação de algoritmos e implementação de regras de negócio;
- Correção de eventuais bugs da aplicação em produção;
- Integrações com plataformas de serviços.

## Diferenciais
- Horário flexível;
- Equipe unida e time enxuto;
- Liberdade para incorporar novas ferramentas e tecnologias;
- Ótima localização do escritório, ao lado do metrô;
- Conhecer técnicas e gostar de discutir interface/usabilidade de produto;
- Contato direto com a equipe em todos os níveis da empresa, todos tem voz na empresa;
- Dress Free.

## Requisitos
**Obrigatórios:**
- Experiência mínima de 4 anos atuando como desenvolvedor;
- Experiência com PHP >= 5.6 avançado (OOP, design patterns e boas práticas);
- Banco de dados MySQL;
- GIT e versionamento;
- Linux e Apache (pode ser básico);
- Ter trabalhado no desenvolvimento de sistemas web - experiências em outras startups seria um diferencial;
- Habilidade de comunicação e de trabalho em time.

**Desejáveis:**
- Experiência com AWS (S3, SQS, EC2, AURORA DB) e deploy;
- Experiência com o Framework CodeIgniter 3+;

**Diferenciais:**
- Conhecimento em APIs Sociais (Facebook);
- Conhecimentos em estatística;
- Conhecimento em APIs de Ads (Facebook Ads e/ou Google AdWords);
- Proatividade para resolução de problemas;
- Código limpo e organizado;
- Node.js e MongoDB;
- Proatividade para resolução de problemas;
- Cultura Scrum;
- Espírito de equipe.

## Contratação
- Regime PJ a combinar (favor enviar pretenção salarial junto com o envio de seu seu CV e GitHub/LinkedIn/Portfólio)
- Início imediato

## Nossa empresa
Nós somos uma empresa com uma missão bastante clara: Empoderar varejistas a terem o controle de sua multipresença digital e centralizar o marketing digital em um único lugar. A NerdMonster é líder em seu segmento e já conta com mais de 30 mil estabelecimentos físicos usando sua plataforma.

Buscamos ativamente desenvolvedores capazes, motivados a procura de novos desafios através da programação focada sempre em tecnologias de ponta com Machine Learning, BigData e Inteligência Artificial.

## Como se candidatar
Por favor envie um email para marcos.lavorato@nerdmonster.com com seu CV em anexo e GitHub/LinkedIn/Portfólio - enviar no assunto: PHP Developer na NerdMonster Digital Retail

## Labels
- Alocado
- PJ
- Pleno
- Sênior
- Especialista

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
