### ISSUE TITLE
[São Paulo/SP] Desenvolvedor PHP na Pagar.me

### ISSUE THREAD

**Issue by sfeu17** [phpdevbr/vagas#31]
## Descrição da vaga

A equipe usa PHP para integrar a API da Pagar.me nas maiores plataformas de e-commerce do Brasil (Magento, OpenCart, PrestaShop, WooCommerce, etc). 
Pra conhecer melhor o trabalho do time: https://github.com/pagarme/pagarme-php

## Local

Escritório, São Paulo - Vila Olímpia

## Benefícios

- Horário flexível
- Vale refeição
- Vale transporte
- Gympass
- Assistência médica
- Assistência odontológica

## Requisitos

**Obrigatórios:**
- Experiência com PHP (projetos pessoais ou experiências profissionais)
- Gosta de entender a fundo sobre diferentes negócios e tecnologias
- Gosta de trabalhar com projetos open source
- Não suporta “só” seguir ordens em ambientes quadrados
- Busca um lugar para se desenvolver tecnicamente

**Desejáveis:**
- Conhecimento com Git
- Experiência com trabalho em equipe
- Experiência com integrações usando API

**Diferenciais:**
- Conhecimento em NodeJs
- Conhecimentos de Metodologias Ágeis
- Experiência com plataformas de e-commerce (Magento, OpenCart, PrestaShop, WooCommerce, etc)

## Contratação

CLT

## Nossa empresa

Pagar.me é uma empresa brasileira de pagamentos online, do grupo Arpex Capital, que trabalha para simplificar o recebimento de todo tipo de pagamentos pela Internet.
A Pagar.me foi construída por/para desenvolvedores e respiramos tecnologia por aqui! Para continuar inovando, precisamos de mais devs que gostem de trabalhar em equipe, tenham muita vontade de se desafiar e crescer com a gente! Nossa equipe está aumentando e temos espaço pra todo perfil de dev.

## Como se candidatar

Envie um email para code@pagar.me com seu CV/Github anexado com assunto: "Dev PHP"

**Comment by nic** [comment]
@sfeu17 Vaga preenchida?
