### ISSUE TITLE
[São Paulo/SP] PHP Developer na PRAVALER

### ISSUE THREAD

**Issue by carolrecruiter** [phpdevbr/vagas#311]
## Descrição da vaga

Já pensou em trabalhar na empresa que é gestora do maior programa de crédito universitário privado do Brasil e que transforma a vida de milhares de estudantes por meio da educação? 

Agora você pode! Venha atuar como Programador PHP em um dos nossos Squads (Melhoria Contínua, Sustentação, Gestão de Riscos, Produtos, Clientes e/ou TI)! 

## Local

Nosso escritório fica em Pinheiros - São Paulo, SP.

## Benefícios

- Assistência Médica
- Assistência Odontológica
- Vale Refeição
- Vale Transporte
- Benefício Farmácia
- Seguro de Vida
- GymPass
(PLR)

#### Diferenciais

- horário flexível
- Home Office 4x/mês

## Requisitos

**Obrigatórios:**
Para integrar esse time, é necessário que você tenha experiência com: 
- PHP 7.2 avançado; 

**Desejáveis:**
Esperamos também que você conheça: 
- PostgreSQL; 
- API Rest; 
- Nginx; 
- DynamoDB; 
- Symfony; 
- Laravel; 
- Métodos Ágeis.

## Contratação

CLT

## Nossa empresa
Somos uma Fintech de crédito estudantil e lideramos o mercado brasileiro! Sempre buscamos soluções inovadoras e sustentáveis, transformando a vida de pessoas por meio da Educação.
Dá um olhada no nosso LinkedIn: [https://www.linkedin.com/company/pravaler/]

## Como se candidatar

Você poderá se candidatar através do LinkedIn - [https://www.linkedin.com/jobs/view/1071752196/]
Caso não tenha seu perfil por lá, envie o seu CV para talentos@pravaler.com.br

### Alocação:
- Presencial

### Contratação:
- CLT

### Experiência
- Pleno
- Sênior

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
