### ISSUE TITLE
[Uberlândia/MG] Analista Desenvolvedor(a) de Sistemas PHP na Softbox

### ISSUE THREAD

**Issue by milagloria** [phpdevbr/vagas#318]
Descrição das atividades:
Atuar na codificação do sistema na tecnologia PHP conforme arquitetura e padrão de desenvolvimento definidos.

Formação necessária:
Superior Incompleto dos cursos de Sistemas de Informação, Ciências da Computação ou afins.

Requisitos:
Experiência com a plataforma PHP e conhecimento em MySQL, HTML, CSS e Javascript.

Tipo de Contratação: CLT

Local: Softbox, Uberlândia/MG

Vaga: Presencial/Alocado

Nível de candiado: Em aberto

Candidatar:
[https://softbox.com.br/job/analista-desenvolvedor-de-sistemas-php/](url)

Labels:
- CLT
- Presencial/Alocado
- Em Aberto

**Comment by ravanscafi** [comment]
@milagloria a vaga é presencial, remoto ou flexível?
a contratação é CLT, PJ, estágio, outra ou em aberto?
e o nível do candidato? júnior, pleno, sênior ou em aberto?

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
