### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) Pleno ou Sênior PHP na Cashfly

### ISSUE THREAD

**Issue by thiagobutignon** [phpdevbr/vagas#319]
## Descrição da vaga

Projeto de meio de pagamentos sendo construído em MySql, Laravel e Vue.js.

## Local

Escritório, São Paulo/SP - Pinheiros

## Requisitos
- Experiência com PHP
- Laravel
- Banco de dados relacional
- Testes unitários

**Desejáveis:**
- conhecimentos em Symphony

**Diferenciais:**
- Algum framework front-end em Javascript como Angular, React ou Vue.JS
- Ter trabalhado em startups é um diferencial

## Contratação

PJ a combinar

## Nossa empresa

Aqui na Corporação XPTO somos líderes em...

## Como se candidatar

Por favor envie um email para thiago@betaquark.com e bruno@betaquark.com com seu CV anexado - enviar no assunto: Vaga PHP

### Alocação:
- Presencial

### Contratação:
- PJ

### Experiência
- Pleno
- Sênior

**Comment by moreiraandre** [comment]
@thiagobutignon São líderes em? Têm site?

**Comment by vidalvasconcelos** [comment]
@thiagobutignon Symfony, right?

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
