### ISSUE TITLE
[Barueri/SP] Programador(a) Pleno na BusUp

### ISSUE THREAD

**Issue by dtamelini** [phpdevbr/vagas#320]
A nova solução de compartilhamento de compartilhamento de ônibus por demanda o BusUp é um conceito inovador em mobilidade inteligente que permite que os passageiros reservem ônibus sob demanda, para lazer (festivais, pontos turisticos e etc) e deslocamento díario para ir e voltar do trabalho. 
Os usuários podem configurar e reservar suas próprias rotas no aplicativo (iOS e Android) e dividir o custo da tarifa entre seus amigos ou colegas. O BusUp também está disponível para clientes B2B e B2G que desejam criar suas próprias rotas através de uma plataforma web dedicada. 
Ao empregar algoritmos inteligentes artificiais patenteados que determinam tempos ideais de coleta, locais e rotas de veículos, em combinação com módulos de pagamento que permitem aos passageiros dividir a tarifa e dividir os custos, a BusUp é capaz de oferecer uma das soluções mais inovadoras em transporte coletivo transporte.

Estas serão suas principais funções:
·         Resolução de incidentes relacionados aos clientes do BusUp no Brasil. 
·         Assistência técnica ao pessoal da BusUp Brasil. 
·         Participação em novos desenvolvimentos organizados pela Espanha que afetam o funcionamento da plataforma no Brasil.
 
Requisitos mínimos
- Experiência de pelo menos 2 anos programando com PHP.
- Conhecimento básico de framework Laravel.
- Conhecimento básico de trabalhar com o GIT.
- Conhecimento de javascript (o conhecimento de Ionic, Vue, Angular etc. é valorizado)
- Banco de dados com o MySQL.
- Autônomo, independente e autodidata, com alta capacidade de aprendizagem e iniciativa.
- Capacidade de trabalho em equipe.

Contrato PJ
- Espanhol desejável 

Enviar currículo para danilo@busup.com

**Comment by moreiraandre** [comment]
@dtamelini bom dia! Posso enviar o currículo pra onde?

**Comment by dtamelini** [comment]
> @dtamelini bom dia! Posso enviar o currículo pra onde?

eviar para danilo@busup.com

obrigado.

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
