### ISSUE TITLE
[Curitiba/PR] PHP Developer na Regazzo

### ISSUE THREAD

**Issue by Lucimarafreitas01** [phpdevbr/vagas#324]
Desenvolvedor FullStack -  PHP PL/SQL

Descrição da vaga/ atividade:
Trabalhar com desenvolvimento de sistemas em PHP e PL/SQL, atuando em desenvolvimento front-end e back-end. Atendimento de atividades e tickets de suporte abertos pelo cliente. Trabalhar com sistema distribuído e hospedado em nuvem (AWS/Azure).

É necessário possuir conhecimentos em:
•	PHP 4/5 (avançado)
•	Banco de dados Oracle 12g e PL/SQL
•	Conhecimento de framework Zend ou Laravel
•	HTML/CSS 3 e Jquery
•	Bootstrap 4
•	APIs Restfull e SOAP
•	Versionamento com Git
É desejável ter:
•	Conhecimento Padrões de projeto e arquitetura (Design Patterns)
•	Conhecimento em padrão de documentação com UML
•	Conhecimento de metodologias de desenvolvimento como: Scrum, XP, RUP e etc

É necessário ter:

•	Facilidade de comunicação e pró-atividade
•	Perfil autodidata

É um diferencial ter:
•	Inglês Intermediário ou superior
•	Conhecimento na plataforma da Atlasian (Jira ou Confluence)
•	Utilizado profissionalmente metodologias de CI/CD

## Curitiba - PR

 Escritório, Curitiba/PR - Centro

#### Diferenciais

- Horário Super Flexível
- monte a sua máquina como desejar

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com PHP 5+
- Cursado ou em fase de conclusão de curso na área (Ciência da computação, Sistemas de Informação, Análise de sistemas e etc)

## Contratação

PJ a combinar

CLT

## Como se candidatar

Por favor envie um email para administrativo@regazzo.com.br com seu CV anexado - enviar no assunto: Vaga PHP com pretensão salarial e disponibilidade

### Alocação:
- Presencial
- Flexível 

### Contratação:
- CLT
- PJ

### Experiência

- Pleno
- Sênior
- Especialista

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
