### ISSUE TITLE
[Campinas/SP] PHP Developer na Vercan Tecnologia

### ISSUE THREAD

**Issue by vercan-tecnologia** [phpdevbr/vagas#325]
## Descrição da vaga

Desenvolver e dar suporte em sistemas utilizando o Framework Laravel.

## Local

Campinas/SP - São Bernardo.

## Benefícios

- Plano de saúde
- PLR

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com PHP 7+, Orientação a Objetos e Arquitetura MVC 
- Padrões de desenvolvimento em PHP (PSRs) 
- Conhecimento em HTML, CSS e Javascript;
- Experiência com componentes de interface de usuário Bootstrap ou outros;
- Experiência comprovada com Framework Laravel 5.5+
- Integração com APIs Rest e SOAP
- Desenvolvimento de API Restful
- Experiência com banco de dados, preferencialmente MySQL
- Git e outros gerenciadores de dependências 
- Saber escrever um código limpo, organizado e legível

**Desejáveis:**
- Metodologias Ágeis
- Experiência com ERP
- Integração com Gateways de Pagamentos
- NF-e, NFS-e e CT-e
- Boleto Registrado

**Diferenciais:**
- Vue JS
- Testes (TDD)
- Integração Contínua 
- Task Runners (Gulp, Webpack)
- Docker

## Contratação

PJ a combinar

## Nossa empresa

Vercan uma empresa de desenvolvimento de software formada por uma equipe multidisciplinar de profissionais do mundo de TI  e Comunicação.

## Como se candidatar

Por favor envie um email para bruno.maximo@vercan.com.br com seu CV anexado - enviar no assunto: Vaga Laravel

### Alocação:
- Presencial

### Contratação:
- PJ
- Freelance

### Experiência
- Pleno
- Sênior

**Comment by vercan-tecnologia** [comment]
Como posso fechar a vaga?

**Comment by ravanscafi** [comment]
Pronto, @vercan-tecnologia
