### ISSUE TITLE
[Luxemburgo/Luxemburgo] PHP Developer at Docler Holding

### ISSUE THREAD

**Issue by quintanilhar** [phpdevbr/vagas#326]
## Descrição da vaga

- Work with multiple technologies: PHP, MySQL, MSSQL, MongoDB, Memcache, Redis, RabbitMQ, FMS, other distributed and in-house built systems
- High availability systems
- High traffic systems (35 million daily visitors)
- 2000 servers distributed among 4 datacenters worldwide
- Take part in the research of new technologies and solutions

## Local

Luxembourg/Luxembourg

## Benefícios

- Relocation package and support
- Meal vouchers
- Private health insurance
- Sympass card
- Additional holiday entitlement based on length of service with the company
- Free gym membership
- Conferences, certifications, technical workshops, trainings and language courses
- Latest hardware, multiple monitors

#### Diferenciais

- Dynamic and friendly atmosphere
- A multi-cultural environment made of 30 different nationalities, with English as the official language
- Daily breakfast in the office
- Free coffee, tea, and fresh fruit every day
- Fantastic events, including Christmas Parties, Family Days, Hackathons and other surprises
- Chill rooms, creative areas, and LAN parties
- Company branded merchandise (goodies)
- High-quality of life offered by Luxembourg

## Requisitos

**Obrigatórios:**

- 3 years of software development experience (in PHP projects)
- OOP skills and knowledge of design patterns
- Clean Coding is your most important principle
- Experience with Relational Databases and NoSQL technologies
- Passionate about self-improvement and web technologies
- Upper intermediate English knowledge (B2) or higher

**Desejáveis:**

- Experience in any other Web Development technology
- Knowledge of Unit Testing and Test Driven Development
- Familiarity with Extreme Programming (XP)
- Knowledge of Agile methodologies

**Diferenciais:**

- Experience with Live Streaming and Stream Encoding technologies
- Experience working with high-availability, high-performance, scalable systems

## Contratação

Relocation required to Luxembourg

## Nossa empresa

Does the thought of working with Scalable Web Architecture intrigue you? Over 200 developers are working around the world (and clock) always ensuring that our service maintains its highest standard at all times. If you would like to join a diverse international team and work on interesting projects that challenge your knowledge and expertise, you’re the kind of person we want! Come and join us at our headquarters in Luxembourg!

## Como se candidatar

Por favor, envie um email para ricardo.quintanilha@doclerholding.com com o assunto "PHP Developer DH" e o seu CV em anexo.

### Alocação:
- Presencial

### Contratação:
- Contrato

### Experiência
- Pleno
- Sênior
- Especialista

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
