### ISSUE TITLE
[São Paulo/SP] PHP Developer na Taxation Mind

### ISSUE THREAD

**Issue by feijaocosta** [phpdevbr/vagas#327]
## Descrição da vaga
Buscamos programador PHP, com experiência em desenvolvimento de aplicações web. 
Somos uma empresa de Consultoria Fiscal, e desenvolvemos ferramentas para tratamento e gestão de dados de clientes.

## Local
Presencial, São Paulo/SP - Lapa

## Benefícios
- VR + VT

## Requisitos
**Obrigatórios:**
- Experiência com PHP 5+
- Experiência com Banco de Dados

## Contratação
CLT

## Como se candidatar

Por favor envie um email para carlos.costa@taxationmind.com.br com seu CV anexado e pretenção salarial - enviar no assunto: Vaga PHP

### Alocação:
- Presencial

### Contratação:
- CLT

### Experiência
- Pleno
- Sênior

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
