### ISSUE TITLE
[Barueri/SP] PHP Developer na Fingerprint

### ISSUE THREAD

**Issue by deizepi** [phpdevbr/vagas#329]
## Descrição da vaga

Desenvolver painéis administrativos (dashboard) para produtos e serviços (contendo controle de acesso - ACL, trilha de auditoria, relatórios, CRUD, etc), fazer integrações com meios de pagamento (cartões de crédito e débito, boleto, débito em conta, dinheiro) através dos mais diversos canais (aplicativo, máquina de cartão, site, e-mail, etc).

## Local

Remoto ou Escritório, Barueri/SP - Alphaville

## Benefícios

- Plano de saúde
- Seguro de vida
- Restaurante no local
- VT
- VA (no valor de R$ 80,00/mês)
- PLR

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com PHP
- Conhecimento em HTML, CSS e Javascript
- Conhecimento em MariaDB

**Desejáveis:**
- Conhecimento em Phalcon (Framework PHP) ou outro framework
- Conhecimento em VueJS
- Conhecimento em OAUTH2

**Diferenciais:**
- Experiência com painéis administrativos
- Experiência com API
- Experiência com meios de pagamento

## Contratação

CLT para presencial
PJ para remoto

## Nossa empresa

A Fingerprint é uma gráfica de dados variáveis (boletos, faturas, extratos, mensagens personalizadas, etc.) há 25 anos no mercado, nos últimos 5 anos decidimos inovar os meios de pagamento, ingressamos no setor com uma ferramenta completa para ONGs, hospitais, igrejas, etc. e não paramos por aí, estamos constantemente trabalhando para entregar a melhor solução em meios de pagamento para os demais setores.

## Como se candidatar

Por favor envie um email para laraujo@fingerprint.com.br com seu CV anexado - enviar no assunto: GIT - PHP Devoloper

### Alocação:
- Presencial
- Remoto (apenas para PJ)

### Contratação:
- CLT
- PJ

### Experiência
- Júnior
- Pleno
- Sênior

**Comment by deizepi** [comment]
A vaga continua em aberto.

**Comment by guilhermeoa07** [comment]
Os 2 anos de experiência também é necessário para Júnior?

**Comment by deizepi** [comment]
Boa tarde, por favor, encaminhe esse email para laraujo@fingerprint.com.br (falar com a Lilian) com o currículo em anexo. Embora a experiência seja importante, valorizamos muito a busca por conhecimento do candidato.

Muito obrigado.



Sent via the Samsung Galaxy S8, an AT&T 4G LTE smartphone


-------- Mensagem original --------
De: Guilherme Oliveira <notifications@github.com>
Data: 05/03/19 16:47 (GMT-03:00)
Para: phpdevbr/vagas <vagas@noreply.github.com>
Cc: David Deizepi <david_deizepi@hotmail.com>, Author <author@noreply.github.com>
Assunto: Re: [phpdevbr/vagas] [Barueri/SP] PHP Developer na Fingerprint (#329)


Os 2 anos de experiência também é necessário para Júnior?

**Comment by deizepi** [comment]
A vaga continua em aberto.

**Comment by fhpimenta** [comment]
Enviei currículo no dia 12/02, e não entraram em contato, @deizepi

**Comment by deizepi** [comment]
@fhpimenta agradecemos o envio do seu currículo. Estamos avaliando todos os currículos enviados e entraremos em contato com candidatos cujo perfil mais se adequam às vagas.

**Comment by deizepi** [comment]
A vaga continua em aberto.

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
