### ISSUE TITLE
[Campinas/SP] PHP Developer na Every System

### ISSUE THREAD

**Issue by renanevery** [phpdevbr/vagas#330]
## Descrição da vaga

Buscamos um profissional de para atuar em suporte e desenvolvimento de sistemas PHP, utilizando o framework Laravel.

## Local

Campinas/SP - Guanabara (com possibilidade de atuar em home office)

## Benefícios

- Plano de saúde
- VR

#### Diferenciais

- Flexibilidade de horário
- Grande possibilidade de crescimento
- frigobar sempre cheio :P

## Requisitos

- Experiência em desenvolvimento web com PHP, MySQL, HTML, JavaScript e CSS.
- Conhecimentos intermediários  no framework Laravel
- Utilização de boas práticas de Programação e códigos reutilizáveis
- Garantir que as entregas correspondem às especificações pré-estabelecida pelo PO
- Colaborar com outros membros do time
- Conhecimento em Git
- Vivência em ambiente linux
- Conhecimentos desejáveis (Bootstrap, JQuery, Ajax  e Vue.js)

## Contratação

CLT a combinar

## Nossa empresa

A Every System é uma empresa especializada em Cloud Computing e Segurança da Informação, relativamente nova, mas com um grande potencial de crescimento, onde você poderá crescer junto. Somos movidos por inovação!

## Como se candidatar

Por favor envie um email para [contato@everysystem.com.br](mailto:contato@everysystem.com.br) com seu CV anexado.

**Comment by jonaswebdev** [comment]
Qual faixa salarial oferecida?

**Comment by renanevery** [comment]
Vaga preenchida!
Obrigado à todos!
