### ISSUE TITLE
[Belo Horizonte/MG] Desenvolvedor(a) PHP na Smart Total

### ISSUE THREAD

**Issue by megandavulpi** [phpdevbr/vagas#336]
### Sobre a empresa: Smart Total

Smart Total é uma plataforma inovadora para agilizar o envio de informações para o eSocial e oferecer benefícios para os colaboradores. Para todos os tamanhos de empresas, desde as microempresas até as grandes indústrias, todos precisam estar em dia com a documentação de seus empregados e Smart Total é uma ferramenta essencial para o bom andamento desse controle. 

De maneira prática e integrada, o sistema conecta profissionais da área de saúde e segurança do trabalho e medicina assistencial às necessidades da sua empresa. E se a sua empresa também quer proporcionar vantagens para seus empregados e atender às novas regras da legislação trabalhista e previdenciária, você precisa conhecer a Smart Total.

### Descrição: Quais serão as suas responsabilidades?

Analisar as histórias a serem desenvolvidas;
Codificar, testar e publicar no ambiente de homologação;
Corrigir problemas no sistema legado;
Promover o ambiente de homologação para o de produção.

### Procuramos profissionais com experiência em:

PHP;
Laravel;
jQuery;
Bootstrap.

### Você gostará de trabalhar aqui se:

Valoriza um ambiente de trabalho em constante desenvolvimento e crescimento;
Acredita que aprender mais sobre tecnologia e soft skills vão fazer de você um(a) profissional melhor;
Trabalha com proatividade e valoriza projetos em equipe;
Trabalha de forma organizada e é centrado(a) nos seus objetivos.

### Benefícios:

Vale Transporte ou Vale Combustível;
Vale Refeição;
Assistência Médica.

### Labels:

Presencial
CLT
Pleno

### Candidatar: http://bit.ly/smarttotal_github

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
