### ISSUE TITLE
[Florianópolis/SC] PHP Developer na Zallpy Group

### ISSUE THREAD

**Issue by maikealame** [phpdevbr/vagas#337]
## Descrição da vaga

Trabalhar com Sistemas Internos de Cliente, com funcionalidades como administrativo e financeiro.
**Vaga com limite de 1 mês**, com chance de efetividade no mesmo ou em outros projetos.

## Local

Centro de Inovação ACATE Primavera, Florianópolis/SC
[Ver no Google Maps](https://www.google.com/maps/uv?hl=pt-BR&pb=!1s0x952747679119978f%3A0x3f87d152eb7c78d5!2m22!2m2!1i80!2i80!3m1!2i20!16m16!1b1!2m2!1m1!1e1!2m2!1m1!1e3!2m2!1m1!1e5!2m2!1m1!1e4!2m2!1m1!1e6!3m1!7e115!4shttp%3A%2F%2Fpasseioprimavera.com.br%2Fimpact_hub-2%2F!5sACATE%20Primavera%20coworking%20-%20Pesquisa%20Google&imagekey=!1e10!2sAF1QipMpgqR0MMtOTmp4P3o4LX2tbxmIA2CY16WGUAVl&sa=X&ved=2ahUKEwi_q8aGwc3gAhWoHLkGHT9mCMwQoiowCnoECAYQBg)

Temos escritório em POA/RS

## Benefícios

- Plano de saúde
- VR / VT

## Requisitos

**Obrigatórios:**
- Experiência com PHP 5+ e Symfony

**Desejáveis:**
- conhecimentos em SCRUM

## Contratação

- CLT
- Freela
- PJ
Avaliamos qualquer tipo de efetividade acima, basta enviar sua proposta.

## Nossa empresa

Empresa especializada no atendimento a grandes corporações, suprindo todas as necessidades de aplicações de softwares, serviços e infraestrutura, aliando tecnologias de alto desempenho a expertise de uma equipe multidisciplinar, oferecendo soluções de ponta a ponta em TI. 
Inovador, o Zallpy Group auxilia na otimização de processos, redução de custos e aperfeiçoamento de produtos e serviços, agregando resultados reais para os negócios de seus clientes.

## Como se candidatar

Por favor envie um email para maike.alame@zallpy.com com seu CV anexado - enviar no assunto: Vaga Symfony SC

### Alocação:
- Presencial

### Contratação:
- CLT
- Freela
- PJ

### Experiência
- Pleno

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
