### ISSUE TITLE
[Belo Horizonte/MG] Desenvolvedor(a) BackEnd PHP na Task 

### ISSUE THREAD

**Issue by megandavulpi** [phpdevbr/vagas#342]
### Sobre a empresa: Task Internet

Com mais de 20 anos de mercado, a Task é líder em hospedagem de sites em Belo Horizonte. Conta com uma equipe altamente qualificada, focada em qualidade e atendimento diferenciado. Para nos conhecer melhor, acesse nosso site.

### Descrição: O que você fará na Task?

Irá auxiliar no desenvolvimento e codificação de soluções, tanto internas quanto para clientes externos. E para isso precisamos que você esteja com grande interesse de crescer e agregar nosso time. É uma aventura com muitas possibilidades. Você conviverá em um ambiente rodeado de tecnologia. Quer um mundo melhor que esse? Não tem. Você precisa ter facilidade em entender documentação, aprender com a leitura técnica e conseguir gerar documentação do que for criado por você.

### Requisitos que você precisa atender:

Experiência com PHP;
Experiência com Laravel versão 5 ou superior;
Conhecimento de HTML 5, CSS3;

### Diferenciais que vão contar pontos para você:

Conhecimento em MySql;
Noções de SEO;
Versionamento com Git/SVN;
UI/UX;7
Vue.js;
React Native;

### Oferecemos um tudo para você crescer:

Salário compatível com o mercado;
Clima descontraído;
Carga horária de 6h diárias;
Vale refeição;
Fazer parte de uma equipe foda e com grande possibilidade de crescimento e conhecimento;
Plano de saúde Unimed 100% custeado pela Task.

### Seus desafios serão:

Programar, codificar e testar os projetos criados;
Ajudar a idealizar novos projetos;
Acompanhamento de entregas;
Auxiliar na criação de uma equipe de alta performance.

### Labels:

Iniciante / Junior
Alocado

### Candidatar: http://bit.ly/taskphp_github

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
