### ISSUE TITLE
[Guarulhos/SP] PHP Developer na B2 Mídia

### ISSUE THREAD

**Issue by cjuca** [phpdevbr/vagas#343]
## Descrição da vaga

Projeto de aplicativo de comunicação corporativa.

**Desejável o conhecimento em:** 

**Responsabilidade:**
- Desenvolver melhorias, alterações e correções na plataforma da empresa, trabalhando no backend, frontend e mobile;
- Trabalhar em conjunto com analista na elaboração e desenvolvimento de novas funções para a plataforma;
- Projetar e implementar integrações com sistemas de terceiros;
- Organizar e manter organizado o código-fonte dos projetos no Git;
  
**Perfil**
-    Comprometimento com entrega e qualidade
- ·         Trabalhar EM equipe, COMO equipe e PELA equipe
- ·         Autogerenciamento (Controle de prazos e atividades)
- ·         Disponibilidade para jornadas estendidas ou em regime de plantão previamente comunicados"
- ·         Disponibilidade para deslocamentos pontuais
- ·         Adepto à boas práticas de produção e convívio em grupo

## Local

Gurarulho/SP

## Benefícios
·         Vale-transporte
·         Seguro de vida
·         Plano de Saúde - 20% de subsídio

## Requisitos

**Obrigatórios:**
- Linguagem PHP 7.2
- Banco de dados MySQL
- Entendimento de APIs REST
-GIT

**Desejáveis:**
- Javascript (Angular)
- Java (Android)
- Swift (iOS)
- Zend Framework

**Diferenciais:**

## Contratação

CLT ou PJ a combinar

## Nossa empresa
A B2 Mídia é especialista em Comunicação Corporativa. Desde 2010, trazemos soluções para a comunicação de pequenas, médias e grandes empresas. Acreditamos que a felicidade do colaborador interfere diretamente em sua produtividade, por isso, buscamos meios e ações que promovam esse ambiente nas empresas dos nossos clientes. A alegria dá lucro!

## Como se candidatar

Por favor envie um email para juca@lab3dvlp.com com seu CV anexado - enviar no assunto: Vaga PHP - B2 Mídia

### Alocação:
- Presencial

### Contratação:
- CLT
- PJ

### Experiência
- Pleno

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
