### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) PHP SR na Mobly

### ISSUE THREAD

**Issue by penelopevitoria** [phpdevbr/vagas#348]
### **Descrição da vaga**

Desafio, autonomia e inovação. Está é a nossa proposta, maior e-commerce de Móveis do Brasil. Procuramos profissional curioso, dinâmico e que goste de metodologia ÁGIL. 
Temos em nosso DNA tecnologia e inovação. Trabalhamos com horários flexíveis, home office e dress code informal. Achou que combina com você? Mande seu currículo pra gente!

**Atividades:** 

Análise e desenvolvimento de novas funcionalidades para a plataforma de e-commerce e backofice com foco em performance, escalabilidade, segurança e qualidade. 
Integração de sistemas internos e de parceiros através de webservices REST/SOAP.

### **Benefícios**

- Vale refeição
- Vale transporte
- Plano de saúde
- Plano odontológico
- Outros

### **Requisitos Obrigatórios:**

Manjar de MySQL e PHP

### **Requisitos desejáveis**

React, SCRUM, Vue.js, Symfony 2, Redis, Laravel 5, Memcached

### **Como se candidatar?**

Regime CLT // Entre R$ 5 000,00 a R$ 7 000,00.

Cadastre-se para concorrer à vaga: http://bit.ly/2Y7pJdc

**Comment by moreiraandre** [comment]
@penelopevitoria Link não funciona

**Comment by xtfs** [comment]
@penelopevitoria como o @moreiraandre mencionou
> @penelopevitoria Link não funciona

 o link abre, porém o registro não funciona.

Após colocar o e-mail e clicar em **Continuar** o mesmo retorna um erro 500 na url: https://www.geekhunter.com.br/candidates/candidates/0/check_registration?email=sarcer@gmail.com

**Comment by penelopevitoria** [comment]
Bom dia @xtfs e @moreiraandre.

Tudo certo?

Peço desculpas pelo inconveniente. Tivemos um problema como nosso banco de dados durante a madrugada. Já estamos trabalhando para contornar a situação. Novamente, desculpas pelo imprevisto.

**Comment by xtfs** [comment]
Olá @penelopevitoria 
Agora está funcionando, obrigado pelo feedback.

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
