### ISSUE TITLE
[Campinas/SP] Desenvolvedor PHP na StarCorp Informática

### ISSUE THREAD

**Issue by starcorpgolfieri** [phpdevbr/vagas#35]
## Local

Escritório, Campinas - SP

## Requisitos

**Obrigatórios:**
- PHP (Language)

**Desejáveis:**
- S.O.L.I.D. (concept)
- PHPUnit (Unit Testing Tool)
- Composer (Dependency Management Tool)
- Dependency Injection (Concept)

**Diferenciais:**
- Behat (Functional Testing Tool)
- PSR - PHP Standard Rules (Language Standard)

## Contratação

- PJ a combinar

## Como se candidatar

Por favor envie um email para souphp@souoriginal.com.br com seu CV anexado - enviar no assunto: #VPHPGIT

**Comment by rscafi** [comment]
@starcorpgolfieri Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.
