### ISSUE TITLE
[São Paulo/SP] PHP Developer na GSN

### ISSUE THREAD

**Issue by kathedrall** [phpdevbr/vagas#350]
## Descrição da vaga

Projeto  PHP e  Zend Framework 1
## Local

Escritório, São Paulo/SP - Lapa

## Requisitos

**Obrigatórios:**
- Experiência com PHP 5+
- Experiência com Banco de Dados Mysql
- Experiencia com Zend ou Laravel
- Experiencia com Java Script / Jquery
- Experiencia com Testes Unitario
- Experiencia com Docker

**Desejáveis:**
- conhecimentos em Magento 1 e Zend Framework 1

## Contratação

PJ  R$ 9000,00

## Nossa empresa

Somos uma  HR TECH

## Como se candidatar

Por favor envie um email para  gabriela.vaccari@gsn.com.br com seu CV anexado - enviar no assunto: Vaga PHP

### Contratação:
- PJ

### Experiência
- Sênior

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
