### ISSUE TITLE
[São Paulo/SP] PHP Developer na HubChain

### ISSUE THREAD

**Issue by ThamirisSales** [phpdevbr/vagas#353]
**Desenvolvedor PHP / Back-end.**

**Requisitos**
•	Git
•	Js
•	Php
•	Outras linguagens de programação (java, python, C#, C++)
•	Agile
•	Php frameworks (zend, laravel, lumen, etc)
•	Automação de builds (npm, composer, etc)
•	Linux
•	Apis
•	Testes unitários
•	Bancos de dados relacionais (mysql, postgresql)

**Diferencial**
•	Ambiente descontraído e agradável
•	Várias coisas boa para comer no escritório (frutas, refrigerante, suco, salgadinho, pão etc.))

**Local**
•	Próximo ao Aeroporto de Congonhas, São Paulo / SP

**A vaga é presencial. O regime de contratação é á combinar PJ ou CLT**. Faixa salarial é de R$ 3 mil a 3,5 mi + benefícios. Interessados devem enviar currículo para thamiris.sales@bkconsultoria.com.br

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
