### ISSUE TITLE
[Santos/SP] PHP Developer na Zaptrade

### ISSUE THREAD

**Issue by hribeirozap** [phpdevbr/vagas#355]
## Descrição da vaga

Desenvolvimento de projetos WEB
Manutenções evolutivas e corretivas em sistemas desenvolvidos em PHP/MySQL
Propor soluções e desenvolver novas tecnologias para melhorar sistemas legado.
Trabalhar com equipe multidisciplinar em ambiente ágil de desenvolvimento

## Local

Remoto ou Escritório, Santos/SP - Gonzaga

## Requisitos

**Obrigatórios:**
- experiência com PHP 5+
- experiência com MySQL
- HTML
- Javascript
- JQuery

**Desejáveis:**
Vivência em métodos ágeis de desenvolvimento
Conhecimento em C# (.NET)
Framework Symfony
Integração com API's,
Vue.JS

## Contratação

PJ a combinar

## Nossa empresa

A ZAPTRADE é uma empresa focada em Tecnologias de Negócios com mais de 20 anos de mercado. Entregamos soluções para toda a cadeia de COMEX e segmentos como Varejo, Terminal Portuário/Logística, Farmácia, dentre outros.

## Como se candidatar

Por favor envie um email para henrique.ribeiro@zaptrade.com.br com seu CV anexado - enviar no assunto: Vaga PHP

### Alocação:
- Flexível (Remoto parcial)

### Contratação:
- PJ
- Freelance

### Experiência
- Pleno

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
