### ISSUE TITLE
[São Paulo/SP] PHP Developer no Promobit

### ISSUE THREAD

**Issue by silverwolfx10** [phpdevbr/vagas#356]
## Descrição da vaga
Temos duas vagas para desenvolvedor PHP.

Como um desenvolvedor em nossa equipe você vai contribuir com a arquitetura da aplicação, novas tecnologias, automatização de tarefas, implementar melhorias de layout e correções de bugs.

Aqui você vai encontrar um time que trabalha com metodologia ágil Scrum, juntos atendemos demandas de novas funcionalidades do produto, e apoiamos as áreas com melhorias nos processos existentes com desenvolvimento de ferramentas internas.

## Local

Ao lado do Parque Ibirapuera

## Requisitos

**Obrigatórios:**

- Controle de versão (Git)
- HTML5 e CSS3
- Javascript puro e jQuery
- PHP com orientação a objetos
- MySQL

**Diferenciais:**

- REST
- Ter trabalhado com framework PHP (ex: Respect, SLIM, ZEND, Laravel, etc...)
- TDD
- Web Scraping

## Contratação

- PJ a combinar
- Somente alocado

## Nossa empresa

O Promobit é uma startup que usa inteligência coletiva para encontrar as melhores ofertas do Brasil. Somos uma plataforma que empodera o consumidor, permitindo e incentivando a troca de conhecimento e informações dentro da comunidade.

Somos uma equipe de pessoas apaixonadas pelo que fazem e que trabalham duro todos os dias para honrar a nossa missão: "aumentar o grau de satisfação do consumidor brasileiro".

E estamos buscando um desenvolvedor(a) pleno para nos ajudar com a evolução de nossos produtos. 

## Como se candidatar

Envie um email para leandro@promobit.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Vaga PHP e com profile do linkedin, ou acesse: https://www.promobit.com.br/index/vaga/8

### Alocação:
- Presencial

### Contratação:
- PJ

### Experiência
- Pleno

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
