### ISSUE TITLE
[Santo André/SP] PHP Developer na C4W Labz

### ISSUE THREAD

**Issue by renamelo** [phpdevbr/vagas#357]
## Descrição da vaga

Procuramos profissionais para completar o nosso time para o desenvolvimento de uma plataforma para contratação de serviços de limpeza.

## Local

- Santo André / Remoto

## Requisitos

- 2 a 3 anos de experiência com PHP >= 5.6
- PSR’s
- 12 fatores
- Versionamento Git
- Conhecimentos em Linux distribuição Ubuntu
- Containers com Docker
- Laravel (a partir da versão 5.6)
- Modelagem em banco de dados relacional
- Javascript, Biblioteca CSS Bootstrap
- Serviços RESTFUL para criação e integração
- Criação e gerenciamento de dependências via composer
- Design de API's REST

**Desejáveis:**

- Conhecimento e experiência em métodos ágeis, principalmente Scrum
- CI/CD
- PHPUnit

**Diferenciais:**

- Conhecimento em serviços em cloud AWS S3, SQS, EC2
- Conhecimento em algum framework front-end
- DevOps
- Jenkins
- Kubernetes

## O que esperamos dos candidatos

- Ter boa comunicação e disponibilidade para discutir insistentemente melhorias aos nossos produtos.
- Paixão por trabalho em equipe ainda que seja com poucos colaboradores, pois levamos a sério a colaboração entre os nossos times.
- Leitura, escrita e fala corretas e objetivas.
- Ouvir é outra habilidade chave, pois os feedbacks dos clientes devem ser levados a sério e discutidos em equipe para melhorarem os nossos produtos.
- Ter habilidade para desenvolver uma aplicação baseada em API.

## Contratação

PJ a combinar

## Nossa empresa

A C4W Labz conta com um time multidisciplinar e sempre utilizando todo nosso conhecimento de marketing, engenharia de software e administração de negócios para criar soluções tecnológicas que ajudam as empresas a crescerem cada vez mais.

## Como se candidatar

Quer fazer parte do nosso time?
Envie um e-mail para:

- samuel.fonte@c4wlabz.com
- renan.melo@c4wlabz.com

E conte sobre a sua experiência e projetos que já realizou.

### Alocação:
- Flexível (Remoto parcial)
- Presencial

### Contratação:
- PJ a combinar

### Experiência
- Pleno

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
