### ISSUE TITLE
[Joinville/SC] PHP Developer na A2C

### ISSUE THREAD

**Issue by programadormarin** [phpdevbr/vagas#359]
## Descrição da vaga

Procuramos um (a) profissional apaixonado (a) pelo desafio de conectar pessoas e marcas por meio de experiências relevantes, com foco em tecnologia, boa experiência em CMS e Frameworks PHP (como Symfony, Wordpress, Drupal, Laravel) e gerenciamento de Cloud Hosts (AWS, Azure, Locaweb, etc) Linux. 
Irá atuar no desenvolvimento de sites, sistemas e integrações em parceria direta com o time de Front-end e demais competências.

## REQUISITOS

- Conhecimentos em Wordpress e plugins;
- Ter experiência de no mínimo 3 anos com PHP;
- Saber informar aplicativos em Hostings (Amazon, Locaweb, Rackspace, etc);
- Conhecimento intermediário em Linux e configuração do servidor cloud / aplicação;
- Conhecimentos em Apache, NGINX, MySql, GIT.
- Graduação em Sistemas de Informação ou Engenharia de Software;
- Residir em Joinville (preferência), região grande ou distante com disponibilidade para as reuniões presenciais semanais;
- Manual de instruções

## DIFERENCIAIS

- Experiência com um destes frameworks: Symfony, Laravel, Zend;
- Conhecimento em Drupal 8 (preferencial) ou Drupal 7;
- Conhecimento em Docker;
- Inglês intermediário ou fluente;
- Pós-Graduação ou especializações
- Certificações (online, presencial, etc.)
- Compartilhar conhecimento (artigos, blog, livro, palestras, workshops, etc.)

## RESPONSABILIDADES:

- Desenvolvimento backend em projetos;
- Ajustes, correções e melhorias em demandas pontuais;
- Contato e resolução direta com o cliente;
- Suporte a demandas internas de integração e automatização;
- Analisar e propor novas facilidades, demandas, projetos;
- Suporte e manutenção de Cloud Hosts (Linux) ..

## BENEFÍCIOS

- Plano de saúde: após 90 dias (experiência), sendo 50% da mensalidade paga pela A2C;
- Plano odontológico: após 90 dias (experiência);
- Auxílio com alimentação ou refeição de R $ 21,00 por dia / útil;
- Vale transporte com desconto de 6% do salário;
- Apoio em eventos nacionais e internacionais e intercâmbio.
- Auxílio em capacitação: Sob demanda e análise do impacto do dia a dia (50%)
- Possibilidade de empreender dentro da própria A2C.
- Ambiente inovador e descontraído.
- Convênio com Sesc;
- Seguro de vida
- Licença Paternidade de 10 dias.
- Licença Maternidade de 150 dias (5 meses).
- Livro aberto (A A2C compra o livro que você quer ler)
- Ingresso de Cinema GNC à 15,00 via cowork.
- Pesquisa de Clima Semanal
- Avaliação de desempenho 360 °.
- A2C Compartilha (Oportunidade de Oculto com o Workshop e Artigos)
- Happy Hour Mensal.
- Dia de folga (Dia de folga no aniversário).

## Modelo de contratação

- CLT
- PJ

## Local de trabalho

- Presencial em Joinville / SC
- Remoto

Envie seu currpiculo em: [Recruitebox](https://a2ctransforma.recruiterbox.com/jobs/fk0jo77/)

**Comment by ravanscafi** [comment]
@programadormarin Regime de contratação? Alocação? Experiência?

**Comment by programadormarin** [comment]
> @programadormarin Regime de contratação? Alocação? Experiência?

Editado!!!

**Comment by matheus-souza** [comment]
# Erro ao submeter currículo
![image](https://user-images.githubusercontent.com/14989876/60749769-3de63d80-9f75-11e9-8454-c5846478eb7d.png)

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
