### ISSUE TITLE
[Porto Alegre/RS] PHP Developer na BK Consultoria

### ISSUE THREAD

**Issue by ThamirisSales** [phpdevbr/vagas#360]
A Bk Consultoria está contratando Developoer  PHP para atuar em uma empresa multinacional no segmento educacional, uma das maiores redes de educação superior do mundo que está presente em 25 países.

REQUISITOS:
. Formação completa ou cursando em TI ou areas afins;
. Experiência em linguagens de desenvolvimento PHP e banco de PostgreSQL

## Local
15 minutos do Shopping Iguatemi e do Bourbon Country

## Benefícios
- Plano de saúde e odonto
- VR 
- VT

## Contratação
CLT a combinar

## Como se candidatar
Por favor envie seu currículo e pretensão salarial para thamiris.sales@bkconsultoria.com.br -  enviar no assunto: Vaga PHP Porto Alegre

### Alocação:
- Presencial

### Experiência
- Júnior
- Pleno

-

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
