### ISSUE TITLE
[Joinville/SC] PHP Developer pela Acadde Human Capital

### ISSUE THREAD

**Issue by AccadeHumanCapital** [phpdevbr/vagas#367]
## Descrição da vaga
Consultoria em RH assessorando uma startup em processo de expansão na busca de um profissional Front-End Developer Mobile.

Atribuições:
– Foco em analisar e desenvolver a estrutura de trabalho para a equipe de desenvolvimento;
– Desenvolvimento de novas features;
– Melhoria do framework MVC;
– Prestar suporte à equipe quanto aos padrões de desenvolvimento.

## Local

Escritório localizado no bairro Saguaçu em Joinville/SC

## Requisitos

**Obrigatórios:**
– Sólida experiência com Frameworks PHP, MVC e Orientação à Objetos;
– Mínimo de 2 anos de experiência anterior como Programador/Desenvolvedor Sênior;

**Diferenciais:**
– Experiência com Segurança da Informação (em nível de infraestrutura e aplicação);
– Excelente habilidade comunicativa;
– Experiência com Code Review, TDD e PHPUnit.

## Contratação

PJ

## Nossa empresa

Na Accade Human Capital stuamos na seleção de pessoas para posições Estratégicas, Administrativas e Técnicas, captando candidatos diferenciados com características alinhadas à filosofia e cultura da sua organização.

Utilizamos metodologia estruturada para compreensão do segmento e negócio da empresa cliente, alinhamento de perfil, atração de candidatos, processo de triagem, seleção de talentos, aplicação de métodos, elaboração de relatórios e monitoramento do processo.

## Como se candidatar

Por favor envie um email para talentos@accade.com.br com seu CV anexado com pretensão salarial - enviar no assunto: Front-End Developer Mobile - Joinville

## Labels
- Presencial
- PJ
- Sênior
- Joiville/SC

**Comment by mvnp** [comment]
Olá. Eu sou programador home office, moro em Floripa. Estou disposto a receber depois da execução do job. Caso tenha interesse numa possível contratação PJ remoto ou por job, aguardo o seu contato.

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
