### ISSUE TITLE
[Santos/SP] PHP Developer na Box Delivery

### ISSUE THREAD

**Issue by jeanboxdelivery** [phpdevbr/vagas#371]
### Descrição da vaga
Desenvolvimento e manutenção de projetos WEB em PHP/Node/MySQL, Propor soluções e 
desenvolver novas tecnologias para melhorar o atual sistema e futuras aplicações.

### Local
Escritório, Santos/SP

##### Obrigatórios:
- PHP
- MySQL, NoSQL
- Conceito APIS RESTful
- Javascript
- Git
- Integração com API's,
- Repositories, Transformers
- Clean Code

#### Diferencial
- Usar PSR
- Laravel
- React, Vue
- Unit and Feature Tests
- Gcloud, Kubernets
- Docker
- Go, Python, Ruby e NodeJs

### Contratação
PJ a combinar

### Nossa empresa
O Box Delivery é uma StartUp de entregas que liga o comerciante com os entregadores disponíveis da região.
Hoje estamos em pleno crescimento, com atuação em várias cidades do Brasil. 

### Como se candidatar
Por favor envie um e-mail para renato@boxdelivery.com.br com seu CV anexado - enviar no assunto: Vaga PHP
 
### Experiência
Pleno/Senior

## Labels
- regime/PJ
- alocação/Presencial
- experiência/Pleno/Senior

### Alocação:
- Presencial

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
