### ISSUE TITLE
[São Paulo/SP] Pleno PHP Developer na Convenia

### ISSUE THREAD

**Issue by conveniadev** [phpdevbr/vagas#373]
## Descrição da vaga

Um pouco sobre a nossa stack:
- Frameworks Laravel e Codeigniter
- RabbitMQ
- Infra AWS
- API Rest e GraphQL
- VueJS

## Local

Escritório, São Paulo/SP - Alameda Campinas 977

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche
- ...

#### Diferenciais

Beneficios flexíveis com as opções:

- Cartão Refeição
- Cartão Alimentação
- Plano de Saúde
- Plano Dental
- Desconto farmácia
- Smart Fit + Bio Ritmo
- Chef´s club (desconto em restaurantes)
- Clube de Vantagens Convenia
- Seguro de Vida
- Estacionamento
- Auxílio creche
- Vale Transporte

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com Laravel
- Experiência com API REST
- Experiência com testes (BDD, TDD)

**Diferenciais:**
- Mensageria - RabbitMQ
- Microserviços
- Graphql
- Experiência com SCRUM
- Princípios SOLID

## Contratação

CLT

## Nossa empresa

A Convenia tem a responsabilidade de transformar o RH das empresas, transformando a burocracia em uma experiência fluida e agradável.

Estamos buscando desenvolvedores(as) Back-end para uma vaga presencial, em São Paulo - Capital.

Acreditamos em um trabalho inteligente, com bom relacionamentos, alinhamento de cultura e que seja divertido. 

Se você tem uma pegada de startup e tá afim de vir fazer acontecer e compor nossos times de devs, chega mais.

## Como se candidatar

Por favor se cadastre pelo link: https://convenia.recruitee.com/o/desenvolvedora-backend-pleno-php/c/new

### Alocação:
- Presencial

### Contratação:
- CLT
- PJ

### Experiência
- Pleno

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
