### ISSUE TITLE
[Lisboa/Portugal] PHP Developer na Aubay

### ISSUE THREAD

**Issue by alexandregvale** [phpdevbr/vagas#376]
Descrição da vaga
Projetos em vários setores de atividade, usando diversas tecnologias de PHP e Front-end.

Local
Portugal: Lisboa

Benefícios
• Plano de saúde
• Visto de Trabalho para Portugal
• Outras

Diferenciais
• Formações técnicas e comportamentais
• Prémios de referências de recrutamento
• Eventos team Building
• Convívio mensal
• Oferta de aniversário

Requisitos
Obrigatórios:
• Conhecimentos em desenvolvimento PHP e experiência com diferentes frameworks (Laravel, Zend, Symfony);
• Conhecimentos em JavaScript (jQuery), HTML, CSS
• Fluencia em inglês.

Diferenciais:
• Experiência internacional

Contratação
Apoio em todo o processo para obtenção de visto de trabalho para Portugal.

Nossa empresa
A Aubay, é uma empresa de origem francesa presente em diversos países na Europa.
Como cerca de 7000 pessoas desenvolvemos projetos nas mais diversas tecnologias.
Neste momento, temos várias vagas em aberto para várias posições.

Como se candidatar
Por favor envie para avale@aubay.com com seu CV em inglês anexado colocando no assunto PHP_19.

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
