### ISSUE TITLE
[São Paulo/SP] Desenvolvedor PHP FullStack no Beedoo

### ISSUE THREAD

**Issue by ptcmariano** [phpdevbr/vagas#377]
## Descrição da vaga
Atuará na criação de novas features e manutenção do sistema além de trabalhar consultas no DB grandes e complexas para geração de relatórios, frontend (css/js) utilizando bootstrap/proprietário/Vuejs.

Experiência mínima de 2 anos em:

- PHP7+

- MySQL

- Modelagem de dados relacionais

- Javascript

- JQuery

- HTML

- CSS

- Codeigniter

- GIT

- Vue.js

Diferenciais:

- Vivência com alguma framework JS reativo (Preferencialmente Vue.js)

- Websocket

- NodeJS

- AWS

Local de Trabalho: SÃO JOSÉ DOS CAMPOS-SP ou SÂO PAULO-SP

Fulltime

Startup Style

Homeoffice

PLR e Partnership

## Contratação

PJ

Valor: a combinar! Faça a inscrição e deixe sua expectativa.

## Sobre Beedoo
Construímos uma plataforma para tornar a comunicação e a capacitação de equipes de atendimento mais ágil, produtiva e eficiente. Acreditamos que quando você combina um propósito poderoso com grandes pessoas que são as melhores no que fazem, você obtém uma cultura diferente de qualquer outra. Para um novo mundo de trabalho, o Beedoo oferece uma nova maneira de aprender com conceitos de Social e Micro Learning, Gamification , Gestão analítica, base de conhecimento cognitiva e inteligência artificial.

## Como se candidatar

Inscrições pelo typeform (apenas 9 perguntas +-3 minutos): https://daniellima14.typeform.com/to/rsLM4z

### Alocação:
- Flexível (Remoto parcial)

### Contratação:
- PJ

### Experiência
- Pleno
- Sênior

**Comment by THAYLLER** [comment]
a empresa ajuda candidatos de fora a se estabelecer em sp?

**Comment by ptcmariano** [comment]
> a empresa ajuda candidatos de fora a se estabelecer em sp?

Oi Thayller, obrigado por perguntar. A gente já teve casos de colaboradores mudarem pra SJC e teve ajuda sim a se estabeler lá. O que pode acontecer também em SP.

Boa sorte,

Abraço.

**Comment by THAYLLER** [comment]
Entendi agradeço
