### ISSUE TITLE
[Franca/SP e São Carlos/SP] 5 vagas para Desenvolvedores(as) Sênior PHP pela Betta Tecnologia

### ISSUE THREAD

**Issue by fhferreira** [phpdevbr/vagas#379]
## Descrição da vaga

Experiência e conhecimentos em PHP com framework Laravel;
Experiência e conhecimentos em LINUX;
Experiência e conhecimento em Docker; 
Experiência e conhecimentos com Arquitetura Onion e Arquitetura Hexagonal;
Experiência e conhecimentos em Redis;
Experiência e conhecimentos em programação orientada a serviços (baixo acoplamento);
Experiência em programação utilizando design patterns;
Experiência com Arquitetura de Eventos;
Experiência utlizando Kafka (rdkafka); [https://kafka.apache.org/]
Experiência com testes unitários utilizando PHPUnit;
Experiência com S.O.L.I.D;
Experiência com Banco de dados MySQL, MongoDB;
Experiência com API's e paradigma RESTFul; 

**Desejável que haja conhecimento em:**
Conhecimento sobre ElasticSearch;
Conhecimento sobre Kubernetes;
Conhecimento sobre Lumen (Laravel Micro-Framework);
Conhecimento sobre programação asyncrona com PHP;
Conhecimento sobre utilização de coroutines com PHP;

## Local

Escritórios, São Carlos e Franca/SP

## Como se candidatar

Por favor envie um email para flaviometalvale@gmail.com com seu CV anexado - enviar no assunto: Vaga Senior PHP

### Alocação:
- Presencial
- Flexível (Remoto parcial)

### Contratação:
- CLT
- PJ

### Experiência
- Sênior

**Comment by THAYLLER** [comment]
E ai meu querido blz? Cara quando o nome da empresa que ta com essa vaga aberta?

**Comment by ravanscafi** [comment]
fala @fhferreira, tem o nome da empresa?

**Comment by fhferreira** [comment]
Fala @ravanscafi a Betta Tecnologia de Franca está contratando para uma Startup de São Carlos.

**Comment by THAYLLER** [comment]
@fhferreira alguma novidade referente ao processo seletivo vejo que vc ta atualizando a vaga aqui mas nunca teve um contato da empresa

**Comment by fhferreira** [comment]
Ainda está ocorrendo, estão analisando alguns devs.

**Comment by THAYLLER** [comment]
entendi vlw

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
