### ISSUE TITLE
[Belo Horizonte/MG] PHP FullStack PJ na SSX Digital

### ISSUE THREAD

**Issue by guireisbh** [phpdevbr/vagas#380]
## Descrição da vaga

Gostar de trabalhar em home office e com motivação para trabalhar com programação em nível pleno. Proativo, Observador, Curioso e esforçado.

Conhecimentos técnicos: Noções de metodologia ágil, scrum, e gostar de estudar e aprender mais. Saber Laravel e Angular 2 e 4 em diante são diferenciais.

Atividades: Wordpress. Desenvolvimento backend e frontend de sistemas e sites, softwares e plataformas web. Otimização de sistemas e instalação em AWS e Azure.

## Local

Belo Horizonte - MG - Santa Efigênia
Home Office - Reuniões presenciais para Projetos

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com PHP 5+
- 2 anos de experiência com Wordpress
- Laravel
- Versionamento de Projetos
- Bitbucket
- Scrum

**Desejáveis:**
- Angular 2 em diante
- Node.JS
- Vue
- AWS

**Diferenciais:**
- projetos de ERP

## Contratação

- Contrato PJ de 160h / mensais
- R$4.000,00 / mês
- Bônus por Produtividade

## Nossa empresa

Há 10 anos no mercado. Somos Agência de Publicidade e também Software House. Equipe de 4 desenvolvedores. Entregamos soluções de websites, intranets, sistemas tailor-made, portais e etc.

## Como se candidatar

Por favor envie um email para vagas@ssxdigital.com.br com seu CV anexado - enviar no assunto: Vaga PHP FullStack

### Alocação:
- Flexível (Remoto parcial)

### Contratação:
- PJ

### Experiência
- Pleno

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
