### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) PHP/Laravel Pleno/Sênior pela Holden RH

### ISSUE THREAD

**Issue by jokapoa** [phpdevbr/vagas#381]
**Desenvolvedor PHP - São Paulo -SP**
Experiência: Pleno
Tipo de Contratação CLT
Atividades:

Fazer analise de requisitos, modelagem de solução / arquitetura, integração com API´S de terceiros.
Atua com desenvolvimento de aplicações web fullstack, criação de novas funcionalidades e manutenção em sistema.
Bom relacionamento interpessoal, trabalho em equipe.
 
Requisitos:

Experiência com desenvolvimento em PHP de +3 anos;
Experiencia com algum framework de frontend ( Vue, etc);
Solido Conhecimento com : PHP, Javascript, HTML5, CSS3, ,Arquitetura MVC e banco de dados PostgreeSQL.
Experiência com Laravel 5.4+

Cliente:

Empresa de tecnologia localizada na região da Av Paulista/SP

### Alocação:
- Presencial

### Contratação:
- CLT
### Experiência
- Pleno

Enviar curriculo para ti@holdenrh.com.br

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
