### ISSUE TITLE
[São Paulo/SP] PHP Fullstack Developer no HIAE (Hospital Israelita Albert Einstein)

### ISSUE THREAD

**Issue by maranesi** [phpdevbr/vagas#382]
## Descrição
Profissional irá compor uma squad no desenvolvimento de um novo produto utilizando as melhores práticas de mercado, tendo a oportunidade de participar do processo de concepção da aplicação.

## Atividades
•    Atuar com desenvolvimento de aplicações web fullstack.
•    Realizar integração com API de terceiros.
•    Participar do processo criativo e concepção de novas features.

## Local
Eretz/Lab Inovação HIAE - Vila Mariana, São Paulo

## Disponibilidade
•    Imediata

## Requisitos
•    Formação superior na área de tecnologia.
•    3 anos de experiência com PHP 5+.
•    Bons fundamentos em OO, PSR, SOLID, Design Patterns.
•    Experiência com Laravel
•    Experiência com React
•    Controle de versão GIT.

**Diferenciais**:
•    Testes unitários com PHP e Javascript
•    Redux, Material UI
•    Docker
•    Conhecimento em serviços em cloud AWS

## Contratação
•    CLT, PJ;

### Alocação
Presencial

### Experiência
Pleno

## Sobre o Lab
O laboratório de inovação é uma iniciativa da Sociedade Beneficente Israelita Brasileira Albert Einstein que tem como principal missão fomentar o ambiente de empreendedorismo e inovação em saúde no Brasil. 

## Como se candidatar
Interessados enviar currículo com pretensão salarial para: bruno.maranesi@inovacaoeinstein.com.br com o assunto "[HIAE] - PHP Fullstack Developer"

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
