### ISSUE TITLE
[Porto Alegre/RS] Desenvolvedor(a) PHP Junior na Agência Kaizen

### ISSUE THREAD

**Issue by robertomartins** [phpdevbr/vagas#385]
### O que nós buscamos
Desenvolvimento e manutenção de sites, gerenciamento de conteúdos dos sites gerenciados pela a Agência Kaizen.
Setor de desenvolvimento em crescimento tomando rumo para desenvolvimento de apps web e mobile. Oportunidade para aprendizado.

### Principais responsabilidades.
- Conhecimentos em PHP, Javascript, HTML/CSS e Banco de dados MySQL.
- Ajustes e inserções de conteúdos nas plataformas

### Conhecimentos Diferenciais
- Laravel
- Wordpress
- Drupal
- jQuery
- Bootstrap

100% presencial Porto Alegre

### Benefícios
CLT 1.500 + VT + VA/VR 22,00/dia 
Bom ambiente de trabalho. 

https://www.instagram.com/digitalkaizen/
https://www.facebook.com/KaizenMarketingDigital/
https://www.agenciakaizen.com.br/

Envie e-mail para naimara@agenciakaizen.com.br

**Comment by robertomartins** [comment]
A título de informação. Ainda temos vagas na empresa.

**Comment by davialmeida** [comment]
Por que será né?

**Comment by robertomartins** [comment]
Realmente não é as melhores tecnologias para se trabalhar. Nem o melhor salário. Mas não esperamos alguém com um exímio conhecimento e experiência. Talvez seja uma alternativa melhor que um estágio. Como programador que sou, vejo como uma oportunidade. Mas como não posso demonstrar como funciona nossa filosofia e estrutura, só posso convidar quem se interessar para conversar com a gente. 
Mas obrigado pelo seu comentário. Vou levar pra vida. 😆

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
