### ISSUE TITLE
[Belo Horizonte/MG] PHP Developer na 123Milhas

### ISSUE THREAD

**Issue by marcoscoelho** [phpdevbr/vagas#386]
## Descrição da vaga

👨‍💻 Desenvolvedor(a) Junior / Pleno

## Local

Belo Horizonte/MG

## Benefícios

- Vale-transporte ou vale-combustível
- Vale-alimentação
- Plano de saúde Bradesco
- Curso de inglês

## Requisitos

**Obrigatórios:**
- Experiência em PHP 
- Experiência em em banco dados MySQL 
- Experiência com Laravel
- Trabalhar com Git/github
- Trabalhar em equipe

**Desejáveis:**
- Nodejs
- NoSQL
- Vagrant
- Amazon AWS

## Nossa empresa

✈✈✈ http://123milhas.com.br ✈✈✈

## Como se candidatar

Por favor envie um email para marcos.coelho@plataforma13.com.br com seu CV anexado - enviar no assunto: Vaga PHP

### Alocação:
- Presencial

### Contratação:
- CLT

### Experiência
- Júnior
- Pleno

**Comment by davialmeida** [comment]
No caso não sou de minas gerais, caso eu passasse no processo seletivo a empresa ajudaria na alocação?

**Comment by marcoscoelho** [comment]
@davialmeida Caso seja contrato você pode solicitar um tempo p/ se estabelecer, mas a empresa não dá esse tipo de suporte, temos colaboradores de outras localidades que mudaram p/ BH por conta própria mesmo.

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
