### ISSUE TITLE
[Joinville/SC] PHP Developer na Clínica Ágil 

### ISSUE THREAD

**Issue by Vagas-HunterCo** [phpdevbr/vagas#387]
## Descrição da vaga
O Clínica Ágil é um produto desenvolvido para para profissionais de fisioterapia, temos como missão compreender as necessidades tecnológicas do cliente, oferecendo soluções inovadoras de forma ágil, transparente, precisa e comprometida com sua satisfação.

## Local
Avenida Rolf Wiest, 277 - Bom Retiro, Joinville - SC

## Benefícios
- Um ambiente de trabalho flexível, com grande possibilidade de crescimento.
- Auxílio Alimentação
- Seguro de Vida
- Vale transporte ou auxilio estacionamento
- Bermudas allowed.

## Requisitos

**Obrigatórios:**
- PHP
- HTML5
- Javascript
- CSS
- JQuery
- MYSQL
- Algum Framework
- Git

**Desejáveis:**
- CodeIgniter
- Vivência com desenvolvimento ágil

**Diferenciais:**
- Conhecimentos na área da saúde

## Contratação
CLT

## Nossa empresa
O Clínica Ágil é um produto desenvolvido para para profissionais de fisioterapia, temos como missão compreender as necessidades tecnológicas do cliente, oferecendo soluções inovadoras de forma ágil, transparente, precisa e comprometida com sua satisfação.

O Clínica Ágil possui uma equipe altamente treinada no desenvolvimento de Sistemas Web, conhecedores das mais modernas linguagens de programação, além de dispormos de inúmeras cases de sucessos em empresas de todos os portes

## Como se candidatar

Clique nesse link: https://bit.ly/2XJ2Dc7

### Alocação:
- Presencial

### Contratação:
- CLT

### Experiência
- Júnior
- Pleno

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
