### ISSUE TITLE
[Rio de Janeiro/RJ] PHP Developer Backend na Folha Dirigida

### ISSUE THREAD

**Issue by muriloime** [phpdevbr/vagas#388]
Meus amigos na Folha dirigida estão montando um time bacana e pediram pra divulgar a vaga: 

## Descrição da vaga

Desenvolvimento de aplicações Web / Desktop. Implementação das funcionalidades levantadas pelas áreas demandantes. Integração de Sistemas. Automação de Processos. Desenvolvimento de webservices. Manutenção em aplicações existentes. Análise de causa raiz dos problemas reportados.

Atribuições da vaga de Desenvolvedor Back-end:
✔️ Manutenção de ambientes PHP; 
✔️ Desenvolvimento de novos serviços e projetos; 
✔️ Versionamento de conteúdos utilizando o Git. 
✔️ Manutenção de ambiente em produção

## Local

Copacabana, Rio de Janeiro - RJ

## Benefícios

🚀 Somos uma startup, então a possibilidade de crescimento profissional é enorme! 
😃 Ambiente positivo e descontraído
💰 PLR - Participação Trimestral nos lucros
📘 Aprendizado intensivo das melhores práticas e estratégias digitais
🕘 Flexibilidade de horários e home-office em alguns dias do mês

## Requisitos

**Obrigatórios:**
✔️ 2 anos de experiência como desenvolvedor 
✔️ Raciocínio lógico e analítico 
✔️ Trabalho com metodologias ágeis 
✔️ HTML5; 
✔️ PHP e Framework Laravel (5.3 e 5.7); 
✔️ Ferramentas para controle de versão (git); 
✔️ Experiência em desenvolvimento de sites responsivos e versão mobile; 
✔️ Desenvolvimento de sites com interações em Javascript (Javascript ES6+) 
✔️ Conhecimentos em Wordpress;

**Diferenciais:**
✔️ Gulp; 
✔️ Greensock; 
✔️ Node.JS; 
✔️ Vue.JS; 
✔️ React.js 
✔️ React Native 
✔️ Soluções de banco SQL e NoSQL 
✔️ Conhecimento em nuvem (AWS) é desejável. 
✔️ Conhecimento em soluções mobile e JavaScript são desejáveis. 

## Informações

👉 Local de trabalho: Copacabana – RJ
👉 Remuneração: a combinar
👉 Forma de Contratação: PJ 
👉 Benefícios: Horário Flexível, PLR Trimestral, 2 recessos de 15 dias por ano e cozinha/copa equipada. 
👉 Carga Horária: 40 horas semanais.

## Como se candidatar

Por favor envie um email para vagas@folhadirigida.com.br com seu CV anexado - enviar no assunto: Vaga PHP

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
