### ISSUE TITLE
[Belo Horizonte/MG] Programador Laravel na Founders

### ISSUE THREAD

**Issue by Luc45** [phpdevbr/vagas#39]
Fala galera!

Sou o lead-programmer de uma grande agência que atende empresas nacionalmente conhecidas. Estou querendo montar um time de devs focados em Laravel para criar sites e sistemas com código limpo, documentado, bem arquitetado e com metodologias de deploy organizadas, etc.

O trabalho é presencial, com contratação via CLT ou MEI, de 9h às 18h, a empresa fica pertinho do BH Shopping. Procuramos programadores Jr., Pleno ou Sênior com especialidade em Laravel. Conhecimentos em outras linguagens/frameworks é um diferencial.

Se você se encaixa nesse perfil, entre em contato. Se conhece algum amigo, por favor, indique!

Para se candidatar, envie um e-mail para: lucas.figueiredo@founders.com.br

**Comment by yanmagale** [comment]
@Luc45 divulga a vaga no [Slack do Minas Dev](https://minasdev.org) e no slack do [PHPMG](http://phpmg.com/), com certeza achará uma galera boa por lá :smile:

**Comment by rscafi** [comment]
@Luc45 e @yanmagale, convidem o pessoal a dar "watch" nesse repositório também! :wink:

**Comment by deyvisonrocha** [comment]
@Luc45 como vocês contratam  via MEI? Pergunto porque não tem a atividade de Desenvolvedor Web ou algo similar, no caso, não encontrei quando abri a minha. Pode me ajudar com isso?

**Comment by diegocandido** [comment]
@deyvisonrocha Por lei não pode! Profissões ligadas a TI, advogados, engenheiros, médicos, etc. Devem haver formação superior para exercer a função. Para o governo profissionais de TI deveriam ter todos nível superior, ou alguma forma de regulamentação (que não existe) não pode ser MEI, mas podem ser ME (Micro Empresa). Tudo na visão do governo! ;)

**Comment by deyvisonrocha** [comment]
@diegocandido Valeu pela explicação. Como sempre o estado tentando tomar conta de nossas vidas.

**Comment by leonardodecuritiba** [comment]
@Luc45 é uma vaga presencial?

**Comment by Luc45** [comment]
@leonardodecuritiba sim!

**Comment by rscafi** [comment]
@Luc45 Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.
