### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) PHP Sênior na PicPay

### ISSUE THREAD

**Issue by brunasantosmp** [phpdevbr/vagas#390]
## Descrição da vaga

Estamos conduzindo um projeto bem interessante para a fintech PicPay, que tem como objetivo revolucionar a forma que movimentos e armazenamos nosso dinheiro. 

## Local

Vila Leopoldina - Flexibilidade para homeoffice (algumas vezes na semana) 

## Benefícios

Assistências médica e odontológica;
Seguro de vida;
Vale Mobilidade (use com combustível, transporte público, bike, etc...)
Vale Refeição ou Vale Alimentação;
Vale Cultura;
PicPay Acolhe - Serviços 0800 (anônimo) que oferece apoio jurídico, social, psicológico e financeiro;

#### Diferenciais

Frutinhas e café à vontade no escritório;
No dress code;
Fazer parte de um time incrível

## Requisitos

**Obrigatórios:**

•	Sólida experiência em desenvolvimento PHP;
•	Conhecimento em Laravel, Lumen e/ou Symfony;
•	Conhecimento em Metodologias Ágil/Scrum;

**Desejáveis:**

**Diferenciais:**
- projetos opensource

## Contratação

•	Docker;
•	Atuação com banco de dados MySQL e/ou Mongo;
•	Git;
•	Design Patterns;
•	Clean Code;

## Nossa empresa

Uma empresa sólida que integra de maneira simples diversos serviços e transações financeiras que melhoram a qualidade de vida dos usuários.

## Como se candidatar

Enviar Cv/Linkedin p/ brunasantos@michaelpage.com.br

### Alocação:
- Presencial
- Flexível (Remoto parcial)

### Contratação:
- CLT

### Experiência
- Sênior

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
