### ISSUE TITLE
[Belo Horizonte] Eng. Sw. Senior / Arquiteto de Software

### ISSUE THREAD

**Issue by bernardoassis** [phpdevbr/vagas#4]
## Descrição da vaga

Estamos buscando um Arquiteto de Software e Analistas de Sistemas em todos os níveis com foco em desenvolvimento PHP, front-end e back-end!
## Local

Escritório, Belo Horizonte - Santa Lúcia (entre a Raja e a BR356, perto do Falls Shopping)
## Benefícios

Refeição / VT / Lanche
## Requisitos

**Obrigatórios:**
- \+ de 5 anos de experiência desenvolvendo aplicações web utilizando tecnologias web (PHP, Ruby, Python);
- \+ de 3 anos de experiência desenvolvendo websites utilizando HTML, CSS e JavaScript;
- \+ de 3 anos de experiência com frameworks e/ou bibliotecas como Zend, Symfony, Laravel, Doctrine, Spark, Grails, Django, Ruby on Rails, EmberJS, Angular;
- Experiência em escrita de testes de unidade para aplicações web;
- Experiência em definição de processos de integração contínua para desenvolvimento web front-end;
- Experiência em escrita de consultas SQL de alta performance;
- Conhecimento em padrões de desenvolvimento de software web (MVC, MVVM, etc);
- Habilidade na definição das melhores práticas de para o desenvolvimento de software de alta qualidade (Integração Contínua, Vagrant, etc);
- Conhecimento de UML, padrões de integração de sistemas.

**Desejáveis:**
- Experiência com plataformas de infraestrutura como serviços, em especial Amazon Services
- Experiência na escrita de testes de unidade em PHP e JavaScript;
- Conhecimento de infra-estrutura tecnológica para o ambiente PHP (Apache/Nginx, Ubuntu/CentOS, MySQL, Memcache/Redis);
- Conhecimento de ORM's como Doctrine (preferencialmente) ou Propel;

**Diferenciais:**
- Conhecimento de controle de versão de código-fonte Git;
- Experiência de trabalho em equipes de desenvolvimento ágil;
- Habilidade em gestão de multiplas tarefas e definição de prioridades;
- Habilidade de trabalho com independência e supervisão mínima;
- Disposição em compartilhar o seu conhecimento com as pessoas da área de tecnologia da empresa;
- Boa habilidade de comunicação escrita e verbal;
- Disposição para aprender novas tecnologias e aplicá-las em um curto espaço de tempo;
- Espírito de equipe em um time multi-disciplinar;
- Capacidade de analisar situações e informações, realizando avaliação crítica e conclusiva, apontando direcionamentos para subsidiar as tomadas de decisões.
## Contratação

CLT
## Nossa empresa

A eMotion Digital é uma empresa de tecnologia focada em produção, distribuição de conteúdo e desenvolvimento de projetos incríveis (apps iOS/Android/HTML5) para o mercado de SVA (Serviços de Valor Agregado) para operadoras no mundo inteiro!
## Como se candidatar

Por favor envie um email para bernardo@emotiondigital.com.br com seu CV anexado - enviar no assunto: Vaga Arquiteto / Eng Sw Sr

**Comment by joubertredrat** [comment]
@nic vaga preenchida

**Comment by nic** [comment]
@joubertredrat Muito obrigado por avisar! You rock!!! ;)
