### ISSUE TITLE
[Belo Horizonte - MG] Dev Front End

### ISSUE THREAD

**Issue by rhcontamobi** [phpdevbr/vagas#40]
## Descrição da vaga

•	Atuar no desenvolvimento dos produtos;
•	CSS, HTML5 e Javascript;
•	Bootstrap e soluções responsivas;
•	Análise de usabilidade (UI) e experiência do usuário (UX);
•	Gulp / Grunt / SASS / Compass;
•	Controle de versão GIT e desenvolvimento em ambiente Linux;
•	React Native ou Ionic (desejável);
•	Elaboração de layouts de aplicações web e mobile (desejável).
•	Formação na área de Tecnologia da Informação, preferencialmente em Desenvolvimento de Software.

## Local

Belo Horizonte/MG

## Benefícios

- Vale Refeição ou Alimentação;
- Vale Transporte;
-  Seguro de Vida.

## Requisitos

**Obrigatórios:**
•	Formação na área de Tecnologia da Informação, preferencialmente em Desenvolvimento de Software;
•	CSS, HTML5 e Javascript;
•	Bootstrap e soluções responsivas;
•	Análise de usabilidade (UI) e experiência do usuário (UX);
•	Gulp / Grunt / SASS / Compass;
•	Controle de versão GIT e desenvolvimento em ambiente Linux.

**Desejáveis:**
•	React Native ou Ionic (desejável);
•	Elaboração de layouts de aplicações web e mobile (desejável).

**Diferenciais:**

## Contratação

CLT

## Nossa empresa

A conta.MOBI é uma Startup do ramo financeiro que fornece uma Conta Digital, dentre outros serviços, para quem é Microempreendedor Individual (MEI). 

www.conta.mobi 

## Como se candidatar

Interessados enviar cv + portfólio para rh@conta.mobi com o assunto “DEV FRONT END”

**Comment by Marlysson** [comment]
Show!!
Mas teria mais candidados aqui : https://github.com/frontendbr/vagas/issues , não ..?

**Comment by rhcontamobi** [comment]
@Marlysson Obrigada pela dica :D

**Comment by rscafi** [comment]
como vi que vocês postaram lá, https://github.com/frontendbr/vagas/issues/424, vou fechar aqui já que o foco é vagas em PHP :)
