### ISSUE TITLE
[São Paulo/SP] Desenvolvedor PHP na Itelios

### ISSUE THREAD

**Issue by rruppel** [phpdevbr/vagas#41]
## Descrição da vaga
Boa noite pessoal,

A Itelios é uma empresa francesa focada em e-commerce e soluções omnichannel e buscamos bons desenvolvedores PHP para trabalharem com as plataformas Drupal e/ou Magento. 
Não é obrigatório conhecer bem essas plataformas porque damos espaço para aprender aqui dentro.
Nosso intuito é formar um time muito qualificado, com pessoas apaixonadas por tecnologia e por entregar valor aos clientes.
Buscamos preferencialmente Plenos e Seniores.
Os projetos são muito desafiadores porque trabalhamos sempre com grandes clientes, nos quais os volumes de transações são sempre muito grandes.
Aqui dentro tem muita oportunidade e muita chance de aprender coisas - eu gosto de dar o meu próprio depoimento porque entrei como estagiário, tive a chance de trabalhar na França pela empresa e hoje sou o principal diretor da empresa no Brasil.
Quero encontrar pessoas de perfil guerreiro e que queiram fazer sempre o melhor.  Damos bastante liberdade para toda a equipe e o lucro da empresa é sempre muito compartilhado com o time.

## Local

O escritório fica na Haddock Lobo, travessa da Av. Paulista, próximo ao Metro Consolação.
Preferimos o trabalho presencial e estamos fazendo as primeiras experiências com algumas pessoas remotas.

## Benefícios

- Não descontamos VR e VT da folha
- horário com boa flexibilidade (pedimos para chegar até 10h30)
- Plano de Saúde e Odontológico
- empresa bastante horizontal, ou seja, todos podem participar de todas as decisões, conforme o interesse de cada um
- 1 caixinha de Dolce Gusto por mês :)
- café a vontade

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com PHP 5+
- bom inglês

**Desejáveis:**
- conhecimento em Drupal ou Magento

**Diferenciais:**
- projetos opensource

## Contratação

CLT a combinar

## Nossa empresa

Se quiser mais informações, veja aqui: http://www.itelios.com.br

## Como se candidatar

Pelo link http://vagas.itelios.com.br/job/analista-desenvolvedor-php-senior
Ou por email: contato@itelios.com

**Comment by giovannicruz97** [comment]
Ainda em aberto @rruppel ?

**Comment by rruppel** [comment]
Ainda em aberto sim @giovannicruz97 ! Somos rigorosos na seleção o que sempre dificulta fechar o processo seletivo!
Abs

**Comment by rscafi** [comment]
@rruppel Vaga preenchida?

**Comment by rruppel** [comment]
@rscafi  ainda tenho vagas abertas nesta posição!

**Comment by ValdeiltonFelix** [comment]
Tem vaga para trabalho home office ??

**Comment by rruppel** [comment]
Estamos, neste momento, em um período de testes da liberação de home office 100% conforme a vontade de cada pessoa - sendo assim, acho que há espaço para conversamos sim

abs

**Comment by ravanscafi** [comment]
Olá @rruppel,
A vaga ainda está aberta?

_(sou administrador das vagas e estou fechando as que já foram preenchidas)_

**Comment by rruppel** [comment]
Pode fechar Ravan

Obrigado!

Abs

ITELIOS
Rafael Ruppel Ruiz • CEO Brasil
t. +55 11 2504-3474 | m. +55 11 99665-2521 | itelios.com.br
The Connected Commerce Agency – ITELIOS, Part of Capgemini


De: Ravan Scafi <notifications@github.com>
Enviada em: quarta-feira, 17 de outubro de 2018 15:16
Para: phpdevbr/vagas <vagas@noreply.github.com>
Cc: Rafael Ruppel Ruiz <rafael.ruppel@itelios.com>; Mention <mention@noreply.github.com>
Assunto: Re: [phpdevbr/vagas] [São Paulo/SP] Desenvolvedor PHP na Itelios (#41)


Olá @rruppel<https://github.com/rruppel>,
A vaga ainda está aberta?

(sou administrador das vagas e estou fechando as que já foram preenchidas)
