### ISSUE TITLE
[Curitiba/PR] PHP Developer Wordpress na Tesis

### ISSUE THREAD

**Issue by iperacchi** [phpdevbr/vagas#428]
## Descrição da vaga

Você será o responsável pelo desenvolvimento de uma aplicação utilizando o WordPress com o ACF.

## Local

Escritório, Curitiba - Rua João Domachoski, 132

#### Diferenciais

- Equipamento Mac

## Requisitos

- Bootstrap 3,4
- HTML5
- CSS3
- JavaScript
- WordPress intermediário

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para dev@tesis.digital com seu CV anexado - enviar no assunto: Vaga PHP Wordpress

### Alocação:
- Presencial

### Contratação:
- PJ

### Experiência
- Estágio
- Júnior
- Pleno

**Comment by filipecsweb** [comment]
Há possibilidade de trampo remoto, caso comprovada experiência?
