### ISSUE TITLE
[São Paulo] Desenvolver Web Júnior/Pleno | FTD Educação

### ISSUE THREAD

**Issue by m4ctavares** [phpdevbr/vagas#44]
## Nossa empresa

A FTD Educação é uma das grandes empresas do segmento de livros didáticos e soluções educacionais que conta atualmente com mais de 1.500 colaboradores espalhados por todo território nacional. Venha fazer parte de um time dinâmico, parceiro e unido que desenvolve soluções Web/Fluig para diversos sistemas de apoio dentro da organização.

## Descrição da vaga

A FTD Educação está construindo um time ágil para atender as crescentes demandas do setor WEB e estamos buscando novos integrantes para fazer parte de nossa equipe aqui na matriz da empresa no bairro da *Bela Vista*.

Nossos projetos são divididos em duas frentes, sendo:
- WEB : PHP7 em novos projetos (PHP5 para antigos) todas seguindo o padrão LAMP;
- Fluig : Javascript, HTML5 e CSS3 para desenvolvimento de projetos GED, BPM e WCM.

Nem precisa dizer que os desafios são grandes e que qualidade e comprometimento irão fazer parte do seu desenvolvimento diário e na entrega de cada projeto.

## Local

Rua Rui Barbosa, 156 - Bela Vista, São Paulo - SP. Presencial.

## Benefícios

- Vale Transporte
- Vale Refeição
- Assistência médica
- Assistência odontológica (opcional)
- Plano de participação nos resultados

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento de software em uma ou mais linguagens de alto nível:
 - Ótimo conhecimento em PHP (Projetos pessoais e profissionais)
 - **Ótimo conhecimento em Javascript** (Não só jQuery ou AngularJS)
 - Bons conhecimentos em HTML5 e CSS3
 - Ter ótimo relacionamento em equipe

**Desejáveis:**
- Bons conhecimentos em Linux (Debian)
- Conhecimentos em Yii (1 e 2), Laravel ou equivalente
- Conhecimento em *Git* e integrações via API
- **BPM**
- Bootstrap, Material Design
- TDD e Design Pattern

**Diferenciais:**
- MySQL, PostgreSQL, NoSQL
- Pentaho, Jenkins, **Docker**, WSO2, AWS, Google Cloud Platform

## Contratação

CLT

## Como se candidatar

Por favor envie um e-mail para paula.santos@ftd.com.br com seu CV anexado - enviar no assunto: [DEVWEB2S2018]. Também não esqueça de informar caso tenha projetos, portfólios e github.

**Comment by guilherme90** [comment]
Vaga já foi preenchida?

**Comment by m4ctavares** [comment]
Boa tarde Rafael, ainda não.

**Comment by guilherme90** [comment]
Olá Marcos, email enviado! =)

**Comment by rscafi** [comment]
@m4ctavares Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.
