### ISSUE TITLE
[Bauru/SP] Desenvolvedor PHP Pleno/Sênior na ArcaSolutions

### ISSUE THREAD

**Issue by rharcasolutions** [phpdevbr/vagas#45]
## Descrição da vaga

Conhecimento avançado em PHP, Conhecimento intermediário em XHTML/CSS e Javascript, MySQL e modelagem de dados, Conhecimento avançado em Inglês; Sera visto como um diferencial conhecimento em Symfony ou framework similar, Elasticsearch

## Local

 Escritório, Bauru SP- Vila Santa Tereza

## Benefícios

Convenio médio
Convenio Odontológico
Vale transporte
Seguro de vida
Convenio com Farmácia
Vale refeição ou alimentação
Plano de Carreira

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com PHP 5+

**Desejáveis:**
- conhecimentos em Symfony 

**Diferenciais:**
- conhecimentos em Elasticsearch

## Contratação

CLT salario a combinar

## Nossa empresa

http://arcasolutions.com.br/sobre.php
![final-final](https://user-images.githubusercontent.com/30184986/28227759-cac1ea6c-68b1-11e7-9526-3fc7bb028515.png)

## Como se candidatar

 Interessados enviar currículo para cv@arcasolutions.com com sigla Prog

**Comment by rscafi** [comment]
@rharcasolutions Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.
