### ISSUE TITLE
[São Paulo/SP] PHP Developer Junior/Pleno na Influu

### ISSUE THREAD

**Issue by influu** [phpdevbr/vagas#453]
## Descrição da vaga
Desenvolvimento de novos projetos e manutenções com PHP e Laravel.

## Local
Presencial, São Paulo - Metro Faria Lima

## Requisitos

**Obrigatórios:**
- 1 anos de experiência com desenvolvimento PHP

**Desejáveis:**
- conhecimentos em Vuex
- conhecimentos em Wordpress
- conhecimentos em CSS

## Contratação

PJ a combinar

## Nossa empresa

Somos uma agência com foco no mercado de influenciadores

## Como se candidatar

Por favor envie um email para contato@influu.me com seu CV anexado - enviar no assunto: [Vaga PHP] + Nome_Sobrenome

## Labels

- alocação/Flexível
- alocação/Presencial
- experiência/Junior
- experiência/Pleno
- regime/PJ

**Comment by Soutorafez** [comment]
Vaga full time?
