### ISSUE TITLE
[São Paulo/SP] Full Stack na Ide@l

### ISSUE THREAD

**Issue by Rafael-BP** [phpdevbr/vagas#458]
##  Descrição da vaga

Somos uma startup que desenvolve soluções para a área de comércio exterior.

Contamos com um time que é livre para interagir, cooperar entre si, e evoluir junto.

Dentre as nossas soluções, temos robôs de automação  de atividades e de coleta de dados, sistemas gerencial e financeiro para a área de Comércio Exterior e diversas soluções auxiliares.

Nossa empresa está em expansão. Venha aprender e crescer com a gente!

## Local

Escritório, São Paulo/SP - Vergueiro/Paraíso

#### Diferenciais

- Empresa próxima a metrôs e a todos os serviços básicos
- Ambiente descontraído e informal
- Pode usar shorts e roupas casuais
- Home-office algumas vezes no mês após um tempo de empresa
- Espaço para propor ideias e contribuir com a evolução do time
- Frigobar

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com PHP 5+
- Orientação a Objetos
- MVC (conceito e implementação)
- Modelagem de sistemas com UML
- Conhecer e utilizar as boas práticas (SOLID, PSR, KISS, etc)
- Criação de APIs REST (respeitando o protocolo HTTP) e SOAP
- Banco de dados relacionais (MySQL)
- Versionamento de código (GIT)
- Composer
- HTML5 e CSS3
- JS e manipulação do DOM
- Experiência com algum framework JS moderno, de preferência Vue.js
- Desenvolvimento web responsivo
- Gerenciadores de pacotes - NPM
- Conhecimentos básicos em Linux
- Saber trabalhar em equipe e ser proativo

**Desejáveis:**
- Conhecimentos em Design Patterns
- Teste unitário
- Saber construir ambientes com Docker
- Conhecimento em Kanban e SCRUM
- Saber utilizar GitFlow
- Refactoring
- Pré-processadores CSS, de preferência SASS
- Noções de usabilidade e UX
- Bootstrap e experiência em seguir guidelines

**Diferenciais:**
- HTML semântico
- ES6
- Conhecimentos em padrões HTML, CSS e de componentização - preferência BEM e design atômico
- MongoDB
- Empacotadores e automatizadores, de preferência Webpack
- Participa de comunidades (ex: PHPSP, UXCafeBR, etc) e eventos de TI

## Contratação

PJ a combinar

## Nossa empresa

Uma startup que, por meio da tecnologia, traz inovação e inteligência para a cadeia logística e o mercado de Comércio Exterior.

Acesse o nosso site e conheça a nossa empresa: www.tideal.com.br

## Como se candidatar

Por favor envie um email para ideal@haidar.srv.br com seu CV anexado - enviar no assunto: Vaga Full Stack

### Alocação:
- Presencial

### Contratação:
- PJ

### Experiência
- Pleno

**Comment by Rafael-BP** [comment]
Processo seletivo ainda em andamento :)

**Comment by alcoforadog** [comment]
Existe a possibilidade de ser remoto?

**Comment by Rafael-BP** [comment]
> Existe a possibilidade de ser remoto?

Boa tarde. Tudo bem?
Ainda não. Mas hoje trabalhamos com 3 dias de home por mês e podemos negociar o horário de entrada/saída nos dias presenciais.
Abraços.

**Comment by Rafael-BP** [comment]
Processo seletivo ainda em andamento :)

**Comment by Rafael-BP** [comment]
Processo seletivo finalizado :)
