### ISSUE TITLE
[Mogi das Cruzes/SP] Desenvolvedor(a) PHP na Resource IT

### ISSUE THREAD

**Issue by LeandroRenzi** [phpdevbr/vagas#459]
## Descrição da vaga

Profissional para atuar em Squad (mesa estendida) com projeto de melhoria contínua com PHP no cliente do ramo de locação de automóveis e logistica.

## Local
Mogi das Cruzes - SP (próximo a estação Brás Cubas)

## Benefícios

•	Plano de saúde Sulamérica Exato Apto 
•	Convênio Odontológico - Porto Seguro
•	Seguro de vida
•	VR de R$ 440,00
•	Auxílio creche
•	Convenio Farmácia

## Requisitos

**Obrigatórios:**

•    Experiência consolidada com desenvolvimento em PHP
•    GIT
•    Facilidade para trabalho em equipe

##Desejável
Láravel

## Como se candidatar

Por favor envie um email para leandro.renzi@resourceit.com com seu CV anexado - enviar no assunto: [VAGA PHP - MC] [Seu nome completo]

## Labels
- backend
- linguagem/PHP
- experiencia/sênior
- experiencia/pleno

### Alocação:
- Presencial

### Contratação:
- CLT

### Experiência
- Pleno/Sênior

**Comment by LeandroRenzi** [comment]
novas vagas abertas ;)

**Comment by Devitibeck** [comment]
Bom dia! Remoto?

Em qua, 19 de fev de 2020 10:23, LeandroRenzi <notifications@github.com>
escreveu:

**Comment by LeandroRenzi** [comment]
Bom dia!
                Infelizmente não está previsto home office pra essas vagas.

De: Patrick Barbosa <notifications@github.com>
Enviada em: quarta-feira, 19 de fevereiro de 2020 10:25
Para: phpdevbr/vagas <vagas@noreply.github.com>
Cc: Leandro Renzi <leandro.renzi@qintess.com>; Author <author@noreply.github.com>
Assunto: Re: [phpdevbr/vagas] [Mogi das Cruzes/SP] Desenvolvedor(a) PHP na Resource IT (#459)

Bom dia! Remoto?

Em qua, 19 de fev de 2020 10:23, LeandroRenzi <notifications@github.com>
escreveu:
