### ISSUE TITLE
[São Paulo/SP] Desenvolvedor PHP Pleno na Btime

### ISSUE THREAD

**Issue by vaynard** [phpdevbr/vagas#46]
## Descrição da vaga

Nossa solução é um SaaS de Gestão de Equipes Externas, usamos tecnologia PHP onde nosso stack se baseia em: Symfony Framework, MySQL, Redis, RabbitMQ. Procuramos um profissional que tenha sólidos conhecimentos de arquitetura e capacidade de pensar fora da caixa solucionando problemas de forma simples e rápida, levando-se em conta temas como segurança, tratamento de erros, separação de camadas/responsabilidades, performance, reusabilidade e aderência a padrões de projetos.

## Local

WeWork Paulista, São Paulo - SP | em frente ao metrô ;)

## Nossa empresa

A Btime é uma startup que está mudando a forma com que as pessoas trabalham. Fomos acelerados pela Liga AutoTech, e buscamos formar uma equipe qualificada e multidisciplinar para atender a crescente demanda, com objetivo de construir soluções em conjunto, onde maior valor é o sucesso de nossos clientes.

Nós oferecemos um ambiente descontraído em que todos os membros possuem a liberdade e responsabilidade de criar as melhores soluções possíveis, isso contando com o suporte de todos os membros, do estagiário até o CEO.

Se você quer mudar a vida das pessoas e a forma que elas trabalham, ou melhor, se você quer mudar o mundo =), venha com a Btime e faça parte dessa história.

## Aqui você irá

- Garantir o desenvolvimento de software com qualidade, através de integração contínua, automação de testes e profundos code-reviews;
- Construir plataformas sustentáveis e estáveis para novas ideias de produto; 
- Encontrar soluções simples e elegantes para problemas difíceis; 
- Trabalhar com TDD e Testes Automatizados; 
- Trabalhar com metodologia ágil scrum;
- Trabalhar com APIs REST;
- Trabalhar com time multidisciplinar.

## Oferecemos

- máquina de chopp com lençol freático =)
- flexibilidade de horário
- café e leite a vontade
- mesa de ping pong
- área de descanso

## Requisitos

**Obrigatórios:**
- PHP 5+
- Symfony
- MySQL
- Design Patterns
- PHPUnit

**Desejáveis:**
- Git/BitBucket
- Google APIs
- Redis
- RabbitMQ
- RESTFul API
- Docker

**Diferenciais:**
- TDD
- SOLID (object-oriented design)
- Elastic Search
- Java
- NodeJs

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para team@btime.com.br com seu CV ou um nude anexado =)
Enviar no assunto: Vaga PHP

**Comment by joubertredrat** [comment]
Cara, como uma vaga pode ser tão linda assim? Balançou meu coração demais @vaynard

**Comment by vinyguedess** [comment]
Aceita remoto ?
