### ISSUE TITLE
[São Paulo/SP] Desenvolvedor PHP na Ide@l 

### ISSUE THREAD

**Issue by Rafael-BP** [phpdevbr/vagas#466]
##  Descrição da vaga

Somos uma startup que desenvolve soluções para a área de comércio exterior.

Contamos com um time que é livre para interagir, cooperar entre si, e evoluir junto.

Dentre as nossas soluções, temos robôs de automação  de atividades e de coleta de dados, sistemas gerencial e financeiro para a área de Comércio Exterior e diversas soluções auxiliares.

Nossa empresa está em expansão. Venha aprender e crescer com a gente!

## Local

Escritório, São Paulo/SP - Vergueiro/Paraíso

#### Diferenciais

- Empresa próxima a metrôs e a todos os serviços básicos
- Ambiente descontraído e informal
- Pode usar shorts e roupas casuais
- Home-office algumas vezes no mês após um tempo de empresa
- Espaço para propor ideias e contribuir com a evolução do time
- Frigobar

## Requisitos

**Obrigatórios:**
- 1 ano de experiência com PHP 5+
- Orientação a Objetos
- MVC (conceito e implementação)
- Conhecer e utilizar as boas práticas (SOLID, PSR, KISS, etc)
- Banco de dados relacionais (MySQL)
- Versionamento de código (GIT)
- Composer
- HTML5 e CSS3
- JS e manipulação do DOM
- Conhecimentos básicos em Linux
- Modelagem de sistemas com UML
- Saber trabalhar em equipe e ser proativo

**Desejáveis:**
- Criação de APIs REST (respeitando o protocolo HTTP) e SOAP
- Experiência com algum framework JS moderno, de preferência Vue.js
- Noções de usabilidade e UX
- Bootstrap e experiência em seguir guidelines
- Desenvolvimento web responsivo

**Diferenciais:**
- Conhecimentos em Design Patterns
- Refactoring
- HTML semântico
- Participa de comunidades (ex: PHPSP, UXCafeBR, etc) e eventos de TI

## Contratação

PJ a combinar

## Nossa empresa

Uma startup que, por meio da tecnologia, traz inovação e inteligência para a cadeia logística e o mercado de Comércio Exterior.

Acesse o nosso site e conheça a nossa empresa: www.tideal.com.br

## Como se candidatar

Por favor envie um email para ideal@haidar.srv.br com seu CV anexado - enviar no assunto: Vaga PHP

### Alocação:
- Presencial

### Contratação:
- PJ

### Experiência
- Junior
- Pleno

**Comment by Rafael-BP** [comment]
Processo seletivo ainda em andamento :)

**Comment by mvnp** [comment]
Na verdade, eu como especialista em home office, acho que a empresa já deveria deixar o funcionário a vontade desde o começo do trabalho para trabalhar inclusive em casa afim de mensurar a sua produtividade enquanto que pessoa auto-gerenciável. 

Assim não corre o risco de perder daqui 6 meses um funcionário bom de empresa que não é bom sem alguém para gerenciar.

**Comment by Rafael-BP** [comment]
@mvnp 
Bom dia tudo bem?

Entendo seu posicionamento como _especialista_, mas hoje não é essa a politica e a forma de trabalhar da empresa.

Agradeço o interesse.

**Comment by Rafael-BP** [comment]
Processo seletivo finalizado :)
