### ISSUE TITLE
[Remoto] PHP Developer no Controlook

### ISSUE THREAD

**Issue by martinusso** [phpdevbr/vagas#467]
#394  Descrição da vaga

Buscamos um Desenvolvedor Fullstack Pleno/Sênior para desenvolver melhorias e otimizações em nosso sistema atual.

## Local

Remoto, Vitória/ES

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento PHP, Python e/ou Go;
- Conhecimento de bancos de dados relacionais (Postgres);
- Testes automatizados;
- Conhecimento básico de tecnologias front-end (Javascript, HTML5, CSS3);
- Git - colaboração e organização dos fluxos;

**Desejáveis:**
- Experiência com arquiteturas RESTful;
- Familiaridade com ambiente Linux;
- Integração contínua e entrega contínua (CI/CD);
- Conhecimento de bancos de dados não relacionais;

## Contratação

PJ / CLT, a combinar

## Como se candidatar

Enviar Github/CV para o e-mail: jobs@controlook.com - enviar no assunto: Vaga PHP

### Alocação:
- Remoto

### Contratação:
- CLT
- PJ

### Experiência
- Pleno
- Sênior

**Comment by THAYLLER** [comment]
Ainda aberto?

**Comment by THAYLLER** [comment]
Quanto tempo demoram pra responder um candidato?
