### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) PHP Pleno na WeJam

### ISSUE THREAD

**Issue by crispossa** [phpdevbr/vagas#47]
## Descrição da vaga

Para quem mora em SP ou deseja se mudar. Essa vaga NÃO é para trabalho remoto.

Estamos procurando desenvolvedor(a) PHP para trabalhar com projetos de treinamento corporativo, conciliação jurídica, plataformas de incentivo, games de apostas, integrações com APIs externas, plataformas de recrutamento, BI, além de sites institucionais e games.
Somos uma equipe multidisciplinar com foco em autonomia e liberdade. Em alguns projetos você será responsável desde a modelagem de banco de dados até a entrega final.

Estamos crescendo muito e estamos procurando quem esteja afim de fazer além do básico e que queira crescer junto com a gente.

## Local

Somente alocado @ Brooklin - São Paulo

## Requisitos

**Obrigatórios:**
- Domina php oop
- Domina os conceitos de mvc
- Experiência com laravel 5+
- Domina mysql
- Noções de normalizacão até nível 3
- Noções dos principais design patterns
- Conhecimentos básicos de frontend
- Vivência com trabalho em equipe
- Git básico
- Bom raciocínio lógico
- Engenharia reversa de código

**Desejáveis:**
- Conhecimento em banco de dados não relacional
- Experiência com vuejs
- Conhecimento de outras linguagens backend
- Configuração de servidores unix
- Raciocínio analítico
- Análise de dados

## Contratação

PJ a combinar

## Benefícios

13º salário
Férias remuneradas

## Nossa empresa

Somos uma agência com uma proposta diferente. Não apenas executamos jobs, mas criamos envolvimento com nossos clientes e projetos.

Participamos desde a concepção do projeto até sua publicação numa filosofia ponta-a-ponta, onde planejamos, construímos e desenvolvemos ideias incríveis.

Desenvolvemos sistemas únicos e realmente desafiantes, além de campanhas publicitárias inteiras que impactam clientes finais em diversas mídias.

Venha fazer parte da nossa equipe!

We Ad! We Rock! We Jam!

[WeJam](http://wejam.click/)

## Como se candidatar

Envie currículo atualizado e link do github (se for ativo) para queroserdev@wejam.email até 31 de julho.

**Comment by rscafi** [comment]
@crispossa poderia acertar os **Benefícios** e o **Nossa empresa**? Verifiquei que você deixou essas informações sem preencher, pode ficar um pouco confuso.

**Comment by crispossa** [comment]
Valeu @rscafi Já adicionei as infos solicitadas. Muito obrigado!

**Comment by crispossa** [comment]
@rscafi alterei o título para deixar claro a experiência desejada. ;)

**Comment by rscafi** [comment]
@crispossa Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.
