### ISSUE TITLE
[São Paulo/SP] Desenvolvedor Full Stack (Júnior / Pleno) na It Model

### ISSUE THREAD

**Issue by icarcal** [phpdevbr/vagas#48]
## Descrição da vaga

Estamos procurando novos integrantes para nosso time

O profissional precisa ter auto-gerenciamento, proatividade e estar em busca de aprendizado, com interesse de ampliar os conhecimentos de forma geral.

Trabalhamos com um time enxuto, multidisciplinar, utilizando metodologias ágeis e sempre entregando o melhor para o nosso negócio.

Nossa stack é baseada em PHP, Framework Laravel, MySQL, mas também possuímos algumas features em Node.js e não temos medo de usar novas tecnologias.

## Local

Centro empresarial Mega Polo Moda - R. Barão de Ladário, 566/670 - Brás, São Paulo - SP
Parte presencial / parte home-office (vamos alinhar após o contato inicial)

## Benefícios

- À combinar

## Requisitos

**Obrigatórios:**
- ```PHP (OOP)```
- Frameworks de mercado (```Laravel```, ```Yii2```, ```Zend```)
- ```Redis```
- ```Git```
- ```MySQL```
- ```HTML```, ```CSS```
- ```Javascript``` (vanilla e libs / frameworks)

**Desejáveis:**
- ```Design Patterns```
- ```Experiência com APIs```
- ```Testes automatizados```
- ```Vagrant / Homestead```
- Pré-processadores CSS (```SAAS, LESS```)
- Automatizadores de tarefas (```Gulp, Webpack, Grunt```)

**Diferenciais**
- ```Docker```
- Conhecimentos em ```Node.js```

## Contratação

PJ à combinar

## Nossa empresa

A [It Model](https://itmodel.com) existe para facilitar e estreitar a relação profissional entre modelos e agências, disponibilizando toda uma rede social com conteúdos e ferramentas exclusivas para auxiliar na busca por oportunidades e profissionais do mundo da moda.

## Como se candidatar

Ficou interessado? Envie um e-mail para icaro@itmodel.com com o assunto ”[Vaga Full Stack]”, informando seu GitHub/LinkedIn/Portfólio e vamos conversar.

**Comment by vinyguedess** [comment]
Aceita remoto ?

**Comment by icarcal** [comment]
@vinyguedess conseguimos viabilizar parte do período como remoto, manda e-mail pra gente, vamos conversar.

**Comment by lucasmarques73** [comment]
Mandei email.

**Comment by rscafi** [comment]
@icarcal Vaga preenchida?

**Comment by icarcal** [comment]
Ainda não, mas estamos passando por uma restruturação na empresa então vou deixar a issue fechada.
Muito obrigado.
