### ISSUE TITLE
[Barueri/SP] PHP Developer na Printi

### ISSUE THREAD

**Issue by bbertolani** [phpdevbr/vagas#480]
https://www.linkedin.com/jobs/view/1481221484/

Buscamos um Desenvolvedor Backend Sênior que será responsável por por todo o desenvolvimento de novas tecnologias pro nosso sistema da Printi. ❤

O QUE ESPERAMOS DE VOCÊ?

Domínio técnico com experiência significativa comprovada em PHP;
Conhecimentos sólidos em banco de dados relacionais e não-relacionais (preferencialmente MySQL e Redis);
Manjar de  Arquitetura MVC (CakePHP, Laravel, Zend ou outro);
Ser viciado em tecnologia;
Brilho nos olhos por alavancar negócios;
Ter raciocínio analítico;
É resiliente e entusiasta;
...e principalmente que seja proativo e inovador (não é papo de RH, SÉRIO!)

O QUE VOCÊ VAI FAZER?

Desenvolver sistemas web;
Criar APIs e microservices com implementação, documentação e testes unitários;
Desenvolver com a melhor performance possível;
Atuar em projetos para o desenvolvimento da empresa
Solucionar eventuais problemas que possam surgir no dia a dia
 
O QUE VOCÊ IRÁ GANHAR?
Muuuito conhecimento;
Desafios diários;
Home Office;
Crescer em uma empresa que dobra de tamanho anualmente;
Trabalhar em um ambiente dinâmico e divertido;
Remuneração e benefícios incríveis;

Barueri

**Comment by tdias25** [comment]
Remoto ou semi presencial?

**Comment by bbertolani** [comment]
Semi presencial
