### ISSUE TITLE
[Porto Alegre/RS] PHP Developer na AIORIA

### ISSUE THREAD

**Issue by gbtagliari** [phpdevbr/vagas#482]
## Descrição da vaga

Procuramos pessoa desenvolvedora para estágio em desenvolvimento de WebServices REST, integração com banco de dados PostgreSQL/MySQL em usando o Framework Laravel no ambiente da Amazon (AWS).

## Local

Porto Alegre, bairro Petrópolis.

## Benefícios

- VR de R$ 18,00/dia

#### Diferenciais

- espaço de jogos
- horários flexíveis
- café SEMPRE disponível ☕️

## Requisitos

**Obrigatórios:**
- vontade de aprender!

**Desejáveis:**
- arquitetura API RESTful
- modelagem de BD

**Diferenciais:**
- experiência em PHP
- experiência na criação de API
- inglês

## Contratação

Estágio

## Nossa empresa

A AIORIA trabalha com o desenvolvimento de projetos utilizando a metodologia ágil aliada ao scrum em nossos sprints.

Gosta de desafios? Somos especialistas em tirar idéias do papel e entregamos o MVPs (aplicativo iOS, aplicativo Android, backoffice e WS) em duas semanas. 

Ou seja, trabalhos numa semana com um aplicativo para marcação de consulta médica e, na outra, estamos trabalhando com uma fintech! 💪

## Como se candidatar

Por favor envie um email para contato@aioria.com.br com seu CV anexado - enviar no assunto: Vaga Estágio PHP

### Alocação:
- Presencial
- Flexível (Remoto parcial)

### Contratação:
- Estágio

### Experiência
- Estágio
- Júnior

**Comment by FernandaTarallo** [comment]
Aceita remoto?

**Comment by gbtagliari** [comment]
> Aceita remoto?

Olá, Fernanda! Não sei te dizer ao certo, mas envia o teu CV pro e-mail que o pessoal aqui avalia! 
Boa sorte!!

**Comment by gbtagliari** [comment]
Fechando a vaga!
