### ISSUE TITLE
[Belo Horizonte] Analista de Sistemas Jr/Pl

### ISSUE THREAD

**Issue by bernardoassis** [phpdevbr/vagas#5]
## Descrição da vaga

Estamos buscando um Arquiteto de Software e Analistas de Sistemas em todos os níveis com foco em desenvolvimento PHP, front-end e back-end!
## Local

Escritório, Belo Horizonte - Santa Lúcia (entre a Raja e a BR356, perto do Falls Shopping)
## Benefícios

Refeição / VT / Lanche
## Requisitos

**Obrigatórios:**
- \+ de 1 ano de experiência desenvolvendo aplicações web utilizando tecnologias web (PHP, Ruby, Python);
- \+ de 1 ano de experiência desenvolvendo websites utilizando HTML, CSS e JavaScript;
- \+ de 1 ano de experiência com frameworks e/ou bibliotecas como Symfony, Laravel, Doctrine, Spark, Grails, Django, Ruby on Rails, EmberJS, Angular;
- Experiência em escrita de consultas SQL (Banco de dados MySQL ou PostgreSQL);
  Conhecimento em padrões de desenvolvimento de software web (MVC, MVVM, etc).

**Desejáveis:**
- Experiência com plataformas de infraestrutura como serviços, em especial Amazon Services
- Conhecimento de infra-estrutura tecnológica para o ambiente PHP (Apache/Nginx, Ubuntu/CentOS, MySQL, Memcache/Redis).

**Diferenciais:**
- Conhecimento de controle de versão de código-fonte Git;
- Experiência de trabalho em equipes de desenvolvimento ágil;
- Habilidade de trabalho com independência e supervisão mínima;
- Disposição em compartilhar o seu conhecimento com as pessoas da área de tecnologia da empresa;
- Boa habilidade de comunicação escrita e verbal;
- Disposição para aprender novas tecnologias e aplicá-las em um curto espaço de tempo;
- Espírito de equipe em um time multi-disciplinar;
- Capacidade de analisar situações e informações, realizando avaliação crítica e conclusiva, apontando direcionamentos para subsidiar as tomadas de decisões.
## Contratação

CLT
## Nossa empresa

A eMotion Digital é uma empresa de tecnologia focada em produção, distribuição de conteúdo e desenvolvimento de projetos incríveis (apps iOS/Android/HTML5) para o mercado de SVA (Serviços de Valor Agregado) para operadoras no mundo inteiro!
## Como se candidatar

Por favor envie um email para bernardo@emotiondigital.com.br com seu CV anexado - enviar no assunto: Vaga Analista de Sistemas

**Comment by ByTecno** [comment]
Enviado!

**Comment by joubertredrat** [comment]
@bernardoassis esta vaga ainda está aberta?

**Comment by joubertredrat** [comment]
@nic vaga preenchida

**Comment by nic** [comment]
Valew por avisar @joubertredrat ;)
