### ISSUE TITLE
[Porto Alegre/RS] PHP Developer na InventSys

### ISSUE THREAD

**Issue by cleberar** [phpdevbr/vagas#501]
## Descrição da vaga

Estamos crescendo, e para construírmos uma base sustentável nesse crescimento, estamos contratando PHP Developer para fazer parte desta jornada.

## Local

Presencial em Porto Alegre - Cidade Baixa

## Requisitos

**Obrigatórios:**

- Conhecimento do uso do git
- Programação em PHP7
- Domínio de Bancos de Dados MySQL

**Diferenciais:**
- NodeJS e JavaScript
- React e React Native
- Conhecimento de NoSql

## Contratação

PJ - CLT a combinar

## Nossa empresa

Somos uma Startup com foco na gestão de serviços de Facility, Provemos uma plataforma integrada e parametrizável para gestão de operação completa de serviços.

## Como se candidatar

Para se candidatar envie um e-mail para inventsys@inventsys.com.br com o assunto: Vaga Programador PHP

### Alocação:
- Presencial
- Flexível (Remoto parcial)

### Contratação:
- CLT
- PJ

### Experiência
- Pleno

**Comment by AlexSJ** [comment]
Olá, boa tarde, no caso Flexível (Remoto parcial) seria alguns dias da semana? Tem algum exemplo?
