### ISSUE TITLE
[São Paulo/SP] PHP Developer na Mutant

### ISSUE THREAD

**Issue by reinaldo-gomes** [phpdevbr/vagas#504]
## Descrição da vaga

Se você gosta de desafios, não se acomoda com a rotina de uma única aplicação, tem um perfil protagonista em todas as etapas de criação e melhorias e tem interesse em desenvolver conhecimento em uma linguagem secundária de trabalho (Python), temos uma oportunidade que combina com o seu perfil! 
 
Estamos montando um time de desenvolvimento para atender a demanda por criação de aplicações (principalmente de automatização de tarefas) que possam potencializar e revolucionar a forma de trabalho das equipes internas da empresa, e eventualmente criar soluções que sejam utilizadas também por nossos clientes externos.

## Local

Escritório em São Paulo/SP - Jardim Europa

## Benefícios

- Plano de saúde
- VR/VA
- Vale transporte
- Demais benefícios CLT

### Diferenciais

- Sala de jogos/descanso
- Código de vestimenta liberal
- Happy Hour toda semana com cerveja liberada
- Home office parcial
- Horário flexível
- Ambiente inclusivo

## Requisitos

**Obrigatórios:**
- curso superior completo na área de tecnologia
- experiência com desenvolvimento web em PHP
- experiência com framework web (preferencialmente Laravel)
- experiência em testes de unidade e integração
- experiência com JavaScript / Bootstrap
- experiência com Git Version Control
- experiência com bases de dados relacionais (mysql)
- inglês: fluência em leitura de documentação e artigos

**Desejáveis:**
- capacidade analítica e senso crítico
- familiaridade com planos e casos de teste
- familiaridade com as culturas Agile e DevOps
- experiência com ferramentas de deploy automático
- familiaridade com linha de comando e ambiente Linux
- vontade e atitude para melhorar os processos utilizados
- iniciativa para identificar e sugerir a implementação de novos processos

## Contratação

CLT a combinar

## Nossa empresa

A Mutant é uma empresa focada em experiência do cliente e plataformas digitais, e que está em pleno crescimento. Saiba mais em: https://mutantbr.com/sermutant/

## Como se candidatar

Envie um email para reinaldo.gomes@mutantbr.com, com CV e pretensão - enviar no assunto: Vaga PHP

### Alocação:
- Presencial

### Contratação:
- CLT

### Experiência
- Pleno

**Comment by reinaldo-gomes** [comment]
continuamos procurando

**Comment by THAYLLER** [comment]
aceitam remoto?
