### ISSUE TITLE
[Remoto] Full Stack PHP Developer na Rede Industrial

### ISSUE THREAD

**Issue by matheus-souza** [phpdevbr/vagas#508]
## Descrição da vaga

Venha fazer parte do time que está mudando a industria brasileira através de sistemas!

O Programador(a) trabalha no desenvolvimento e manutenção de soluções industriais digitais. A posição é para fullstack, trabalhando com PHP (e frameworks) no backend e JavaScript no frontend.

## Local

Remoto

## Benefícios

- Home office
- Equipe unida e motivada
- Ótimo ambiente de trabalho
- Oportunidade de crescimento
- Flexibilidade de horário

#### Diferenciais

- Trabalhe de onde quiser
- Trabalhe o horário que preferir (com reuniões previamente marcadas)
- Trabalhe com foco no resultado

## Requisitos

**Obrigatórios:**
- Ampla experiência com PHP 7+
- Ampla experiência com JavaScript
- Experiência com bancos relacionais
- Experiência sistemas de versionamento Git
- Vontade de aprender e ser aberto a mudanças

**Desejáveis:**
- Conhecimentos em Laravel
- Conhecimentos em Slim Framework
- Conhecimentos em AngularJS
- Conhecimentos em VueJS
- Conhecimentos em Docker

**Diferenciais:**
- Projetos OpenSource
- Pontuação no StackOverflow

## Contratação

PJ

## Como se candidatar

Por favor preencha o formulário de candidatura [clicando aqui](https://forms.gle/aBxmX1RNUA7i8Exa9)
### Alocação:
- Remoto

### Contratação:
- PJ
- Freelance

### Experiência
- Júnior
- Pleno
- Sênior

**Comment by sarettaweb** [comment]
Pode ser remoto de outros estado...

 

Meu linkedin é 

https://www.linkedin.com/in/andresaretta/

 

 

André Saretta

De: Matheus Henrique de Souza [mailto:notifications@github.com] 
Enviada em: sábado, 30 de novembro de 2019 18:28
Para: phpdevbr/vagas
Cc: Subscribed
Assunto: [phpdevbr/vagas] [Remoto] Full Stack PHP Developer na Rede Industrial (#508)

 


Descrição da vaga


Venha fazer parte do time que está mudando a industria brasileira através de sistemas!

O Programador(a) trabalha no desenvolvimento e manutenção de soluções industriais digitais. A posição é para fullstack, trabalhando com PHP (e frameworks) no backend e JavaScript no frontend.


Local


Remoto


Benefícios


*	Home office
*	Equipe unida e motivada
*	Ótimo ambiente de trabalho
*	Oportunidade de crescimento
*	Flexibilidade de horário


Diferenciais


*	Trabalhe de onde quiser
*	Trabalhe o horário que preferir (com reuniões previamente marcadas)
*	Trabalhe com foco no resultado


Requisitos


Obrigatórios:

*	Ampla experiência com PHP 7+
*	Ampla experiência com JavaScript
*	Experiência com bancos relacionais
*	Experiência sistemas de versionamento Git
*	Vontade de aprender e ser aberto a mudanças

Desejáveis:

*	Conhecimentos em Laravel
*	Conhecimentos em Slim Framework
*	Conhecimentos em AngularJS
*	Conhecimentos em VueJS
*	Conhecimentos em Docker

Diferenciais:

*	Projetos OpenSource
*	Pontuação no StackOverflow


Contratação


PJ


Como se candidatar


Por favor preencha o formulário de candidatura clicando aqui <https://forms.gle/aBxmX1RNUA7i8Exa9> 


Labels


Alocação:


*	Remoto


Contratação:


*	PJ
*	Freelance


Experiência


*	Júnior
*	Pleno
*	Sênior

**Comment by matheus-souza** [comment]
> Pode ser remoto de outros estado... Meu linkedin é https://www.linkedin.com/in/andresaretta/ 

Pode sim, apenas precisa preencher o formulário...

**Comment by AndersonKV** [comment]
a vaga ainda ta disponível? tenho experiencia intermediário com javascript, nodejs e react js será que posso mandar?

**Comment by tdias25** [comment]
ainda está aberta?
