### ISSUE TITLE
[Remoto] PHP Developer na VLabs

### ISSUE THREAD

**Issue by carolina-am** [phpdevbr/vagas#518]
## Descrição da vaga

Procuramos um(a) desenvolvedor(a) de Back com experiência em PHP, que goste de desafios e de resolver problemas. O candidato vai compor o time de desenvolvimento da VLabs, trazendo soluções de automação e logística para diversas empresas.
- Você terá a oportunidade de trabalhar e aprender muito sobre logística. 
- Você vai construir plataformas que serão utilizadas em grandes empresas e por muitos usuários.
- Você construirá em cima dos produtos existentes e contribuirá para seu roadmap.

## Local

Remoto

## Benefícios e Diferenciais

- Remuneração competitiva
- Autonomia na escolha do horário de trabalho

## Requisitos

**Obrigatórios:**
- Experiência com PHP
- Rest api
- Sênior ou Pleno

**Desejáveis:**
- conhecimentos em Laravel

## Contratação

PJ

## Nossa empresa

A V-labs é uma empresa de tecnologia focada em soluções logísticas.
Nascemos com o objetivo de otimizar desde processos de intralogística até a distribuição de mercadorias. 
Temos dois produtos: o Adrenalina e o Skylt. O Adrenalina é um software de gestão de distribuição focado em reduzir o custo logístico de indústrias e embaixadores. O Skylt é uma plataforma de ressuprimento inteligente. Com ela é possivel solicitar para qualquer local da fábrica o abastecimento de um item. É o iFood da indústria.

## Como se candidatar

Por favor preencha o seguinte formulário: http://app.pipefy.com/public/form/FKjrqIBK
Nele você vai colocar suas informações básicas, de contato e profissionais.

### Alocação:
- Remoto 100%

### Contratação:
- PJ

### Experiência
- Pleno
- Sênior
- Especialista

**Comment by marcelosousa46** [comment]
Para avaliação!

*Marcelo Sousa*
Programador
*(85) 99176-0967*

Tecnologias:
PHP/Laravel,
Python/Django
Delphi



Em sex., 20 de dez. de 2019 às 16:06, Carol Monteiro <
notifications@github.com> escreveu:
