### ISSUE TITLE
[Rio de Janeiro/RJ] Desenvolvedor PHP/Wordpress na Webedia

### ISSUE THREAD

**Issue by diegoos** [phpdevbr/vagas#53]
## Descrição da vaga

Estamos em busca de pessoas com interesse em trabalhar com grandes projetos e grandes responsabilidades, capazes de solucionar problemas e vencer desafios, sempre prezando pela escalabilidade, performance e qualidade do sistema. Valorizamos pessoas que tem paixão pelo que fazem, com perfil dinâmico, capazes de se adaptarem a diversas situações de projeto, dedicadas e que estejam em constante processo de evolução e aprendizado.

A vaga se destina a profissionais de nível junior e pleno.

## Local

Escritório, Botafogo - Rio de Janeiro/Rj

## Benefícios

- VR/VA
- VT
- Plano de Saúde / Dental
- Café da manhã e lanche da tarde. ;)

## Requisitos

**Obrigatórios:**
- Inglês intermediário / avançado;
- Amplo conhecimento em PHP;
- Amplo conhecimento em Wordpress;
- Amplo conhecimento em tecnologias Front-end e responsividade (HTML5, CSS e JavaScript);
- Conhecimento em Linux / UNIX;
- Conhecimento em APACHE;
- Conhecimento em bancos de dados (SQL);
- Conhecimento com sistemas de versionamento, preferencialmente Git;

**Diferenciais:**
- Experiência com AWS;
- Experiência com sistemas de cache como Akamai, Redis, Varnish, etc;
- Conhecimento com pré-processadores de CSS (Sass, Webpack);
- Conhecimento em APIs sociais (Facebook, Google, Twitter, etc);
- Conhecimentos em outras linguagens de programação para back-end;

## Contratação

CLT

## Nossa empresa

A Webedia é um grupo de mídia digital de origem francesa presente atualmente em sete países, com verticais que totalizam 92 milhões de visitantes únicos por mês, cobrindo temáticas de entretenimento como cinema, games, gastronomia, celebridades/glamour, viagem e influenciadores.

No Brasil, publicamos seis verticais próprios como os líderes TudoGostoso (gastronomia), AdoroCinema (cinema) e IGN (games); além de PurePeople, Purebreak e PureViagem. Somos hoje o 12º maior grupo de mídia digital no Brasil, com total de 34 milhões de visitantes únicos por mês. Considerando apenas a área de entretenimento, o ComScore apontou a operação brasileira da Webedia como uma das sete maiores audiências digitais da América Latina, em ranking liderado pelo YouTube.

## Como se candidatar

Por favor envie um email para diego.oliveira@webedia-group.com com seu CV anexado - enviar no assunto: [Vaga PHP/Wordpress] Nome

**Comment by rscafi** [comment]
@diegoos Vaga preenchida?

**Comment by diegoos** [comment]
@rscafi sim, vaga preenchida já.
