### ISSUE TITLE
[Remoto] PHP Developer na i10digital

### ISSUE THREAD

**Issue by carol-monteiro** [phpdevbr/vagas#538]
## Descrição da vaga

Procuramos um(a) desenvolvedor(a) de Back com experiência em PHP, que goste de desafios e de resolver problemas. O candidato vai compor o time de desenvolvimento da nossa plataforma de WebBanking para empresas.

## Local

Remoto

## Benefícios e Diferenciais

- Remuneração competitiva
- Final de semana de 3 dias
- Autonomia na escolha de horário de trabalho
- Auxílio atividade física

## Requisitos

**Obrigatórios:**
- Experiência com PHP
- Rest api
- Pleno ou Sênior

**Desejáveis:**
- conhecimentos em Laravel

## Contratação

PJ

## Nossa empresa

A i10 é um banco digital focado em empresas que traz soluções financeiras direto para a plataforma do cliente. Queremos pessoas que tenham a ambição de crescer junto com a gente, em um ambiente de aprendizagem e dedicação.

## Como se candidatar

Preencha o seguinte formulário com suas informações básicas, de contato e profissionais.
http://app.pipefy.com/public/form/mGr6EdGp

### Alocação:
- Remoto 100%

### Contratação:
- PJ

### Experiência
- Pleno
- Sênior

**Comment by dersonsena** [comment]
@carol-monteiro essa vaga ainda está em aberto? Submeti no link dessa oferta.

**Comment by carol-monteiro** [comment]
@dersonsena, estamos retomando o processo. Se você se inscreveu no link eu recebi aqui seus dados, pode ficar tranquilo. Vamos analisar todos e qualquer coisa entro em contato.
