### ISSUE TITLE
[Remoto] PHP Developer Invillia

### ISSUE THREAD

**Issue by GabriellyLeonel** [phpdevbr/vagas#539]
## Descrição da vaga

Inglês AVANÇADO;
Conhecimentos e experiência em PHP 7.0;
Laravel e Phalcon (obrigatório);
Desenvolvimento Ágil - Scrum e Kanban;
Soluções e definições de arquitetura;
Desejável conhecimento – Git, Symfony2 e Doctrine ;
Experiência com banco de dados;
Experiência com webservices REST/SOAP;
Desenvolvimento de testes automatizados.

## Local

Remoto.

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche

#### Diferenciais

- 2 horas de almoço
- atuação 100% remoto

## Contratação

CLT 

## Nossa empresa

Nós somos a Invillia,
Somos mais de 400 Invillianos atuando dentro e fora do Brasil, gerando oportunidades todos os dias para clientes potenciais em diversos segmentos e tecnologias. 
Estamos com posições para atuar em alguns dos nossos clientes veja em nosso site alguns deles
Faça uma imersão aqui https://invillia.com/ 

## Como se candidatar

Por favor envie um email para gabrielly.leonel@invillia.com com seu CV anexado - enviar no assunto: Vaga PHP / e pretensão salarial CLT

### Alocação:
- REMOTO

### Contratação:
- CLT

### Experiência
- Pleno
- Sênior

**Comment by romulo2735** [comment]
Muito boa a vaga, candidatura enviada!
