### ISSUE TITLE
[Alphaville/SP] Programador PHP na E.dev

### ISSUE THREAD

**Issue by vinyvicente** [phpdevbr/vagas#54]
## Descrição da vaga

Projeto pontual numa Software House.

## Local

Remoto e esporadicamente (para detalhamento do projeto) pessoalmente no escritório.
Centro de Apoio - Santana de Parnaíba (Alphaville)/SP

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com PHP 5+
- MySQL
- CodeIgniter
- **Git** (criar branch, fazer merge, push, pull, seguir fluxo)

**Desejáveis:**
- Deslocamento para o escritório para trabalhar junto conosco

## Contratação

PJ à combinar

## Como se candidatar

Por favor envie um email para guilherme.lobo@edev.com.br com seu CV anexado - enviar no assunto: Vaga PHP

**Comment by vinyvicente** [comment]
Ainda estamos atrás de gente.

**Comment by styvesamson** [comment]
Blz,  mandei meu cv ai

**Comment by linikerdev** [comment]
Sou do RJ, aceita remoto?

**Comment by dieggop** [comment]
Já mandei o meu!!!

**Comment by vinyvicente** [comment]
@linikerdev Sim!

**Comment by vinyguedess** [comment]
A vaga ainda está aberta ?

**Comment by vinyvicente** [comment]
Sim
