### ISSUE TITLE
[Remoto] PHP Developer na Empreender

### ISSUE THREAD

**Issue by andreas-monday** [phpdevbr/vagas#540]
## Descrição da vaga

Desenvolver ferramentas online usando PHP, HTML e Javascript. 
É desejável experiência com bibliotecas Codeigniter, Jquery, Bootstrap. 
Experiência com uso de webservice http request.

## Local

Remoto

**Desejáveis:**
- conhecimentos em Codeigniter

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para contato@empreender.com.br com seu CV anexado e pretensão salarial para PJ, 8h
Enviar no assunto: Vaga PHP

### Alocação:
- Remoto

### Contratação:
- PJ

### Experiência
- Pleno
- Sênior

**Comment by dersonsena** [comment]
Essa vaga ainda está em aberto? De qualquer forma, já submeti.
