### ISSUE TITLE
[Ribeirão Preto/SP] PHP Developer na Cohros

### ISSUE THREAD

**Issue by natanaelphp** [phpdevbr/vagas#544]
## Descrição da vaga

A Cohros está em busca de um desenvolvedor PHP pleno presencial.

## Local

Escritório, Ribeirão Preto/SP - Alto da Boa Vista

## Benefícios

- Assistência médica e odontológica
- Vale Alimentação

#### Diferenciais

- Café da manhã
- Happy hour
- Sala de descanso e rede
- Laracasts

## Requisitos

**Obrigatórios:**
- Experiêcia em PHP, OOP, MySQL, HTML, CSS, Javascript, GIT
- Familiaridade com as PHP Standards Recommendations (PSRs)
- Conhecimentos de SOLID e REST
- Laravel ou similar
- VueJS ou similar

**Desejáveis:**
- Testes Unitários
- Conhecimentos em Amazon web services (RDS, EBS, EC2, S3, Route 53)
- Ferramentas de Deploy

## Contratação

CLT

## Nossa empresa

Nós acreditamos que a tecnologia pode resolver muitos problemas nas empresas e melhorar o
mundo corporativo. Por isso nós escolhemos trabalhar para isso! Então, desenvolvemos uma
solução tecnológica de gestão, conectando o desempenho das pessoas ao desempenho da
empresa.

Nossa solução busca facilitar as atividades das lideranças na gestão de suas equipes (bom para
os líderes)! Ajuda o RH, gerando bases de informações para uma Gestão de Pessoas mais justa
e meritocrática (bom para o RH e para os colaboradores). Nossa solução também potencializa
os resultados das empresas. Isso é muito bom para os empresários e acionistas, porque terão
retorno do seu investimento.

Nossa solução está super dentro da nossa missão, que é muito importante: queremos
transformar a relação entre empresa e colaboradores em uma parceria de sucesso! Numa
relação ganha – ganha: se a empresa ganha, todo mundo ganha!!!

Estamos em constante evolução. Ideias e inovações para aprimorar nossos sistemas, nossos
métodos e processos de trabalho são parte do cotidiano!

Transparência, amizade e confiança fazem parte da cultura que queremos para nossa empresa.
Nosso ambiente é descontraído, pouca burocracia e muito aprendizado!

## Como se candidatar

Por favor envie um email para ti@cohros.com.br com seu CV anexado - enviar no assunto: VAGA PROGRAMADOR PHP

### Alocação:
- Presencial

### Contratação:
- CLT

**Comment by natanaelphp** [comment]
O processo está em andamento.
Ainda estamos aceitando currículos.

**Comment by natanaelphp** [comment]
A vaga foi preenchida.

**Comment by guilherme90** [comment]
@natanaelphp e você / Cohros nem ao menos me deu um feedback do meu processo seletivo, em? Que maravilha!!

**Comment by natanaelphp** [comment]
@guilherme90 até onde eu sei o pessoal aqui procurou responder a todos que participaram do processo. De qualquer forma peço desculpas em nome da Cohros pelo ocorrido.
