### ISSUE TITLE
[São Paulo/SP] PHP Developer Sênior na Deloitte

### ISSUE THREAD

**Issue by diogom-42** [phpdevbr/vagas#545]
## Descrição da vaga

O profissional irá atuar no desenvolvimento de sites e CMS (Content Management System), em PHP juntamente com WordPress, sendo executadas on cloud, consumindo backlog de melhorias, bem como a implementação de novas funcionalidades na aplicação atual. É esperado que o profissional possua maturidade, comprometimento, capacidade de gestão autônoma de tempo, muita vontade de aprender e entregar resultado.

## Local

Av. Chucri Zaidan, 1240 - Golden Tower – 9º andar , São Paulo/SP - Chácara Sto. Antônio.

## Requisitos

**Obrigatórios:**
• Frameworks JS: Vue.js, React, Angular, JavaScript frameworks, jQuery;
• HTML5 e CSS frameworks como Bootstrap ou Foundation
• Experiência em desenvolvimento e consumo de API RESTful / Protocolo HTTP;
• Sólidos conhecimentos em arquitetura e prática dos princípios Clean Code, Design Patterns e padrão PSR;
• Banco de dados SQL (MS SQL, mySQL, MongoDB);
• Metodologias ágeis (Scrum / Kanban);
• DevOps: CI/CD, Testes automatizados, fluxo de versionamento com GIT;

**Desejáveis:**
• Bancos NoSQL (MongoDB, Elasticsearch, Redis, etc); 
• Cloud Amazon AWS;
• Conhecimentos de Containers (Docker, Kubernetes);
• Conhecimentos de TDD, DDD e/ou BDD;
• Jira para controle de Projetos Agile;
• Maven;
• Swagger;
• Ter construído produtos e aplicações do zero; 

## Contratação

CLT

## Como se candidatar

Interessados enviar CV por e-mail para jveiga@deloitte.com com o assunto [Oportunidade: PHP Developer]

### Alocação:
- Presencial
- Flexível (Remoto parcial)

### Contratação:
- CLT

### Experiência
- Sênior
- Especialista

**Comment by mandelaloko** [comment]
Existe a possibilidade de full remoto?

**Comment by diogom-42** [comment]
@mandelaloko apenas presencial mesmo.
