### ISSUE TITLE
[Remoto] Desenvolvedor(a) PHP Fullstack na SSX Digital

### ISSUE THREAD

**Issue by guireisbh** [phpdevbr/vagas#553]
## Descrição da vaga

Desenvolvedor PHP para projetos em Laravel e Plugins para Wordpress. Será sob demanda.
Início imediato.

## Local

Empresa localizada em Belo Horizonte, Mas com clientes em SP, RJ, DF, RS, Roma e Londres.

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com PHP 7+
- 3 anos de experiência com Laravel
- Experiência com desenvolvimento de plugin para Wordpress

**Desejáveis:**
- Experiência com Node.JS
- Experiência com React/Vue.JS
- Digital Ocean
- Google Cloud

## Contratação

PJ a combinar

## Nossa empresa

Software House que trabalha com software tailor-made e também atende agências de publicidade para demandas específicas.

## Como se candidatar

Por favor envie um email para vagas@ssxdigital.com.br com seu CV anexado - enviar no assunto: Vaga PHP

### Alocação:
- Remoto

### Contratação:
- PJ

### Experiência
- Pleno
- Sênior

**Comment by Piulres** [comment]
Opa! 
www.renanemigdio.com
:)
