### ISSUE TITLE
[Barueri/SP] Programador PHP/Laravel na Plugae

### ISSUE THREAD

**Issue by faguiargptools** [phpdevbr/vagas#56]
## Descrição da vaga

Vaga para programador PHP com ênfase em Laravel. Auxílio no desenvolvimento de aplicação interna e automatização de processos manuais. Desenvolvimento de websites para clientes e aplicativos mobile.

Necessário conhecimento do framework Laravel, bancos de dados MySQL e Postgres, angular JS e VueJS desejáveis. Conhecimento em ferramentas como Photoshop e Illustrator são diferenciais.

## Local

Tamboré - Barueri/SP

## Benefícios

- VT/VR
- Refeitório
- Horário flexível
- Ambiente descontraído

## Requisitos

**Obrigatórios:**
- Experiência com Framework Laravel 5.*
- Experiência com Banco de dados Mysql/PgSQL

**Desejáveis:**
- conhecimentos em VueJS
- conhecimentos em AngularJS
- Bootstrap
- processamento de filas
- experiência em integrações com APIs

## Contratação

PJ/CLT a combinar

## Nossa empresa

Se sua empresa ainda não tem a própria loja online ou atua em marketplaces, nós colocamos seu produto em contato com 60 milhões de compradores todos os dias!

## Como se candidatar

Por favor envie um email para ti@plugae.com.br com seu CV anexado - enviar no assunto: Vaga PHP

**Comment by marcelosousa46** [comment]
Remoto?


Marcelo Sousa
(85) 98502-3111

Em 8 de agosto de 2017 11:16, Fabio Aguiar <notifications@github.com>
escreveu:

**Comment by rscafi** [comment]
@faguiargptools Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.
