### ISSUE TITLE
[Rio de Janeiro/RJ] Desenvolvedor(a) PHP FullStack Pleno na Benfeitoria

### ISSUE THREAD

**Issue by andretefras** [phpdevbr/vagas#566]
<img width="250px" src="https://benfeitoria.com/v2/dist/img/benfeitoria/logo/pink.png">

**A empresa**

A Benfeitoria é um laboratório de inovação que nasceu para fomentar uma cultura mais humana, colaborativa e realizadora no Brasil. Começamos em 2011 com o financiamento coletivo (nosso principal experimento).

**Cenário:**

Estamos em expansão, estruturando o time de engenharia de software para lidar com a evolução da  nova versão da nossa plataforma de financiamento coletivo.

Além da nova plataforma, temos o desafio de conciliar a manutenção do produto atual com a entrega continua de melhorias pontuais.

**Responsabilidade:**

- Reescrever, juntamente com outros membros do time, a nova versão da plataforma de financiamento coletivo da Benfeitoria.
- Oferecer soluções adequadas a entrega de valor para o negócio.
- Zelar pela manutenção da plataforma de financiamento coletivo da Benfeitoria.

**Local:**

Atualmente trabalhamos remotamente, porém nossa sede fica situada no Centro do Rio de Janeiro.

**Perfil da contratação:**

- Ser cordial com os colegas de trabalho
- Ter fácil acesso ao centro do Rio de Janeiro
- Ser pontual, compromissado com horários e entregas
- Ser crítico quanto a qualidade das entregas

**Formação:**

Cursando ou formado em Sistemas de Informação, Análise e Desenvolvimento de Sistemas, Engenharia de Software, Ciência da Computação ou curso relacionado à área de TI.

**Requisitos Obrigatórios:**

- 4 anos de experiência com PHP 5+
- 4 anos de experiência com MySQL
- Laravel 5+
- JavaScript
- VueJS
- HTML5 e CSS3
- SASS
- Git

**Requisitos Desejáveis:**

- Gitflow
- ECMAScript 6+
- Gulp
- Conhecimento sobre design patterns criacionais, estruturais e comportamentais
- TDD

**Diferenciais:**

- Perfil no Github com código que possa ser avaliado
- Docker
- Familiaridade com bibliotecas como VueX, Nuxt, BootstrapVue, Vuetify, etc
- Zend Framework 2
- Linux & Terminal
- Cloud

**Detalhes:**

- Remuneração de R$ 4.000,00 a R$ 5.500,00 de acordo com o nível de experiência
- Contratação PJ, por contrato
- Plano de carreira com revisões anuais
- Vale refeição
- Férias remuneradas
- 13º salário
- Fundo financeiro destinado a emergências
- Fundo financeiro destinado a capacitação

**Diferenciais:**

- Horário flexível
- 1 dia de home office após período de experiência

**Candidatura:**

O candidato deverá realizar o teste abaixo, enviando um PULL REQUEST para o mesmo repositório.

https://github.com/benfeitoria/dev-test/blob/master/test-blog.md

Se o candidato possuir projetos que possam ser consultados, fica isento do teste.

Um e-mail com o currículo em anexo deve ser enviado para [dev@benfeitoria.com](dev@benfeitoria.com).

**Labels**

- Pleno
- Alocado
- PJ

**Comment by Devitibeck** [comment]
Por 7 mil eu aceitaria a vaga, por 4.000 só echo 'ola mundo'

Em qui., 7 de mai. de 2020 às 12:41, André Assis <notifications@github.com>
escreveu:

**Comment by Devitibeck** [comment]
Pleno FullStack = Sênior Backend. Esse valor ta totalmente fora do padrão.

Em qui., 7 de mai. de 2020 às 17:23, Patrick Barbosa <
patrickbarbosa.dp@gmail.com> escreveu:

**Comment by tifannyknox** [comment]
não existe pleno fullstack, que eu saiba fullstack é senior. Valor fora do padrão.

**Comment by aleksmont** [comment]
Valor totalmente errado, fora da realidade. Praticamente impossível de levar a sério.

**Comment by Piulres** [comment]
Ta precisando de ajuda?
www.renanemigdio.com

vem de zap

**Comment by caiquesandrade** [comment]
RJ sendo RJ, querendo mendigar profissionais.

**Comment by wmendes** [comment]
Isso é salário de 2012. Depois dá entrevista dizendo que tá com não sei quantas vagas abertas e não tem profissional.

**Comment by andretefras** [comment]
O valor esta de acordo com nossas possibilidades atuais pessoal.

Somos transparentes e gostaríamos de poder oferecer mais. Trabalhamos para chegar nesse momento. A jornada é longa.

Abraço a todos e boa sorte na procura.

**Comment by leoqbc** [comment]
Segundo a pesquisa do glassdoor:
https://www.glassdoor.com.br/Sal%C3%A1rios/desenvolvedor-php-pleno-sal%C3%A1rio-SRCH_KO0,23.htm

A média de salário está compatível com PHP Pleno, agora cabe interpretação do que seria **Requisitos Obrigatórios** e do quanto é necessário dominar os conceitos pedidos e muito mais de como o profissional será exigido, espero que empresa entenda que Fullstack não é pau pra toda obra.

Porém galera acho que estão reclamando de barriga cheia(na minha opinião), não se esqueçam que tem pessoas tendo cortes de seus salários em 50%(sem falar em demissões) e que a economia está totalmente desregulada.

Ver empresa contratando em meio a pandemia e segurando meio que a pontas para não desqualificar o profissional(cabe opinião divergente) é motivador.

De qualquer forma acho legal que ocorra esse tipo de feedback, dos dois lados, parabéns @andretefras por se importar em dar um retorno e ao pessoal por exporem suas visões

**Comment by tifannyknox** [comment]
Exatamente, FullStack não é pau pra toda obra. Acredito que os conhecimentos técnicos da vaga está exigindo muito de um pleno, além disso o salario não é compatível. Além do mais deixamos claro que pelo nível da empresa e o que ela faz, não é pra qualquer um mesmo, tem que ter conhecimento nível bom pra não fazer gambirra e depois ter que "refazer" os sistemas. 

É chato ficar criticando vagas, mas o cliente precisa ter um pouco de bom senso na hora de fazer requisitos de vagas de acordo com o nível/salario.

**Comment by andretefras** [comment]
Obrigado @leoqbc!

O contexto atual é realmente complicado para todos, mas também acredito que não sirva de desculpa para algumas situações.

A pessoa esta sendo contratada para trabalhar com um time e complementar conhecimento, além de absorver novos. Gostamos de trabalhar de forma leve, sem sobrecarga.

Posso estar contratando, mas também sou desenvolvedor e entendo algumas aflições do mercado. Aqui, até mesmo pela cultura da empresa, tentamos ser justos na medida do possível com o que podemos oferecer, nos baseando também em benchmark de mercado para definir nossa progressão salarial.

Abração

**Comment by andretefras** [comment]
Vaga preenchida. \o

Como o candidato tinha experiência além dos requisitos da vaga, entrou como senior.
