### ISSUE TITLE
[Sāo Paulo/SP] Estágio em desenvolvimento Wordpress na BLU365

### ISSUE THREAD

**Issue by raphaguasta** [phpdevbr/vagas#567]
## Descrição da vaga

**Aqui você vai trabalhar com:**

- Desenvolvimento de temas responsivos e performáticos para Wordpress
- Desenvolvimento de plugins Wordpress
- Docker
- Serviços AWS
- Consumo de APIs client e server side

**O que esperamos de você:**

- Preocupado com organizaçāo e qualidade do código
- Acompanhar as novidades e atualzaçōes, a tecnologia evolui rápido!
- Estudo e aprendizado constante (temos cursos pagos pela empresa)
- Habilidade de evoluir por conta própria
- Nāo ter apego a frameworks, libs... Código é código!

## Local

Estamos no Cubo Itaú, o maior centro de empreendedorismo tecnológico da América Latina!
(Início remoto devido a pandemia)
Vila Olímpia - Sāo Paulo, SP

## Benefícios

- Vale Transporte
- Vale Refeiçāo
- Férias
- Incentivo a cursos
- No Dress Code
- Horário flexível

#### Diferenciais

- Refeitório com microondas
- Pebolim, mesa de ping-pong, sinuca
- Chopp free a partir das 18:00hrs :)

## Requisitos

**Obrigatórios:**

- Conhecimentos básicos em JS, HTML, CSS e PHP
- Conhecimentos básicos de desenvolvimento Wordpress (templates e pages, wp_query, loop, funções auxiliares)

**Desejáveis:**
- Git
- Protocolo HTTP e consumo de APIs
- Familiaridade com ambiente Linux e uso de linhas de comando (shell)

## Contratação

Estágio

## Nossa empresa

Com a proposta de ajudar os brasileiros a negociarem suas dívidas e a se manterem no azul sempre, a BLU365 oferece uma plataforma de negociação fácil, intuitiva e digital, para seus clientes ficarem no azul o ano todo.

## Como se candidatar

Encaminhar cvs para: estagios@blu365.com.br

## Labels

- Presencial
- Estágio
- Estágio

**Comment by emanuelbiet** [comment]
Encaminhei a vaga pra um amigo e ele disse que o retorno é que o email não existe.
