### ISSUE TITLE
[São Paulo/SP] Programador PHP Júnior na Uotz

### ISSUE THREAD

**Issue by weverest** [phpdevbr/vagas#57]
[São Paulo/SP] Programador PHP Júnior 
## Descrição da vaga

Vaga para programador PHP nível Júnior. Auxílio no desenvolvimento e manutenção de aplicações.

Necessário conhecimento de POO, bancos de dados MySQL e JavaScript.
Conhecimento em Laravel e VueJS são diferenciais.

## Local

Pinheiros - São Paulo/SP

## Benefícios

- VR
- Refeitório
- Horário flexível
- Ambiente descontraído

## Requisitos

**Desejáveis:**
- conhecimentos em VueJS
- Bootstrap

## Contratação
A combinar

## Nossa empresa

Há 12 anos trabalhamos a experiência de clientes reais em inteligência aplicada aos negócios. Somos pioneiros na criação da Jornada do Cliente, metodologia que mapeia todos os pontos de contato com as marcas para gerar insights transformadores para decisões táticas e estratégicas dos nossos parceiros

## Como se candidatar

Por favor envie um email para diogo.brito@uotz.com.br com seu CV anexado - enviar no assunto: Vaga PHP Júnior

**Comment by marcelosousa46** [comment]
Remoto?


Marcelo Sousa
(85) 98502-3111

Em 8 de agosto de 2017 15:03, weverest <notifications@github.com> escreveu:

**Comment by weverest** [comment]
Olá Marcelo!
A vaga não é para trabalhar remoto :(

**Comment by devEdipo** [comment]
@weverest ,

A vaga já foi preenchida?

Atte,.

**Comment by rscafi** [comment]
@weverest Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.
