### ISSUE TITLE
[São Paulo/SP] Analista Desenvolvedor PHP na Just Digital

### ISSUE THREAD

**Issue by daniiell3** [phpdevbr/vagas#58]
## Descrição da vaga

Estamos em busca de desenvolvedores apaixonados por construir produtos digitais de qualidade, que estejam atualizados com as melhores práticas e tecnologias, envolvidos e engajados com comunidades de software.

## Local

Escritório, São Paulo - Chácara Sto. Antônio

## Benefícios

- Vale Transporte ou Auxílio Combustível 300,00/mês + Auxílio Estacionamento R$ 170,00/mês (ambos apenas se você realmente vem de carro)
- Vale-refeição de R$ 594,00
- Assistência médica (30% empresa / 70% colaborador)
- Participação no bônus anual com base nos lucros da empresa (PLR)
- Seguro de vida em grupo

#### Diferenciais

- mesa de ping pong
- mesa de bilhar
- 4 home-offices por mês

## Requisitos

**Obrigatórios:**
- PHP 5.6+ (Desejável 7.1) Orientado a Objetos
- Design Patterns (Conhecimento teórico e prático ao mínimo em 1)
- MySQL (Modelagem, Relacionamentos, Comandos Básicos, Joins, Procedure) 
- Conhecimento prático do fluxo de versionamento com GIT
- Criação e consumo de API
- Linux e Shell Script

**Desejáveis:**
- Conhecimento em um ou mais frameworks PHP
- Docker / SysOps / AWS / MS Azure
- Testes unitários e comportamentais
- Inglês
- Integrações (Pagamento, serviços)

**Diferenciais:**
- Drupal
- Wordpress

## Contratação

CLT Full

## Nossa empresa

Somos uma empresa de tecnologia, desde 2008 na estrada, especializada em criar software e plataformas digitais com o objetivo de reter e aproximar clientes, parceiros e colaboradores, das empresas que atendemos.

Trabalhamos em parceria com as áreas de TI, Inovação, Marketing e Digital, definindo as melhores estratégias, oferecendo as melhores soluções e desenvolvendo software sob medida. 

Sempre com pensamento ágil e foco na necessidade e experiência do usuário, visamos lançar rápido eliminando desperdício.

Diferente das consultorias de TI e empresas de desenvolvimento de software, prezamos o rápido atendimento, a flexibilidade para adequar nossos processos, a resposta rápida à mudanças e a proximidade com nossos clientes.

## Como se candidatar

Candidate-se em [Recruiterbox](https://justdigital.recruiterbox.com/jobs/fk0fhfs)

**Comment by daniiell3** [comment]
Labels: Alocado, CLT, Júnior, Pleno, Sênior

**Comment by xtfs** [comment]
A vaga ainda está aberta?

**Comment by daniiell3** [comment]
@xtfs Sim, mais do que nunca.

Desculpa a demora pra responder

**Comment by rscafi** [comment]
@daniiell3 Vaga preenchida?

**Comment by daniiell3** [comment]
@rscafi Ainda temos vagas

**Comment by paulodealmeida** [comment]
@daniiell3 o link está dando 404, tenho outra forma para eu me candidatar?

**Comment by renanoliveira0** [comment]
@daniiell3 , o link não está funcionando
