### ISSUE TITLE
[São Paulo/SP] Programador(a) WEB com experiência na ITWS

### ISSUE THREAD

**Issue by tomazzoleia** [phpdevbr/vagas#585]
## Descrição da vaga

Programador WEB com experiência para dar manutenção em sistemas.

## Local

- Escritório, São Paulo/SP - Moema

## Benefícios

- Ajuda de custo para combustível e refeição;

## Requisitos

**Obrigatórios:**
- PHP
- Javascript
- CSS

**Desejáveis:**
- Bootstrap
- Framework (YII ou LARAVEL)
- Angular

**Competências**
- Capacidade analítica
- Raciocínio lógico
- Conhecimento em inglês
- Ágil
- Boa comunicação

## Contratação
PJ a combinar

## Período de trabalho
Integral (8:00 às 17:00)

## Nossa empresa
ITWS

## Como se candidatar
Por favor envie um email para tomazzoleia@gmail.com com seu CV anexado - enviar no assunto: Vaga PHP: <seu_nome>
Qualquer dúvida entre em contato via whatsapp 11 98059-8397

### Alocação:
- Presencial

### Contratação:
- PJ

### Experiência
- Pleno
- Sênior

**Comment by erandirjunior** [comment]
Somente presencial?

**Comment by tomazzoleia** [comment]
Infelizmente não amigo, mas é um horário flexível e o pessoal é bacana.

**Comment by erandirjunior** [comment]
@tomazzoleia ficou um pouco confuso sua resposta. Em relação a minha situação, seria interessante se fosse home office.

**Comment by tomazzoleia** [comment]
Olá tudo bem? Sim, presencial.

Se tiver interesse e experiência pode me chamar no whatsapp 11980598397

Em ter, 30 de jun de 2020 12:58, Erandir Junior <notifications@github.com>
escreveu:
