### ISSUE TITLE
[São Paulo/SP] Desenvolvedor PHP+Laravel+MySQL Pleno/Sênior

### ISSUE THREAD

**Issue by SergioSCF** [phpdevbr/vagas#59]
## Descrição da vaga

Estamos em busca de um desenvolvedor PHP Pleno/Sênior, com grandes responsabilidades, capaz de solucionar problemas, vencer desafios e entregar nos prazos determinados e combinados pelo próprio desenvolvedor.

O projeto atual já está em andamento e precisamos de alguém que possa dar uma velocidade maior junto com outros desenvolvedores do time.

A vaga se destina a um profissional de nível Pleno/Sênior.

## Local

Escritório, São Paulo - Moema

## Requisitos

**Obrigatórios:**
- Fortes conhecimentos em PHP;
- MySQL;
- Laravel;
- JQuery;
- GIT;
- Bootstrap;
- Amplo conhecimento em tecnologias Front-end e responsividade (HTML5, CSS e JavaScript);
- WebService REST
- JSon

**Desejáveis:**
- Experiência com AWS;
- Conhecimento em APIs sociais (Facebook, Google, Twitter, etc);

## Contratação

Contratação: PJ a combinar
Nível: Pleno/Sênior
Local: Moema/SP
Horário: Seg-Sex com horário flexível

## Como se candidatar

Enviar currículo com o título "Vaga Dev Pleno PHP" para sergio.gri@gmail.com

**Comment by rscafi** [comment]
@SergioSCF Vaga preenchida?

**Comment by SergioSCF** [comment]
Sim

Atenciosamente,

Sergio Costa Faria
sergio.gri@gmail.com
+55 11 98634-7527
http://linkedin.com/in/sergiocostafaria

Em 12 de jan de 2018, à(s) 19:55, Ravan Scafi <notifications@github.com> escreveu:
