### ISSUE TITLE
[São Paulo/SP] [Remoto] PHP Engineer na Convenia

### ISSUE THREAD

**Issue by casimiroarruda** [phpdevbr/vagas#594]
## Descrição da vaga

Se você curte um ambiente com autonomia, compartilhamento de conhecimento e grandes desafios, veja abaixo detalhes do job 👀

Estamos em uma missão para acabar com a burocracia do RH através de tecnologia. O time de engenharia da Convenia está alçando novos voos e para tal precisamos de uma pessoa experiente no desenvolvimento web, que transforme as necessidades do negócio em novidades e melhorias no nosso produto.

Como Analista de Desenvolvimento Pleno (Backend PHP) seus maiores desafios serão:

- Analisar a necessidade do produto e propor possíveis implementações
- Atuar junto ao time para implementar as Histórias de Usuário no produto
- Manter e evoluir a suíte de testes e qualidade do código
- Interagir com as demais tribos (frontend, infra, design, etc) para a evolução dos produtos
- Colaborar na definição e execução de OKRs
- Sugerir melhorias para o time de engenharia e produto

## Local

Remoto ou Escritório, São Paulo/SP - Jardim Paulista

## Benefícios

Ninguém melhor do que você para escolher seus próprios benefícios, no Convenia você recebe pontos e escolhe como deseja montar seu pacote de benefícios escolhendo entre as opções abaixo:

- Vale Refeição
- Vale Alimentação
- Plano de Saúde
- Plano Dental
- Total Pass (Academias)
- Estacionamento
- Go Green (Cartão despesas Alelo)
- Desconto farmácia
- Chef´s club (Desconto em restaurantes)
- Clube de Vantagens Convenia
- Seguro de Vida
- Vale Transporte
- Auxílio creche
- Day off no aniversário

## Requisitos

**Obrigatórios:**

- Experiência em sistemas baseados em Laravel 6+
- Fluência em PHP 7+
- Habilidade em trabalhar com Bancos de Dados(SQL,NoSQL), Mensageria e Cache
- Fluência no consumo de APIs (REST/ful, GraphQL)
- Conhecimento de técnicas e ferramentas de testes, depuração e logging
- Conhecimento em segurança web e OWASP
- Excelente comunicação escrita
- Bom relacionamento interpessoal

**Desejáveis:**

- Conhecer bem boas práticas (SOLID, DesignPatterns, SOA, etc)
- Tiver facilidade em apresentar ideias e prover treinamentos
- Entender bem e aplicar padrões (REST, PSR, etc)

## Contratação

CLT

## Nossa empresa

Somos uma empresa de tecnologia que quer trazer facilidade e eficiência na gestão de pessoas das empresas. Queremos tornar a vida do gestor mais fácil, menos burocrática, para que ele consiga pensar menos em processos e mais no que realmente importa: pessoas. :heart_eyes:

Aqui na Convenia queremos proporcionar a melhor experiência para todas as pessoas: clientes e colaboradores

﻿Valorizamos o compartilhamento de ideias, o desenvolvimento de uma cultura de trabalho em equipe, respeito a diversidade, autonomia em seus desafios, ser fora da caixa e aprender com os erros. :muscle:

Juntos construímos uma cultura *welovepeople*  :purple_heart:

Seja bem vindo à Convenia !

## Como se candidatar

Acesse a [página dessa oportunidade no Gupy](https://convenia.gupy.io/jobs/244078) e clique em `Candidatar-se para a vaga`.

### Alocação:
- Remoto
- Presencial opcionalmente

### Contratação:
- CLT

### Experiência
- Pleno
- Sênior

**Comment by Piulres** [comment]
Gosto do projeto de vocês. Vamos trocar figurinhas? 
www.renanaemigdio.com
:)

**Comment by casimiroarruda** [comment]
@ravanscafi poderia adicionar o label `remoto`, por favor?

**Comment by gigante** [comment]
@casimiroarruda, muito bacana o projeto e a proposta... aplicando agora :heavy_check_mark:
