### ISSUE TITLE
[Remoto] PHP Developer na Apiki

### ISSUE THREAD

**Issue by nathaliaambrosio** [phpdevbr/vagas#597]
## Sobre o nosso cliente:

A Apiki é uma empresa especializada em WordPress, plataforma líder mundial de gestão de conteúdo, que tem a missão de desenvolver soluções digitais para potencializar e integrar negócios no mundo inteiro.

A produtora web pertence ao grupo iMasters e atualmente mantém escritórios em Governador Valadares, Minas Gerais e em São Paulo, capital paulista. 

Apiki é uma mistura de ousadia, inovação, marketing e tecnologia. Uma empresa que já nasceu à frente do seu tempo, em 2008, precisava de um nome que representasse sua essência. 

## Requisitos técnico:

Conhecimento intermediário em PHP;
Conhecimento em JS (Node.js, React.js)
Conhecimento Docker
Conhecimento SQL (MySQL);
Conhecimento em versionamento com Git;
Conhecimento em configuração de CI/CD ( GitLab e/ou GitHub)
Linux e scripts para o mesmo (Shell Script / Bash)

**Diferencial:**

Vivência com WordPress e/ou WooCommerce;
Conhecimento com soluções de Cloud.

## Local
Remoto 

### Contratação:
PJ

### Experiência
- Júnior
- Pleno

## Como se candidatar

Por favor envie um email para rafael.clementino@beit.work com seu CV anexado - enviar no assunto: Vaga PHP

**Comment by leoaugusto13** [comment]
Enviado!
