### ISSUE TITLE
[Santos, SP] Desenvolvedor PHP | Cubbo

### ISSUE THREAD

**Issue by diegomalone** [phpdevbr/vagas#6]
## Descrição da vaga

Procuramos um desenvolvedor PHP para trabalhar em nossos projetos já existentes e participar de novos projetos junto com nossa equipe de desenvolvimento.
## Local

Santos, SP.
## Benefícios
- Ambiente descontraído, informal e dinâmico
- Oportunidade de contribuir efetivamente para a evolução de uma startup
- Possibilidade de crescimento na empresa
- Contratação PJ
## Requisitos

Obrigatórios
- Conhecimento em frameworks PHP
- Conhecimentos em Git
- Conhecimento em banco de dados
- Boas práticas de desenvolvimento
- Facilidade para trabalhar em equipe
- Inglês técnico
- Disponibilidade para trabalho presencial em Santos, SP

Desejáveis
- Experiência com APIs RESTful
- Experiência com Laravel
- Conhecimento em CSS e JavaScript
- Domínio sobre testes unitários, de interface e TDD
- Experiência em desenvolvimento ágil
- Curiosidade e vontade de aprender novas ferramentas e tecnologias
- Capacidade de pensar e resolver problemas de forma criativa

Diferenciais
- Conhecimento em UX/UI
- Projetos Open Source
- Experiência em startups
- Perfil ativo no GitHub e StackOverflow
## Contratação

PJ a combinar.
## Nossa empresa

O Cubbo Design Studio é uma empresa formada por inovação e comprometimento, pioneira na baixada santista em seu segmento. Com o foco em projetos inovadores, desenvolvendo aplicativos e sistemas para facilitar a vida de clientes e empresas.
## Como se candidatar

Por favor envie um email para vagas@cubbo.com.br com o título "Vaga PHP".

**Comment by joubertredrat** [comment]
Boa noite @diegomalone 
A vaga ainda está aberta?
A vaga é somente PJ ou existe alguma possibilidade de CLT?

**Comment by diegomalone** [comment]
Opa @joubertredrat 

A vaga que criamos na época foi preenchida, mas deixamos o anúncio aqui porque sempre estamos precisando de gente.
Damos preferência à contratos PJ, mas dependendo da situação, pode ser possível CLT sim.

Se tiver interesse, manda um email pra gente que a gente conversa.

**Comment by diegomalone** [comment]
Temos outra vaga nesse perfil aberta.

**Comment by nic** [comment]
@diegomalone vaga preenchida?

**Comment by diegomalone** [comment]
Vaga preenchida! Obrigado!
