### ISSUE TITLE
[Remoto] Back-end Developer Laravel para API na RockApps

### ISSUE THREAD

**Issue by erickne** [phpdevbr/vagas#607]
## Descrição da vaga

Desenvolvimento de aplicação backend API em Laravel com plena liberdade de criação e para atuar em regime home office. A vaga é para um novo projeto de uma StartUp da beleza que recebeu um novo a porte de capital.

## Local

Remoto.

## Requisitos

**Obrigatórios:**
- Laravel Avançado (Model, Controller, Requests, Validation, Events, Notification, Console, Routes, Traits, etc)
- Testes Unitários
- TDD
- Experiência em desenvolvimento de aplicações com LAMP Stack (Linux/ Apache/ MySQL/ PHP).
- Conhecimento em construção de RESTful APIs

**Desejáveis:**
- Horizon
- Gestão de filas (Queues)

**Diferenciais:**
- Criação e manutenção de Packages
- Conhecer sobre Jenkins e Continuous Integration
- Conhecimentos em React e React Native

## Contratação

PJ a combinar

## Nossa empresa

Fornecemos soluções de software com preços competitivos e complexidade variada para empresas, startups e indivíduos.

## Como se candidatar

Por favor envie um email para carreiras@rockapps.com.br com seu CV anexado - enviar no assunto: Vaga LARAVEL

### Alocação:
- Remoto

### Contratação:
- PJ

### Experiência
- Sênior

**Comment by Devitibeck** [comment]
Você precisa de um programador back end ou full stack?


Em qui, 30 de jul de 2020 16:53, Erick Engelhardt <notifications@github.com>
escreveu:
