### ISSUE TITLE
[São Paulo/SP] Desenvolvedor WEB PHP Pleno na Atitude

### ISSUE THREAD

**Issue by michaeldouglas** [phpdevbr/vagas#61]
## Descrição da vaga

Estamos procurando um desenvolvedor web pleno que possua conhecimentos em: Javascript, 
PHP e banco de dados relacional. 

## Local

Rua Bragança Paulista, 145 | São Paulo - SP, CEP: 04727-000

## Benefícios

 - Décimo terceiro salário.
 - Férias + 1/3 sobre as férias.
 - Almoço.
 - Vaga de garagem no local.
 - Bônus de até 2 salários.

## Requisitos

**Obrigatórios:**
- No mínimo 1 ano de experiência com PHP 5+
- No mínimo 1 ano de experiência com Javascript.
- No mínimo 1 ano de experiência com banco de dados relacional.

**Desejáveis:**
- Conhecimentos em NodeJS
- AngularJS
- AWS

## Contratação

PJ a combinar

## Nossa empresa

Sobre a empresa Atitude foi Fundada em 1988, em São Paulo, a Atitude é uma provedora de 
serviços em tecnologia e comunicação na web.

Com mais de 1500 WebMeetings realizados desde 2003, a empresa é referência nacional no 
desenvolvimento de soluções de comunicação via internet - a partir dos seus 3 estúdios, da sede 
dos clientes, ou de qualquer outro local.

## Como se candidatar

Por favor envie um email para michael.douglas@atitude.com.br com seu CV anexado - enviar no assunto: Vaga desenvolvedor WEB PHP

**Comment by deyvisonrocha** [comment]
É bom colocar a localidade da vaga no título: [São Paulo/SP] ...

**Comment by tharcius** [comment]
Tem previsão para alguma vaga remota (home office)?

**Comment by michaeldouglas** [comment]
A vaga foi preenchida, obrigado a todos por enviarem seus currículos.
