### ISSUE TITLE
[Salvador/BA] PHP Developer na T.O. Sistemas

### ISSUE THREAD

**Issue by adimariooliveira** [phpdevbr/vagas#616]
## Descrição da vaga

Projeto Licitação WEB.

## Local

Escritório, Salvador Ba - Paralela/Alphaville

## Benefícios

- Plano de saúde
- Aux. Transporte

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com PHP 5+

**Desejáveis:**
- conhecimentos em Laravel
- Ajax
- Javascript

**Diferenciais:**

## Contratação

CLT

## Nossa empresa

T.O. sistemas de informática, prestamos serviços para órgãos públicos.

## Como se candidatar

Por favor envie um email para adimario.oliveira@gmail.com com seu CV anexado - enviar no assunto: Vaga PHP

### Alocação:
- Presencial

### Contratação:
- CLT

### Experiência
- Pleno
- Sênior

**Comment by devLopez** [comment]
Enviado!
