### ISSUE TITLE
[São Paulo/SP] Programador PHP Júnior pela Talent Four

### ISSUE THREAD

**Issue by AmandaPlaca** [phpdevbr/vagas#62]
Programador PHP_Jr
Conhecimentos técnicos:  HTML5, CSS 3, JavaScript, jQuery e layout responsivo (mobile first), PHP avançado, orientação a objeto, GIT, postgresql e  Zend, WordPress  (diferencial CMS) e SQL avançado. 
• Front-end : Bootstrap, Angular. 
• Conhecimentos básicos em metodologias ágeis (Scrum, Kanban, etc.).
Local de trabalho: prox. estação Pinheiros
Contratação CLT diretamente pelo cliente.

Interessados ou Indicações enviar currículo para: ketty.lacerda@talentfour.com.br
![php jr](https://user-images.githubusercontent.com/31107789/29426175-2cd3c594-835c-11e7-9e6b-7a038520b7cf.jpg)

**Comment by rscafi** [comment]
@AmandaPlaca é pra trabalhar na TalentFour? o regime de contratação é CLT ou PJ

Por favor, veja como as outras vagas são claras e já essa, nem tanto. Se possível, atualize as informações.
Isso pode ajudar sua empresa a encontrar mais interessados.

**Comment by AmandaPlaca** [comment]
@rscafi sou nova aqui...rsrsrs. Valeu pela dica, ja atualizei na vaga.

**Comment by RafaelaCassianoCampos** [comment]
A vaga já foi preenchida?

**Comment by vinyguedess** [comment]
@mateusguedess

**Comment by rscafi** [comment]
@AmandaPlaca Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.
