### ISSUE TITLE
[Remoto] Desenvolvedor(A) PHP na Eskive

### ISSUE THREAD

**Issue by LarissaGandarela** [phpdevbr/vagas#621]
## Descrição da vaga

Na Eskive você vai poder contribuir ativamente com arquitetura da aplicação, desenvolvimento de novas tecnologias, automatização de tarefas, triagem de problemas técnicos e análise e Correções de bugs. 

## Local

Remoto.

## Requisitos

**Obrigatórios:**
- GIT
- PHP
- Test Driven Development (TDD)
- SOLID Principles
- Experiência com framework Laravel
- Experiência com desenvolvimento de APIs
- SQL
- MySQL
- RabbitMQ
- Redis
- Inglês técnico avançado (leitura de documentações e entendimento de video aulas no idioma)
- HTML
- CSS
- JavaScript (ES2015 ou posterior)
- Conhecimento em Azure ou AWS

**Diferencial:**
- Experiência com Vue ou React
- Domínio de conceitos em desenvolvimento seguro
- Familiaridade com framework SCRUM
- Familiaridade com Docker
- Experiência com Microserviços
- Experiência com Elasticsearch
- Experiência em gestão de equipes

## Contratação

- PJ

## Benefícios

- 30 dias de férias remuneradas.

## Nossa empresa

A Eskive é a plataforma brasileira de monitoramento de vulnerabilidade humana em segurança da informação. Muito mais que simulação de Phishing, a Eskive conta com mais de 10 sensores de análise para que os gestores de Segurança da Informação consigam antever, treinar e preparar as empresas para os ataques de engenharia social.

## Como se candidatar

Fazer o cadastro no seguinte site:  **byintera.in/eskivec1**

Dúvidas:
https://www.linkedin.com/in/larissagandarela/

### Alocação:
- Remoto

### Contratação:
- PJ

### Experiência
- Pleno
- Sênior

**Comment by moreiraandre** [comment]
Boa tarde @LarissaGandarela 
No site para inscrição existem vários outros requisitos para esta vaga, como:

# Para este desafio, é necessário:
GIT
PHP
Test Driven Development (TDD)
SOLID Principles
Experiência com framework Laravel
Experiência com desenvolvimento de APIs
SQL
MySQL
RabbitMQ
Redis
Inglês técnico avançado (leitura de documentações e entendimento de video aulas no idioma)
HTML
CSS
JavaScript (ES2015 ou posterior)
Conhecimento em Azure ou AWS

# ...e será um diferencial se você:
Experiência com Vue ou React
Domínio de conceitos em desenvolvimento seguro
Familiaridade com framework SCRUM
Familiaridade com Docker
Experiência com Microserviços
Experiência com Elasticsearch
Experiência em gestão de equipes

Os itens do site são realmente necessários, ou só o que consta aqui no GitHub já é o suficiente?
