### ISSUE TITLE
[Belo Horizonte/MG] Desenvolvedor Full Stack Pleno na conta.MOBI

### ISSUE THREAD

**Issue by rhcontamobi** [phpdevbr/vagas#63]
## Descrição da vaga

•	Entender a estrutura de desenvolvimento definida pela empresa;
•	Sinalizar possíveis problemas ou a trazer as soluções mais adequadas;
•	Estar atento às regras definidas para o desenvolvimento de um projeto de software.

## Local

Belo Horizonte/MG

## Benefícios

- Vale Alimentação ou Refeição;
- Vale Transporte
- Plano de Saúde (co participativo);
- Plano Odontológico;
- Seguro de Vida.

## Requisitos
•	Formação na área de Tecnologia da Informação, preferencialmente em Desenvolvimento de Software;
•	Projetar, desenvolver, testar e acompanhar o ciclo de vida de um projeto de desenvolvimento de software, como:
Sistemas Operacionais
Ferramentas de versionamento e de virtualização
Servidores web e hospedagem
Design de interface
UX 
Web Services
Desenvolvimento e manipulação de APIs
Frameworks de desenvolvimento
Padrões de arquitetura

**Obrigatórios:**
PHP + PSR’s
Design patterns
Symfony, Laravel ou Zend
Git
Composer
MySQL
REST
CSS/HTML/JS
Linux

**Desejáveis:**
Amazon AWS
OAuth2
RabbitMQ
Docker
Redis
AngularJS

## Contratação

CLT Efetivo

## Nossa empresa

A conta.MOBI é uma startup do ramo financeiro que fornece uma Conta Digital, dentre outros serviços, para quem é Microempreendedor Individual (MEI). 

Ao contrário de bancos tradicionais, a conta.MOBI não possui taxa de manutenção e pode ser utilizada gratuitamente.

Oferecendo serviços completos para quem tem um negócio a tocar.

Apesar de ter o objetivo de auxiliar microempresários e microempreendedores individuais (MEIs), essa conta digital pode também ser utilizada por pessoas físicas. 

## Como se candidatar

Por favor envie um email para rh@conta.mobi com seu CV anexado - enviar no assunto: Dev Full Stack

**Comment by vinyguedess** [comment]
Aceita remoto ?

**Comment by rscafi** [comment]
@rhcontamobi Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.
