### ISSUE TITLE
[Remoto] PHP Back-end Developer na JSL

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [phpdevbr/vagas#632]
## Descrição da vaga

Desenvolver softwares e recursos para dispositivos móveis, que podem englobar desde sistemas extranet, intranet até aplicativos, de acordo com as necessidades da empresa.

Atuar no desenvolvimento de aplicativos ou sistemas, programando nativamente ou por meio de outras linguagens. Responsável por todo o projeto de desenvolvimento, desde a análise das necessidades do cliente, planejamento dos recursos do aplicativo, desenvolvimento, implantação de arquitetura, ferramentas e recursos, até a realização e configuração de testes.

## Local

Remoto

## Benefícios

- 100% Home Office

## Requisitos

**Obrigatórios:**
- Domínio técnico com experiência significativa comprovada em PHP
- Arquitetura MVC (CakePHP, Laravel, Zend ou outro)
- Conhecimento de JavaScript, não apenas jQuery
- Conhecimentos sólidos em banco de dados relacionais e não-relacionais (preferencialmente MySQL e MongoDB)
- Intimidade com Git ou outro versionador
- Apache e configuração de servidores (para projetos)
- Raciocínio lógico e capacidade analítica

## Contratação

CLT

## Nossa empresa

Atuando no mercado desde 1956 e com clientes de diversos setores da economia brasileira, a JSL é a empresa com o mais amplo portfólio de serviços logísticos do Brasil, líder no segmento em que atua. Operando em todo o território nacional e mais quatro países do Mercosul, a Companhia presta serviços de alto valor agregado, que vão desde o transporte de cargas até a terceirização total das cadeias logísticas, sempre de forma integrada, flexível, customizada e ágil.

A história da JSL foi construída sob um sólido princípio: entender seus clientes para atendê-los com qualidade e agilidade. A atuação e liderança no mercado brasileiro se deve a capacidade que a JSL têm de planejar, implantar e operar serviços customizados, acompanhando as necessidades dos seus clientes.

## Como se candidatar

Candidate-se através do link: https://bit.ly/3gzsV9A

### Alocação:
- 100% Remoto

### Contratação:
- CLT

### Experiência
- Pleno

**Comment by erandirjunior** [comment]
Olá, faz tempo que me candidatei e não obtive nenhum retorno do processo seletivo, isso é normal?

**Comment by FrancieleGhizzoni** [comment]
Bom dia Erandir,

Ainda estamos avaliando candidaturas para essa vaga, no entanto percebi que
você não respondeu ao questionário da vaga.

Para que possamos dar andamento na análise da sua candidatura, responda em:
https://bit.ly/3gsH08s

Abraço


Franciele Ghizzoni - Tech Recruiter
2020, Coodesh
https://coodesh.com
f.ghizzoni@coodesh.com <http://coodesh.com/>


Em sex., 11 de set. de 2020 às 20:39, Erandir Junior <
notifications@github.com> escreveu:

**Comment by erandirjunior** [comment]
Bom dia @FrancieleGhizzoni, acabei de responder ao formulário.

**Comment by FrancieleGhizzoni** [comment]
Vaga em análise de candidaturas.
