### ISSUE TITLE
[Remoto] PHP Fullstack Developer na Vip Commerce

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [phpdevbr/vagas#633]
## Descrição da vaga

Buscamos uma Pessoa Desenvolvedora Fullstack com maior foco em Back-end PHP. Profissional com perfil de destaque e que possa crescer de maneira acelerada juntamente com a VipCommerce.

## Local

Remoto

## Benefícios

- PJ ou CLT
- Plano Saúde Unimed
- Boa flexibilidade de horários de trabalho
- Subsídio de cursos e eventos em determinadas periodicidades
- Vale alimentação

#### Diferenciais

- 100% Home Office

## Requisitos

**Obrigatórios:**
- Ser engajado com os ideias do negócio, abraçar as causas da empresa e frequentemente ser "confundido com o dono", pelo aspecto do pensamento comprometido.
- Ser engajado em pequenos times, clima de startup e negócios que crescem de maneira acelerada (pouca zona de conforto / Lean Startup)
- Escreva código bem projetado, testável e eficiente
- Habituado em trabalhar com metodologias ágeis / scrum
- Conhecimentos em TDD e BDD
- Saber trabalhar em equipe, em times (participativo, paciente, mediador)
- +2 anos de experiência em posição semelhante
- Essencial trabalhar em ambiente Linux
- Conhecimentos em escrever Unit Tests (PHP Unit)
- Experiência em escrever REST APIs usando PHP Laravel
- Domínio de programação orientada a objetos usando linguagens como PHP ou Typescript

**Diferenciais:**
- Conhecimentos em desenvolvimento front-end usando Angular
- Conhecimentos básicos em Microservices
- Contato com cultura DevOps e CI/CD
- Conhecimentos em Cake PHP

## Contratação

PJ a combinar

## Nossa empresa

A VipCommerce é uma empresa especializada em e-grocery, especificamente e-commerce para supermercados, atacarejos e atacados. Atualmente é Líder no segmento na vertente white-label, integrada e homologada com os maiores ERP´s do segmento. 

## Como se candidatar

Candidate-se através do link: https://bit.ly/31z2o7R

### Alocação:
- Remoto

### Contratação:
- PJ

### Experiência
- Pleno

**Comment by erandirjunior** [comment]
@FrancieleGhizzoni me candidatei a um tempo, porém não obtive nenhum retorno do processo seletivo, isso é normal?

**Comment by FrancieleGhizzoni** [comment]
Vaga em análise de candidaturas.
