### ISSUE TITLE
[Remoto] PHP/Laravel Developer em Plataforma EAD  

### ISSUE THREAD

**Issue by Conchetto** [phpdevbr/vagas#635]
#394  Descrição da vaga

Plataforma EAD em Laravel, etc.

## Local

Remoto ou Escritório, São Paulo/SP - Vila Olímpia

#### Diferenciais

- trabalho 100% remoto
- você faz seu horário, trabalho no seu modo, única referência é os prazos e demandas combinadas juntos

## Requisitos

**Obrigatórios:**
- conhecimentos em Laravel
- conhecimentos sólidos em JS / HTML / CSS

**Diferenciais:**
- interesse por ux ou design

## Contratação

PJ a combinar

## Nossa empresa

Somos uma startup de educação voltada para o público científico e médico.

## Como se candidatar

Por favor envie um email para lconchetto@gmail.com com seu CV anexado - enviar no assunto: Vaga PHP

### Alocação:
- 100% remoto

### Contratação:
- PJ
- Freelance

### Experiência
- Júnior
- Pleno

**Comment by YaakovDantas** [comment]
Como é a remuneração ?
