### ISSUE TITLE
[Belo Horizonte/MG] Analista de Testes na conta.MOBI

### ISSUE THREAD

**Issue by rhcontamobi** [phpdevbr/vagas#64]
## Descrição da vaga

•	Identificar os Itens de Teste-alvo a serem avaliados pelo esforço de teste
•	Definir os testes apropriados necessários e quaisquer Dados de Teste associados
•	Coletar e gerenciar os Dados de Teste
•	Avaliar o resultado de cada ciclo de teste
•	Reportar para a equipe de desenvolvimento os resultados dos testes

## Local

Belo Horizonte/MG

## Benefícios

Vale Alimentação ou Refeição;
Vale Transporte
Plano de Saúde (co participativo);
Plano Odontológico;
Seguro de Vida.

## Requisitos
•	Curso Técnico ou Superior na Área de Tecnologia da Informação
**Obrigatórios:**
•	Possuir experiência na Área de SQA
•	Experiência em testes automatizados e testes unitários
•	Conhecimento de Metodologias Ágeis (SCRUM)
•	Conhecimento de Linux
•	Conhecimento básico de PHP
•	Conhecimento de Banco de Dados (preferencialmente Mysql)
•	Conhecimento de Ambiente de Versionamento Git

## Contratação

CLT Efetiva

## Nossa empresa

A conta.MOBI é uma startup do ramo financeiro que fornece uma Conta Digital, dentre outros serviços, para quem é Microempreendedor Individual (MEI).

Ao contrário de bancos tradicionais, a conta.MOBI não possui taxa de manutenção e pode ser utilizada gratuitamente.

Oferecendo serviços completos para quem tem um negócio a tocar.

Apesar de ter o objetivo de auxiliar microempresários e microempreendedores individuais (MEIs), essa conta digital pode também ser utilizada por pessoas físicas.

## Como se candidatar

Por favor envie um email para rh@conta.mobi com seu CV anexado - enviar no assunto: Analista de Testes

**Comment by devEdipo** [comment]
@rhcontamobi,

Aceitar CV de outro estado?

Atte;

**Comment by rhcontamobi** [comment]
@devEdipo Sim, caso a pessoa tenha disponibilidade de mudança :)

**Comment by devEdipo** [comment]
@rhcontamobi,

CV encaminhado.

**Comment by rscafi** [comment]
@rhcontamobi Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.
