### ISSUE TITLE
[São José dos Campos/SP] Desenvolvedor Full-stack Júnior na Climatempo

### ISSUE THREAD

**Issue by denilsonraimundo** [phpdevbr/vagas#66]
## Descrição da vaga

Vaga para Desenvolvedor Full-stack Júnior na Climatempo (www.climatempo.com.br)

## Local

Parque Tecnológico, São José dos Campos - SP

## Benefícios

- VR e VT
- Home Office após período de experiência;
- Flexibilidade no horário de trabalho para acompanhar eventos de tecnologia;

## Requisitos

**Bons conhecimentos em:**
- HTML
- CSS
- Javascript
- NodeJS
- PHP
- SQL
- NoSQL
- RESTful

## Contratação

CLT

## Como se candidatar

Os interessados deverão fazer o teste pré-entrevista detalhado no link abaixo:
https://github.com/climatempo/challenge-accepted

**Comment by linikerdev** [comment]
Sou analista de sistemas e trabalho no RJ, aceita remoto?

**Comment by HelissonMS** [comment]
Só uma dúvida, na seção "Stacks" está dizendo para utilizar PHP ou Javascript, só entre parenteses está reforçado o NodeJS... É obrigatório o uso do NodeJS ou posso simplesmente fazer uma SPA em VueJs, por exemplo?

**Comment by denilsonraimundo** [comment]
Olá @linikerdev, de inicío não rola, só presencial mesmo. Obrigado pelo contato!

**Comment by lucasapos** [comment]
@denilsonraimundo, achei bem legal as caraterísticas da vaga, existe algum fator geográfico que influência na contratação, estou bem longe geograficamente isso seria algum impedimento? 

Aguardo um retorno.  obrigado!

**Comment by denilsonraimundo** [comment]
Olá @lucasapos, a princípio precisamos de alguém alocado em São José dos Campos, a questão de morar longe não é problema para participar da seleção, mas no momento da contratação preferimos alguém de fácil acesso a São José, ok?

**Comment by RodrigoVieirasjc** [comment]
Olá boa noite, bem eu me encaixo por morar na cidade de São José dos Campos, estou interessado em trabalhar com vocês. Vou mandar meu currículo para vocês analisarem no momento estou parado. Muito obrigado

**Comment by denilsonraimundo** [comment]
Opa, faz um PR no nosso desafio @RodrigoVieirasjc, assim você tem mais chances.

**Comment by rscafi** [comment]
@denilsonraimundo Vaga preenchida?

**Comment by denilsonraimundo** [comment]
Sim @rscafi, fechando a issue... Obrigado pelo espaço!
