### ISSUE TITLE
[São Paulo/SP] Desenvolvedor PHP Sênior na Orfeus

### ISSUE THREAD

**Issue by diogo-arantes** [phpdevbr/vagas#67]
## Descrição da vaga
Backend com experiência e domínio de PHP para o desenvolvimento de um sistema que engloba as funcionalidades de CRM + BI + BIG DATA

## Local
Apenas São Paulo.
Remoto (3 dias/sem) e no escritório (2 dias/sem – prox.Faria Lima)

## Requisitos
**Obrigatórios (O que já temos)**
 PHP (OO)
 MySql
 Linux
 Git
 API
 Vontade, determinação, comprometimento

**Desejáveis (também já usamos)**
Doctrine
Silex
Python
Micro Serviços
AWS

## Contratação
PJ compatível

## Nossa empresa
Procuramos pessoas criativas e determinadas, dispostas a aprender, compartilhar conhecimento, que se interessem por novas tecnologias de programação e tenham mentalidade de Startup

## Como se candidatar
Enviar CV para jobs@orfeus.com.br com assunto Vaga Backend PHP ou chamar no Whatsapp 11 986408282

**Comment by clmadrazo** [comment]
se fosse 100% remoto eu topava

**Comment by rscafi** [comment]
@diogo-arantes Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.
