### ISSUE TITLE
[Remoto]  Pessoa desenvolvedora de software PHP Senior na Talentify.io

### ISSUE THREAD

**Issue by gnumoksha** [phpdevbr/vagas#673]
## A empresa
A Talentify.io nasceu da fusão de 3 empresas distintas em 3 áreas diferentes: Digital Media, Advertising e HR Consulting. Nossa plataforma de SaaS ajuda empresas a superar seus maiores desafios na  busca e contratação de talentos em grande escala.
## A vaga
Estamos constantemente adicionando novas features e aperfeiçoando as já existentes. Como desenvolvedor sênior, você será responsável por criar código limpo, testável e de alta qualidade, além de auxiliar o restante da equipe a migrar código existente para a nova arquitetura orientada a domínio. Somos adeptos do desenvolvimento ágil, integração contínua, code review e testes automatizados. Com isso, nossa equipe busca constantemente desenvolver e aprimorar o produto para estarmos sempre à frente do mercado.

## Obrigatório
- PHP 7
- Desenvolvimento de testes
- Desenvolvimento Agil
- Web Services (RESTful ou SOAP ou JSON-RPC, etc)
- Algum dos frameworks PHP (Phalcon, Zend, Symfony, Laravel)
- Familiaridade com as PHP Standards Recommendations (PSRs)
- GIT
- Banco de dados relacional (MySQL, PostgreSQL, etc)
## Desejável
- Arquitetura hexagonal
- DDD
- Microserviços
- Filas de mensagens (RabbitMQ, Apache Kafka, Amazon SQS, etc)
- Elasticsearch
- Linux
- Amazon Web Services (AWS)
- CI/CD
- Ingles (leitura, escrita e conversacao)  

## Remuneração
- R$8000 - R$10000

## Como se candidatar
[Aqui](https://talentify-brasil.talentify.io/job/desenvolvedor-php-sr-barueri-sp-talentify--3?utm_source=gnumoksha)

### Alocação:
- Remoto
- Presencial

### Contratação:
- CLT
- PJ

**Comment by gnumoksha** [comment]
@ravanscafi coloca remoto e CTL, por favor. Ha tags para salario?

**Comment by ravanscafi** [comment]
@gnumoksha não, não temos. coloquei as tags (tinha usado de referência o que você deixou ali no final do issue)

**Comment by francysreymer** [comment]
O link nao funciona mais, a vaga ainda esta aberta?

**Comment by ravanscafi** [comment]
ping @gnumoksha

**Comment by gnumoksha** [comment]
> O link nao funciona mais, a vaga ainda esta aberta?

Temos vagas. Voce pode submeter o teste em https://github.com/Talentify/backend-careers e enviar um email para tobias.ferreira@talentify.io
