### ISSUE TITLE
[São Paulo/SP] Desenvolvedor PHP CodeIgniter + MySQL (Pleno/Sênior) na NerdMonster

### ISSUE THREAD

**Issue by nerdmonsterdigitalretail** [phpdevbr/vagas#68]
## Descrição da vaga
O time de desenvolvimento da NerdMonster está procurando um programador full-stack (ou um programador focado em backend) apaixonado por desafios envolvendo programação.

Nós somos uma empresa com uma missão bastante clara: Empoderar varejistas pequenos, médios e grandes redes a terem o controle de sua reputação digital e centralizar seu marketing digital em um único lugar.

Buscamos ativamente desenvolvedores capazes, motivados a procura de novos desafios através da programação.

## Local
Pinheiros - São Paulo (ao lado do metrô Pinheiros)

## Requisitos

**Obrigatórios:**
- Experiência com PHP especialmente com o Framework CodeIgniter;
- Ter trabalhado no desenvolvimento de sistemas web e websites - experiências em outras startups seria um diferencial;
- Ter conhecimentos de front-end (HTML, JavaScript e jQuery);
- Banco de dados MySQL;
- GIT;
- Linux e Apache (pode ser básico).

**Desejáveis:**
- Experiência com AWS;
- Conhecimento da estrutura de servidores e processos de Deploy (DevOps);
- Conhecimento em APIs sociais (Facebook e Google);
- Conhecimento em APIs de Ads (Facebook Ads e/ou Google AdWords).

**Diferenciais:**
- Proatividade para resolução de problemas;
- Espírito de equipe.

## Contratação
Freelancer alocado para projeto com escopo fechado.

## Como se candidatar
- Por favor envie um email para contact@nerdmonster.com com seu CV ou Portfólio.
- Enviar no assunto: Desenvolvedor PHP CodeIgniter + MySQL - SP.

**Comment by clmadrazo** [comment]
poderia ser remoto?

**Comment by nerdmonsterdigitalretail** [comment]
Olá, tudo bem? Nesse primeiro momento seria apenas alocado mesmo. =)

**Comment by vinyguedess** [comment]
Se for possível remoto 2 dias na semana eu quero participar.

**Comment by nerdmonsterdigitalretail** [comment]
Oi Viny, tudo bem? Podemos negociar sobre isso... Poderia nos mandar um e-mail com suas informações para falarmos mais? Abraços!

**Comment by vinyguedess** [comment]
Mandei @nerdmonsterdigitalretail

**Comment by rscafi** [comment]
@nerdmonsterdigitalretail Vaga preenchida?

**Comment by nerdmonsterdigitalretail** [comment]
Olá! Ainda não, vamos conversar?

Em 12 de jan de 2018 19:56, "Ravan Scafi" <notifications@github.com>
escreveu:

@nerdmonsterdigitalretail <https://github.com/nerdmonsterdigitalretail>
Vaga preenchida?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/phpdevbr/vagas/issues/68#issuecomment-357365586>, or mute
the thread

**Comment by ravanscafi** [comment]
Olá @nerdmonsterdigitalretail,
A vaga ainda está aberta?

_(sou administrador das vagas e estou fechando as que já foram preenchidas)_

**Comment by nerdmonsterdigitalretail** [comment]
Oi Ravan, tudo bem?

Obrigado por perguntar. Acabamos fechando a vaga por uma indicação.Pode fechar a vaga sim. 

Abs!
