### ISSUE TITLE
[Santo André/SP] Desenvolvedor PHP / Laravel na DIN DIGITAL

### ISSUE THREAD

**Issue by mariosmello** [phpdevbr/vagas#69]
## Descrição da vaga

Desenvolvedor PHP para integração e manutenção de sites e sistemas web. Geralmente utilizando o framework Laravel. 

## Local
Escritório: R. Lúcio Veiga, 53 - Sala 02 - Centro, Santo André - SP

https://goo.gl/maps/deVy5xCMtZG2

## Benefícios

- Vale transporte
- Vale refeição
- Convênio médico AMIL (50%)
- Convênio odontológico AMIL (50%)
- Frigobar, comida, café
- Horário flexível
- Possibilidade de 1 dia na semana como home office

## Requisitos

**Obrigatórios:**
- PHP - OO
- PHP - Procedural
- Laravel Framework
- Experiência em integração de websites
- Experiência em construções de API's REST
- Integração com API's e SDKS externas
- Git
- Composer
- Vagrant

**Desejáveis:**
- Javascript Básico
- Teste de Unidade / Integração
- Noções de estruturação e configuração de servidores

**Diferenciais:**
- NodeJS

## Contratação

CLT

## Como se candidatar

Realizando teste disponível em: https://github.com/dindigital/test-back-2017

**Comment by rscafi** [comment]
@mariosmello Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.
