### ISSUE TITLE
[Belo Horizonte] Desenvolvedor Backend Sênior/Pleno

### ISSUE THREAD

**Issue by naroga** [phpdevbr/vagas#7]
## Descrição da vaga

Como membro da equipe de Produto, você será responsável pela elaboração de novas ferramentas, manutenção das ferramentas existentes e pela tomada de decisões relacionadas à arquitetura das aplicações e dos microsserviços que compõem o ecossistema da Sympla.

## Funções desta posição:

* Contribuir com as decisões de arquitetura da nossa aplicação, buscando uma arquitetura flexível e moderna que acompanhe o crescimento constante;
* Ajudar a manter um “espírito” ágil;
* Ter orgulho de colocar em produção um código que é usado por milhões de pessoas Brasil afora. Para isso, qualidade deverá ser sua obsessão;
* Monitorar o desempenho dos serviços que compõem o ecossistema da Sympla, para identificar gargalos de desempenho e problemas de performance em geral, assegurando a continuidade das operações e a melhor experiência para o usuário;

## Local

Presencial, R. Fernandes Tourinho, 147, Savassi, Belo Horizonte

## Benefícios
* Ambiente criativo, inovador e estimulante;
* Regime de contratação CLT;
* Salário compatível com o mercado;
* Vale transporte (ônibus ou gasolina);
* Vale refeição ou Vale-alimentação;
* No dress code (pode trabalhar de bermuda, chinelo, etc);
* Clima descontraído;
* Café, bebidas variadas e snacks;
* Horário Flexível;
* Plano de saúde e odontológico, desconto em farmácias;

## Requisitos

**Obrigatórios:**
* Excelente conhecimento de pelo menos uma linguagem de programação de alto nível: PHP, Python ou outras. Acreditamos que bons desenvolvedores conseguem ser produtivos em qualquer tecnologia ;)
* Capacidade de priorizar o seu próprio trabalho a partir das linhas gerais definidas pela equipe e de feedbacks recebidos dos usuários finais;
* Ser flexível, independente e responsável;
* Ser curioso, com muita vontade de experimentar e aprender coisas novas;
* Ter senso de organização, atenção a detalhes e foco;
* Conhecer os conceitos de startup;
* Must rock!

**Desejáveis:**
* Vivência em aplicações que recebam quantidade massivas de acessos simultâneos;
* Conhecimento em sistemas distribuídos;
* Conhecimento em banco de dados relacional;
* Experiência em desenvolvimento de APIs Restful.
* Inglês e/ou espanhol intermediário.

## Contratação

CLT, salário a combinar.

## Nossa empresa

A Sympla é uma startup sediada em Belo Horizonte que, em menos de três anos de existência, se tornou a plataforma de eventos mais utilizada no Brasil e possui o site com o maior número de eventos à venda no país. 

Com o objetivo de simplificar e otimizar a criação e gestão de eventos para produtores e melhorar a experiência da compra de ingressos online pelos participantes, oferecemos diversas ferramentas eficazes e soluções inteligentes para todas as etapas de um evento. Aqui, você poderá participar da expansão de uma startup jovem e que já é referência no mercado online ticketing no país. 

Encara o desafio?

## Como se candidatar

Envie seu currículo pelo nosso link 'trabalhe conosco': http://www.sympla.com.br/trabalhe-conosco#job-9501

![Our team](http://d1gkntzr8mxq7s.cloudfront.net/57b5d36738797.png)

**Comment by ByTecno** [comment]
Enviado!

**Comment by nic** [comment]
@naroga Vaga preenchida?
