### ISSUE TITLE
[Remoto] PHP/Laravel Developer trabalhando em horário flexível na Jurisbot.com.br

### ISSUE THREAD

**Issue by esg877** [phpdevbr/vagas#703]
## Descrição da vaga

Somos uma startup de legaltech, que está crescendo e precisamos de colaboradores. Pessoas honestas, engajadas e que talvez estejam cansadas das babaquices do mundo corporativo, de prazos e expectativas irreais, ou simplesmente querendo crescer e apostar em si mesmo. O volume de trabalho será definido pelo Dev, que poderá aceitar ou recusar as demandas caso a caso. Vaga compatível com outros trabalhos e até com emprego CLT.

Somos um time pequeno, coeso e prezamos pela qualidade de vida de nossos colaboradores. 

## Local

Remoto - Horário flexível. Somos focados em entregas e não em chatear nossos colaboradores.

## Benefícios

De início, não queremos oferecer um emprego CLT para depois mandar a pessoa embora em 90 dias, como muitas empresas "espertas" fazem. Somos transparentes e honestos, e prezamos demais por essas qualidades. A vaga é para freelancer, e como toda startup, a chance de crescer e ter ganhos enormes é o principal atrativo. Eventualmente, pode evoluir para um contrato de trabalho, ou mesmo uma oferta de sociedade. 

#### Diferenciais

O dev trabalhará auxiliado por um CTO MUITO experiente (e MUITO gente boa), de modo que terá oportunidade de aprender e crescer profissionalmente (e ensinar também, estamos sempre aprendendo!). 

"Ambiente" (remoto) de trabalho com muito respeito, valorizamos o tempo com a família e acreditamos em construir uma empresa com base em valores humanos, e não apenas técnicos.

## Requisitos

**Obrigatórios:**
- Boa experiência com PHP + Laravel
- Boa experiência com bancos de dados relacionais

**Desejáveis:**
- Conhecimentos em Elastic Search ou vontade de aprender.
- Conhecimentos da infra AWS

# Contratação

PJ a combinar

## Nossa empresa

Somos uma startup jurídica sediada no Rio de Janeiro. 
Conheça nosso trabalho em jurisbot.com.br, e veja se nosso trabalho tem ressonância com seus interesses.

## Como se candidatar

Por favor envie um email para sac@jurisbot.com.br com seu CV anexado - enviar no assunto: Vaga PHP
Alternativamente, pode nos contatar pelo Instagram ou Facebook (busque por Jurisbot).

Remuneração compatível com a senioridade do Dev. 
Oferecemos contrato justo, sem multas nem amarras, nem clausulas-pegadinha. 
Queremos pessoas que QUEIRAM estar conosco. 
Profissionais de excelência e ética têm GRANDES chances de virarem sócios. Mande seu CV e converse conosco.

### Alocação:
- Remota

### Contratação:
- PJ
- Freelance

### Experiência
- Pleno
- Sênior
- Especialista

**Comment by Devitibeck** [comment]
Bom dia! Está dando e-mail não encontrado

Em seg., 9 de nov. de 2020 às 17:15, esg877 <notifications@github.com>
escreveu:

**Comment by esg877** [comment]
Prezados,
aparentemente este email era usado por meio de um catch all que foi desativado. Estamos resolvendo. Neste ínterim, favor usar o email sac@jurisbot.com.br ou ed0877@gmail.com. Ou então através de Facebook ou Instagram. Obrigado e desculpem o inconveniente.
Att.,
ESG

**Comment by esg877** [comment]
Ola Patrick,
pois é estamos com esse problema desde ontem. Você deseja enviar CV? Pode
mandar por aqui. Vou editar a vaga para mudar este email ate que se resolva
o problema. Desculpe pelo inconveniente.
Att.,
Edoardo


Em ter., 10 de nov. de 2020 às 10:48, Patrick Barbosa <
notifications@github.com> escreveu:

**Comment by viniciusdevlacerda** [comment]
Em ter., 10 de nov. de 2020 às 11:56, esg877 <notifications@github.com>
escreveu:
