### ISSUE TITLE
[São Paulo/SP] Desenvolvedor PHP (Laravel) na ColdVector

### ISSUE THREAD

**Issue by leoallvess** [phpdevbr/vagas#72]
## Descrição da vaga

Procuramos um Desenvolvedor PHP (Pleno/Senior) com vontade de aprender e ensinar, disposto a vestir a camisa e crescer conosco. Estamos modelando nossos processos, então sua experiência será importante para nós. 

### Principais funções
- Ajudar no desenho, documentação e desenvolvimento de sistemas;
- Manutenção em sistemas legados;
- Manutenção em sites;

## Local

Presencial na Av. Paulista, próximo ao metrô Consolação, São Paulo.

## Benefícios

- Vale Alimentação
- Vale Transporte
- Convênio Médico

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com PHP 5+
- Experiência com Laravel 5+
- Controle de versão com GIT
- Vagrant
- MySQL
- Comprometimento

**Desejáveis:**
- Experiência em plataformas open source (Wordpress e Magento)
- Experiência em integrações com APIs
- AWS
- NPM

**Diferenciais:**
- Estrutura de servidores e processos de Deploy
- Proatividade para resolução de problemas;

## Contratação

a combinar

## Nossa empresa

Passamos  recentemente por um reposicionamento, voltando às origens, deixando de ser uma agência digital para voltar a ser uma software house. Desta forma, podemos dizer que somos uma (micro) empresa nova, mas com muita vontade de crescer e em busca de pessoas com esta mesma mentalidade.

## Como se candidatar

Por favor envie um email para leonardoalves@coldvector.com com seu CV anexado e pretensão salarial - enviar no assunto: Vaga PHP

**Comment by leoallvess** [comment]
Obrigado pelos ajustes Ravan!

**Comment by rscafi** [comment]
@leoallvess Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.
