### ISSUE TITLE
[Lavras/MG] Desenvolvedor PHP na Technolog

### ISSUE THREAD

**Issue by giovanireis1** [phpdevbr/vagas#74]
Vaga aberta para Desenvolvedor PHP com desejável conhecimento nas linguagens PHP, Javascript, Jquery e, preferencialmente com conhecimento em linguagem SQL. 

Local: 
Lavras-MG

Benefícios:
- Plano de Saúde
- Vale Alimentação

Requisitos:
- 2 anos de experiência com PHP 5+

Desejáveis:
- conhecimentos em javascript, jquery, boopstrap e linguagem sql para SQL Server

Contratação
- Regime CLT

 Como se candidatar

Por favor envie um email para talentos@technolog.com.br com seu CV anexado - enviar no assunto: Vaga PHP

**Comment by rscafi** [comment]
@giovanireis1 Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.
