### ISSUE TITLE
[REMOTO] [Bauru] Programador PHP Pleno/Senior - FullStack na UP OutSourcing

### ISSUE THREAD

**Issue by giovanarezende** [phpdevbr/vagas#741]
## Descrição da vaga

Esta oportunidade tem como objetivo a construção de recursos que envolvem tecnologias de back-end (servidores, banco de dados, modelagem e programação) com front-end (interface).

Responsabilidades:
- Colaborar com o time de desenvolvimento
- Reportar diariamente o andamento das atividades
- Ser pró-ativo colaborando para a resolução de problemas do time
- Trabalhar respeitando os processos ágeis de desenvolvimento

## Local

Remoto 

## Benefícios

- Modalidade PJ
- Aulas de Inglês avançado para Empresas
- 10 dias pagos de férias
- Horário flexivível (respeitando eventuais reuniões com base no fuso da Europa)
- Home Office
- Escritório em Bauru / SP com estrutura de suporte completa
- PLR Mensal
- Cursos e Certificações
- Webinars e ajuda de profissional para Saúde Mental
- Folga em dias específicos previamente planejado

## Requisitos

**Obrigatórios:**
- 3 anos de experiência ou mais
- Inglês Intermediário - não exige fala mas é um diferencial
- Experiência com Banco de Dados MySql / similar
- Experiência básica em Javascript
- Experiência com Symfony ou Laravel
- Conhecimentos com API / REST / XML

## Contratação

PJ 

## Nossa empresa

UP Outsourcing é uma empresa localizada em Bauru, no interior de São Paulo, a 326 km da capital com uma média de 379.000 habitantes.

Nós oferecemos oportunidades para desenvolvedores Web, baseado em Princípios de Desenvolvimento Ágil. Também auxiliamos Startups com Protótipos usando os Princípios de Inovação para a necessidade do cliente.

## Como se candidatar

Envie seu currículo para:  rh@upoutsourcing.com

### Alocação:
- Remoto

### Contratação:
- PJ

### Experiência
- Pleno
- Sênior

**Comment by devLopez** [comment]
Olá @giovanarezende, qual o valor pago? Ou é a combinar?

**Comment by giovanarezende** [comment]
@devLopez Olá, Matheus. O valor está à combinar, pois depende do nível e tempo de experiência.

**Comment by giovanarezende** [comment]
@ravanscafi esta vaga já foi fechada! Como faço para excluir?
