### ISSUE TITLE
[São Paulo/SP] Desenvolvedor PHP pela PSM Company

### ISSUE THREAD

**Issue by fwfreitas** [phpdevbr/vagas#75]
## Descrição da vaga

Desenvolvedor PHP

## Local

Escritório, São Paulo - Vila Leopoldina 

## Benefícios

- Vale refeição
- Vale transporte 
- Assistência médica
- Assistência odontológica 
- Seguro de vida 

## Requisitos

**Obrigatórios:**
- Experiência com PHP

**Desejáveis:**
- conhecimentos em desenvolvimento web 

**Diferenciais:**
- Angularjs 
- Nodejs

## Contratação

CLT

## Nossa empresa

Em seu 10º ano de atuação, a PSM Company é referência de mercado nos serviços especializados de Recrutamento e Seleção, Terceirização de Mão de Obra e Gestão de Pessoas.

A nossa história de sucesso, esta baseada em nosso modelo de negócios que proporcionam assertividade e qualidade no processo seletivo, baixo Turn Over e isenção de riscos e passivos trabalhistas.

Somos especializados na identificação de Talentos para as áreas de TI / Telecom como também para as áreas operacionais e administrativas.

## Como se candidatar

Por favor envie um email para vanessa.almeida@psmcompany.com.br com seu CV anexado - enviar no assunto: Desevolvedor PHP

**Comment by rscafi** [comment]
@fwfreitas Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.
