### ISSUE TITLE
BLUMENAU - DESENVOLVEDOR PHP - DATA FRETE

### ISSUE THREAD

**Issue by gabrielanatascha** [phpdevbr/vagas#756]
Oportunidade para Desenvolvedor PHP Pleno - Atuação 100% presencial. 

Requisitos: PHP, GIT, HTML5, MySQL, Javascript.

Desejáveis: AWS, CSS3 e GO. 

Benefícios: vale alimentação, vale transporte, plano odontológico e outros convênios. 

Interessados deverão encaminhar currículo para: escolhacertarh19@gmail.com com o título da vaga.

**Comment by pablo-moraes** [comment]
Nenhuma forma de contato ou algo assim?

**Comment by leandro47** [comment]
como faz pra se candidatar? não vejo mais informações

**Comment by afzardo1** [comment]
Onde envio o currículo

**Comment by gabrielanatascha** [comment]
> Acho que faltou a forma de candidatura.
> Se as pessoas não tiverem como entrar em contato para enviar currículo ou algo assim, como elas vão se candidatar a sua vaga?

**Comment by gabrielanatascha** [comment]
> Onde envio o currículo

Bom dia, pode encaminhar para escolhacertarh19@gmail.com :)

**Comment by gabrielanatascha** [comment]
> como faz pra se candidatar? não vejo mais informações

Bom dia, pode encaminhar para escolhacertarh19@gmail.com :)

**Comment by gabrielanatascha** [comment]
> como faz pra se candidatar? não vejo mais informações

Bom dia, pode encaminhar para escolhacertarh19@gmail.com :)

**Comment by gabrielanatascha** [comment]
> Acho que faltou a forma de candidatura.
> Se as pessoas não tiverem como entrar em contato para enviar currículo ou algo assim, como elas vão se candidatar a sua vaga?

Oi Pablo, desculpe. Já inclui ali acima. Eu sou nova na plataforma. Obrigada

**Comment by gabrielanatascha** [comment]
Oi Pablo, tudo bem?

A empresa está aberta para contratações CLT ou PJ, mas de qualquer forma,
precisará estar presencial em período integral.

Atenciosamente,

Gabriela - Escolha Certa RH

Em sáb., 9 de jan. de 2021 às 21:37, Pablo Moraes <notifications@github.com>
escreveu:

**Comment by gabrielanatascha** [comment]
Olá Leandro, como vai?

Podes encaminhar seu currículo para escolhacertarh19@gmail.com

Obrigada

Em seg., 11 de jan. de 2021 às 00:30, LEANDRO DA SILVA <
notifications@github.com> escreveu:

**Comment by gabrielanatascha** [comment]
Olá Alexandre, como vai?

Podes encaminhar seu currículo para escolhacertarh19@gmail.com

Obrigada

Em seg., 11 de jan. de 2021 às 08:26, Alexandre Farinelli Zardo <
notifications@github.com> escreveu:
