### ISSUE TITLE
[Remoto] PHP/Laravel Developer Pleno na Influu

### ISSUE THREAD

**Issue by influu** [phpdevbr/vagas#758]
## Descrição da vaga
Desenvolvedor Laravel+Vue+AdminLTE.

## Nossa empresa
Somos uma agência com foco no mercado de influenciadores.

## Local
Remoto

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento de aplicações complexas com PHP/LARAVEL;
- Experiência em testes
- Experiência com Banco de Dados MySql/MariaBD
- Conhecimentos com API REST
- Versionamento de código utilizando GIT
- Confortável em trabalhar 100% remoto

## Contratação
PJ

## Como se candidatar
Por favor envie um email para contato@influu.me com seu CV ou Link Git- enviar no assunto: [VAGA_Laravel] + Nome + Sobrenome

## Labels
- PJ
- Pleno
- Remoto
- Sênior

**Comment by influu** [comment]
> Fullstack?

Sim.. vc pode me enviar um email?

**Comment by Devitibeck** [comment]
Eu entendo como todas as peças se conectam (front-end, back-end, database,
camadas de rede, etc). Sou deve back end não atuo no front.

Em sex, 22 de jan de 2021 07:09, Influu <notifications@github.com> escreveu:
