### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) PHP / Laravel na Plugg.to

### ISSUE THREAD

**Issue by reginaldojunior** [phpdevbr/vagas#76]
## Descrição da vaga

Você é fera em Laravel e sabe realizar comunicação entre APIs? Temos uma vaga para você!

Quer trabalhar em uma empresa onde não será apenas mais um funcionário?

Trabalhe em uma startup, que não para de crescer e que irá te oferecer tudo que precisa para que alcance todo seu potencial, em um ambiente informal, onde você terá sempre oportunidade de aprender coisas novas e fazer a diferença.

Horário de trabalho flexível, possibilidade de trabalhar remotamente 1 dia da semana, aprendizado continuo em novas tecnologias são apenas alguns dos benefícios.

Candidata-se agora! 

## Local

Escritório a 5 min do Metrô Barra Funda - SP

## Benefícios

 - Vale-transporte
 - Vale-refeição
 - Férias remuneradas
 - Possibilidade de Home Office 1 dia por semana

## Requisitos

**Obrigatórios:**
	
- Sólidos conhecimentos em PHP
- Sólidos conhecimentos com framework Laravel
- Sólidos conhecimentos em MySQL
- Sólidos conhecimentos em APIs RESTFul
- Conhecimentos em GIT
- Conhecimentos em HTML, CSS, JavaScript

**Desejáveis:**
	
- Conhecimentos em Bootstrap, Vue.js, Datatables
- Conhecimentos em MongoDB
- Conhecimentos em Linux/Debian
- Conhecimentos em Node.js
- Conhecimentos em SOAP
- Configuração/Tuning Apache
- Conhecimento nos CMS, WordPress, Magento, Opencart, PrestaShop

## Contratação

PJ ou CLT a combinar

## Nossa empresa

Plugg.To é um hub de integração de e-commerce que possibilita integrações rápidas e inteligentes entre plataformas de lojas virtuais, ERPs, Fornecedores e Marketplaces.

Com isso é possível vender muito mais utilizando múltiplos canais de venda, mantendo porém estoques sincronizados, e recebimento e gerenciamento de pedidos em um único ponto.

Diversas ferramentas de automações são oferecidos pelas integrações para possibilitar que tarefas repetidas em um Marketplace específico sejam realizadas sem interferência manual.

A empresa, fundada no início 2013 recebeu investimento da Wayra e do Fundo de investimento MercadoLivre no início de 2015 e desde então não para de crescer.

## Como se candidatar

Por favor envie um email para reginaldo.junior@plugg.to com seu CV anexado - enviar no assunto:  #SP Desenvolvedor(a) PHP / Laravel 

## OBS

Vagas para pleno e sênior.

**Comment by marcelosousa46** [comment]
Pode ser 100% remoto?


Marcelo Sousa
(85) 98502-3111

Em 6 de outubro de 2017 11:23, Reginaldo Junior <notifications@github.com>
escreveu:

**Comment by reginaldojunior** [comment]
@marcelosousa46 não, no momento estamos com um dia remoto só.

**Comment by reginaldojunior** [comment]
Vaga preenchida! ❤️ 😄
