### ISSUE TITLE
Vaga Programador com Experiência em Vídeos - "Ffmpeg"  - Home Office 

### ISSUE THREAD

**Issue by cristianpazdasilva** [phpdevbr/vagas#767]
Vaga com para programador com Experiência em Vídeos ""Ffmpeg". Interessados, enviar o questionário abaixo respondido para
webprogramdesen@gmail.com

Pretensão salarial:
Descrever experiência (Quantos anos) em desenvolvimento, listar projetos envolvidos:
Disponibilidade de horas por dia (em quais horários e dias:
Qual a experiência com trabalho remoto, home office:
Motivo do desligamento do último trabalho:

**Comment by Devitibeck** [comment]
WTF?

Em qui., 21 de jan. de 2021 às 13:10, cristianpazdasilva <
notifications@github.com> escreveu:

**Comment by ravanscafi** [comment]
Olá @cristianpazdasilva, esse repositório é somente para vagas **PHP** e por esse motivo a mesma vaga será fechada, favor procure outros repositórios adequados para postar essa vaga.
