### ISSUE TITLE
[Remoto] Web Developer Full-Stack na Planne

### ISSUE THREAD

**Issue by Jesm** [phpdevbr/vagas#771]
## Sobre a Planne

Venha trabalhar em uma empresa de rápido crescimento e que impacta milhares de consumidores em todo o Brasil. A Planne oferece uma solução SaaS para que Pequenas e Médias empresas do setor de serviços e turismo possam vender online com segurança e flexibilidade. Aqui você irá influenciar decisões importantes no desenvolvimento de um roadmap cheio de desafios, em uma empresa que tem a tecnologia na sua essência.

## Descrição da vaga

Procuramos desenvolvedores para nos auxiliar na expansão da nossa plataforma web de reservas. Como estamos em um momento de evolução do nosso stack, as responsabilidades incluem não só a manutenção da base de código atual, como o aprimoramento da plataforma para novas tecnologias.

Buscamos pessoas dispostas a trabalhar com autonomia na arquitetura e desenvolvimento de novas funcionalidades, sempre visando boas práticas para garantir a manutenibilidade, escalabilidade e performance da aplicação.

A carga horária é composta de 40 horas semanais, com flexibilidade de horário.

## Local

100% remoto. 

## Requisitos

- Experiência com desenvolvimento Web;
- Conhecimentos de HTML, CSS e JavaScript;
- Experiência com bancos relacionais (MySQL, PostgreSQL, ...);
- Git;
- Conhecimentos de metodologias ágeis.

## Diferenciais

- Experiência com PHP/Laravel;
- Conhecimentos em Go;
- Experiência com algum framework Front-end (React, Vue.js, Angular, ...);
- Noções de AWS;
- Virtualização e containers (Docker);
- Experiência com APIs REST.

## Regime

PJ ou CLT, a combinar.

## Salário

A combinar, de acordo com experiência prévia e pretensão.

## Como se candidatar

Envie seu currículo para o email jobs@planne.com.br, com o assunto "Vaga Pessoa desenvolvedora Web Full-Stack". Se possível, inclua portfólio e/ou perfil no GitHub.

## Tempo médio de feedbacks

Até 4 dias após processo seletivo.

### Alocação

- Remoto

### Regime

- PJ
- CLT

### Nível

- Pleno

**Comment by Jesm** [comment]
Continuamos com a vaga em aberto!

**Comment by Piulres** [comment]
renanemigdio.com , vamos conversar?
:)

**Comment by Jesm** [comment]
@Piulres entrei em contato via email!

**Comment by Jesm** [comment]
Vaga preenchida.
