### ISSUE TITLE
[Campinas/SP] Webdesigner / Desenvolvedor(a) PHP / Wordpress na e.Mix

### ISSUE THREAD

**Issue by diego-emix** [phpdevbr/vagas#78]
## Descrição da vaga

Instalação e configuração do WordPress, Plugins de segurança, personalização de temas responsivos. Criação layouts funcionais e responsivos, design gráfico, criação de artes, imagens e infográficos.

## Local

Escritório, Centro de Campinas/SP

## Benefícios

- Vale Transporte
- Convênio Médico - Sulamerica Saúde
- Café da Manhã todos os dias
- Frutas a tarde todos os dias :)
- Folga para o aniversariante, no mês de aniversário
- Ambiente descontraído e criativo

## Requisitos

**Obrigatórios:**
- PHP
- Wordpress
- MySQL
- CSS
- JavaScript

**Desejáveis:**
- Photoshop avançado
- Corel Draw
- Criação de artes gráficas
- SEO
- Fullstack

**Diferenciais:**
- JavaScript avançado
- Marketing Digital

## Contratação

CLT

## Nossa empresa

A e.Mix tem mais de 19 anos no mercado de desenvolvimento web, principalmente em softwares para empresas do comércio exterior. 

## Como se candidatar

Interessados encaminhar currículo com pretensão salarial para rh@emixbrasil.com.br colocando no assunto: “Web Designer”

**Comment by rscafi** [comment]
@diego-emix Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.
