### ISSUE TITLE
[Remota] Back-end Developer PHP Pleno/Senior na UP Outsourcing

### ISSUE THREAD

**Issue by giovanarezende** [phpdevbr/vagas#780]
## Descrição da vaga

A UP Outsourcing está com uma oportunidade de Programador PHP Backend Pleno/Senior para atuar com a construção de recursos que envolvem tecnologias de back-end (servidores, banco de dados, modelagem e programação) para um cliente norte-americano da UP.

## Local

Remoto 

## Benefícios

- Modalidade PJ
- Aulas de Inglês avançado para Empresas
- 10 dias pagos de férias
- Horário flexível (respeitando eventuais reuniões com base no fuso da Europa)
- Home Office
- Escritório em Bauru/SP com estrutura de suporte completa
- PLR Mensal
- Cursos e Certificações
- Webinars e ajuda de profissional para Saúde Mental
- Folga em dias específicos previamente planejado

## Requisitos

**Obrigatórios:**
- Inglês intermediário
- Experiência sólida com PHP
- Experiência com Banco de Dados MySQL
- Conhecimentos em Javascript / jQuery
- Conhecimentos com API / REST / XML / SOAP

**Diferenciais:**
- Boa conversação no inglês
- Mais de 6 anos de experiência com PHP

## Contratação

PJ 

## Nossa empresa

A UP é uma empresa de OutSourcing, Consultoria e Startup, responsável pelo desenvolvimento de sistemas web.

Fornecemos oportunidades para desenvolvedores Web baseado em Princípios de Desenvolvimento Ágil e também auxiliamos Startups em Protótipos usando Princípios de Inovação para a necessidade do cliente.

Se você é curioso(a), colaborativo(a) e busca por inovação, dinamismo e propósito, venha fazer parte do nosso time!

## Como se candidatar

Se interessou? Corra e mande o seu currículo para rh@upoutsourcing.com

### Alocação:
- Remoto

### Contratação:
- PJ

### Experiência
- Pleno
- Sênior

**Comment by ravanscafi** [comment]
@giovanarezende existem várias vagas abertas que você postou. todas são diferentes, ou existem duplicadas? pode por favor fechar as que não se aplicam/estão duplicadas?

**Comment by giovanarezende** [comment]
@ravanscafi as vagas são diferentes. Revisarei as vagas publicadas, talvez você tenha visto alguma que postamos em janeiro, aquelas foram fechadas nessa semana.
