### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) PHP Backend Pleno/Sênior na eConciliador

### ISSUE THREAD

**Issue by dextervip** [phpdevbr/vagas#79]
## Nossa empresa

Somos uma startup com 4 anos de operação e em forte expansão. Proprietária do maior plataforma de conciliação judicial e extrajudicial via web do país, contando em seu portfólio com empresas líderes nos segmentos bancário, aviação, e-commerce, telecom, entre outras. Estamos ampliando a nossa equipe de desenvolvimento e temos uma forte projeção de crescimento para este ano. Estamos adotando tecnologias e ferramentas modernas em nosso ambiente de desenvolvimento, o que proporciona um ambiente favorável para se manter atualizado e em aprendizado contínuo.

## Principais funções

- Modelar, documentar e desenvolver novos recursos para o sistema;
- Manutenção nos sistemas incluindo legados;

## Obrigatórios
- Experiência em PHP >= 4 anos
- Orientação a Objetos
- Princípios de S.O.L.I.D
- Noções de Design Patterns
- Experiência em frameworks, preferível Symofny/Laravel
- Git

## Desejáveis
- Testes unitários 
- Implementação/Integração de APIs 
- Docker
- AWS (ECS, RDS e SQS)

## Diferenciais
- Conhecimentos em processos de integração contínua e deploy
- Sistemas escaláveis de filas e mensagens 
- Noções de arquitetura de infraestrutura escalável e microservices 

## Local
- Berrini (São Paulo)

## Contratação
- Regime CLT ou PJ Presencial

## Como se candidatar

Enviar um email para vagas@econciliador.com.br com seu CV anexado e pretenção salarial/regime.

**Comment by valniria** [comment]
Pode ser Remoto?

**Comment by rscafi** [comment]
@dextervip Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.
