### ISSUE TITLE
[Bauru, SP] Desenvolvedor PHP | Triata

### ISSUE THREAD

**Issue by mauraodev** [phpdevbr/vagas#8]
## Descrição da vaga

Procuramos um desenvolvedor PHP para trabalhar com novos projetos e alguns já existentes.
## Local

Bauru, SP
## Benefícios
- Ambiente descontraído, informal e dinâmico
- Plano de saúde
- Plano odontologico
## Requisitos

**Obrigatórios:**
- Conhecimento em frameworks PHP
- Conhecimentos em Git
- Boas práticas de desenvolvimento
- Conhecimento em banco de dados
- Facilidade para trabalhar em equipe
- Inglês técnico

**Desejáveis:**
- Conhecimento em Zend 
- Conhecimento em Code Igniter
- Conhecimento em Javascript e CSS

**Diferenciais:**
- Perfil ativo no GitHub e StackOverflow
## Contratação

CLT
## Nossa empresa

A Triata existe para prover soluções estratégicas em comunicação e marketing virtual, gestão de processos e projetos web, por meio da excelência no pensar e fazer, equipe entusiasmada, tecnologia criativa e alianças construtivas
## Como se candidatar

http://www.triata.com.br/site/pt/curriculosimples

**Comment by nic** [comment]
@mauraodev Vaga preenchida?

**Comment by mauraodev** [comment]
@nic foi preenchida
