### ISSUE TITLE
[Nova Lima/MG] Engenheiro(a) de Software na conta.MOBI

### ISSUE THREAD

**Issue by rhcontamobi** [phpdevbr/vagas#81]
## Descrição da vaga

Atividades
•	Elaborar soluções para problemas complexos.
•	Atuar no desenvolvimento dos produtos da empresa.
•	Promover melhorias de desempenho e qualidade de código.
•	Monitorar e elaborar ações preventivas para garantir a resiliência das aplicações.

## Local

Alameda do Ingá, 38 (11º andar) - Vale do Sereno - Nova Lima/MG

## Benefícios
•	VT;
•	Estacionamento;
•	Vale Refeição ou Alimentação;
•	Plano de Saúde;
•	Plano Odontológico;
•	Seguro de Vida. 

## Requisitos

•	Formação superior na área de tecnologia.
•	Ótimos fundamentos em OO, SOLID e Design Patterns.
•	Forte conhecimento em API’s Rest.
•	Domínio de uma linguagem de alto nível Web (PHP / Python / Ruby / Node.JS / Java).
•	Controle de versão GIT e desenvolvimento em ambientes Linux.
•	Experiência em ambientes Amazon (EC2 / ECS / S3 / Route53 / RDS ).

**Desejáveis:**

•	Experiência em arquiteturas de sistemas distribuídos (Microservices / SOA).
•	Conhecimento em processos de CI/CD (Jenkins / CircleCI / GoCD / TravisCI).
•	Experiência em processos ágeis (SCRUM / Nexus / Lessworks / SaFe).
•	Conhecimento em React Native ou Ionic.

## Contratação

CLT Efetivo

## Nossa empresa

 A conta.MOBI é uma Startup do ramo financeiro que fornece uma Conta Digital, dentre outros serviços, para quem é Microempreendedor Individual (MEI). 

www.conta.mobi

## Como se candidatar

Interessados enviar currículo para: rh@conta.mobi com o assunto - Engenheiro de Software

**Comment by rscafi** [comment]
@rhcontamobi Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.
