### ISSUE TITLE
[Remoto] PHP Developer na TZ3 Tecnologia

### ISSUE THREAD

**Issue by dgilbertoni** [phpdevbr/vagas#810]
## Descrição da vaga

Buscamos profissional com experiência em desenvolvimento PHP para atuar no desenvolvimento de novos projetos e manutenção de sistemas existentes.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento PHP
- Conhecimento dos frameworks Code Igniter e Laravel
- MySQL e PostgreSQL
- HTML, Javascript, CSS

**Desejáveis:**
- Conhecimento de Node.js, React, React Native
- Conhecimento de Amazon AWS

## Contratação

PJ a combinar

## Nossa empresa

A TZ3 Tecnologia atua há mais de uma década no mercado de desenvolvimento de projetos 100% customizados de software, período em que entregou centenas de sistemas, apps, websites e robôs de automação de processos aos seus clientes.

## Como se candidatar

Por favor envie um email para rh@tz3.com.br com seu CV anexado e sua pretensão de remuneração mensal - enviar no assunto: Vaga PHP

### Contratação:
- PJ

### Experiência
- Júnior
- Pleno
- Sênior

**Comment by developer-sp** [comment]
Me apliquei para a vaga.
