### ISSUE TITLE
Nova Lima/MG - Desenvolvedor Front End

### ISSUE THREAD

**Issue by rhcontamobi** [phpdevbr/vagas#83]
## Descrição da vaga

•	Confeccionar o novo site da empresa e realizar as manutenções;
•	Elaboração de layouts de aplicações web;
•	Atuar no desenvolvimento dos produtos da empresa.

## Local

Nova Lima/MG

## Benefícios

•	VT;
•	Estacionamento;
•	Vale Refeição ou Alimentação;
•	Plano de Saúde;
•	Plano Odontológico;
•	Seguro de Vida. 

## Requisitos

Conhecimentos
•	Wordpress avançado;
•	PHP para Wordpress;
•	CSS, HTML5 e Javascript;
•	SASS / Compass;
•	Bootstrap ou outra solução responsiva;
•	Gulp / Grunt;
•	Controle de versão GIT e desenvolvimento em ambiente Linux;

Diferenciais:
•	React Native;
•	Ionic;
•	Vue.js;
•	Elaboração de layouts de aplicações web e mobile;
•	Conhecimento de usabilidade (UI) e experiência do usuário (UX);
•	Formação na área de Tecnologia da Informação, preferencialmente em Desenvolvimento de Software.

## Contratação

CLT Efetivo

## Nossa empresa

A conta.MOBI é uma Startup do ramo financeiro que fornece uma Conta Digital, dentre outros serviços, para quem é Microempreendedor Individual (MEI). 

## Como se candidatar

Interessados enviar currículo para: rh@conta.mobi com o assunto – Dev Front End

**Comment by rscafi** [comment]
Aqui é exclusivo para vagas de PHP. Para vagas de front-end, favor usar https://github.com/frontendbr/vagas
