### ISSUE TITLE
[São Paulo/SP] Desenvolvedor PHP na GlobalHitts

### ISSUE THREAD

**Issue by Guilbertsa** [phpdevbr/vagas#84]
## Descrição da vaga

Trabalhar na manutenção e criação de sistemas web. 

## Local

Escritório, São Paulo - Morumbi

## Benefícios
a combinar

## Requisitos
O perfil do programador é sênior full stack, especificação funcional , técnica ,front-end e Backend.

**Obrigatórios:**

- 3 anos de experiência com PHP 5+
- CodeIgniter, Javascript, HTML e CSS,JQuery, Bootstrap, Git , MySQL e Oracle.
- Inglês técnico.

## Contratação

CLT

## Nossa empresa

GlobalHitts,  30 anos de experiência no mundo de TI nos respaldam como uma das empresas mais importantes no setor. Somos especialistas no desenvolvimento e implementação de soluções inovadoras e vanguardistas para enfrentar as necessidades que nos apresenta a era digital na que vivemos.

Site da [empresa:](http://www.globalhitss.com/?lang=pt-br)http://www.globalhitss.com/?lang=pt-br

## Como se candidatar

Por favor envie um email para guilbert.araujo@net.com.br com seu CV anexado - enviar no assunto: Vaga PHP

**Comment by rscafi** [comment]
@Guilbertsa qual o nome da empresa? é "Hitts"? não consegui localizar no google, seria bom ter essa informação

**Comment by Guilbertsa** [comment]
Bom dia @rscafi   a empresa é a GlobalHitts http://www.globalhitss.com/?lang=pt-br
já atulizei a vaga.

abs

**Comment by gabidavila** [comment]
Antiga Hildebrando....

**Comment by rscafi** [comment]
@Guilbertsa Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.

**Comment by Guilbertsa** [comment]
@rscafi 

Bom dia, a vaga foi cancelada obrigado por fechar a issue.

abs
