### ISSUE TITLE
Python Developer - Remoto - Trabalhe com a Joyjet Digital (França)

### ISSUE THREAD

**Issue by dilsonalexandre** [phpdevbr/vagas#846]
## Descrição da vaga

Você gostaria de trabalhar em projetos internacionais, trabalhando remotamente para uma empresa francesa de tecnologia? Pois precisamos de talentos com experiência em Python e que estejam interessados em viver uma experiência internacional na carreira, construindo produtos digitais de sucesso para os nossos clientes e para a Joyjet Digital. 

## Local

Remoto.

## Benefícios
- Seguro de saúde
- Curso grátis para estudar
- 30 dias de férias por ano

## Requisitos

**Obrigatórios:**
- 3 anos de experiência como desenvolvedor back-end
- Compreensão proficiente de REST API
- Python
- Django Framework
- HTML/CSS
- GIT

**Desejáveis:**
- React Js
- Flask API
- C#

## Contratação

PJ a combinar.

## Nossa empresa

Aqui, na Joyjet, dizemos que somos os pioneiros do espaço digital e temos orgulho de ser exploradores e criadores geeks, de bom coração e apaixonados. Ajudamos as empresas a crescer, prosperar e impulsionar seus negócios digitais, graças ao design, estratégia, marketing e tecnologia de ponta.

No nosso dia a dia, grande parte da equipe fala português, mas é bom saber que nos comunicamos em inglês por meio de mensagens. As reuniões e convocatórias com a equipe acontecem em português e inglês.

## Como se candidatar

Por favor envie um email para jobs@joyjet.com com seu CV anexado - enviar no assunto: Vaga Python Developer.

### Contratação:
- PJ a combinar

**Comment by ravanscafi** [comment]
Olá @dilsonalexandre, esse repositório é somente para vagas **PHP** e por esse motivo a mesma vaga será fechada, favor procure outros repositórios adequados para postar essa vaga.
