### ISSUE TITLE
[São Paulo/SP] Dev. Full Stack na Creditoo

### ISSUE THREAD

**Issue by Wesckley** [phpdevbr/vagas#85]
## Descrição da vaga

- Atuar no desenvolvimento dos produtos da empresa.
- Prezar pela qualidade do código e a consistência dos testes unitários.

## Local

Escritório, São Paulo - Vila Olímpia (próximo a estação Vila Olímpia)

## Benefícios

- Horário flexível
- Vale Transporte (Somente CLT)
- Vale Refeição (Somente CLT)

## Requisitos

**Obrigatórios:**
- Laravel 5.4
- Angular 4
- MySQL 5.7

**Desejáveis:**
- Testes
- Docker
- Git

## Contratação

CLT e PJ a combinar

## Nossa empresa

Vem pra Creditoo! Somos uma startup promissora no ramo de crédito consignado. Aqui você vai encontrar um ótimo ambiente para trabalhar e uma equipe nota 10.

## Como se candidatar

Por favor envie um email para wesckley.uno@creditoo.com.br com seu CV anexado - enviar no assunto: Vaga Dev. Full Stack

**Comment by rscafi** [comment]
@Wesckley Vaga preenchida?

**Comment by Wesckley** [comment]
@Ravan foi preenchida sim, mas pode deixar seu currículo?

Em 12 de jan de 2018 7:57 PM, "Ravan Scafi" <notifications@github.com>
escreveu:

@Wesckley <https://github.com/wesckley> Vaga preenchida?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/phpdevbr/vagas/issues/85#issuecomment-357365862>, or mute
the thread
