### ISSUE TITLE
UI Engineer - Remoto - Trabalhe com a Joyjet Digital (França)

### ISSUE THREAD

**Issue by dilsonalexandre** [phpdevbr/vagas#852]
## Descrição da vaga
Você é um Engenheiro de UI? Você gostaria de trabalhar em projetos internacionais, remotamente para uma empresa de tecnologia francesa? Envie-nos seu currículo e vamos nos conhecer.

## Local

Remoto para empresa Francesa.

## Benefícios

Plano de saúde
Curso grátis para estudar
30 dias de férias por ano

#### Diferenciais

- Convivência leve e divertida.
- Projetos de inovação.

## Requisitos

**Obrigatórios:**
- Mais de 3 anos de experiência com HTML, CSS, JavaScript e Git para aplicativos da web e móveis
- Experiência com ReactJS e Styled-Components/CSS Modules
- Experiência nos principais processos do desenvolvimento de aplicativos da web, incluindo design, desenvolvimento, desempenho, integração, análise, usabilidade e acessibilidade

**Desejáveis:**
. Storybook
. React Testing-Library
. Server Side Rendering
. Integração com REST e/ou GraphQL
. Redux

**Diferenciais:**
- Inglês avançado.

## Contratação

PJ a combinar

## Nossa empresa

Aqui na Joyjet, dizemos que somos os pioneiros do espaço digital e temos orgulho de ser exploradores e criadores geeks, de bom coração e apaixonados. E estamos totalmente comprometidos em construir produtos digitais de sucesso para nossos clientes e para nós mesmos. Ajudamos as empresas a crescer, prosperar e impulsionar seus negócios digitais, graças ao design, estratégia, marketing e tecnologia de ponta.

No nosso dia a dia, grande parte da equipe fala português, mas é bom saber que nos comunicamos em inglês por meio de mensagens. As reuniões e convocatórias com a equipe acontecem em português e inglês.

## Como se candidatar

Por favor envie um email para jobs@joyjet.com com seu CV anexado - enviar no assunto: Vaga UI Engineer

### Alocação:
- Presencial

### Contratação:
- PJ

### Experiência
- Pleno
- Sênior
- Especialista

**Comment by Piulres** [comment]
Que vaga linda pra mim! Gostaria! www.renanemigdio.com

**Comment by ravanscafi** [comment]
Olá, esse repositório é somente para vagas **PHP** e por esse motivo a mesma vaga será fechada, favor procure outros repositórios adequados para postar essa vaga.
