### ISSUE TITLE
 iOS Developer (Swift / Objective C) - Trabalhe remoto com a Joyjet Digital (França)

### ISSUE THREAD

**Issue by dilsonalexandre** [phpdevbr/vagas#853]
## Descrição da vaga
Você é um iOS Developer (Swift / Objective C)? Você gostaria de trabalhar em projetos internacionais, trabalhando remotamente para uma empresa de tecnologia francesa? Você tem atitude positiva, postura pró-ativa, espírito jovem e leveza para conviver! 

Envie-nos seu currículo e vamos nos conhecer.

## Local

Remoto.

## Benefícios

- Plano de saúde
- Curso grátis para estudar
- 30 dias de férias por ano

## Requisitos

**Obrigatórios:**

Requisitos obrigatórios:
. 3 years of experience
. Java
. Swift
. HTML/CSS
. GIT

**Desejáveis:**
. React
. React Native
. Flutter
. Objective C

## Nossa empresa

Aqui na Joyjet, dizemos que somos os pioneiros do espaço digital e temos orgulho de ser exploradores e criadores geeks, de bom coração e apaixonados. E estamos totalmente comprometidos em construir produtos digitais de sucesso para nossos clientes e para nós mesmos. Ajudamos as empresas a crescer, prosperar e impulsionar seus negócios digitais, graças ao design, estratégia, marketing e tecnologia de ponta.

No nosso dia a dia, grande parte da equipe fala português, mas é bom saber que nos comunicamos em inglês por meio de mensagens. As reuniões e convocatórias com a equipe acontecem em português e inglês.

## Como se candidatar

Por favor envie um email para jobs@joyjet.com com seu CV anexado - enviar no assunto: Vaga iOS Developer. 

### Contratação:
- PJ a combinar

### Experiência
- Pleno
- Sênior
- Especialista

**Comment by Devitibeck** [comment]
Esse repositório aqui não é apenas pra php?

Em ter, 13 de abr de 2021 12:44, dilsonalexandre ***@***.***>
escreveu:

**Comment by ravanscafi** [comment]
Olá @dilsonalexandre, esse repositório é somente para vagas **PHP** e por esse motivo a mesma vaga será fechada, favor procure outros repositórios adequados para postar essa vaga.
