### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) Backend Sênior na SumUp

### ISSUE THREAD

**Issue by alexandre-xavier** [phpdevbr/vagas#87]
## Descrição

Quer fazer a diferença na vida de milhares de pequenos negócios ao redor do mundo e ainda fazer parte de um time engajado em encontrar soluções de pagamentos com inovação e tecnologia?

Hoje, centenas de milhares de pequenos negócios em 31 países ao redor do mundo contam com SumUp para receber pagamentos.  Além de trabalharmos com hardware próprio, aplicações mobile e web, desenvolvemos um conjunto de APIs e SDKs para integrar o pagamento SumUp em outros aplicativos e serviços.

Estamos em busca de profissionais altamente qualificados para a contribuir com soluções performáticas e sustentáveis em um ambiente de alta complexidade.
Concorrência, escalabilidade e alta disponibilidade estão presentes no nosso dia a dia.

Criamos nossa própria solução de pagamento de ponta-a-ponta para que possamos sempre oferecer o melhor valor e serviço por um preço que todos podem pagar. Temos grandes desafios à nossa frente e precisamos de pessoas inteligentes e criativas para nos ajudar a enfrentá-los. 

Se você acha que tem o que é necessário e quer fazer parte desta mudança, junte-se a nós.

## Local

Presencial, Pinheiros - São Paulo - SP (próximo a estação Pinheiros do metrô).

## Requisitos

**Obrigatórios:**

- Fluência em inglês (you'll be part of a truly global organization).
- Formação em Ciência da Computação / Sistemas de Informação ou areas relacionadas.
- Experiência em desenvolvimento PHP com frameworks modernos (Symfony, Silex, Laravel, Phalcon e afins).
- Estar disposto a aprender uma nova linguagem de programação.
- Bom conhecimento em Algoritimos, Estrutura de Dados, Orientação a Objetos e Banco de Dados Relacionais.

**Desejáveis:**

- Expêriencia em plataformas SOA e/ou Microservices.
- Expêriencia em agile methodologies/techniques (Scrum, XP, Kanban, Pair-programming).

**Diferenciais:**

- Conhecimento em Ruby

## Benefícios

**Padrão:**

- Vale-refeição R$ 600,00 por mês
- VT ou estacionamento

**Mimos:**

- Hack-time (liberdade de gastar 10% do seu tempo em "passion projects")
- Monte sua maquina como desejar (Dell ou MacBook, Linux/macOs/Windows)
- Frutas
- Xbox
- Café Espresso Italian Coffee

**Opcionais**

- Gym-pass
- Plano odontólogico

## Contratação

CLT - Salário a combinar

## Nossa empresa

Fundada em 2012 em Berlim, a SumUp é uma fintech que é líder em pagamentos móveis (mPOS) na Europa e está em alto crescimento no mercado brasileiro. Nossa missão é ajudar o pequeno negócio a crescer oferecendo a ele soluções rápidas, intuitivas e acessíveis para aceitar cartão.

A SumUp é movida por um propósito: os pagamentos devem ser tão simples e intuitivos que as pessoas mal percebem quando uma transação acontece, é mais fácil que usar dinheiro. As nossas maquininhas são um primeiro passo em direção a essa revolução.

Sabemos o quão vital é o pagamento para pequenas empresas, então usamos nossa tecnologia para resolver seus problemas. Acreditamos na comunicação aberta e transparente, não em regras rígidas e hierarquias.

Se você está procurando a chance de inovar e perturbar a indústria de pagamentos, junte-se a nós. 

Mais informações: https://sumup.com.br/trabalhe-conosco/

## Como se candidatar?

Através do link: https://sumup.workable.com/j/42E8AA6FB6

**Comment by joubertredrat** [comment]
Putz @alexandre-xavier que vaga linda! Se fosse 3 meses atras, estaria enviando CV agora mesmo!

Desejo sucesso ao escolhido pra esta vaga.

**Comment by mmiranda** [comment]
nunca é tarde @joubertredrat :D

**Comment by joubertredrat** [comment]
@mmiranda Já estou com data de partida para Portugal, só falta comprar as passagens.

**Comment by gnumoksha** [comment]
Olá, @alexandre-xavier. Por que "Formação em Ciência da Computação / Sistemas de Informação ou areas relacionadas" é obrigatório?

**Comment by alexandre-xavier** [comment]
Olá @gnumoksha, tudo bom?

A SumUp tem uma cultura de valorizar bastante a formação acadêmica dos seus colaboradores.
Entretanto sabemos que nada substituí a experiência handson.

Caso você tenha um bom fit com todo o restante, você com certeza pode aplicar.

Dentre todos os requisitos obrigatórios este é o único que conseguimos flexibilizar olhando caso a caso.

Abraços

**Comment by vaynard** [comment]
Ah se fosse pra trabalhar em Berlin =)

**Comment by gnumoksha** [comment]
@alexandre-xavier obrigado pela resposta.
