### ISSUE TITLE
[Alphaville/SP] Desenvolvedor(a) PHP Sênior na PSM Company

### ISSUE THREAD

**Issue by radenberger** [phpdevbr/vagas#88]
## Descrição da vaga

Desenvolver sistema de saúde mas não preciso de conhecimentos específicos deste negócios.

## Local

In loco, em Alphaville - São Paulo

## Benefícios

- Vale Transporte
- Vale Refeição
- Assistência Médica e Odontológica
- Seguro de Vida
- Auxílio Creche
- Seguro de Vida
- Cartão Good Card
- Parcerias com Escolas de Idiomas/Universidades/Instituições Técnicas 

## Requisitos

**Obrigatórios:**
- Profunda experiência com Desenvolvimento em PHP
- Experiência voltada com desenvolvimento de sistemas ou negócios de E-commerce.

## Contratação

CLT Full

## Nossa empresa

Em seu 10º ano de atuação, a PSM Company é referência de mercado nos serviços especializados de Recrutamento e Seleção, Terceirização de Mão de Obra e Gestão de Pessoas.

A nossa história de sucesso, esta baseada em nosso modelo de negócios que proporcionam assertividade e qualidade no processo seletivo, baixo Turn Over e isenção de riscos e passivos trabalhistas.

Somos especializados na identificação de Talentos para as áreas de TI / Telecom como também para as áreas operacionais e administrativas.

## Como se candidatar

Enviar um e-mail com currículo atualizado e pretensão salarial para felipe.radenberger@psmcompany.com.br
Aceitamos indicações.

**Comment by rscafi** [comment]
@radenberger Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.
