### ISSUE TITLE
[Belo Horizonte/MG] Desenvolvedor(a) PHP Pleno na Sapiens Solutions

### ISSUE THREAD

**Issue by guireisbh** [phpdevbr/vagas#90]
## Descrição da vaga
Programador pleno com experiência em Wordpress, JavaScript, JQuery, Bootstrap, PHP5+, MySQL.

## Local
Belo Horizonte - Savassi
Trabalhar no local

## Benefícios
- Almoço no Restaurante
- 1 ou 2 horas de almoço
- Lanche na empresa
- Área de descanso

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com PHP 5+
- 2 anos de experiência com Wordpress

**Desejáveis:**
- Angular 2 e 4

**Diferenciais:**
- Woocommerce
- Plugins para Wordpress

## Contratação
CLT ou PJ a combinar

## Como se candidatar
Por favor envie um email para rh@sapiensolutions.com.br com seu CV anexado - enviar no assunto: Vaga PHP Pleno

**Comment by rscafi** [comment]
@guireisbh Vaga preenchida?

**Comment by rscafi** [comment]
Fechado por inatividade.
