### ISSUE TITLE
[Alphaville/SP] Desenvolvedor PHP Sênior na Talentify

### ISSUE THREAD

**Issue by magroski** [phpdevbr/vagas#91]
## Descrição da vaga

Desenvolvimento de sistemas distribuidos em PHP. Realizar testes de carga, identificar gargalos e otimizar o desempenho de sistemas. Identificar, monitorar e corrigir bugs e exceptions. Desenvolver testes automatizados e garantir a qualidade do software.

## Local

Presencial, Alphaville/Barueri - SP

## Requisitos

**Obrigatórios:**
- 5 ou mais anos de experiência com PHP;
- Experiência com banco de dados SQL;

**Desejáveis:**
- Experiência com PhalconPhp;
- Experiência em testes, monitoramento e otimização;

**Diferenciais:**
- Experiência com infraestrutura AWS;

## Contratação

CLT. R$6.000,00 - R$8.000,00 mensal

## Nossa empresa

Acreditamos que a combinação Marketing + Tecnologia + Pessoas é a base do R&S do Futuro! E que todas as partes envolvidas em um processo seletivo podem ter uma experiência inteligente, ágil e descomplicada.

## Como se candidatar

[Aqui](https://br.talentflux.com/desenvolvedor-php-senior-barueri-sp-talentify-1)

**Comment by joubertredrat** [comment]
Vaga linda!

**Comment by wallace-araujo** [comment]
Ola  amigo caso aparece uma vaga como pleno..me da um toq
sou de Barueri ficaria feliz em trabalha na minha cidade..

**Comment by vinyvicente** [comment]
Conheço a empresa, lugar legal, ótima oportunidade :)

**Comment by rpaggi** [comment]
To tentando me candidatar, mas na hora de colocar o e-mail ele está dando um alert dizendo: "Ocorreu um erro. Tente novamente"
