### ISSUE TITLE
[São Paulo/SP] Desenvolvedor(a) PHP Júnior na QueroQuitar!

### ISSUE THREAD

**Issue by thiagoericson** [phpdevbr/vagas#92]
## Nossa empresa

Somos uma Fintech premiada focada na recuperação de crédito, em rápido crescimento, com inúmeros desafios, conectadas a grandes players de diferentes setores.

## Principais funções

- Atuará inicialmente em aplicações console de automatização de fluxo de jornada do cliente;

## Requisitos

**Obrigatórios:**
- Experiência em PHP >= 1 ano
- Laravel
- Git
- Princípios de Orientação a Objeto
- Noções de Domain Driven Design

**Desejáveis:**
- Ambiente AWS
- ES6
- HTML
- Conhecimentos de SOAP e REST

**Diferenciais:**
- Participar da comunidade Laravel Brasil

## Contratação

CLT - R$ 2.000,00

## Local

Escritório, São Paulo - Higienópolis

## Benefícios

- cursos online
- mesa de frutas
- ambiente cooperativo e descontraído 
- vale trasporte
- vale refeição
- próximo ao metrô Paulista (linha 4)

## Como se candidatar

Por favor envie um email para vagas@queroquitar.com.br com seu CV anexado - enviar no assunto: Vaga PHP Júnior

**Comment by vinyguedess** [comment]
@mateusguedess

**Comment by rscafi** [comment]
@thiagoericson Vaga preenchida?

**Comment by thiagoericson** [comment]
Oir @rscafi , ainda não.

**Comment by ravanscafi** [comment]
Olá @thiagoericson,
A vaga ainda está aberta?

_(sou administrador das vagas e estou fechando as que já foram preenchidas)_

**Comment by thiagoericson** [comment]
@ravanscafi Oi @ravanscafi , não mais. Podemos fechá-la.

Abs.
