### ISSUE TITLE
[Curitiba/PR] 4 vagas p/ Desenvolvedor(a) Full Stack PHP pela GRGIT

### ISSUE THREAD

**Issue by fhferreira** [phpdevbr/vagas#93]
##Repassando:

Estamos com a oportunidades abaixo:

Desenvolvedor Full Stack Php Pl e Sr - 4 vagas

Bootstrap, JQuery/Javascript, MySQL. Habilidades com AWS, twig, Shell Scripting, Rest API’s, Laravel será um diferencial.

Caso tenham interesse em conhecer a vaga por favor encaminhem o cv com pretensão CLT.
Enviar CV para recrutamento@grgit.com.br - "A/C Gélia Gomes via Flávio Ferreira".

Benefícios : Ass Médica + Odontológica + vt + vr + seguro de vida.

Local centro - Curitiba - PR.

**Comment by clmadrazo** [comment]
Aceita remoto?

**Comment by ravanscafi** [comment]
Olá @fhferreira,
A vaga ainda está aberta?

_(sou administrador das vagas e estou fechando as que já foram preenchidas)_

**Comment by ravanscafi** [comment]
_(fechado por falta de resposta)_
