### ISSUE TITLE
Florianópolis/SC PHP Developer na AltoQi

### ISSUE THREAD

**Issue by Steporto** [phpdevbr/vagas#960]
## Nossa empresa

A AltoQi é uma holding com soluções altamente especializadas para a construção civil. Somos movidos por grandes desafios e estamos em busca de pessoas que estejam dispostas a trabalhar com propósito, tecnologia e estar em constante aprendizagem.

Estamos em crescimento e buscando novos talentos. Procuramos alguém que esteja disposto a embarcar nessa trajetória conosco e gerar impactos positivos na vida das pessoas. Por isso, estamos à procura de pessoas da área de Programação, para se juntarem à nossa equipe e nos ajudarem a crescer, através de nossas aplicações e contribuir com a nossa Unidade de Negócios QiSat, que é a responsável pelo segmento de educação dentro da holding AltoQi. Aqui somos motivados pelo ideal de propagar conhecimento de qualidade, elevando o nível da Construção Civil.

## Descrição da vaga

Desde o desenvolvimento intermediário/avançado de websites na linguagem PHP, até o gerenciamento avançado em banco de dados MySQL.

## Local

Remoto, Escritório em Florianópolis/SC

## Benefícios

- Oportunidade de começar uma nova era e contribuir para a alavancagem da empresa;
- Trabalhe com mais segurança em home office durante a pandemia;
- Opções de Vale alimentação e/ou Vale refeição;
- Convênio com a ACATE (Associação Catarinense de Tecnologia);
- Convênio com o SESC;
- Auxílio home office de R$ 100,00 durante a pandemia;
- Parcerias com redes de farmácia, restaurantes e faculdades;
- No dress code investimos no conforto, não há códigos para se vestir, desde que se sinta bem!
- Oportunidade de trabalhar com profissionais que são referência no mercado.
- Faça parte de uma equipe que acredita na diversidade e inclusão. Aqui você pode ser você mesmo.

#### Diferenciais

- Horário flexível
- Equipamentos completos, para trabalho home office

## Requisitos

**Obrigatórios:**
- Experiência com programação PHP 
- Experiência com desenvolvimento de Moodle
- 
**Desejáveis:**

- Conhecimentos com o sistema operacional Linux (DEBIAN)
- Metodologia ágil de desenvolvimento Scrum e GitLab, Docker,
- Layout responsivo
- Lógica de programação

**Diferenciais:**

- conhecimentos em Laravel

## Contratação

CLT 

## Como se candidatar

Por favor realize seu cadastro em nosso sitehttps://grupoaltoqi.solides.jobs/vacancies/87213#vacancyDescription , em caso de dúvidas entre em contato através stefanie.bentzviller@altoqi.com.br

### Alocação:

- Remoto

### Experiência
- Pleno
- Sênior

**Comment by developer-sp** [comment]
Me apliquei para a vaga pelo site.
