### ISSUE TITLE
[São Paulo/SP] Desenvolvedor PHP BackEnd - INTI

### ISSUE THREAD

**Issue by rgmd** [phpdevbr/vagas#98]
Quer trabalhar em um ambiente dinâmico e ágil, atuando na concepção e desenvolvimento de novos produtos? Se interessa por startups, quer fazer a diferença e crescer junto conosco?

### **Nossa empresa: INTI**
http://www.byinti.com
Local de trabalho: Avenida Paulista, São Paulo-SP
Alocação presencial

Fazemos parte da **ACE**, maior aceleradora de startups da América Latina
https://acestartups.com.br

Estamos buscando profissinal desenvolvedor **PHP Pleno/Senior** 

### Pré Requisitos:
- Framework Yii2 (Preferencialmente), Laravel ou Similar;
- Aptidão em Javascript/Jquery;
- Banco de Dados Relacional (MySQL, Oracle, MSSQL) e NoSQL (MongoDB);
- Amazon AWS;
- Composer, GIT e outros;
- Metodologias ágeis (SCRUM)

### Benefícios
- Excelente localização
- Ambiente descontraído
- Frutas 
- Café Nespresso
- Dayoff mensal
- Massagem 1x/mês

### Contrato
- CLT ou PJ

### Interessou? Manda um CV! 
rafaguerramd@gmail.com

![powerbyinti](https://user-images.githubusercontent.com/26577166/33128301-185b714e-cf73-11e7-9a00-dc655b3f0cd9.jpg)

**Comment by rscafi** [comment]
@rgmd a vaga é CLT ou PJ? preciso completar as informações

**Comment by vinyguedess** [comment]
@mateusguedess

**Comment by rgmd** [comment]
CLT ou PJ. Completei na descrição :)

**Comment by ravanscafi** [comment]
Olá @rgmd ,
A vaga ainda está aberta?

_(sou administrador das vagas e estou fechando as que já foram preenchidas)_

**Comment by ravanscafi** [comment]
_(fechado por falta de resposta)_
