### ISSUE TITLE
[Uberlândia/MG] Desenvolvedor(a) PHP Magento na Softbox

### ISSUE THREAD

**Issue by thsoftbox** [phpdevbr/vagas#99]
**Nossa empresa: Softbox**
http://www.softbox.com.br

**Local de trabalho:** Uberlândia/MG

**Descrição da vaga:** 
- Executar atividades/demandas de desenvolvimento corretivo e evolutivo de sistemas; - Realizar atividades de preparação e configuração de ambiente para desenvolvimento; - Realizar análise de escopo de demandas e planejamento de execução; - Linguagem PHP - Framework Magento

**Benefícios**
- Vale-alimentação
- Vale-combustível
- Convênio médico e odontológico
- Ambiente descontraído
- Sala de jogos (XBOX One, mesa de ping-pong e pebolim)
- Happy-hour mensal
- Ambiente temático Star Wars
- Localização em shopping.

**Requisitos**
- Experiência com desenvolvimento em grande escala
- Experiência com desenvolvimento em PHP
- Conhecimentos em Magento

**Contratação**

CLT a combinar

**Como se candidatar**

Por favor envie um email para talentoshumanos@softbox.com.br com seu CV anexado - enviar no assunto: Vaga PHP/Magento

**Comment by ravanscafi** [comment]
Olá @thsoftbox ,
A vaga ainda está aberta?

_(sou administrador das vagas e estou fechando as que já foram preenchidas)_

**Comment by ravanscafi** [comment]
_(fechado por falta de resposta)_
